### PR TITLE
Aerospike 7.1.0.2

### PR DESCRIPTION
**Pull request by pvinh-spike**
https://download.aerospike.com/download/server/notes.html

### CODE REVIEW

**Comment by tianon** [comment]
Hmm, there doesn't appear to be any change / version bump in the `Dockerfile` changes here?

**Comment by pvinh-spike** [comment]
Images rebuilt due to Ubuntu 22.04 base image updated.

**Comment by tianon** [comment]
I'm confused -- that's already how _all_ images in this program work, automatically.  In other words, this PR won't actually rebuild anything (it will only retag things, because no source has changed), and _all_ existing tags are already either rebuilt/repushed or in queue to be rebuilt automatically due to the base image update.

You can see this via the `org.opencontainers.image.created` annotations on https://oci.dag.dev/?image=aerospike:ce-7.1.0.2.

**Comment by pvinh-spike** [comment]
Since the immutable tag 7.1.0.2_2 not recorded, I'm closing the PR.  Thanks

**Comment by pvinh-spike** [comment]
N/A

**Comment by tianon** [comment]
Just to be 100% explicitly clear: _none_ of our tags are "immutable" -- we do not support that concept, and do not plan to.
(See https://github.com/docker-library/official-images#what-are-official-images, especially that fourth bullet point.)

If users want or need an "immutable" reference to an image, that's the purpose of the content-addressable image digest ("pull by digest").

**Comment by pvinh-spike** [comment]
Understood.  Thanks for explaining.

**Pull request closed without merging**
