### PR TITLE
arangodb 3.3.22 and 3.4.5

### PR DESCRIPTION
**Pull request by fceller**
Updated ArangoDB to 3.3.22 and 3.4.5

### CODE REVIEW

**Comment by tianon** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index b8535b5..fdf35d5 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,4 +1,4 @@
 arangodb:2.8.11 @ amd64
 arangodb:3.2.17 @ amd64
-arangodb:3.3.21 @ amd64
+arangodb:3.3.22 @ amd64
 arangodb:latest @ amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index e483150..1a8d682 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -3,7 +3,7 @@ arangodb:2.8.11
 arangodb:3.2
 arangodb:3.2.17
 arangodb:3.3
-arangodb:3.3.21
+arangodb:3.3.22
 arangodb:3.4
-arangodb:3.4.4
+arangodb:3.4.5
 arangodb:latest
diff --git a/arangodb_3.3.21/Dockerfile b/arangodb_3.3.22/Dockerfile
similarity index 98%
rename from arangodb_3.3.21/Dockerfile
rename to arangodb_3.3.22/Dockerfile
index 85a5dcf..70695ac 100644
--- a/arangodb_3.3.21/Dockerfile
+++ b/arangodb_3.3.22/Dockerfile
@@ -3,7 +3,7 @@ MAINTAINER Frank Celler <info@arangodb.com>
 
 ENV ARCHITECTURE amd64
 ENV DEB_PACKAGE_VERSION 1
-ENV ARANGO_VERSION 3.3.21
+ENV ARANGO_VERSION 3.3.22
 ENV ARANGO_URL https://download.arangodb.com/arangodb33/Debian_9.0
 ENV ARANGO_PACKAGE arangodb3-${ARANGO_VERSION}-${DEB_PACKAGE_VERSION}_${ARCHITECTURE}.deb
 ENV ARANGO_PACKAGE_URL ${ARANGO_URL}/${ARCHITECTURE}/${ARANGO_PACKAGE}
diff --git a/arangodb_3.3.21/docker-entrypoint.sh b/arangodb_3.3.22/docker-entrypoint.sh
similarity index 100%
rename from arangodb_3.3.21/docker-entrypoint.sh
rename to arangodb_3.3.22/docker-entrypoint.sh
diff --git a/arangodb_latest/Dockerfile b/arangodb_latest/Dockerfile
index 4ccb5dd..d02f5de 100644
--- a/arangodb_latest/Dockerfile
+++ b/arangodb_latest/Dockerfile
@@ -1,7 +1,7 @@
 FROM alpine:3.8
 MAINTAINER Frank Celler <info@arangodb.com>
 
-ENV ARANGO_VERSION 3.4.4
+ENV ARANGO_VERSION 3.4.5
 ENV ARANGO_URL https://download.arangodb.com/arangodb34/DEBIAN/amd64
 ENV ARANGO_PACKAGE arangodb3_${ARANGO_VERSION}-1_amd64.deb
 ENV ARANGO_PACKAGE_URL ${ARANGO_URL}/${ARANGO_PACKAGE}
@@ -33,7 +33,11 @@ RUN cd /tmp                                && \
     echo chgrp 0 /var/lib/arangodb3 /var/lib/arangodb3-apps && \
     echo chmod 775 /var/lib/arangodb3 /var/lib/arangodb3-apps && \
     rm -f /usr/bin/foxx && \
-    rm -f ${ARANGO_PACKAGE}* data.tar.gz
+    wget http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/numactl-2.0.12-r2.apk && \
+    wget http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/numactl-tools-2.0.12-r2.apk && \
+    apk add ./numactl-2.0.12-r2.apk && \
+    apk add ./numactl-tools-2.0.12-r2.apk && \
+    rm -f ${ARANGO_PACKAGE}* data.tar.gz numactl-2.0.12-r2.apk numactl-tools-2.0.12-r2.apk
 # Note that Openshift runs containers by default with a random UID and GID 0.
 # We need that the database and apps directory are writable for this config.
 
diff --git a/arangodb_latest/docker-entrypoint.sh b/arangodb_latest/docker-entrypoint.sh
index 6295cb0..a091e60 100755
--- a/arangodb_latest/docker-entrypoint.sh
+++ b/arangodb_latest/docker-entrypoint.sh
@@ -14,6 +14,26 @@ case "$1" in
     *) ;;
 esac
 
+# check for numa
+NUMACTL=""
+
+if [ -d /sys/devices/system/node/node1 -a -f /proc/self/numa_maps ]; then
+    if [ "$NUMA" = "" ]; then
+        NUMACTL="numactl --interleave=all"
+    elif [ "$NUMA" != "disable" ]; then
+        NUMACTL="numactl --interleave=$NUMA"
+    fi
+
+    if [ "$NUMACTL" != "" ]; then
+        if $NUMACTL echo > /dev/null 2>&1; then
+            echo "using NUMA $NUMACTL"
+        else
+            echo "cannot start with NUMA $NUMACTL: please ensure that docker is running with --privileged"
+            NUMACTL=""
+        fi
+    fi
+fi
+
 if [ "$1" = 'arangod' ]; then
     # /var/lib/arangodb3 and /var/lib/arangodb3-apps must exist and
     # be writable by the user under which we run the container.
@@ -38,15 +58,19 @@ if [ "$1" = 'arangod' ]; then
         echo "automatically choosing storage engine"
     fi
     if [ ! -f /var/lib/arangodb3/SERVER ] && [ "$SKIP_DATABASE_INIT" != "1" ]; then
+        if [ ! -z "$ARANGO_ROOT_PASSWORD_FILE" ]; then
             if [ -f "$ARANGO_ROOT_PASSWORD_FILE" ]; then
                 ARANGO_ROOT_PASSWORD="$(cat $ARANGO_ROOT_PASSWORD_FILE)"
+            else
+                echo "WARNING: password file '$ARANGO_ROOT_PASSWORD_FILE' does not exist"
+            fi
 	fi
         # Please note that the +x in the following line is for the case
         # that ARANGO_ROOT_PASSWORD is set but to an empty value, please
         # do not remove!
         if [ -z "${ARANGO_ROOT_PASSWORD+x}" ] && [ -z "$ARANGO_NO_AUTH" ] && [ -z "$ARANGO_RANDOM_ROOT_PASSWORD" ]; then
             echo >&2 'error: database is uninitialized and password option is not specified '
-            echo >&2 "  You need to specify one of ARANGO_ROOT_PASSWORD, ARANGO_NO_AUTH and ARANGO_RANDOM_ROOT_PASSWORD"
+            echo >&2 "  You need to specify one of ARANGO_ROOT_PASSWORD, ARANGO_ROOT_PASSWORD_FILE, ARANGO_NO_AUTH and ARANGO_RANDOM_ROOT_PASSWORD"
             exit 1
         fi
         
@@ -71,7 +95,7 @@ if [ "$1" = 'arangod' ]; then
 
         echo "Initializing database...Hang on..."
 
-        arangod --config /tmp/arangod.conf \
+        $NUMACTL arangod --config /tmp/arangod.conf \
                 --server.endpoint tcp://127.0.0.1:$ARANGO_INIT_PORT \
                 --server.authentication false \
 		--log.file /tmp/init-log \
@@ -91,9 +115,11 @@ if [ "$1" = 'arangod' ]; then
                 cat /tmp/init-log
                 exit 1
             fi
+
             let counter=counter+1
             ARANGO_UP=1
-                arangosh \
+
+            $NUMACTL arangosh \
                 --server.endpoint=tcp://127.0.0.1:$ARANGO_INIT_PORT \
                 --server.authentication false \
                 --javascript.execute-string "db._version()" \
@@ -114,7 +140,7 @@ if [ "$1" = 'arangod' ]; then
                 ;;
             *.js)
                 echo "$0: running $f"
-                        arangosh ${ARANGOSH_ARGS} \
+                $NUMACTL arangosh ${ARANGOSH_ARGS} \
                         --server.endpoint=tcp://127.0.0.1:$ARANGO_INIT_PORT \
                         --javascript.execute "$f"
                 ;;
@@ -123,7 +149,7 @@ if [ "$1" = 'arangod' ]; then
                 for d in $f/*; do
                     DBName=$(echo ${d}|sed "s;$f/;;")
                     echo "restoring $d into ${DBName}";
-                            arangorestore \
+                    $NUMACTL arangorestore \
                         ${ARANGOSH_ARGS} \
                         --server.endpoint=tcp://127.0.0.1:$ARANGO_INIT_PORT \
                         --create-database true \
@@ -158,6 +184,8 @@ if [ "$1" = 'arangod' ]; then
     fi
 
     set -- arangod "$@" --server.authentication="$AUTHENTICATION" --config /tmp/arangod.conf
+else
+    NUMACTL=""
 fi
 
-exec "$@"
+exec $NUMACTL "$@"
````

</details>

**Comment by tianon** [comment]
We've seen a _lot_ of issues mixing packages from Alpine Edge with a release -- are you sure you want to go ahead with this?

**Comment by KVS85** [comment]
@tianon we tested such mixed configuration internally and didn't find issues. Also, it's only for specific starting mode of ArangoDB which is not used by default. So we assume it's OK for us to mix.

Can you please give it a green light?

**Comment by yosifkit** [comment]
The two apk files should really should be verified in someway, as noted in the [README](https://github.com/docker-library/official-images/tree/885bfe7d277d52837bc84e303d5b947bc83d75d7#image-build). A gpg signature validation would be best but a sha256 embedded directly in the Dockerfile is better than nothing.

Not sure what conflicts might happen, but have you tried adding the edge apk repo and just using `apk` to install these two from edge? (That way you get the verification that apk does.)

**Pull request merged**
