### PR TITLE
Update Clear Linux OS to 34900

### PR DESCRIPTION
**Pull request by clrbuilder**
Update Clear Linux OS latest+base images to release 34900

@bryteise @mdhorn @phmccarty

### CODE REVIEW

**Comment by yosifkit** [comment]
Removal of `etc/os-release` seems unexpected. Was this intentional?

**Comment by mdhorn** [comment]
> Removal of `etc/os-release` seems unexpected. Was this intentional?

That should be a link to /usr/lib/os-release ... investigating.

**Comment by phmccarty** [comment]
Looks like all of the files and directories created via `systemd-tmpfiles` (from `/etc` and `/var`) disappeared from the image. Certainly unexpected...

**Comment by mdhorn** [comment]
@yosifkit We found to root cause; related to a new version of systemd.
Please close this PR and we will get the fixes in next week's automated PR.

**Pull request closed without merging**
