### PR TITLE
Add Peter and Talon to maintainers list

### PR DESCRIPTION
**Pull request by Moghedrin**
Mostly so I can say I'm an official image maintainer and don't feel like I'm a lying sack of sh*t.

### CODE REVIEW

**Comment by yosifkit** [comment]
We'll need @psftw's acceptance :+1:, but LGTM.

**Comment by tianon** [comment]
LGTM :heart:

**Comment by psftw** [comment]
LGTM :+1: :fearful:

**Comment by yosifkit** [comment]
:tada:

**Pull request merged**
