### PR TITLE
Update Ubuntu 2024-03-01

### PR DESCRIPTION
**Pull request by ROCKsBot**
Update Ubuntu to the latest published OCI tarballs as of 2024-03-01.

### CODE REVIEW

**Comment by tianon** [comment]
```diff
+bin.usr-is-merged/
+lib.usr-is-merged/
+sbin.usr-is-merged/
```

Are all of these intentionally part of the final rootfs?

**Comment by tianon** [comment]
(I'm guessing those are an unintentional symptom of some of the usrmerge changes happening in devel right now :eyes:)

**Comment by cjdcordeiro** [comment]
Hum good catch. @woky any insights on this?

**Comment by tianon** [comment]
https://git.launchpad.net/ubuntu/+source/base-files/commit/debian?id=8bd2acfaf3d61c68c19ba5b24806bd1645238138 :eyes:

I think I recall seeing something about needing to use `debootstrap --no-merged-usr` to get correct merged-usr of Noble with this approach? (that might've been in the `#debian-apt` IRC channel :sweat_smile:)

**Comment by cjdcordeiro** [comment]
Right, @julian-klode can provide more in-depth details about this, but in short:
 - this is indeed a consequence of in-devel changes. Those diversions should disappear eventually.

@tianon I think we can proceed for now since this is the devel release.

**Pull request merged**
