### PR TITLE
Add irssi to official images.

### PR DESCRIPTION
**Pull request by jfrazelle**
IRC FOR THE IRC GODS

### CODE REVIEW

**Comment by tianon** [comment]
YOU DIDN'T EVEN USE THE SCRIPT

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh > ../path/to/official-images/checkout/library/irssi
```

**Comment by jfrazelle** [comment]
#newb
#cantAlphebetizeEither

**Comment by tianon** [comment]
Of course, if upstream comes along and wants to maintain this, we'll have no qualms about giving it up. :+1:

**Comment by yosifkit** [comment]
If you base it on `buildpack-deps:jessie-curl` you can share a layer, but it is up to you.  Is a docs PR incoming?

**Comment by jfrazelle** [comment]
DOCS FOR THE DOCS GODS
(working on it)

**Comment by tianon** [comment]
If users want to bind-mount their own local `~/.irssi`, we can even document the `-u $(id -u):$(id -g) -v $HOME/.irssi:/home/user/.irssi` trick here, but we'll definitely need to be sure we document the `-e TERM` requirement.

What's especially cool about having `~/.irssi` as a volume regardless is that we can probably run this image with the new-in-1.5 `--read-only` flag too. :+1:

**Comment by yosifkit** [comment]
@tianon made updates to the Dockerfile.  Can you update the refs here?

**Comment by jfrazelle** [comment]
yes almost done with docs both will be pushed in a sec :D

**Comment by yosifkit** [comment]
LGTM
Build test of #423; 1e5355eebe9928b2741aed668e40f5c2f4401a35 (`irssi`):

```console
$ ./bashbrew/bashbrew.sh build https://raw.githubusercontent.com/docker-library/official-images/1e5355eebe9928b2741aed668e40f5c2f4401a35/library/irssi
Fetching irssi (git://github.com/jfrazelle/irssi) ...
Processing irssi:0.8.17 ...
Processing irssi:0.8 ...
Processing irssi:0 ...
Processing irssi:latest ...
```

**Comment by tianon** [comment]
LGTM of course :innocent:

**Comment by jfrazelle** [comment]
such official
wow future
so client

**Comment by cpuguy83** [comment]
Wait, can you trust this person?

**Comment by tianon** [comment]
Probably not, Jess is pretty sketch.  Let's revert to be sure.

**Comment by jfrazelle** [comment]
Super untrustworthy give 0 stars out of 5 would not buy again

On Friday, January 23, 2015, Tianon Gravi <notifications@github.com> wrote:

> Probably not, Jess is pretty sketch. Let's revert to be sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/official-images/pull/423#issuecomment-71260267>
> .
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Pull request merged**
