### PR TITLE
Adding 2.1.6 and 2.2.4

### PR DESCRIPTION
**Pull request by dalanmiller**

### CODE REVIEW

**Comment by stuartpb** [comment]
@dalanmiller You inadvertently inserted bogus Dockerfiles before adding these tags: https://github.com/rethinkdb/rethinkdb-dockerfiles/commit/070e882edd51f8c33579d5b5b025550512d97c4c

We should rebase that commit out and change the suggested commit hash to the rebased version before pushing this to the registry.

**Comment by dalanmiller** [comment]
Thank you for that @stuartpb, I think I was returning to the script and ran it on accident. I might add automatic `git commit` confirmation later.

**Comment by dalanmiller** [comment]
Closing this an opening new one.

**Comment by stuartpb** [comment]
> I might add automatic git commit confirmation later.

I'd say merging rethinkdb/rethinkdb-dockerfiles#24 is the better immediate solution here.

**Pull request closed without merging**
