### PR TITLE
Update iojs to v2.2.0

### PR DESCRIPTION
**Pull request by pesho**
Related: nodejs/docker-iojs#66

### CODE REVIEW

**Comment by Starefossen** [comment]
**[@rvagg writes](https://twitter.com/rvagg/status/604956690031755264):**

> Maybe hold off on @official_iojs v2.2.0, a minor change broke npm, we'll get a v2.2.1 out within the next 24 hours to rectify it.

**Comment by pesho** [comment]
Closing, will open a new PR for v2.2.1.

**Comment by pesho** [comment]
Superseded by docker-library/official-images#774

**Comment by pesho** [comment]
Superseded by docker-library/official-images#774

**Pull request closed without merging**
