### PR TITLE
consul: 1.10.2, 1.9.9 and 1.8.15

### PR DESCRIPTION
**Pull request by eculver**
New releases today.

### CODE REVIEW

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

**Comment by tianon** [comment]
Friendly ping?

Also going to cc some of the most recent previous image updaters:
@mikemorris @freddygv @rboyer @mkeeler
(since there aren't any explicit humans listed in the `Maintainers:` line and I can't ping the @hashicorp/consul group thanks to GitHub limitations :grimacing:)

**Comment by mikemorris** [comment]
Thanks for the ping @tianon, I'll try to get this cleaned up and resolved!

**Comment by mikemorris** [comment]
@tianon Migrated fully to the OCI spec labels in our source Dockerfile and pushed a commit with updated commit shas, hope that'll do it!

**Pull request merged**
