### PR TITLE
Add "windowsservercore" variants to "mongo"

### PR DESCRIPTION
**Pull request by tianon**
https://github.com/docker-library/mongo/pull/109

### CODE REVIEW

**Comment by tianon** [comment]
```diff
diff --git a/mongo_3.0-windowsservercore/Dockerfile b/mongo_3.0-windowsservercore/Dockerfile
new file mode 100644
index 0000000..00bbf15
--- /dev/null
+++ b/mongo_3.0-windowsservercore/Dockerfile
@@ -0,0 +1,48 @@
+FROM microsoft/windowsservercore
+
+SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
+
+# PATH isn't actually set in the Docker image, so we have to set it from within the container
+RUN [Environment]::SetEnvironmentVariable('PATH', 'C:\mongodb\bin;' + $env:PATH, [EnvironmentVariableTarget]::Machine);
+# doing this first to share cache across versions more aggressively
+
+ENV MONGO_VERSION 3.0.12
+ENV MONGO_DOWNLOAD_URL http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-${MONGO_VERSION}-signed.msi
+ENV MONGO_DOWNLOAD_SHA256 be537b5fdc1763bb8640ac6384a44fa787c12499cfa648338c0695c5752de18a
+
+RUN Write-Host ('Downloading {0} ...' -f $env:MONGO_DOWNLOAD_URL); \
+	(New-Object System.Net.WebClient).DownloadFile($env:MONGO_DOWNLOAD_URL, 'mongo.msi'); \
+	\
+	Write-Host ('Verifying sha256 ({0}) ...' -f $env:MONGO_DOWNLOAD_SHA256); \
+	if ((Get-FileHash mongo.msi -Algorithm sha256).Hash -ne $env:MONGO_DOWNLOAD_SHA256) { \
+		Write-Host 'FAILED!'; \
+		exit 1; \
+	}; \
+	\
+	Write-Host 'Installing ...'; \
+# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#install-mongodb-community-edition
+	Start-Process msiexec -Wait \
+		-ArgumentList @( \
+			'/i', \
+			'mongo.msi', \
+			'/quiet', \
+			'/qn', \
+			'INSTALLLOCATION=C:\mongodb', \
+			'ADDLOCAL=all' \
+		); \
+	\
+	Write-Host 'Verifying install ...'; \
+	Write-Host '  mongo --version'; mongo --version; \
+	Write-Host '  mongod --version'; mongod --version; \
+	\
+	Write-Host 'Removing ...'; \
+	Remove-Item mongo.msi -Force; \
+	\
+	Write-Host 'Complete.';
+
+VOLUME C:\\data\\db C:\\data\\configdb
+
+# TODO docker-entrypoint.ps1 ? (for "docker run <image> --flag --flag --flag")
+
+EXPOSE 27017
+CMD ["mongod"]
diff --git a/mongo_3.3-windowsservercore/Dockerfile b/mongo_3.3-windowsservercore/Dockerfile
new file mode 100644
index 0000000..0b8588f
--- /dev/null
+++ b/mongo_3.3-windowsservercore/Dockerfile
@@ -0,0 +1,48 @@
+FROM microsoft/windowsservercore
+
+SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
+
+# PATH isn't actually set in the Docker image, so we have to set it from within the container
+RUN [Environment]::SetEnvironmentVariable('PATH', 'C:\mongodb\bin;' + $env:PATH, [EnvironmentVariableTarget]::Machine);
+# doing this first to share cache across versions more aggressively
+
+ENV MONGO_VERSION 3.3.11
+ENV MONGO_DOWNLOAD_URL http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-${MONGO_VERSION}-signed.msi
+ENV MONGO_DOWNLOAD_SHA256 cea09e54b6540bfd4f6c55a058f81d96a543557eb023289cad36d577424bd079
+
+RUN Write-Host ('Downloading {0} ...' -f $env:MONGO_DOWNLOAD_URL); \
+	(New-Object System.Net.WebClient).DownloadFile($env:MONGO_DOWNLOAD_URL, 'mongo.msi'); \
+	\
+	Write-Host ('Verifying sha256 ({0}) ...' -f $env:MONGO_DOWNLOAD_SHA256); \
+	if ((Get-FileHash mongo.msi -Algorithm sha256).Hash -ne $env:MONGO_DOWNLOAD_SHA256) { \
+		Write-Host 'FAILED!'; \
+		exit 1; \
+	}; \
+	\
+	Write-Host 'Installing ...'; \
+# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#install-mongodb-community-edition
+	Start-Process msiexec -Wait \
+		-ArgumentList @( \
+			'/i', \
+			'mongo.msi', \
+			'/quiet', \
+			'/qn', \
+			'INSTALLLOCATION=C:\mongodb', \
+			'ADDLOCAL=all' \
+		); \
+	\
+	Write-Host 'Verifying install ...'; \
+	Write-Host '  mongo --version'; mongo --version; \
+	Write-Host '  mongod --version'; mongod --version; \
+	\
+	Write-Host 'Removing ...'; \
+	Remove-Item mongo.msi -Force; \
+	\
+	Write-Host 'Complete.';
+
+VOLUME C:\\data\\db C:\\data\\configdb
+
+# TODO docker-entrypoint.ps1 ? (for "docker run <image> --flag --flag --flag")
+
+EXPOSE 27017
+CMD ["mongod"]
diff --git a/mongo_windowsservercore/Dockerfile b/mongo_windowsservercore/Dockerfile
new file mode 100644
index 0000000..6e11cdd
--- /dev/null
+++ b/mongo_windowsservercore/Dockerfile
@@ -0,0 +1,48 @@
+FROM microsoft/windowsservercore
+
+SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
+
+# PATH isn't actually set in the Docker image, so we have to set it from within the container
+RUN [Environment]::SetEnvironmentVariable('PATH', 'C:\mongodb\bin;' + $env:PATH, [EnvironmentVariableTarget]::Machine);
+# doing this first to share cache across versions more aggressively
+
+ENV MONGO_VERSION 3.2.9
+ENV MONGO_DOWNLOAD_URL http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-${MONGO_VERSION}-signed.msi
+ENV MONGO_DOWNLOAD_SHA256 348db5060e5c821acbd170331e806ea0233626837e6ea30e7d0e8dc72cc2e41f
+
+RUN Write-Host ('Downloading {0} ...' -f $env:MONGO_DOWNLOAD_URL); \
+	(New-Object System.Net.WebClient).DownloadFile($env:MONGO_DOWNLOAD_URL, 'mongo.msi'); \
+	\
+	Write-Host ('Verifying sha256 ({0}) ...' -f $env:MONGO_DOWNLOAD_SHA256); \
+	if ((Get-FileHash mongo.msi -Algorithm sha256).Hash -ne $env:MONGO_DOWNLOAD_SHA256) { \
+		Write-Host 'FAILED!'; \
+		exit 1; \
+	}; \
+	\
+	Write-Host 'Installing ...'; \
+# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#install-mongodb-community-edition
+	Start-Process msiexec -Wait \
+		-ArgumentList @( \
+			'/i', \
+			'mongo.msi', \
+			'/quiet', \
+			'/qn', \
+			'INSTALLLOCATION=C:\mongodb', \
+			'ADDLOCAL=all' \
+		); \
+	\
+	Write-Host 'Verifying install ...'; \
+	Write-Host '  mongo --version'; mongo --version; \
+	Write-Host '  mongod --version'; mongod --version; \
+	\
+	Write-Host 'Removing ...'; \
+	Remove-Item mongo.msi -Force; \
+	\
+	Write-Host 'Complete.';
+
+VOLUME C:\\data\\db C:\\data\\configdb
+
+# TODO docker-entrypoint.ps1 ? (for "docker run <image> --flag --flag --flag")
+
+EXPOSE 27017
+CMD ["mongod"]
```

**Comment by tianon** [comment]
```console
$ bashbrew build --namespace test https://github.com/infosiftr/stackbrew/raw/52f052e57eb7c5d0e70296fdbb680aef75635f53/library/mongo
skipping "mongo:2.6.12" (due to exclusive constraints)
skipping "mongo:3.0.12" (due to exclusive constraints)
Building bashbrew/cache:e2b7760e18718db5f3cad5d8aff3c171f69a1cdb9e2135f62364b5734e002adb (mongo:3.0.12-windowsservercore)
Tagging test/mongo:3.0.12-windowsservercore
Tagging test/mongo:3.0-windowsservercore
skipping "mongo:3.2.9" (due to exclusive constraints)
Building bashbrew/cache:b928ee41597f875449cf9b048372076da018d6d3946d7ebfd505072382394538 (mongo:3.2.9-windowsservercore)
Tagging test/mongo:3.2.9-windowsservercore
Tagging test/mongo:3.2-windowsservercore
Tagging test/mongo:3-windowsservercore
Tagging test/mongo:windowsservercore
skipping "mongo:3.3.11" (due to exclusive constraints)
Building bashbrew/cache:c0433b3f39abc8c0d017b8224cdd102416588e925877acfc3c699b6cd0565f7a (mongo:3.3.11-windowsservercore)
Tagging test/mongo:3.3.11-windowsservercore
Tagging test/mongo:3.3-windowsservercore
```

**Comment by tianon** [comment]
I was going to manually run the `mongo-basics` test against one of these built images, but `--link` doesn't work with Windows containers. :innocent:

```console
$ ./test/tests/mongo-basics/run.sh test/mongo:3.0.12-windowsservercore && echo pass || echo fail
.........mongod failed to accept connections in a reasonable amount of time!
+ docker logs 6dcb650806efc97b623900ef0e52741ac9587769bb8788692c9ba9d06887813f
2016-08-17T23:56:33.589+0000 I CONTROL  [initandlisten] MongoDB starting : pid=6292 port=27017 dbpath=C:\data\db\ 64-bit host=WIN-R96HSPNU3PT
2016-08-17T23:56:33.590+0000 I CONTROL  [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
2016-08-17T23:56:33.619+0000 I CONTROL  [initandlisten] db version v3.0.12
2016-08-17T23:56:33.619+0000 I CONTROL  [initandlisten] git version: 33934938e0e95d534cebbaff656cde916b9c3573
2016-08-17T23:56:33.627+0000 I CONTROL  [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1') BOOST_LIB_VERSION=1_49
2016-08-17T23:56:33.627+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2016-08-17T23:56:33.627+0000 I CONTROL  [initandlisten] options: {}
2016-08-17T23:56:33.640+0000 I JOURNAL  [initandlisten] journal dir=C:\data\db\journal
2016-08-17T23:56:33.643+0000 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2016-08-17T23:56:33.813+0000 I JOURNAL  [durability] Durability thread started
2016-08-17T23:56:33.830+0000 I JOURNAL  [journal writer] Journal writer thread started
2016-08-17T23:56:34.009+0000 I INDEX    [initandlisten] allocating new ns file C:\data\db\local.ns, filling with zeroes...
2016-08-17T23:56:34.407+0000 I STORAGE  [FileAllocator] allocating new datafile C:\data\db\local.0, filling with zeroes...
2016-08-17T23:56:34.407+0000 I STORAGE  [FileAllocator] creating directory C:\data\db\_tmp
2016-08-17T23:56:34.531+0000 I STORAGE  [FileAllocator] done allocating datafile C:\data\db\local.0, size: 64MB,  took 0.022 secs
2016-08-17T23:56:34.541+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
MongoDB shell version: 3.0.12
connecting to: mongo:27017/test
2016-08-17T23:58:50.206+0000 I NETWORK  getaddrinfo("mongo") failed: errno:11001 No such host is known.
2016-08-17T23:58:50.208+0000 E QUERY    Error: couldn't initialize connection to host mongo, address is invalid
    at connect (src/mongo/shell/mongo.js:181:14)
    at (connect):1:6 at src/mongo/shell/mongo.js:181
exception: connect failed
fail
```

**Comment by tianon** [comment]
I can interact with the running database by using `docker exec -it <container> mongo localhost/test`, but I can't seem to figure out how to get port mapping working (and both `--link` and `docker network` are non-functional for Windows as far as I can tell).

**Comment by tianon** [comment]
More concretely, I run the `mongod` like this:
```console
$ docker run -d --name mongo -p 27017:27017 test/mongo:windowsservercore             8a9473c28040e10f7c71f31887e1614a39f9d58174e7c34e6cc4abfb0d04384a
```
The client then works like so: (using `winpty` since I'm in Git Bash)
```console
$ winpty docker run -it --rm test/mongo:windowsservercore mongo $(docker inspect -f '{{ .NetworkSettings.Networks.nat.IPAddress }}' mongo)/test
MongoDB shell version v3.3.11
connecting to: 172.22.105.244/test
MongoDB server version: 3.3.11
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
2016-08-18T16:25:13.874+0000 I STORAGE  [main] In File::open(), CreateFileW for '' failed with The system cannot find the path specified
.
Server has startup warnings:
2016-08-18T16:25:00.286+0000 I CONTROL  [initandlisten]
2016-08-18T16:25:00.286+0000 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.3.11) of MongoDB.
2016-08-18T16:25:00.287+0000 I CONTROL  [initandlisten] **       Not recommended for production.
2016-08-18T16:25:00.287+0000 I CONTROL  [initandlisten]
2016-08-18T16:25:00.287+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2016-08-18T16:25:00.287+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2016-08-18T16:25:00.287+0000 I CONTROL  [initandlisten]
>
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
