### PR TITLE
Add dart

### PR DESCRIPTION
**Pull request by athomas**
See also https://github.com/docker-library/docs/pull/1944 for the docs.

---

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream?
    - https://github.com/dart-lang
-	[x] does it fit into one of the common categories? ("service", "language stack", "base distribution")
    - language stack
-	[x] is it reasonably popular, or does it solve a particular use case well?
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/pull/1944
-	[x] official-images maintainer dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ official-images maintainer dockerization review?
-	[x] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[x] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by yosifkit** [comment]
Is there a way the list of hard-linked libraries could be generated from `ldd` or something? I'd hate to miss one on a new release of dart and it will definitely be necessary once another architecture like `arm64v8` is added.  We don't allow separate Dockerfiles per architecture except for base images like Debian where they are `FROM scratch` and add a compressed `tar` file.

The `ARCH` and `PLATFORM` environment variables are not acceptable. These are both inherent to an image (part of the platform object in the OCI image index). To get the architecture within the image, `dpkg --print-architecture` is the most accurate. OS platform can just be hard-coded, since scraping "linux" from `/etc/os-release` would be longer than just using it and Linux-specific code anyway.

`CHANNEL` is rather generic for an environment variable name. This will leak down to users of the image, so something more specific like `DART_CHANNEL` might be desirable.

**Comment by tianon** [comment]
To clarify, we're not suggesting you need to go multi-architecture right off the bat (although I think it would be really low effort), but that embedding `ARCH` and `PLATFORM` directly in the one place they're each used for now is a more acceptable intermediate step towards that, for very similar reasons to why we're suggesting that `CHANNEL` is a bit generic and you probably want to either embed that one too or choose a more descriptive name like `DART_CHANNEL`.

(I can't say for sure, but I imagine @yosifkit is also having the same :raised_eyebrow: moment I did after reading https://dart.dev/get-dart#linux which clearly claims "Supported architectures: x64, ia32, arm, arm64" but the documented channels for consumption and even this PR are still amd64-only.)

**Comment by subfuzion** [comment]
Thanks @tianon and @yosifkit, I've got a draft PR that we're iterating on [here](https://github.com/dart-lang/dart-docker/pull/21) to address your concerns other than multi-arch support. Will ping when we're ready for another look. Given our timeline for next week, we're currently focused on getting the Debian arch pushed for now and plan to iterate on other architectures immediately after.

**Comment by subfuzion** [comment]
@tianon @yosifkit PTAL now, thanks!

**Review by yosifkit — APPROVED** [review]

**Comment by subfuzion** [comment]
Speaking on behalf of our team, thank you for your guidance and helping land this so quickly! You're all awesome and we're grateful. ❤️

**Pull request merged**
