### PR TITLE
Revert official docker kapacitor to 1.5.7

### PR DESCRIPTION
**Pull request by docmerlin**
We found a rather large bug in 1.5.8 and we want to revert the docker kapacitor downloads to 1.5.7

### CODE REVIEW

**Comment by tianon** [comment]
Looks like this got a botched rebase -- I'd suggest trying again with something like `git pull --rebase https://github.com/docker-library/official-images.git master` and force-pushing the result (which _should_ get rid of the errant commits here).

Alternatively, enable the PR setting for allowing maintainers to modify your PR directly and I can handle the rebase for you.

**Comment by tianon** [comment]
Friendly ping @docmerlin @jsternberg

**Comment by tianon** [comment]
:pray: @docmerlin @jsternberg

**Comment by docmerlin** [comment]
@tianon thanks for the ping!  I'm just going to close this one, and open a new one, we ended up already releasing 1.5.9, so this is out of date anyway.

**Pull request closed without merging**
