### PR TITLE
caddy: v2.4.3 release

### PR DESCRIPTION
**Pull request by hairyhenderson**
https://github.com/caddyserver/caddy/releases/tag/v2.4.3

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Hmm... CI's failing with:

```
Invalid 'FROM' + 'Architectures' combinations detected:

 - caddy:2.3.0-builder-alpine (FROM golang:1.15-alpine3.12) -- completely unsupported base!
```

My instinct is that the best way to work around this is simply to stop building the 2.3.0 image. @mholt what do you think?

**Comment by mholt** [comment]
Sure. I don't know what that means, but we have no need for 2.3.0 anymore.

**Comment by hairyhenderson** [comment]
> I don't know what that means

I _think_ it's because of the `alpine-3.12` flavour - with 3.14 out now it's probably explicitly deprecated. But that's just a gut feeling...

**Comment by yosifkit** [comment]
> > I don't know what that means
> 
> I _think_ it's because of the `alpine-3.12` flavour - with 3.14 out now it's probably explicitly deprecated. But that's just a gut feeling...

Correct, for our language images, we try to limit the number of OS versions they are based upon (usually max of two per distribution). So when a new OS release comes out, the older one is usually dropped.

> we have no need for 2.3.0 anymore

Feel free to drop versions that you no longer support. :+1:  That way they'll also drop out of the "Supported Tags" list that appears of the Docker Hub (https://github.com/docker-library/docs/tree/7d084e9d284243ad099a90ef2fbda09c9ad1e505/caddy#supported-tags-and-respective-dockerfile-links).

**Comment by hairyhenderson** [comment]
_Finally_ found some time to get back to this 😓

Ok - I've removed the `:2.3.0` tag so hopefully it should go through now 😉

**Comment by mholt** [comment]
You're awesome @hairyhenderson , thanks so much.

**Pull request merged**
