### PR TITLE
caddy: v2.8.1 release

### PR DESCRIPTION
**Pull request by francislavoie**
https://github.com/caddyserver/caddy/releases/tag/v2.8.1

### CODE REVIEW

**Review by LaurentGoderre — APPROVED** [review]

**Comment by francislavoie** [comment]
Oh wow - just noticed you're from Ottawa @LaurentGoderre :grinning: both @hairyhenderson and I are as well!

**Comment by tianon** [comment]
Perhaps y'all can get together over a pint of maple syrup :eyes: :maple_leaf: :heart:

**Review by tianon — APPROVED** [review]

**Comment by francislavoie** [comment]
@tianon it seems like the `amd64` and `arm64` builds are lagging behind by quite a bit. Is there anything we can do to increase priority on those or something? Every release, we keep getting complaints from people because they tend to take many hours to get their turn in the build queue.

**Comment by whalelines** [comment]
They all appear to be available now. We are investigating ways to make the build system more scalable, but the reality is that some updates trigger thousands of builds and it just takes time to work through them all.

**Pull request merged**
