### PR TITLE
library/perl: Add out-of-the-box SSL support and App::cpm

### PR DESCRIPTION
**Pull request by zakame**
- https://github.com/Perl/docker-perl/pull/118
- https://github.com/Perl/docker-perl/pull/119

### CODE REVIEW

**Comment by tianon** [comment]
Is there a checksum of some kind published for `cpm` releases?
(or would it be too much trouble to add calculation of one to your `Dockerfile`-generation scripts?)

**Comment by zakame** [comment]
@tianon I think that's worth raising to @skaji - the `cpm` we're getting directly from the repo is the fatpacked version, produced as part of the [post-release](https://github.com/skaji/cpm/blob/61df877db9fd6f30f281e51df43a44bf555676ee/dist.ini#L45) that happens right after CPAN upload.

**Comment by skaji** [comment]
I don't prepare checksums.

If you are care about integrity,
please calculate the checksum of cpm by yourself, and check it in docker build.

**Comment by tianon** [comment]
I'm not sure _how_, but somehow this made `cpanm` disappear??

```console
$ docker run --rm --pull=always perl:5.32-slim-buster cpanm --help
5.32-slim-buster: Pulling from library/perl
Digest: sha256:28fdf8fc469b15cf10aece7b6f293527ddd9ffb78fc3a3285c0faf49edfc15c5
Status: Image is up to date for perl:5.32-slim-buster
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "cpanm": executable file not found in $PATH: unknown.
$ docker run --rm --pull=always perl:5.32-slim-bullseye cpanm --help
5.32-slim-bullseye: Pulling from library/perl
Digest: sha256:e9ed5c445c2aee298689f185215dc09d9d7d8ef0b255529c1ccec81a1950272c
Status: Image is up to date for perl:5.32-slim-bullseye
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "cpanm": executable file not found in $PATH: unknown.
```

(I'm very confused)

**Comment by miyagawa** [comment]
yes, this broke my CI as well:

image

**Comment by skaji** [comment]
https://github.com/Perl/docker-perl/blob/master/5.036.000-slim-bullseye/Dockerfile#L46-L56
```
 && cd /usr/local/bin \
...
&& rm -fr ./cpanm
```

So did we remove cpanm?

**Comment by tianon** [comment]
Ahhhhhh, the new `cd` *did* cause trouble.  @zakame we should probably adjust all the paths to `cpm` to be explicit `/usr/local/bin/cpm` and ditch the `cd`, right?

**Comment by miyagawa** [comment]
https://github.com/Perl/docker-perl/pull/119/files

This patch added `cd /usr/local/bin &&` and that `rm -fr ./cpanm` used to remove `/usr/src/cpanm` and now it removes `/usr/local/bin/cpanm`. 🤦

**Comment by tianon** [comment]
FWIW, https://github.com/docker-library/repo-info/tree/f67fee8f4aa8dd1ae8651418d3b3a32601b56de9/repos/perl/remote has digests for each tag from right before this change -- I'm working on a PR to docker-perl now :+1:

**Comment by tianon** [comment]
PR up at https://github.com/Perl/docker-perl/pull/121 :eyes:

**Comment by tianon** [comment]
Given it's already the weekend for involved folks, I've put up https://github.com/docker-library/official-images/pull/12731 to revert _just_ the `cpm` half of this (leaving the SSL addition) so we can get `perl` fixed before the long US weekend :see_no_evil: :heart:

**Comment by tianon** [comment]
Fixed properly via https://github.com/docker-library/official-images/pull/12732 -- builds should be in progress shortly. :+1: :heart: :tada:

**Pull request merged**
