### PR TITLE
Add debian based Amazon Corretto 8 image

### PR DESCRIPTION
**Pull request by duncaan**
This includes the following changes:

- Add debian based image to Amazon Corretto repository: https://github.com/corretto/corretto-8-docker/pull/35

### CODE REVIEW

**Comment by yosifkit** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 19b1f69..fcb19e6 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,3 +1,5 @@
+amazoncorretto:8u232-debian @ amd64
+amazoncorretto:8u232-debian @ arm64v8
 amazoncorretto:11-al2-full @ amd64
 amazoncorretto:11-al2-full @ arm64v8
 amazoncorretto:latest @ amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index e942612..dc32156 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -1,6 +1,8 @@
 amazoncorretto:8
 amazoncorretto:8u232
+amazoncorretto:8u232-debian
 amazoncorretto:8-al2-full
+amazoncorretto:8-debian
 amazoncorretto:11
 amazoncorretto:11-al2-full
 amazoncorretto:11.0.5
diff --git a/amazoncorretto_latest/Dockerfile b/amazoncorretto_8u232-debian/Dockerfile
similarity index 34%
copy from amazoncorretto_latest/Dockerfile
copy to amazoncorretto_8u232-debian/Dockerfile
index 37729c8..7d75588 100644
--- a/amazoncorretto_latest/Dockerfile
+++ b/amazoncorretto_8u232-debian/Dockerfile
@@ -1,15 +1,16 @@
-FROM amazonlinux:2
+FROM debian:buster-slim
 
 # x86_64 args
-ARG rpm_x64=java-1.8.0-amazon-corretto-devel-1.8.0_232.b09-1.x86_64.rpm
+ARG deb_x64=java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
 ARG path_x64=https://d3pxv6yz143wms.cloudfront.net/8.232.09.1
 ARG key_x64=E8EB406377AD2B9E9A4765D19CB3BC6FF6C9FC19
 
 # aarch64 args
-ARG rpm_aarch64=java-1.8.0-amazon-corretto-devel-1.8.0_232.b09-1.aarch64.rpm
+ARG deb_aarch64=java-1.8.0-amazon-corretto-jdk_8.232.09-1_arm64.deb
 ARG path_aarch64=https://d3pxv6yz143wms.cloudfront.net/8.232.09.1
 ARG key_aarch64=E8EB406377AD2B9E9A4765D19CB3BC6FF6C9FC19
-# In addition to installing the RPM, we also install
+
+# In addition to installing the DEB, we also install
 # fontconfig. The folks who manage the docker hub's
 # official image library have found that font management
 # is a common usecase, and painpoint, and have
@@ -18,23 +19,36 @@ ARG key_aarch64=E8EB406377AD2B9E9A4765D19CB3BC6FF6C9FC19
 # See:
 #  https://github.com/docker-library/official-images/blob/master/test/tests/java-uimanager-font/container.java
 
-
 RUN set -eux; \
-    case "$(uname -p)" in \
-        x86_64) rpm=$rpm_x64; path=$path_x64; key=$key_x64 ;; \
-        aarch64) rpm=$rpm_aarch64; path=$path_aarch64; key=$key_aarch64 ;; \
-        *) echo >&2 "Unsupported architecture $(uname -p)."; exit 1 ;; \
+	dpkgArch="$(dpkg --print-architecture)"; \
+	case "$dpkgArch" in \
+			amd64) deb=$deb_x64; path=$path_x64; key=$key_x64 ;; \
+			arm64) deb=$deb_aarch64; path=$path_aarch64; key=$key_aarch64 ;; \
+			*) echo >&2 "Unsupported architecture $dpkgArch."; exit 1 ;; \
 	esac; \
 	\
-    curl -O $path/$rpm \
-    && export GNUPGHOME="$(mktemp -d)" \
-    && gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys $key \
-    && gpg --armor --export $key > corretto.asc \
-    && rpm --import corretto.asc \
-    && rpm -K $rpm \
-    && rpm -i $rpm \
-    && rm -r $GNUPGHOME corretto.asc $rpm \
-    && yum install -y fontconfig \
-    && yum clean all
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+# utilities for keeping Debian and OpenJDK CA certificates in sync
+		ca-certificates fontconfig java-common p11-kit \
+	; \
+	rm -rf /var/lib/apt/lists/*; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		curl \
+		dirmngr \
+		gnupg; \
+	rm -rf /var/lib/apt/lists/*; \
+	curl -O $path/$deb; \
+	export GNUPGHOME="$(mktemp -d)"; \
+  gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys $key; \
+	gpg --armor --export $key > corretto.asc; \
+	apt-key add corretto.asc; \
+	if [ ! -d /usr/share/man/man1 ]; then \
+		mkdir -p /usr/share/man/man1; \
+	fi; \
+	dpkg --install $deb; \
+	rm -rf $GNUPGHOME corretto.asc $deb; \
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false curl dirmngr gnupg
 
 ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
```

</details>

**Comment by tianon** [comment]
cc image maintainers @corretto @jguo11 @ziyiluo @alvdavi

**Comment by alvdavi** [comment]
Hi,

For now, the only official images for Corretto will be the AL2 based ones. We are not planning to make contrib dockerfiles like this one official images.

Thanks, but please do not merge.

**Comment by tianon** [comment]
Fair enough, thanks for confirming @alvdavi!

**Pull request closed without merging**
