### PR TITLE
Update to JRuby commit that includes make

### PR DESCRIPTION
**Pull request by headius**
make is needed for several dummy gems that do not need to build an extension but still attempt to run a Makefile.

See https://github.com/jruby/docker-jruby/issues/81

### CODE REVIEW

**Comment by headius** [comment]
Looks like a new Bundler version, released just before the holidays, no longer works on JRuby 9.2. I will look into this.

**Comment by headius** [comment]
We are opting to remove the 9.2 images. JRuby 9.2 has not been officially supported for some time, and with new Bundler versions not working anymore it seems like a good time to drop it from the images.

**Comment by headius** [comment]
Ok now the failures seem to be some other service going down, a service used to verify the images. I do not see how this could have been related to adding `make`, and in the previous commit these jobs were sucessful.

**Comment by headius** [comment]
Repushed last commit and the down service (appears to have been rubygems.org) is now working. Ready to go!

**Comment by tianon** [comment]
Makes sense, thanks for chasing it!  I'll include my standard copy-pasta here to hopefully help ease your mind on the removal:

> Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

:+1:

**Pull request merged**
