### PR TITLE
SonarQube: add tag `alpine`

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by tianon** [comment]
I'd prefer that this new tag be simply `:alpine` rather than `:latest-alpine`, and I've outlined my reasoning a bit over in #2009. :+1:

**Comment by Godin** [comment]
@tianon okay, changed on `alpine`.

What about existing tags such as `lts-alpine` - should they be changed on `alpine-lts` ?

**Comment by yosifkit** [comment]
The current ordering is fine and most of the images are fairly consistent with a `$version-$distro` (ie, most specific information to least specific) ordering.

LGTM

**Comment by Godin** [comment]
@yosifkit cool, thanks for info

**Comment by Godin** [comment]
Just wondering what prevents merge since PR was updated with requested change?

**Comment by tianon** [comment]
Sorry about that @Godin!

LGTM :+1:

**Comment by Godin** [comment]
@tianon no pb, thx!

**Pull request merged**
