### PR TITLE
Update yourls

### PR DESCRIPTION
**Pull request by LeoColomb**
Changes:

- https://github.com/YOURLS/docker-yourls/commit/06cd297: Bump actions/checkout from v2.3.3 to v2.3.4
- https://github.com/YOURLS/docker-yourls/commit/faa119e: Bump actions/checkout from v2.3.2 to v2.3.3
- https://github.com/YOURLS/docker-yourls/commit/22ee2ef: Bump actions/checkout from v2.3.1 to v2.3.2
- https://github.com/YOURLS/docker-yourls/commit/45b26ce: Update to 1.7.9
- https://github.com/YOURLS/docker-yourls/commit/e0b94b1: Allow using docker secrets for env variables (https://github.com/YOURLS/docker-yourls/pull/57)
- https://github.com/YOURLS/docker-yourls/commit/a8e13b5: Bump actions/checkout from v2.3.0 to v2.3.1
- https://github.com/YOURLS/docker-yourls/commit/1ab4077: Bump actions/checkout from v2.2.0 to v2.3.0
- https://github.com/YOURLS/docker-yourls/commit/de05e1f: Update dependabot.yml
- https://github.com/YOURLS/docker-yourls/commit/06cf288: Bump actions/checkout from v1 to v2.2.0
- https://github.com/YOURLS/docker-yourls/commit/e002ec4: Create Dependabot config file
- https://github.com/YOURLS/docker-yourls/commit/fe07662: update PHP version and ran update.sh

### CODE REVIEW

**Comment by tianon** [comment]
Wouldn't it be slightly more secure to implement `file_env` in PHP directly in https://github.com/YOURLS/docker-yourls/blob/06cd297e39e3ccdded690f52364693c3deaece94/config-docker.php?  Maybe slightly less efficient, but would ensure the secrets aren't ever stored in environment variables (which are much more widely accessible than being in the process memory space like they would be once they're loaded into PHP).

**Comment by tianon** [comment]
See https://github.com/docker-library/wordpress/pull/557 for where I'm finally trying to do exactly that for WordPress (but you've got the benefit of not worrying about backwards compatibility here).

**Comment by LeoColomb** [comment]
@tianon Sorry for my very (very very) late answer.
I've managed to follow your recommendation, thanks for that. Everything should be clear on this point.

Could we just wait for YOURLS v1.8.1 before merging? Got a little issue on 1.8, already fixed but we need to release a new version. I'll ping you when done.

**Comment by LeoColomb** [comment]
@yosifkit Thanks, but I would have appreciated a follow-up to my previous comment...

**Comment by tianon** [comment]
Oops, looks like he got carried away while reviewing the set of pending today, sorry! 😩  Would you like to revert for now, or let it ride?

(Next time I'd suggest marking the PR as a draft or temporarily closing it if you don't want it merged yet 👍)

**Comment by LeoColomb** [comment]
> Would you like to revert for now, or let it ride?

Naa, let it ride 🙂 

> I'd suggest marking the PR as a draft

Ah, good one indeed, forgot about this.

**Comment by yosifkit** [comment]
Sorry, :bow: I saw the new commit & diff comment and just assumed it was the update :disappointed: :facepalm:

**Pull request merged**
