### PR TITLE
Added static-file-server to official images.

### PR DESCRIPTION
**Pull request by halverneus**
From the best I can tell, this static-file-server is the most popular single-purpose static file service on Docker Hub (>216,000 downloads and averaging >2,000 downloads per day). It is a small, easily configurable image for serving content over HTTP or HTTPS.

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[ ] associated with or contacted upstream?
-	[ ] does it fit into one of the common categories? ("service", "language stack", "base distribution")
-	[ ] is it reasonably popular, or does it solve a particular use case well?
-	[ ] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[ ] if `FROM scratch`, tarballs only exist in a single commit within the associated history?
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tianon** [comment]
Just to clarify, what makes this different from something like, say, NGINX or Apache's HTTPd?

> It is a small, easily configurable image for serving content over HTTP or HTTPS.

To compare, `nginx:alpine` is ~8MB on-disk (and NGINX has a large community of users / configuration examples available online and a long track record for being solid, not to mention a lot of features like websocket proxying as well), where this image appears to be ~4MB on-disk, which by itself doesn't seem like a particularly compelling difference IMO.

**Comment by halverneus** [comment]
I don't disagree that it doesn't provide any feature that Nginx or Apache can already provide. The appeal for most users is the simplicity. It does one thing and does it well. This is similar to Traefik, which also provides no features not covered by Nginx or Apache. There are many applications that only need a static file server, but the barrier of entry for those without adminstration experience is a bit high.
I wouldn't have considered adding this to the official library if not for its popularity, despite a complete lack of promotion. Because of the user base, the application is 100% unit and functionally tested before every release and makes every effort to follow all best practices.
Having said that, I have no disagreement with your assessment. I just think it exemplifies how simple it should be to use a Docker service and this is a niche that I believe would encourage the use of Docker for those just starting out.
If you disagree, I will withdraw my pull request without complaint.

**Comment by tianon** [comment]
I want to be totally clear that I think this project is neat and I do not in any way want to discourage you from working on it (especially if it suits a need you have). :heart:

However, in reviewing the project, I'm afraid I don't think it fits the criteria of this program -- it seems to have a small (but growing!) popularity with a set of Docker users, but doesn't have name recognition (nor a name that _can_ really get name recognition, a Google search for "static file server" gives millions of results :smile:), and doesn't have a very broad base of contributors (of either code or issues) on GitHub yet either.

Given also that we have both NGINX and Apache's HTTPd which can both serve this use case out-of-the-box (and `nginx:alpine` is roughly the same image size), I'm inclined to suggest that perhaps we can revisit this much further in your project's future when it's gained a bit more maturity and traction/vocal userbase?

**Comment by halverneus** [comment]
That is completely fair and I'm in no way discouraged. Thank you for your consideration!

**Pull request closed without merging**
