### PR TITLE
Bump Traefik to v2.4.0

### PR DESCRIPTION
**Pull request by ldez**
Hello,

This PR updates Traefik to [v2.4.0](https://github.com/traefik/traefik/releases/tag/v2.4.0).

/cc @kevinpollet @rtribotte @SantoDE @jbdoumenjou

Cheers

### CODE REVIEW

**Review by kevinpollet — APPROVED** [review]
LGTM

**Review by SantoDE — APPROVED** [review]
LGTM

**Review by rtribotte — APPROVED** [review]
LGTM

**Comment by yosifkit** [comment]
Welcome new maintainer @kevinpollet! :smile_cat: 

And thanks to @vdemeester for your previous work :+1: :heart:

**Pull request merged**
