### PR TITLE
qodana: add official Docker images

### PR DESCRIPTION
**Pull request by tiulpin**
# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream?
-	[ ] available under [an OSI-approved license](https://opensource.org/licenses) yes, Dockerfiles are available https://github.com/JetBrains/qodana-docker/blob/main/LICENSE
-	[x] does it fit into one of the common categories? ("service")
-	[x] is it reasonably popular, or does it solve a particular use case well? Yes, https://jetbrains.com/qodana is about to be released this year
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long) https://github.com/docker-library/docs/pull/2297
-	[ ] official-images maintainer dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ official-images maintainer dockerization review?
-	[x] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[x] if `FROM scratch`, tarballs only exist in a single commit within the associated history?
-	[x] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tiulpin** [comment]
cc @tianon @yosifkit for the review

**Comment by tiulpin** [comment]
Thanks for approving the workflow, going to look through the tests

**Comment by tiulpin** [comment]
I made a fork of this repo to run tests, fixed every problem found. Also, added a new external pin (on .NET Core).

**Comment by yosifkit** [comment]
Thank you so much for the contribution!

Unfortunately, as far as I can tell, Qodana is [distributed under](https://github.com/JetBrains/Qodana/discussions/101) the "Qodana Community Linters Agreement" and the "Jetbrains EAP User Agreement", neither of which are [OSI-approved](https://opensource.org/licenses), and as such does not currently meet the criteria for the Official Images program. :sweat_smile:

If you would like to discuss further, I would suggest reaching out to [partners@docker.com](mailto:partners@docker.com) or using the contact form on https://www.docker.com/partners/programs/. :heart:

**Comment by yosifkit** [comment]
Closing given https://github.com/docker-library/official-images/pull/14248#issuecomment-1472791159.

**Pull request closed without merging**
