### PR TITLE
[nats] Release v2.3.0

### PR DESCRIPTION
**Pull request by kozlovic**
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.3.0)

Doc PR: https://github.com/docker-library/docs/pull/1981

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by yosifkit** [comment]
Apologies for the delay, I am hesitant to merge this since our servers have been unable to build Alpine 3.14 based images and we're still working on that (https://github.com/docker-library/official-images/pull/10379#issuecomment-863396878).

If you don't mind the Alpine (and `scratch`) images failing for a bit, we can go ahead and merge.

**Comment by kozlovic** [comment]
@yosifkit Let me check with the rest of my team to see if we should downgrade back to alpine 3.13? Any idea of how long it would take to sort this out?

**Comment by kozlovic** [comment]
@yosifkit In order to decide if I resubmit PR sticking with Alpine 3.13, it would help if I could get an idea on how long it would take to resolve the issue with Alpine 3.14 (and "I don't know" IS a valid answer ;-)). 

As a side note, I am able to build the alpine docker image of NATS, but not sure if the issue is related to your build process or with any image depending on alpine 3.14:
```
$ pwd
nats-docker/2.3.0/alpine3.14
$ docker build -t nats .
[+] Building 1.4s (9/9) FINISHED                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 1.52kB                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/alpine:3.14                                                                                 1.3s
 => [1/4] FROM docker.io/library/alpine:3.14@sha256:234cb88d3020898631af0ccbbcca9a66ae7306ecd30c9720690858c1b007d2a0                           0.0s
 => [internal] load build context                                                                                                              0.0s
 => => transferring context: 1.11kB                                                                                                            0.0s
 => CACHED [2/4] RUN set -eux;  apkArch="$(apk --print-arch)";  case "$apkArch" in   aarch64) natsArch='arm64'; sha256='139521edba99389436c95  0.0s
 => CACHED [3/4] COPY nats-server.conf /etc/nats/nats-server.conf                                                                              0.0s
 => CACHED [4/4] COPY docker-entrypoint.sh /usr/local/bin                                                                                      0.0s
 => exporting to image                                                                                                                         0.0s
 => => exporting layers                                                                                                                        0.0s
 => => writing image sha256:76498d6186a7f6f32174c1769bed31a65e9c119edee924d79afc605370f7173d                                                   0.0s
 => => naming to docker.io/library/nats                                                                                                        0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
$ docker run --rm -ti -p 4222:4222 nats
[1] 2021/06/24 15:02:57.939345 [INF] Starting nats-server
[1] 2021/06/24 15:02:57.939390 [INF]   Version:  2.3.0
[1] 2021/06/24 15:02:57.940264 [INF]   Git:      [56a144a]
[1] 2021/06/24 15:02:57.940274 [INF]   Name:     NBHVFFNDWHWTTJJYLZS2LS7DS645HWT2UZ2A6UQE5SXDRNC2FINPPF2X
[1] 2021/06/24 15:02:57.940284 [INF]   ID:       NBHVFFNDWHWTTJJYLZS2LS7DS645HWT2UZ2A6UQE5SXDRNC2FINPPF2X
[1] 2021/06/24 15:02:57.940292 [INF] Using configuration file: /etc/nats/nats-server.conf
[1] 2021/06/24 15:02:57.940973 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2021/06/24 15:02:57.941043 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2021/06/24 15:02:57.941238 [INF] Server is ready
[1] 2021/06/24 15:02:57.941268 [INF] Cluster name is SOME3ZAj10Agf9wD5mX6DL
[1] 2021/06/24 15:02:57.941277 [WRN] Cluster name was dynamically generated, consider setting one
[1] 2021/06/24 15:02:57.941321 [INF] Listening for route connections on 0.0.0.0:6222
```

**Comment by yosifkit** [comment]
I'm not entirely certain when the builders will be fixed; I'm hopeful that we can get it done before this weekend.

Yeah, I can build locally as well, but our builder servers need an updated Docker in order to get https://github.com/opencontainers/runc/pull/2750. Unfortunately we don't just use the binaries released by Docker since we have more architectures than they release for and we want them all to be using the same process to install updates.

**Comment by kozlovic** [comment]
@yosifkit Thank you for the update. I am going to downgrade to alpine 3.13 and update this PR if you don't mind. We have released yesterday and users are already asking about the docker image ;-)

PS: let me know if it is better to close this PR and open a new one.

**Comment by yosifkit** [comment]
Updating this PR is great. Use a force push if you like.

**Comment by kozlovic** [comment]
@yosifkit Done!

**Comment by kozlovic** [comment]
@yosifkit We are going to do a v2.3.1 release today and wanted to know if the issue with Alpine 3.14 is resolved or if we should stick to Alpine 3.13 for now.

**Comment by yosifkit** [comment]
Builders are updated, so it is fixed now!

**Pull request merged**
