### PR TITLE
Add tests for NextCloud

### PR DESCRIPTION
**Pull request by J0WI**
Follow up of #5834
cc @tilosp @tianon

Once again this is inspired by the WordPress image :innocent:

### CODE REVIEW

**Comment by tilosp** [comment]
looks like this makes ci unstable. take a look at https://travis-ci.org/nextcloud/docker/builds/526845666

i am not sure why this happens, maybe it's taking to long to start up.

**Comment by J0WI** [comment]
The tests are actually right. I can reproduce the issue locally using the i386 images. Before I have only tested amd64.

**Comment by J0WI** [comment]
This is actually an issue in the `i386/php:7.3-apache` image: https://github.com/docker-library/php/issues/822

**Comment by J0WI** [comment]
@tianon thanks for merging this. Could you take a look at the broken i386 image (docker-library/php#822)? This causes our tests to fail on i386 too.

**Pull request merged**
