### PR TITLE
Update to buster for fcgi tests

### PR DESCRIPTION
**Pull request by J0WI**
This makes the setup a little bit faster

### CODE REVIEW

**Comment by yosifkit** [comment]
I would vote no to this change. If we need to run the tests on a non-amd64 architecture, Debian will run on more architectures than Alpine.

**Comment by J0WI** [comment]
Oh, you're right. But I can we at least upgrade to Buster then?
Note: The `cgi-fcgi` binary has been split to another package in Stretch, but it was installed anyway as recommend dependency of `libfcgi0ldbl`.

**Comment by tianon** [comment]
Absolutely +1 to an upgrade to Buster!

**Comment by yosifkit** [comment]
Build test of #7929; 3816dedc; `amd64` (`php:7.4.5-fpm-buster`, `php:7.4.5-fpm-alpine3.11`, `php:7.4.5-fpm-alpine3.10`, `php:7.3.17-fpm-buster`, `php:7.3.17-fpm-stretch`, `php:7.3.17-fpm-alpine3.11`, `php:7.3.17-fpm-alpine3.10`, `php:7.2.30-fpm-buster`, `php:7.2.30-fpm-stretch`, `php:7.2.30-fpm-alpine3.11`, `php:7.2.30-fpm-alpine3.10`, `wordpress:5.4.1-php7.2-fpm`, `wordpress:5.4.1-php7.2-fpm-alpine`, `wordpress:5.4.1-fpm`, `wordpress:5.4.1-fpm-alpine`, `wordpress:5.4.1-php7.4-fpm`, `wordpress:5.4.1-php7.4-fpm-alpine`, `nextcloud:16.0.10-fpm-alpine`, `nextcloud:16.0.10-fpm`, `nextcloud:17.0.6-fpm-alpine`, `nextcloud:17.0.6-fpm`, `nextcloud:18.0.4-fpm-alpine`, `nextcloud:18.0.4-fpm`, `nextcloud:19.0.0beta6-fpm-alpine`, `nextcloud:19.0.0beta6-fpm`):

```console

$ bashbrew build php:7.4.5-fpm-buster
Using bashbrew/cache:3b59f42d2e695cc782e48052c3aae7ba317c62e6bdfee4ed21979c478b4e2de7 (php:7.4.5-fpm-buster)
Tagging php:7.4.5-fpm-buster
Tagging php:7.4-fpm-buster
Tagging php:7-fpm-buster
Tagging php:fpm-buster
Tagging php:7.4.5-fpm
Tagging php:7.4-fpm
Tagging php:7-fpm
Tagging php:fpm

$ test/run.sh php:7.4.5-fpm-buster
testing php:7.4.5-fpm-buster
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.4.5-fpm-alpine3.11
Using bashbrew/cache:cc7d9b18919abbf9b71f9851fa059c8e717dc4b4da11cf84f2b60299c737ef46 (php:7.4.5-fpm-alpine3.11)
Tagging php:7.4.5-fpm-alpine3.11
Tagging php:7.4-fpm-alpine3.11
Tagging php:7-fpm-alpine3.11
Tagging php:fpm-alpine3.11
Tagging php:7.4.5-fpm-alpine
Tagging php:7.4-fpm-alpine
Tagging php:7-fpm-alpine
Tagging php:fpm-alpine

$ test/run.sh php:7.4.5-fpm-alpine3.11
testing php:7.4.5-fpm-alpine3.11
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.4.5-fpm-alpine3.10
Using bashbrew/cache:8e64e7c5d1db5c53caed63a80a6163471ab992e3fabe9a01a20faae8bf4c1cb8 (php:7.4.5-fpm-alpine3.10)
Tagging php:7.4.5-fpm-alpine3.10
Tagging php:7.4-fpm-alpine3.10
Tagging php:7-fpm-alpine3.10
Tagging php:fpm-alpine3.10

$ test/run.sh php:7.4.5-fpm-alpine3.10
testing php:7.4.5-fpm-alpine3.10
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.3.17-fpm-buster
Using bashbrew/cache:c6f8c06223abd89d9f8008b775c6e88e7560f0dddb42272cde84f2d216273b34 (php:7.3.17-fpm-buster)
Tagging php:7.3.17-fpm-buster
Tagging php:7.3-fpm-buster
Tagging php:7.3.17-fpm
Tagging php:7.3-fpm

$ test/run.sh php:7.3.17-fpm-buster
testing php:7.3.17-fpm-buster
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.3.17-fpm-stretch
Using bashbrew/cache:5aaa36d4e78edb17104a07c25d46d7b1e82632814daca33b9856d1289969db38 (php:7.3.17-fpm-stretch)
Tagging php:7.3.17-fpm-stretch
Tagging php:7.3-fpm-stretch

$ test/run.sh php:7.3.17-fpm-stretch
testing php:7.3.17-fpm-stretch
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.3.17-fpm-alpine3.11
Using bashbrew/cache:f1fe4ee0b4f818cad4f757d1bd9c4ddd41d62b08f25007ea3f8206c90fdeee2a (php:7.3.17-fpm-alpine3.11)
Tagging php:7.3.17-fpm-alpine3.11
Tagging php:7.3-fpm-alpine3.11
Tagging php:7.3.17-fpm-alpine
Tagging php:7.3-fpm-alpine

$ test/run.sh php:7.3.17-fpm-alpine3.11
testing php:7.3.17-fpm-alpine3.11
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.3.17-fpm-alpine3.10
Using bashbrew/cache:c5325a1004196b55ba8ce23af58230afb3e8f5ea114a5a65ea08d6c085c941c9 (php:7.3.17-fpm-alpine3.10)
Tagging php:7.3.17-fpm-alpine3.10
Tagging php:7.3-fpm-alpine3.10

$ test/run.sh php:7.3.17-fpm-alpine3.10
testing php:7.3.17-fpm-alpine3.10
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.2.30-fpm-buster
Building bashbrew/cache:8c3498228e7808d28a215f21111a526a2ee17da9f930ef3e30b23ffa5365d61f (php:7.2.30-fpm-buster)
Tagging php:7.2.30-fpm-buster
Tagging php:7.2-fpm-buster
Tagging php:7.2.30-fpm
Tagging php:7.2-fpm

$ test/run.sh php:7.2.30-fpm-buster
testing php:7.2.30-fpm-buster
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.2.30-fpm-stretch
Building bashbrew/cache:ccc784d731f42026c0342c1ea7154a4a163fe5f3dd2132bf76caa82ba66f72e6 (php:7.2.30-fpm-stretch)
Tagging php:7.2.30-fpm-stretch
Tagging php:7.2-fpm-stretch

$ test/run.sh php:7.2.30-fpm-stretch
testing php:7.2.30-fpm-stretch
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.2.30-fpm-alpine3.11
Building bashbrew/cache:f60001fcdaa330759d5cf936cbdab81a53f6cc045bee5677a284a99c203cee0e (php:7.2.30-fpm-alpine3.11)
Tagging php:7.2.30-fpm-alpine3.11
Tagging php:7.2-fpm-alpine3.11
Tagging php:7.2.30-fpm-alpine
Tagging php:7.2-fpm-alpine

$ test/run.sh php:7.2.30-fpm-alpine3.11
testing php:7.2.30-fpm-alpine3.11
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build php:7.2.30-fpm-alpine3.10
Building bashbrew/cache:48584953c129c841ddfd04f146ebd9a69780700dbcf88eb84d2fa98204d42377 (php:7.2.30-fpm-alpine3.10)
Tagging php:7.2.30-fpm-alpine3.10
Tagging php:7.2-fpm-alpine3.10

$ test/run.sh php:7.2.30-fpm-alpine3.10
testing php:7.2.30-fpm-alpine3.10
	'php-fpm-hello-web' [1/1]...passed

```

```console

$ bashbrew build wordpress:5.4.1-php7.2-fpm
Building bashbrew/cache:e3c4d9678f9e87cc8316abd43a478660c8b1371e17bb60195237a49c1d9368fc (wordpress:5.4.1-php7.2-fpm)
Tagging wordpress:5.4.1-php7.2-fpm
Tagging wordpress:5.4-php7.2-fpm
Tagging wordpress:5-php7.2-fpm
Tagging wordpress:php7.2-fpm

$ test/run.sh wordpress:5.4.1-php7.2-fpm
testing wordpress:5.4.1-php7.2-fpm
	'wordpress-fpm-run' [1/1]...passed

```

```console

$ bashbrew build wordpress:5.4.1-php7.2-fpm-alpine
Building bashbrew/cache:ffbaa67e3599552c097a935f4b0a785808aad2b6f45e38e9328e0f3dd47dc862 (wordpress:5.4.1-php7.2-fpm-alpine)
Tagging wordpress:5.4.1-php7.2-fpm-alpine
Tagging wordpress:5.4-php7.2-fpm-alpine
Tagging wordpress:5-php7.2-fpm-alpine
Tagging wordpress:php7.2-fpm-alpine

$ test/run.sh wordpress:5.4.1-php7.2-fpm-alpine
testing wordpress:5.4.1-php7.2-fpm-alpine
	'wordpress-fpm-run' [1/1]...passed

```

```console

$ bashbrew build wordpress:5.4.1-fpm
Building bashbrew/cache:54e740b90542d7bd30b1cb5f0fdd85d7870eefdc35cc751edb72cb71fbef459f (wordpress:5.4.1-fpm)
Tagging wordpress:5.4.1-fpm
Tagging wordpress:5.4-fpm
Tagging wordpress:5-fpm
Tagging wordpress:fpm
Tagging wordpress:5.4.1-php7.3-fpm
Tagging wordpress:5.4-php7.3-fpm
Tagging wordpress:5-php7.3-fpm
Tagging wordpress:php7.3-fpm

$ test/run.sh wordpress:5.4.1-fpm
testing wordpress:5.4.1-fpm
	'wordpress-fpm-run' [1/1]...passed

```

```console

$ bashbrew build wordpress:5.4.1-fpm-alpine
Building bashbrew/cache:81ac444e8d2257266cfe36ca46363ba1af135842f68e5c16085fb43220909e5a (wordpress:5.4.1-fpm-alpine)
Tagging wordpress:5.4.1-fpm-alpine
Tagging wordpress:5.4-fpm-alpine
Tagging wordpress:5-fpm-alpine
Tagging wordpress:fpm-alpine
Tagging wordpress:5.4.1-php7.3-fpm-alpine
Tagging wordpress:5.4-php7.3-fpm-alpine
Tagging wordpress:5-php7.3-fpm-alpine
Tagging wordpress:php7.3-fpm-alpine

$ test/run.sh wordpress:5.4.1-fpm-alpine
testing wordpress:5.4.1-fpm-alpine
	'wordpress-fpm-run' [1/1]...passed

```

```console

$ bashbrew build wordpress:5.4.1-php7.4-fpm
Building bashbrew/cache:ba6b6eb35c3a5440e1e4806dc923f0436fb4d570263e466e74d38c3caabe3bf6 (wordpress:5.4.1-php7.4-fpm)
Tagging wordpress:5.4.1-php7.4-fpm
Tagging wordpress:5.4-php7.4-fpm
Tagging wordpress:5-php7.4-fpm
Tagging wordpress:php7.4-fpm

$ test/run.sh wordpress:5.4.1-php7.4-fpm
testing wordpress:5.4.1-php7.4-fpm
	'wordpress-fpm-run' [1/1]...passed

```

```console

$ bashbrew build wordpress:5.4.1-php7.4-fpm-alpine
Building bashbrew/cache:39ab2ff7c4b0bfc432ff6fb5ac4db029f22c4b3cfa07d66bdf58c0f070936410 (wordpress:5.4.1-php7.4-fpm-alpine)
Tagging wordpress:5.4.1-php7.4-fpm-alpine
Tagging wordpress:5.4-php7.4-fpm-alpine
Tagging wordpress:5-php7.4-fpm-alpine
Tagging wordpress:php7.4-fpm-alpine

$ test/run.sh wordpress:5.4.1-php7.4-fpm-alpine
testing wordpress:5.4.1-php7.4-fpm-alpine
	'wordpress-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:16.0.10-fpm-alpine
Building bashbrew/cache:b9dc0b86dc29676c806464caf2af46dee3b03bebcc8ebb5757e2a92930c7eafb (nextcloud:16.0.10-fpm-alpine)
Tagging nextcloud:16.0.10-fpm-alpine
Tagging nextcloud:16.0-fpm-alpine
Tagging nextcloud:16-fpm-alpine

$ test/run.sh nextcloud:16.0.10-fpm-alpine
testing nextcloud:16.0.10-fpm-alpine
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:16.0.10-fpm
Building bashbrew/cache:05ec9af81e1d69b85d86253590b69971b33e0326e3834018d3f94e4f3a9797c3 (nextcloud:16.0.10-fpm)
Tagging nextcloud:16.0.10-fpm
Tagging nextcloud:16.0-fpm
Tagging nextcloud:16-fpm

$ test/run.sh nextcloud:16.0.10-fpm
testing nextcloud:16.0.10-fpm
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:17.0.6-fpm-alpine
Building bashbrew/cache:5e57b83f959baee5c30a3dd5860305fe00fd9c910251121469e421b563380b6a (nextcloud:17.0.6-fpm-alpine)
Tagging nextcloud:17.0.6-fpm-alpine
Tagging nextcloud:17.0-fpm-alpine
Tagging nextcloud:17-fpm-alpine
Tagging nextcloud:production-fpm-alpine

$ test/run.sh nextcloud:17.0.6-fpm-alpine
testing nextcloud:17.0.6-fpm-alpine
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:17.0.6-fpm
Building bashbrew/cache:c4ae6ebde8e12229edeca254673bd3770c70b50c1a048ee52e2bf918471b280a (nextcloud:17.0.6-fpm)
Tagging nextcloud:17.0.6-fpm
Tagging nextcloud:17.0-fpm
Tagging nextcloud:17-fpm
Tagging nextcloud:production-fpm

$ test/run.sh nextcloud:17.0.6-fpm
testing nextcloud:17.0.6-fpm
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:18.0.4-fpm-alpine
Building bashbrew/cache:452a4f8300f79e5b344b0dad79d062698a6cac136a9b7dd19677a4db929a8007 (nextcloud:18.0.4-fpm-alpine)
Tagging nextcloud:18.0.4-fpm-alpine
Tagging nextcloud:18.0-fpm-alpine
Tagging nextcloud:18-fpm-alpine
Tagging nextcloud:fpm-alpine
Tagging nextcloud:stable-fpm-alpine

$ test/run.sh nextcloud:18.0.4-fpm-alpine
testing nextcloud:18.0.4-fpm-alpine
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:18.0.4-fpm
Building bashbrew/cache:7364d41171cacf9077c2937c442c1ce9279bc5f6807e8edd51dc3b8a435ed422 (nextcloud:18.0.4-fpm)
Tagging nextcloud:18.0.4-fpm
Tagging nextcloud:18.0-fpm
Tagging nextcloud:18-fpm
Tagging nextcloud:fpm
Tagging nextcloud:stable-fpm

$ test/run.sh nextcloud:18.0.4-fpm
testing nextcloud:18.0.4-fpm
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:19.0.0beta6-fpm-alpine
Building bashbrew/cache:3df33369afdb066015c74d0bf979d13cb5389f22610066ad36a90c333c70f4cb (nextcloud:19.0.0beta6-fpm-alpine)
Tagging nextcloud:19.0.0beta6-fpm-alpine
Tagging nextcloud:19.0.0-beta-fpm-alpine
Tagging nextcloud:19.0-beta-fpm-alpine
Tagging nextcloud:19-beta-fpm-alpine

$ test/run.sh nextcloud:19.0.0beta6-fpm-alpine
testing nextcloud:19.0.0beta6-fpm-alpine
	'nextcloud-fpm-run' [1/1]...passed

```

```console

$ bashbrew build nextcloud:19.0.0beta6-fpm
Building bashbrew/cache:2a3a6437fd3c792cf61ee575880865df3cb1726d9ce27803c6ad147989a409f2 (nextcloud:19.0.0beta6-fpm)
Tagging nextcloud:19.0.0beta6-fpm
Tagging nextcloud:19.0.0-beta-fpm
Tagging nextcloud:19.0-beta-fpm
Tagging nextcloud:19-beta-fpm

$ test/run.sh nextcloud:19.0.0beta6-fpm
testing nextcloud:19.0.0beta6-fpm
	'nextcloud-fpm-run' [1/1]...passed

```

**Comment by J0WI** [comment]
Btw, what about `arm32v6`?

**Comment by tianon** [comment]
It'll either get tested against an `arm32v5`, `arm32v7`, or `arm64v8` image.

**Pull request merged**
