### PR TITLE
Bump Scout SBOM indexer to 1.13

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by tianon** [comment]
From https://github.com/docker/scout-cli/releases/tag/v1.13.0, I'm guessing "Enable detection golang main module via ldflags." is the most interesting/useful thing here? :eyes:

**Review by tianon — APPROVED** [review]

**Comment by LaurentGoderre** [comment]
@tainon for us yes!

**Comment by tianon** [comment]
> @\Tainon for us yes!

That's not me :grimacing:

**Comment by LaurentGoderre** [comment]
Ooops

**Pull request merged**
