### PR TITLE
Add Apache Kafka

### PR DESCRIPTION
**Pull request by gprivitera**
# Checklist for Review

-	[ ] associated with or contacted upstream?
-	[ ] does it fit into one of the common categories? ("service", "language stack", "base distribution")
-	[ ] is it reasonably popular, or does it solve a particular use case well?
-	[ ] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[ ] if `FROM scratch`, tarballs only exist in a single commit within the associated history?
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by gprivitera** [comment]
https://github.com/docker-library/docs/pull/824

**Comment by gprivitera** [comment]
Some love for this amazing tool?

**Comment by yosifkit** [comment]
My first question would be whether you've been in contact with Kafka upstream to see if they're either interested in being involved, maintaining the image, providing their blessing for your ownership/maintainership of it, or would even rather there weren't an official image for Kafka at all (which has happened before)? :pray: :sweat_smile:

**Comment by gprivitera** [comment]
Wrote in the official IRC channel and sent a couple of emails, no replies so far.

**Comment by guozhangwang** [comment]
@gprivitera Could you send an email to the apache kafka dev mailing list to ask? https://kafka.apache.org/contact

**Comment by gprivitera** [comment]
@guozhangwang thanks for the reply. Done.

**Comment by gwenshap** [comment]
Hi, I'm on the Apache Kafka PMC and have some questions around what does "official docker image" mean for an Apache project.

Is this an image that gets tested by the Apache Kafka system tests? An image that the PMC votes on as part of the release process? Would the Apache official image need to be hosted on the Apache repository?

I'd love to know more about how other Apache projects manage an official docker image.

**Comment by gwenshap** [comment]
Another question: how do official docker images get tested? I'm pretty sure the proposed image will not work in a cluster because advertised.listeners property is not overridden.

**Comment by gprivitera** [comment]
Hi @gwenshap, I don't think Apache needs to host anything. 
The official image will be on Docker Hub, the image creation begins downloading official releases from Apache mirrors as you probably saw from the Dockerfile.

About `advertised.listeners` properties can be set by providing the image a custom configuration, I'll make few changes and make it configurable with environment variable because as you pointed out the image will not properly in case of multiple brokers.

**Comment by gprivitera** [comment]
I've updated the image to allow `advertised.listeners` configuration via env variables.
I suppose tests can be added directly in this repository, I'll wait for the admins to weight in on that. 
Let me know if I can be of any other help.

**Comment by keeganwitt** [comment]
If you add this, will you also add the other stuff in [confluent/kafka](https://hub.docker.com/r/confluent/kafka/)? Like schema-registry?

**Comment by gprivitera** [comment]
> If you add this, will you also add the other stuff in confluent/kafka? Like schema-registry?

It's really up to the confluent guys, if they want to have all of their images available as official images they can take care of that I suppose. 
I proposed Kafka because I saw Zookeeper being added and I though of this as the perfect next image to be added.

**Comment by yosifkit** [comment]
Hi @gwenshap, thanks for commenting and joining the discussion.  "Official images" are docker images provided by the docker-library to provide starting places and common applications for users of docker and containers in general as well as ensure "Dockerization" best practices and consistency for users.  They were initially mostly maintained by us, but we have grown to include upstream organizations that maintain their Dockerfiles (like nginx) as well as community members that keep the Dockerfiles up to date.  At first there was a rush to just provide images, but now we try to reach out the upstream to ensure they are ok with the community maintaining a new docker image and how much they want to get involved or even if they would rather not have one at this time; especially given that the name "official images" usually causes a few extra bug reports to those upstream creators.

For the Kafka Apache project, you guys can be as involved in the image as you desire.  We have seen some upstream projects just giving the maintainer a git repo to host the files in their organization (like [xwiki](https://github.com/xwiki-contrib/docker-xwiki)) so that it is not just hosted in a random user's github account. The proposed Dockerfile just uses the releases as published by the project on `www.apache.org/dist/kafka/`; so hopefully it wouldn't introduce too much to your test and release process if you wanted to maintain the Dockerfile yourself.  And even if y'all also don't have cycles to maintain it right now, you can approve of this for now and are welcome to change your mind later.

As for other Apache projects, Zookeeper maintainer Patrick Hunt responded with 
> I personally thinking having docker support is valuable for the
> community. I would love to participate, however I don't have any spare
> cycles atm.
> \- http://markmail.org/thread/yu6beeaiaujfv27p#query:+page:1+mid:syfib5khbe3kbwkj+state:results

So we have a Zookeeper image maintained by a [community member](https://github.com/31z4/zookeeper-docker) and he also maintains the Apache Storm image as well.  The [Maven image](https://github.com/carlossg/docker-maven) is maintained by Carlos Sanchez \<carlos at apache.org\> and the [CouchDB image](https://github.com/klaemo/docker-couchdb) is maintained by Clemens Stolle \<klaemo at apache.org\>.

So the resulting docker image would be hosted on the Docker Hub. The docs that appear on a Docker Hub official image (like [mysql](https://hub.docker.com/r/_/mysql/)) can be as detailed as desired or just mostly point to the general configuration documentation and are controlled in [docker-library/docs](https://github.com/docker-library/docs/).

As for testing official images, we do have minimal smoke tests in the `test` directory to test containerization, and try to add more for specific images to ensure we don't push something obviously broken.

**Comment by gprivitera** [comment]
I've updated the image again, let me know if and how we want proceed.

**Comment by gprivitera** [comment]
Hearing no news, I suppose you guys do not want to move forward with this.
I will keep updating the image in any case, just let me know if there is any update.

**Comment by tianon** [comment]
Sorry @gprivitera -- we (the official images team) would love to have a Kafka image, but having upstream involved or at least supportive of the initiative is very important to us (especially since we've had some unhappy upstreams in the past who felt we had accepted things they weren't willing to deal with/support but looked fairly "official" given the name of the program we operate under).

@gwenshap did @yosifkit's explanation help?  Is there more we can do/provide to help make a good case for @gprivitera's work upstream?

**Comment by gprivitera** [comment]
Keeping the image updated, added 1.0.0 and some minor functionalities.

**Comment by tianon** [comment]
Any update?  Anything we can do to help move this forward within the Kafka project? :heart:

**Comment by gprivitera** [comment]
@tianon: mentioning @gwenshap to see if anything changed.

**Comment by gprivitera** [comment]
Unfortunately upstream of Kafka seems really uninterested in this.

**Comment by jouve** [comment]
This issue https://issues.apache.org/jira/browse/KAFKA-7249 refers to images from confluent.io .

**Comment by yosifkit** [comment]
Given the comment on [KAFKA-7249](https://issues.apache.org/jira/browse/KAFKA-7249), I'll close this since it seems the Apache Kafka project recommends using the images from Confluent Inc.

Quoting 7249 below for faster reading:
>Hello Timothy Higinbottom, do you have any issues using the confluentinc/cp-kafka and confluentinc/cp-zookeeper images?
>
>Confluent, as the enterprise support company for Kafka, currently maintains up-to-date production-ready images that closely follow each Apache release, and those images are also supported for Kubernetes deployments from the Confluent Helm Charts. The other components of the Confluent Platform are not required.

**Pull request closed without merging**
