### PR TITLE
rethinkdb 2.3.6

### PR DESCRIPTION
**Pull request by Vanuan**

### CODE REVIEW

**Comment by yosifkit** [comment]
cc maintainer: @dalanmiller (are you still involved in the dockerization of rethinkdb? Is there someone that should be listed instead of or in addition to you?)

I am getting build failures on all but the newest version:. It looks like they also need the new gpg key that was updated in the 2.3.6 Dockerfile.
```console
W: GPG error: http://download.rethinkdb.com jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CF9BDC6F03D1F02B

....
The following images failed to build:

- `rethinkdb`:
  - `rethinkdb:2.0.4`
  - `rethinkdb:2.1.6`
  - `rethinkdb:2.2.6`
  - `rethinkdb:2.3.4`
  - `rethinkdb:2.3.5`
```

<details>
<summary>Diff:</summary>

```diff
warning: insecure protocol git:// detected: git://github.com/rethinkdb/rethinkdb-dockerfiles
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 248573e..0d6aa31 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -2,4 +2,5 @@ rethinkdb:2.0 @ amd64
 rethinkdb:2.1 @ amd64
 rethinkdb:2.2 @ amd64
 rethinkdb:2.3.4 @ amd64
+rethinkdb:2.3.5 @ amd64
 rethinkdb:latest @ amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index a4ad519..aee1679 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -8,4 +8,5 @@ rethinkdb:2.2.6
 rethinkdb:2.3
 rethinkdb:2.3.4
 rethinkdb:2.3.5
+rethinkdb:2.3.6
 rethinkdb:latest
diff --git a/rethinkdb_latest/Dockerfile b/rethinkdb_2.3.5/Dockerfile
similarity index 100%
copy from rethinkdb_latest/Dockerfile
copy to rethinkdb_2.3.5/Dockerfile
diff --git a/rethinkdb_latest/Dockerfile b/rethinkdb_latest/Dockerfile
index a3adfe1..6ba632c 100644
--- a/rethinkdb_latest/Dockerfile
+++ b/rethinkdb_latest/Dockerfile
@@ -4,10 +4,10 @@ MAINTAINER Daniel Alan Miller <dalanmiller@rethinkdb.com>
 
 # Add the RethinkDB repository and public key
 # "RethinkDB Packaging <packaging@rethinkdb.com>" http://download.rethinkdb.com/apt/pubkey.gpg
-RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 1614552E5765227AEC39EFCFA7E00EF33A8F2399
+RUN apt-key adv --keyserver keys.gnupg.net --recv-keys 3B87619DF812A63A8C1005C30742918E5C8DA04A
 RUN echo "deb http://download.rethinkdb.com/apt jessie main" > /etc/apt/sources.list.d/rethinkdb.list
 
-ENV RETHINKDB_PACKAGE_VERSION 2.3.5~0jessie
+ENV RETHINKDB_PACKAGE_VERSION 2.3.6~0jessie
 
 RUN apt-get update \
 	&& apt-get install -y rethinkdb=$RETHINKDB_PACKAGE_VERSION \
```

</details><br/>

On a related note, we should think about removing 2.3.4 and 2.3.5 (probably in the next PR after updating gpg key).  Removing it here will remove it from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding it on the official build server), but the tag will still be available to users who want it.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by dalanmiller** [comment]
Unfortunately no. I think the correct person would be @atnnn (or at least the correct person to start with)

**Comment by yosifkit** [comment]
Thanks @dalanmiller!

@AtnNn, should you be listed here as the maintainer of the rethinkdb official image? Or you and others?  Let us know if you have any questions.

**Comment by tianon** [comment]
Friendly ping @AtnNn -- are you OK with us accepting bump PRs like this from contributors?  Should we update `Maintainers` to list you now? :pray:

(Also, these need a small update as pointed out by @yosifkit above.)

**Comment by reederz** [comment]
Any news on this? :) It's been almost 2 months since [2.3.6](https://github.com/rethinkdb/rethinkdb/releases) is out.

**Comment by Vanuan** [comment]
I can revert all the lines except the latest so that build would pass, but I need a confirmation that this would be merged.

**Comment by yosifkit** [comment]
Since the old versions no longer build with the apt key change, there are two options: drop all the old versions or update the dockerfiles to use the new key.  Since @AtnNn made the most recent commit to the rethinkdb-dockerfiles repo, it would be their call on which way to go (or any other user with commit rights there).

If the old versions are just to keep the image available, then know that removing it here will only remove it from the "Supported" section on the Hub readme, but the tag will still be available to users who want it.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by marshall007** [comment]
Hey guys, sorry this has taken so long. I'll try to hit it tomorrow. As suggested, I think we're going to end up deprecating versions prior to v2.3.6 since the GPG key for signing packages has changed.

**Comment by alehano** [comment]
When?

**Comment by dalanmiller** [comment]
We can close this per #3530

**Comment by tianon** [comment]
Indeed, thanks!

**Pull request closed without merging**
