### PR TITLE
Update Ubuntu 2023-03-15

### PR DESCRIPTION
**Pull request by ROCKsBot**
Update Ubuntu to latest published rootfs tarballs as of 2023-03-15.

### CODE REVIEW

**Comment by tianon** [comment]
Maybe I'm misremembering, but didn't we settle on a two-week cadence for updating this (barring major security updates)?  The downstream effect of this updating every week (not just within DOI but outside DOI as well where `ubuntu` is a _very_ popular base image) seems a little high. :sweat_smile:

**Comment by woky** [comment]
@tianon Indeed we did. Last PR https://github.com/docker-library/official-images/pull/14168 is from 2023-03-01. Did I miss any newer PR?

**Comment by tianon** [comment]
Doh, the serials threw us off, my apologies! :joy: :bow:

**Comment by woky** [comment]
Time flies. Thanks. :-)

**Pull request merged**
