### PR TITLE
Update to PHP7

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Incorporates php7 stable release

### CODE REVIEW

**Comment by md5** [comment]
This appears to be a duplicate of #1236, although it looks like you updated the file by hand instead of running `generate-stackbrew-library.sh` (since only the `latest` tag moved and not `cli`, `apache`, or `fpm`).

See the diff here: https://github.com/docker-library/official-images/pull/1236/files#diff-a91f6a9f720a0e0615d1d888fd98516b

**Comment by Lewiscowles1986** [comment]
sorry I did not notice this other PR (which I think should be several PRs), I'll close this one, I searched for php7 before creating, and I did not know about `generate-stackbrew-library.sh`, is there a place I can read about it, or is it pretty much run it from cli and read what it says?

**Comment by Lewiscowles1986** [comment]
Also just updated my patch-1 branch just-in-case you cannot merge that huge PR, I would really appreciate having PHP7 updated (regardless of what is going on with go, mysql, mongo, drupal & django) :+1:

**Comment by md5** [comment]
@Lewiscowles1986 I'm not aware of any documentation of `generate-stackbrew-library.sh`. As for your concerns about having multiple updates in a single PR, I wouldn't worry about it too much. Since @yosifkit is part of the Official Images team and has already successfully tested the PR, I expect @tianon will test and merge it tomorrow. If there were to be a problem with one of the images, I expect they would just drop it from the PR.

**Pull request closed without merging**
