### PR TITLE
Bugfixes in mongo-express entrypoint

### PR DESCRIPTION
**Pull request by BlackthornYugen**
Fixes to retry and wait logic, see PRs:

https://github.com/mongo-express/mongo-express-docker/pull/56 
https://github.com/mongo-express/mongo-express-docker/pull/70

### CODE REVIEW

**Comment by rtritto** [comment]
Should we wait https://github.com/mongo-express/mongo-express-docker/issues/115?

**Comment by BlackthornYugen** [comment]
> Should we wait [mongo-express/mongo-express-docker#115](https://github.com/mongo-express/mongo-express-docker/issues/115)?

I don't see any PR coming that fixes that issue. Do we know if one is coming? If not, I'd like to the fixes from PR 56 and 70.

**Comment by rtritto** [comment]
> I don't see any PR coming that fixes that issue. Do we know if one is coming? If not, I'd like to the fixes from PR 56 and 70.

No, I didn't find any solution.

**Comment by BlackthornYugen** [comment]
> > I don't see any PR coming that fixes that issue. Do we know if one is coming? If not, I'd like to the fixes from PR 56 and 70.
> 
> No, I didn't find any solution.

Okay, I'll try to have a look this week and if we fix it we can make another update here.

**Review by tianon — APPROVED** [review]

**Pull request merged**
