### PR TITLE
Adding the Semeru Certified Edition image support for JDK11

### PR DESCRIPTION
**Pull request by narkedi**
Adding the images for Semeru Runtimes Certified Edition for JDK11.

### CODE REVIEW

**Comment by narkedi** [comment]
@tianon Can  this PR be merged. Thanks !!

**Comment by tianon** [comment]
Sorry for the delay -- there's some discussion happening inside Docker as to whether this is an appropriate image to include in the official images program, given the software is not under an Open Source license.  I think it would probably be worthwhile to send an email to "`justin.cormack @ docker.com`" and "`jeff_hadfield @ docker.com`" to discuss further with them.

**Comment by narkedi** [comment]
@tianon To give a brief background about this, as such this is the not our first product that we published with a non-Open Source license. We did publish couple of releases of JDK11 and are still publishing JDK8 with IBM ILAN license as part of https://hub.docker.com/_/ibmjava . 

Starting JDK11, we have changed the branding from IBM Java Technology Edition to IBM Semeru Runtime for Certified Edition, and hence we will stop publishing JDK11 and future releases at  "ibmjava" and use "ibm-semeru-runtimes".

**Comment by mstoodle** [comment]
As requested, I've reached out to John and Jeff to discuss the underlying issues here, hoping we can circle back with the result of that conversation shortly (for some definition of "short" :) ).

**Comment by narkedi** [comment]
Closing this as we are not planning to publish Certified Images anymore.

**Pull request closed without merging**
