### PR TITLE
Update php

### PR DESCRIPTION
**Pull request by yosifkit**
Changes:

- https://github.com/docker-library/php/commit/df4636ca: Merge pull request https://github.com/docker-library/php/pull/1464 from jnoordsij/php-8.3
- https://github.com/docker-library/php/commit/f59450af: Add 8.3.0 variant
- https://github.com/docker-library/php/commit/b2ba9199: Update template files for PHP 8.3
- https://github.com/docker-library/php/commit/74548e88: Update 8.2 to 8.2.13
- https://github.com/docker-library/php/commit/671ef331: Update 8.1-rc
- https://github.com/docker-library/php/commit/25e17c7d: Update 8.1 to 8.1.26
- https://github.com/docker-library/php/commit/05882b3e: Update 8.3-rc
- https://github.com/docker-library/php/commit/c3db0de0: Update 8.2-rc

### CODE REVIEW

**Comment by parallels999** [comment]
Great 👍

**Review by LaurentGoderre — APPROVED** [review]

**Comment by devdrops** [comment]
I'm getting a weird output:

```
➜  php-toolbox git:(main) docker run -ti php:8.3.0-alpine php -v
Unable to find image 'php:8.3.0-alpine' locally
8.3.0-alpine: Pulling from library/php
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```

image

Even though the image `php:8.3.0-alpine` does exist on Docker Hub. Caching issue, maybe? :thinking:

**Comment by MarcHagen** [comment]
@devdrops give Jenkins time to build all the images. It still busy building the multi-arch. _as far i can see :)_

**Comment by yosifkit** [comment]
The tags may appear on Docker Hub before the architecture-specific images are built. So right now, they are all the empty manifest since none of them are ready (like `php:8.3.0-alpine` on [Docker Hub](https://hub.docker.com/layers/library/php/8.3.0-alpine/images/sha256-eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb?context=explore) or viewed via [ggcr](https://explore.ggcr.dev/?image=php:8.3.0-alpine@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb&mt=application%2Fvnd.oci.image.index.v1%2Bjson&size=89)). The tags will be updated to a new manifest as each architecture-specific build completes.

**Pull request merged**
