### PR TITLE
Added OpenContainers image-spec labels to the currently updated tags.

### PR DESCRIPTION
**Pull request by Djelibeybi**
Yet another packaging update.

Signed-off-by: Avi Miller <avi.miller@oracle.com>

### CODE REVIEW

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

(Speaking specifically of that bare `maintainer` label.)

**Comment by tianon** [comment]
(You likely intended to use `org.opencontainers.image.authors` instead?)

**Comment by Djelibeybi** [comment]
Well, no. I was maintaining (see what I did there?) the deprecated `MAINTAINER` directive and using `org.opencontainers.image.vendor` as the OpenContainers label that references the source organisation. I can switch the maintainer to author instead, if you prefer?

**Comment by Djelibeybi** [comment]
(Slightly more minutes are required to force push the images, though)

**Pull request merged**
