### PR TITLE
Update java-jre: back to headless

### PR DESCRIPTION
**Pull request by yosifkit**
Thanks @md5 for the catch.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Can you rebuild jruby once this is done?

**Comment by yosifkit** [comment]
@cpuguy83 Sure thing! :+1:

**Comment by tianon** [comment]
LGTM

Build test of #420; 2296750f3f570b9c5638047643cae4a1f39ca02d (`java`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/2296750f3f570b9c5638047643cae4a1f39ca02d/library/java
Fetching java (git://github.com/docker-library/java) ...
Processing java:openjdk-6b33-jdk ...
Processing java:openjdk-6b33 ...
Processing java:openjdk-6-jdk ...
Processing java:openjdk-6 ...
Processing java:6b33-jdk ...
Processing java:6b33 ...
Processing java:6-jdk ...
Processing java:6 ...
Processing java:openjdk-6b33-jre ...
Processing java:openjdk-6-jre ...
Processing java:6b33-jre ...
Processing java:6-jre ...
Processing java:openjdk-7u71-jdk ...
Processing java:openjdk-7u71 ...
Processing java:openjdk-7-jdk ...
Processing java:openjdk-7 ...
Processing java:7u71-jdk ...
Processing java:7u71 ...
Processing java:7-jdk ...
Processing java:7 ...
Processing java:jdk ...
Processing java:latest ...
Processing java:openjdk-7u71-jre ...
Processing java:openjdk-7-jre ...
Processing java:7u71-jre ...
Processing java:7-jre ...
Processing java:jre ...
Processing java:openjdk-8u40-b09-jdk ...
Processing java:openjdk-8u40-b09 ...
Processing java:openjdk-8u40-jdk ...
Processing java:openjdk-8u40 ...
Processing java:openjdk-8-jdk ...
Processing java:openjdk-8 ...
Processing java:8u40-b09-jdk ...
Processing java:8u40-b09 ...
Processing java:8u40-jdk ...
Processing java:8u40 ...
Processing java:8-jdk ...
Processing java:8 ...
Processing java:openjdk-8u40-b09-jre ...
Processing java:openjdk-8u40-jre ...
Processing java:openjdk-8-jre ...
Processing java:8u40-b09-jre ...
Processing java:8u40-jre ...
Processing java:8-jre ...
```

**Comment by md5** [comment]
I just noticed the number of this PR :evergreen_tree::deciduous_tree::palm_tree:

**Pull request merged**
