### PR TITLE
Update rakudo-star to 2024.03

### PR DESCRIPTION
**Pull request by AntonOks**
Adding a bookworm tag for consistency and clarity and switching the FROM alpine Docker image to "alpine:latest"...

### CODE REVIEW

**Comment by tianon** [comment]
Switching to the implicit `alpine:latest` is what I like to call a "square wheel" -- it's technically a rolling tag, but when that square wheel rolls, you might experience some unexpected breakage as a result, so we recommend being explicit (and bumping manually when the wheel rolls and you've done at least a surface-level verification of compatibility).

**Comment by AntonOks** [comment]
> Switching to the implicit `alpine:latest` is what I like to call a "square wheel" -- it's technically a rolling tag, but when that square wheel rolls, you might experience some unexpected breakage as a result, so we recommend being explicit (and bumping manually when the wheel rolls and you've done at least a surface-level verification of compatibility).

@tianon

Thanks for your hint / opinion. We discussed pro's and con's in https://github.com/Raku/docker/pull/60 and part of that is my [thoughts on this case here](https://github.com/Raku/docker/pull/60#discussion_r1545792753).

From my understanding, the "rakudo-star" container was supported, if at all, on a "personal and best effort level". I doubt there were "verification" or the like efforts done...

**Comment by tianon** [comment]
Ah nice, thank you for the references (and for already having thought about / discussed it) :heart:

**Review by tianon — APPROVED** [review]

**Comment by AntonOks** [comment]
> Switching to the implicit `alpine:latest` is what I like to call a "square wheel" -- it's technically a rolling tag, but when that square wheel rolls, you might experience some unexpected breakage as a result, so we recommend being explicit (and bumping manually when the wheel rolls and you've done at least a surface-level verification of compatibility).

Finally, it's about automating merge requests to this repo here... based on GitHub workflows in our "rako/docker" repo... If you have some nice-and-easy examples from other images here, which I / we could just copy-paste to get our rakudo-star "offical-images" up2date, including the "FROM" images of our Dockerfiles, I would be fine either way ;)

And finally, from my understanding and I may be very wrong here... our "bookwork" also points to a "somehow latest stable" and not an "explicit" version, right:
- https://github.com/Raku/docker/blob/master/2024.03/bookworm/Dockerfile

**Comment by tianon** [comment]
`FROM buildpack-deps:bookworm-scm` is explicitly Debian Bookworm (so when Trixie is released, it will _not_ automatically update :smile:)

For automating image update PRs, you'll want to review https://github.com/docker-library/faq#can-i-use-a-bot-to-make-my-image-update-prs :+1:

**Pull request merged**
