### PR TITLE
[percona] update ps-80 version

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by jkabat** [comment]
@yosifkit any chance to get it merged?

**Comment by yosifkit** [comment]
These changes seem a little odd; is this new version just a pre-release or something?  But if the Percona image maintainers are fine with it, it is fine.
```diff
+ENV PS_REPO testing
...
-    percona-release enable ps-80 release
+    percona-release enable ps-80 ${PS_REPO}
```

Test failures are unrelated and are being addressed in https://github.com/docker-library/official-images/pull/13081.

**Comment by jkabat** [comment]
@yosifkit is merging of https://github.com/docker-library/official-images/pull/13081 required prior resolving this PR?

**Comment by yosifkit** [comment]
No, I was just worried that a `testing` (pre-release) version was accidentally going out instead of a `release`. If that is correct and expected, then this is fine. Is the `testing` channel expected for this version (`8.0.30-22.1`)?

**Pull request closed without merging**
