### PR TITLE
Update backdrop

### PR DESCRIPTION
**Pull request by Wylbur**
Update to 1.21.3

Here's the latest release info
https://github.com/backdrop/backdrop/releases/tag/1.21.3
https://github.com/backdrop-ops/backdrop-docker/commit/5ff119dc2849a709d9621a9950eeb6aaca075197

### CODE REVIEW

**Comment by tianon** [comment]
```console
configure: error: unrecognized options: --with-png-dir, --with-jpeg-dir
```

I think these can change to just `--with-png` and `--with-jpeg` on the newer PHP version. :+1:

**Comment by Wylbur** [comment]
@tianon 
I have updated master branch with updates to those arguments.  How do we restart this?

**Comment by tianon** [comment]
Just update `GitCommit:` to point to the new commit and the CI will re-run. :+1:

**Comment by drupol** [comment]
Hi,

Could you please remove me from the maintainers?

Thanks :)

**Comment by drupol** [comment]
Thanks !

**Comment by tianon** [comment]
Looks like it might be worth setting up a basic GitHub Action over in https://github.com/backdrop-ops/backdrop-docker to at least do a `docker build`. :sweat_smile:

**Comment by tianon** [comment]
Something like this in `.github/workflows/ci.yml` is probably a "good enough" start: :wink: :grimacing:

```yaml
name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build 1/apache
      - run: docker build 1/fpm
```

(Then you won't have to wait for us to "Approve and run" here, and could remove that now-defunct `.travis.yml` file that used to do something very similar.)

**Comment by Wylbur** [comment]
We have rebuild the review process, thanks for all your very helpful input!

**Pull request closed without merging**
