### PR TITLE
Add Official Newrelic PHP Daemon Image

### PR DESCRIPTION
**Pull request by murphpdx**
Hello, 
We, the New Relic PHP Agent team, would like to add an official image for our New Relic PHP Agent daemon. 

-	[ ] associated with or contacted upstream? Yes https://github.com/newrelic/newrelic-php-daemon-docker
-	[ ] does it fit into one of the common categories? ("service", "language stack", "base distribution")
-	[ ] is it reasonably popular, or does it solve a particular use case well?
-	[ ] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long) https://github.com/docker-library/docs/pull/1591
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[ ] if `FROM scratch`, tarballs only exist in a single commit within the associated history?
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tianon** [comment]
I'm guessing this is the image we were hypothetically discussing over in https://github.com/docker-library/faq/issues/9? :sweat_smile:

**Comment by murphpdx** [comment]
> I'm guessing this is the image we were hypothetically discussing over in [docker-library/faq#9](https://github.com/docker-library/faq/issues/9)? 😅

Yes, it sure is.

**Comment by tianon** [comment]
So, I think what's discussed there is definitely still relevant here -- while I'm sure this image is useful in combination with New Relic, it's not exactly "generally useful" right?  For example, if someone isn't using the New Relic SaaS product, they wouldn't get any value from this image?

**Comment by murphpdx** [comment]
> So, I think what's discussed there is definitely still relevant here -- while I'm sure this image is useful in combination with New Relic, it's not exactly "generally useful" right? For example, if someone isn't using the New Relic SaaS product, they wouldn't get any value from this image?

That is correct, is your concern with the cost? We do offer a trial period and once that ends the account becomes a free lite account.

**Comment by yosifkit** [comment]
> My initial reaction is that it doesn't sound like the image would be "generally useful"

My reasoning for my reaction is that this image is tied to a single specific SAAS offering. It is not a generic service that you would plug into another system.  All the other images here are a self-contained service, language stack, or base OS; they don't require a hosted service to use.

**Comment by yosifkit** [comment]
Closing given my comment just above: https://github.com/docker-library/official-images/pull/6843#issuecomment-554158766.

**Pull request closed without merging**
