### PR TITLE
Add new NUXEOCTL_CONSOLE_OPTIONS parameter

### PR DESCRIPTION
**Pull request by ffjdm**

### CODE REVIEW

**Comment by tianon** [comment]
cc @dmetzler @akervern

<details>
<summary>Diff:</summary>

```diff
diff --git a/nuxeo_10.1/docker-entrypoint.sh b/nuxeo_10.1/docker-entrypoint.sh
index 2fc1b57..0dc404a 100755
--- a/nuxeo_10.1/docker-entrypoint.sh
+++ b/nuxeo_10.1/docker-entrypoint.sh
@@ -69,7 +69,7 @@ EOF
   fi
 
   if [ "$2" = "console" ]; then
-    exec nuxeoctl console
+    exec nuxeoctl console $NUXEOCTL_CONSOLE_OPTIONS
   else
     exec "$@"
   fi
diff --git a/nuxeo_LTS/docker-entrypoint.sh b/nuxeo_LTS/docker-entrypoint.sh
index 2fc1b57..0dc404a 100755
--- a/nuxeo_LTS/docker-entrypoint.sh
+++ b/nuxeo_LTS/docker-entrypoint.sh
@@ -69,7 +69,7 @@ EOF
   fi
 
   if [ "$2" = "console" ]; then
-    exec nuxeoctl console
+    exec nuxeoctl console $NUXEOCTL_CONSOLE_OPTIONS
   else
     exec "$@"
   fi
diff --git a/nuxeo_latest/docker-entrypoint.sh b/nuxeo_latest/docker-entrypoint.sh
index 2fc1b57..0dc404a 100755
--- a/nuxeo_latest/docker-entrypoint.sh
+++ b/nuxeo_latest/docker-entrypoint.sh
@@ -69,7 +69,7 @@ EOF
   fi
 
   if [ "$2" = "console" ]; then
-    exec nuxeoctl console
+    exec nuxeoctl console $NUXEOCTL_CONSOLE_OPTIONS
   else
     exec "$@"
   fi
````

</details>

**Comment by dmetzler** [comment]
I agree on your last comment.... I tried to review the history of that code (which I wrote :-) ) but I don't remember the exact reason for that.

We will modify accordingly, thx for the review.

**Comment by ffjdm** [comment]
But you could not use this in a compose then

**Comment by ffjdm** [comment]
Indeed but the image has to be cleaned up first. Please see #4776 for this.

**Pull request closed without merging**
