### PR TITLE
Explicitly note that Docker 1.10+ is required for the new Bashbrew

### PR DESCRIPTION
**Pull request by tianon**
This is especially thanks to https://github.com/docker/docker/issues/15785 and thus https://github.com/docker/docker/commit/c8cc4fb8d9a8d0cd155b8d26a3108e7762b623e3.

cc @yosifkit

### CODE REVIEW

**Comment by tianon** [comment]
For a tad bit more detail, `git archive` _always_ creates the tar it generates with `uid/gid` of `0/0`, hard-coded.  For essentially any other tool, this is fine and ignored, but Docker 1.9 and below insisted on extracting to a temporary directory and trying to preserve permissions, and doing so client-side, which causes major problems for non-root Docker users.

**Comment by tianon** [comment]
(This also updates `test-pr.sh` to try very hard to bind-mount `BASHBREW_CACHE` so that builds are a lot faster, and also run as our current user instead of root.)

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
For posterity's sake, I feel I should add that I _did_ attempt to write a shim on top of a tar that just rewrites all the `uid/gid` from `0/0` to `geteuid/getegid`, but in the end we determined it wasn't worth the hassle/overhead just to keep support for Docker 1.9, especially since the way Bashbrew caches makes our reliance on Docker's cache quite a bit less pronounced.

**Pull request merged**
