### PR TITLE
Aerospike 5.1.0.10

### PR DESCRIPTION
**Pull request by volmarl**
https://www.aerospike.com/download/server/notes.html

### CODE REVIEW

**Comment by yosifkit** [comment]
Are there any implications for existing users with the removal of the data `VOLUME`?  Should this be documented on the Docker Hub page (https://github.com/docker-library/docs/)?

**Comment by volmarl** [comment]
no impact. This was superfluous We can still document.

**Comment by yosifkit** [comment]
I'm confused, there are now 2 conflicting PRs to update `aerospike` (this and https://github.com/docker-library/official-images/pull/8876). How do you want us to proceed?

**Comment by volmarl** [comment]
@yosifkit closing the older one.

**Pull request closed without merging**
