### PR TITLE
Update clojure tools-deps variants to version 1.11.1.1200

### PR DESCRIPTION
**Pull request by cap10morgan**
Upstream version bump

### CODE REVIEW

**Comment by cap10morgan** [comment]
I think the CI failure was an intermittent connection issue. Hopefully trying again would fix it.

**Comment by yosifkit** [comment]
I can reproduce the failure locally. After some digging to make sure it wasn't a change in Alpine, it seems to be related to the jdk bump of Eclipse temurin `8u345-b01` to Eclipse temurin `8u352-b08`.

**Comment by cap10morgan** [comment]
> I can reproduce the failure locally. After some digging to make sure it wasn't a change in Alpine, it seems to be related to the jdk bump of Eclipse temurin `8u345-b01` to Eclipse temurin `8u352-b08`.

Huh, OK. I'll dig into it.

**Comment by cap10morgan** [comment]
@yosifkit I think (if it's alright with you) I'm just going to exclude that combo for now (i.e. boot, JDK 8, Alpine). I would bet that its usage is very low to nonexistent.

**Comment by yosifkit** [comment]
Yeah, that's fine.

**Pull request merged**
