### PR TITLE
Add initial GitHub Actions CI

### PR DESCRIPTION
**Pull request by tianon**
~~This is mostly an experiment.~~

https://github.com/docker-library/official-images/pull/7937#issuecomment-624235461 :sweat_smile:

### CODE REVIEW

**Comment by yosifkit** [comment]
:green_apple: :green_heart: :green_salad: :green_book: :green_circle: There was sooo much green! :1st_place_medal: :100:   I like it a lot

Even the error case seems sane on bad/missing commit hash:

>failed fetching/scraping FROM for "hylang" (tags "0.18.0-python3.8-buster, 0.18-python3.8-buster, 0-python3.8-buster, python3.8-buster, 0.18.0-buster, 0.18-buster, 0-buster, buster", arch "amd64")
>
>failed fetching Git repo for arch "amd64" from entry  [...] GitCommit: 5148df70ef281642faeb6508aa74cb14deadbeef\nDirectory: dockerfiles-generated\nFile: Dockerfile.python3.8-buster"
>
>object not found

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/7937#event-3302614425 :smirk:

**Comment by tianon** [comment]
04eed09e8359c7dc50cb1f5d3f78e6c8a68ce7b8 -> https://github.com/docker-library/official-images/runs/647082664?check_suite_focus=true

```console
+ .github/workflows/naughty.sh

Incorrectly formatted 'latest' tags detected:
  hylang:buster-latest

Read https://github.com/docker-library/official-images#tags-and-aliases for more details.

```

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/commit/530ed57e5e86b11c58ca38afccd6cd9db0131537 ->
image
:metal: :exclamation:

**Comment by tianon** [comment]
This has been WAY more successful than I anticipated...  This is no longer an experiment. :sweat_smile:

**Comment by tianon** [comment]
Ouch, we're running into https://github.com/actions/labeler/issues/12 / https://github.community/t5/GitHub-Actions/GitHub-actions-are-severely-limited-on-PRs/m-p/54669/highlight/true#M9249 (in other words, the token GitHub gives us for forks is explicitly read-only). :disappointed: 🤬

(See #7942, #7943, #7944.)

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/commit/a40bfb3617fb765ccabf9794e55f7cece6281696 and https://github.com/docker-library/official-images/commit/088d51bfde4ea9019dd9c7457cb7b5510bf1e04e for our (hopefully temporary??) workaround to this insanity. :sweat_smile:

**Pull request merged**
