### PR TITLE
Update Ubuntu 2024-08-15

### PR DESCRIPTION
**Pull request by ROCKsBot**
Update Ubuntu to the latest published OCI tarballs as of 2024-08-15.

### CODE REVIEW

**Comment by tianon** [comment]
```diff
-usr/local/sbin/unminimize
```

Is `devel` losing the `unminimize` script on purpose? :eyes:

**Comment by utkarsh2102** [comment]
> Is `devel` losing the `unminimize` script on purpose? 👀

Yes and no. 😅 

Yes - `usr/local/sbin/unminimize` is going. But no, we're not losing this. There's `/usr/bin/unminimize` now. :D

For context - `/usr/local/sbin/unminimize` was being shipped via `livecd-rootfs` but now we've packaged `unminimize` as a separate package. src:unminimize, bin:unminimize which provides `/usr/bin/unminimize`. 

Let me know if you have any questions. ;)

**Comment by tianon** [comment]
Oh neat! :partying_face:

Does that mean `bin:unminimize` should be pre-installed in the image so that command stays available, or are users expected in oracular+ to install it themselves when they need it?  (I don't have a strong opinion either way, but we should probably document both the current state and the new state on https://hub.docker.com/_/ubuntu -- I thought we'd done that, but I'm not seeing it :smile:)

**Review by yosifkit — APPROVED** [review]

**Comment by tianon** [comment]
:eyes:

> Does that mean `bin:unminimize` should be pre-installed in the image so that command stays available, or are users expected in oracular+ to install it themselves when they need it? (I don't have a strong opinion either way, but we should probably document both the current state and the new state on https://hub.docker.com/_/ubuntu -- I thought we'd done that, but I'm not seeing it 😄)

The first half of this is probably not urgent since it's _just_ `ubuntu:devel` right now, but certainly something to decide before release! :smile:

either way, we should definitely document it in https://github.com/docker-library/docs/blob/master/ubuntu/content.md :heart:

**Comment by cjdcordeiro** [comment]
Y @tianon that's a valid question we're already having and that we should converge on before the final release. 

Additionally, and for anyone who has asked it before, this PR also introduces riscv64 for all previous and still supported releases ;)

**Pull request merged**
