### PR TITLE
Update YOURLS

### PR DESCRIPTION
**Pull request by LeoColomb**
* Bump YOURLS to v1.9
* Bump PHP to 8.1
* Minor fixes and improvements

### CODE REVIEW

**Comment by LeoColomb** [comment]
Oh, no BuildKit support? 😭

**Comment by tianon** [comment]
Indeed, unfortunately we use plain BuildKit-less `docker build`.

**Comment by LeoColomb** [comment]
Alright, reverted back to plain `docker build` compat.

By the way, as visible with the force-push, we now use a bot to generate the branch for this pull-request.
Do you think it would be possible to allow [this same app](https://github.com/apps/yourls-bot) to create the pull request as well? (it requires to install it on this repo)

**Comment by yosifkit** [comment]
I'm not sure the reason for adding the `ARG` declarations early in the Dockerfile, but they should be declared as late in the Dockerfile as possible in order to minimize `docker build` cache bust when they change.

---

We have other maintainers using automation to submit pull requests and haven't needed a GitHub app so far. Here is our [current bot guidelines](https://github.com/docker-library/faq/tree/2c48cc77c354ec18edc13ac017a8e2a382fae74c#can-i-use-a-bot-to-make-my-image-update-prs).

**Comment by LeoColomb** [comment]
> I'm not sure the reason for adding the `ARG` declarations early in the Dockerfile

This is to avoid multiple static references and reduce mistake surface, without breaking the cache as `ENV` does and allowing to reference it in the `LABEL`s.
But I get the point, and I guess I could move the labeling at a later line.

> other maintainers using automation to submit pull requests

Using "fake" personal accounts, like @docker-library-bot, right?
Yes, this an option, but actually more a workaround now, since it is much better if used with a GitHub App (secure with temp tokens, strict permissions, and not faking a user account). 
But it also come with a downside, which is the app must be installed on the repo.
Let me know what you think about this.

**Comment by tianon** [comment]
> > I'm not sure the reason for adding the `ARG` declarations early in the Dockerfile
> 
> This is to avoid multiple static references and reduce mistake surface, without breaking the cache as `ENV` does and allowing to reference it in the `LABEL`s. But I get the point, and I guess I could move the labeling at a later line.

Unfortunately, `ARG` breaks the cache in the same way `ENV` does. :see_no_evil: :disappointed:

> > other maintainers using automation to submit pull requests
> 
> Using "fake" personal accounts, like @docker-library-bot, right? Yes, this an option, but actually more a workaround now, since it is much better if used with a GitHub App (secure with temp tokens, strict permissions, and not faking a user account). But it also come with a downside, which is the app must be installed on the repo. Let me know what you think about this.

Yes, unfortunately providing an application access to our repository is not something we can accept (it's a pretty wide security issue for us to do so).

**Comment by LeoColomb** [comment]
> Unfortunately, `ARG` breaks the cache in the same way `ENV` does. 🙈 😞

Ok, fixed ✨

> Yes, unfortunately providing an application access to our repository is not something we can accept

Alright

**Pull request merged**
