### PR TITLE
Telegraf 1.14.4

### PR DESCRIPTION
**Pull request by danielnelson**
Tag 1.14.4 and set as latest.

### CODE REVIEW

**Comment by danielnelson** [comment]
I'm unsure what the cause of the test error, seems odd that this file would cause an error during `rm -rf` since we aren't specifically removing it:
```
+ rm -rf telegraf-1.12.6-static_linux_amd64.tar.gz telegraf-1.12.6-static_linux_amd64.tar.gz.asc /usr/src /root/.gnupg
107
rm: can't remove '/root/.gnupg/S.gpg-agent.extra': No such file or directory
```

**Comment by yosifkit** [comment]
It is a common failure; gnupg runs multiple daemons automatically (`dirmngr` and `gpg-agent`) and so there is sometimes a race in deleting the file.  We've had slightly better success when adding `gpgconf --kill all` once gpg verification is done but it is not required. I can merge if you are fine with how it is (esp since the "failing" image hasn't changed)

**Comment by danielnelson** [comment]
Yes, please merge and I'll add the suggested command for the next update.

**Comment by yosifkit** [comment]
LGTM.

This will take some time before it is pushed to the Docker Hub since the build queue is still very full from #8147.

**Pull request merged**
