### PR TITLE
rethinkdb: Remove obsolete (unsupported) releases

### PR DESCRIPTION
**Pull request by stuartpb**
Per https://github.com/docker-library/official-images#library-definition-files, following the style used by Redis

Following discussion from https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/27#issuecomment-212650916

cc @dalanmiller @danielmewes (please don't merge without review from at least one of these)

### CODE REVIEW

**Comment by stuartpb** [comment]
@dalanmiller @danielmewes The assumption I went on in writing this patch is that RethinkDB supports each minor version going back to (at least) 1.15, but doesn't support running unpatched versions of those point-releases. Does that accurately reflect RethinkDB's support policy?

**Comment by tianon** [comment]
LGTM! :+1:

**Comment by dalanmiller** [comment]
I'm not sure what our support policy is @danielmewes, I"ll let you make the call.

**Comment by tianon** [comment]
Maybe it would help to reframe the question a little bit: if there were a bug discovered in 1.15.3, would there be a 1.15.4?

**Comment by danielmewes** [comment]
> Maybe it would help to reframe the question a little bit: if there were a bug discovered in 1.15.3, would there be a 1.15.4?

No. We have occasionally released bug fix releases for one major release before the current one, if a bug was particularly severe.
With our latest release being 2.3.0, we might still release a 2.2.7 in the future. But we will not release a further 2.1.x, 2.0.x, 1.16.x etc.

That being said, major releases do sometimes slightly break compatibility, and some applications might only work with a particular older version of RethinkDB (more precisely: with a particular X and Y in RethinkDB X.Y.z. A change in the z never breaks compatibility, so it should always be ok to only support the highest available z for a given X.Y).
I think we don't need to provide images for versions older than 2.0.x though.

**Comment by yosifkit** [comment]
Thanks for the clarification @danielmewes.  @stuartpb, could you adjust the PR to drop the older  `1.X` versions as well?

**Pull request merged**
