### PR TITLE
archlinux: Release 20240101.0.204074

### PR DESCRIPTION
**Pull request by archlinux-github**
This is an automated release [1].

[1] https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/master/.gitlab-ci.yml

---

Maintainers: @SantiagoTorres @shibumi @hashworks

### CODE REVIEW

**Comment by tianon** [comment]
Merging per https://github.com/docker-library/official-images/pull/15751 discussion 👍

**Comment by aminvakil** [comment]
@hashworks @tianon Thank you for doing this, I can also confirm issue has been fixed.
https://github.com/aminvakil/docker-archlinux/commit/dbd06a2

**Comment by tianon** [comment]
We're probably due for another update sometime soon, right? :sweat_smile:

**Comment by hashworks** [comment]
Sadly I hadn't found time to adjust the deployment to make base-devel and multilib extend from base. I can re-enable the old variant anytime if you think that's okay.

**Comment by tianon** [comment]
Ah yeah, that's fair -- I guess having them up-to-date again is better than making sure they're perfect.  I'm looking through the old discussions and not actually understanding why this still included the new `multilib-devel` (maybe we just didn't notice in our review of it?), but perhaps that's not actually that important.  Please do feel free to re-enable :heart:

**Comment by tianon** [comment]
(as a reminder for myself, that improvement is tracked in https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/100 :rocket:)

**Pull request merged**
