### PR TITLE
Bump Traefik to v2.3.6

### PR DESCRIPTION
**Pull request by rtribotte**
Hello,

This PR updates Traefik to [v2.3.6](https://github.com/traefik/traefik/releases/tag/v2.3.6).

/cc @ldez @jbdoumenjou @SantoDE

Cheers

### CODE REVIEW

**Review by ldez — APPROVED** [review]
LGTM

**Review by kevinpollet — APPROVED** [review]
LGTM

**Review by jbdoumenjou — APPROVED** [review]
LGTM

**Review by SantoDE — APPROVED** [review]
Lgtm

**Comment by yosifkit** [comment]
Thoughts on adding more verification on the downloaded binaries for future releases? (https://github.com/docker-library/official-images/tree/2737545d0e9ecabdf1338051130f5e87f4c6b1cb#image-build)  I think [golang](https://github.com/docker-library/golang/blob/b9cdd8a6c7b927f711963d01fac36f08bf405bb6/1.15/buster/Dockerfile#L22-L69) is the most similar example we have in our repos.

**Pull request merged**
