### PR TITLE
Bump to latest Mono 6.12.0.182 release

### PR DESCRIPTION
**Pull request by directhex**
Includes fix for CVE 2022-30184

### CODE REVIEW

**Comment by tianon** [comment]
Maybe about time for a bump to 6.12.0.199? :eyes:

**Comment by tianon** [comment]
All of these are also `FROM debian:buster-slim`, which is now fully EOL -- should we add a deprecation notice to the `mono` image, or can we expect an update? :pray: :heart:

**Comment by tianon** [comment]
With a lot of love (and zero hard feelings) I've opened https://github.com/docker-library/docs/pull/2481 to document image deprecation :heart:

(Happy to / easy to revert if y'all want to come back and revitalize! :heart_hands:)

**Comment by tianon** [comment]
Oh!  https://www.winehq.org/news/2024091701 slash https://www.codeweavers.com/blog/esme/2024/9/6/pouring-new-life-into-mono-winehq-steps-up-as-the-primary-maintainer slash https://gitlab.winehq.org/mono/mono is exciting news!  Congratulations!! :partying_face:

Perhaps one of @directhex @akoeplinger would be willing to point the appropriate folks here so they can decide whether un-deprecation/revitalization of https://hub.docker.com/_/mono is something that would be interesting in light of this? :eyes: :heart:

(Again, to be clear, no hard feelings either way, but the door is open :heart_hands:)

**Comment by tianon** [comment]
With https://gitlab.winehq.org/mono/mono/-/releases/mono-6.14.0, maybe now's a better time to reconsider / figure out who might be the right person to ask/involve? :innocent: :heart:

**Comment by akoeplinger** [comment]
Ah sorry I missed the notifications. As far as I know the Wine releases don't have binaries yet but @madewokherd would be the right person to talk about this.

**Comment by madewokherd** [comment]
Yeah, I have no idea how to package binaries, and I'm not likely to get to it any time soon, sorry.

**Comment by tianon** [comment]
No worries!  I saw the news, was excited for y'all, and figured it was worth asking, just in case it was a thing that made sense / was interesting. :heart:

**Pull request merged**
