### PR TITLE
Update Semeru release versions 

### PR DESCRIPTION
**Pull request by jayasg12**
This update contains :
  - Maintainer name change. 
  - Semeru 11, 17 and 21 release versions update. 
  - Semeru 21 release included.

### CODE REVIEW

**Comment by tianon** [comment]
```diff
-    TOMCAT_CHECKSUM="06e239d15ff7b72017c1d0752ddb1be4651374f7c1391631ec5619f4981cb2911267bc6b044d6c71a2a74738f70d433b96418951439848121f1d874862ddd3de"; \
-    TOMCAT_DWNLD_URL="https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz"; \
+    TOMCAT_VER=`curl --silent https://dlcdn.apache.org/tomcat/tomcat-9/ | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -n 1` ;\
+    echo $TOMCAT_VER ;\
+    TOMCAT_CSUM_DWNLD_URL="https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VER}/bin/apache-tomcat-${TOMCAT_VER}.tar.gz.sha512";\
+    TOMCAT_DWNLD_URL="https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VER}/bin/apache-tomcat-${TOMCAT_VER}.tar.gz"; \
+    \
+    mkdir -p "${DOWNLOAD_PATH_TOMCAT}" "${INSTALL_PATH_TOMCAT}"; \
+    curl -LfsSo "${DOWNLOAD_PATH_TOMCAT}"/tomcat.tar.gz.sha512 "${TOMCAT_CSUM_DWNLD_URL}"; \
+    curl -LfsSo "${DOWNLOAD_PATH_TOMCAT}"/tomcat.tar.gz "${TOMCAT_DWNLD_URL}"; \
+    TOMCAT_CHECKSUM=$(grep "tar.gz" "${DOWNLOAD_PATH_TOMCAT}"/tomcat.tar.gz.sha512 | awk '{print $1}');\
```

This "detect tomcat version and download checksum" code should be part of your templates instead -- scraping HTML to get the version number is going to be fairly unreliable so should happen outside the critical path of the build.  If you're having issues with downloading Tomcat after the versions go out of support, perhaps consider something like: https://github.com/docker-library/tomcat/blob/065b183fdf5b4ab6f4450e73db6b52d4237f212a/10.1/jdk21/temurin-jammy/Dockerfile#L36-L60

Relatedly, perhaps there's been some progress on https://github.com/docker-library/official-images/pull/10666#issuecomment-945775562 (ways to make this cleaner, such as publishing some pre-calculated cache along with the official downloads) ?

**Comment by AdamBrousseau** [comment]
I'm no expert but could we use the [Tomcat image](https://hub.docker.com/_/tomcat) in a multi-stage build and pull out what we need from it? That would avoid d/ling from Apache and presumably we could just use some kind of :latest tag to always get something in support.

**Comment by AdamBrousseau** [comment]
@tianon in the meantime, are we blocking this PR on reverting to the previous method via ibmruntimes/semeru-containers#110?

**Comment by tianon** [comment]
Downloading vs embedding the checksum for verifying downloaded artifacts is a blocker here, yes.

You _could_ copy the bits from the Tomcat image, yes, but you'd need to steer carefully through https://github.com/docker-library/faq#multi-stage-builds ("best" answer being fully reproducible output).

**Comment by jayasg12** [comment]
Hi @tianon We have reverted back the Tomcat changes introduced for download and verify artifacts. We will explore ways to handle the tomcat versioning and try to commit for next release. Request to Merge this changes to unblock Semeru images publish. Thanks !!

**Comment by tianon** [comment]
Doh, sorry, looks like I got distracted by the Tomcat change and we actually have the same problem for the Semeru downloads too :sob:

```diff
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

**Comment by jayasg12** [comment]
@tianon I have reverted cheksum changes made for openjdk. Kindly review and merge the PR. Thanks !!

**Comment by tianon** [comment]
Looks like we missed some: :eyes:

```diff
diff --git a/ibm-semeru-runtimes_open-21-jdk-centos7/Dockerfile.open.releases.full b/ibm-semeru-runtimes_open-22-jdk-centos7/Dockerfile.open.releases.full
similarity index 69%
copy from ibm-semeru-runtimes_open-21-jdk-centos7/Dockerfile.open.releases.full
copy to ibm-semeru-runtimes_open-22-jdk-centos7/Dockerfile.open.releases.full
index c2f0ce6..875abd1 100644
--- a/ibm-semeru-runtimes_open-21-jdk-centos7/Dockerfile.open.releases.full
+++ b/ibm-semeru-runtimes_open-22-jdk-centos7/Dockerfile.open.releases.full
@@ -20,34 +20,36 @@ ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
...
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

```diff
diff --git a/ibm-semeru-runtimes_open-21-jdk-focal/Dockerfile.open.releases.full b/ibm-semeru-runtimes_open-22-jdk-focal/Dockerfile.open.releases.full
similarity index 70%
copy from ibm-semeru-runtimes_open-21-jdk-focal/Dockerfile.open.releases.full
copy to ibm-semeru-runtimes_open-22-jdk-focal/Dockerfile.open.releases.full
index 79f4413..186981f 100644
--- a/ibm-semeru-runtimes_open-21-jdk-focal/Dockerfile.open.releases.full
+++ b/ibm-semeru-runtimes_open-22-jdk-focal/Dockerfile.open.releases.full
@@ -23,34 +23,36 @@ RUN apt-get update \
...
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

```diff
diff --git a/ibm-semeru-runtimes_open-21-jdk-jammy/Dockerfile.open.releases.full b/ibm-semeru-runtimes_open-22-jdk-jammy/Dockerfile.open.releases.full
similarity index 70%
copy from ibm-semeru-runtimes_open-21-jdk-jammy/Dockerfile.open.releases.full
copy to ibm-semeru-runtimes_open-22-jdk-jammy/Dockerfile.open.releases.full
index 92e28a6..a4f506e 100644
--- a/ibm-semeru-runtimes_open-21-jdk-jammy/Dockerfile.open.releases.full
+++ b/ibm-semeru-runtimes_open-22-jdk-jammy/Dockerfile.open.releases.full
@@ -23,34 +23,36 @@ RUN apt-get update \
...
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

```diff
diff --git a/ibm-semeru-runtimes_open-21-jre-centos7/Dockerfile.open.releases.full b/ibm-semeru-runtimes_open-22-jre-centos7/Dockerfile.open.releases.full
similarity index 69%
copy from ibm-semeru-runtimes_open-21-jre-centos7/Dockerfile.open.releases.full
copy to ibm-semeru-runtimes_open-22-jre-centos7/Dockerfile.open.releases.full
index 27a0815..170f97a 100644
--- a/ibm-semeru-runtimes_open-21-jre-centos7/Dockerfile.open.releases.full
+++ b/ibm-semeru-runtimes_open-22-jre-centos7/Dockerfile.open.releases.full
@@ -20,34 +20,36 @@ ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
...
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

```diff
diff --git a/ibm-semeru-runtimes_open-21-jre-focal/Dockerfile.open.releases.full b/ibm-semeru-runtimes_open-22-jre-focal/Dockerfile.open.releases.full
similarity index 70%
copy from ibm-semeru-runtimes_open-21-jre-focal/Dockerfile.open.releases.full
copy to ibm-semeru-runtimes_open-22-jre-focal/Dockerfile.open.releases.full
index 11480f4..29c6be0 100644
--- a/ibm-semeru-runtimes_open-21-jre-focal/Dockerfile.open.releases.full
+++ b/ibm-semeru-runtimes_open-22-jre-focal/Dockerfile.open.releases.full
@@ -23,34 +23,36 @@ RUN apt-get update \
...
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

```diff
diff --git a/ibm-semeru-runtimes_open-21-jre-jammy/Dockerfile.open.releases.full b/ibm-semeru-runtimes_open-22-jre-jammy/Dockerfile.open.releases.full
similarity index 70%
copy from ibm-semeru-runtimes_open-21-jre-jammy/Dockerfile.open.releases.full
copy to ibm-semeru-runtimes_open-22-jre-jammy/Dockerfile.open.releases.full
index f63c002..9646d49 100644
--- a/ibm-semeru-runtimes_open-21-jre-jammy/Dockerfile.open.releases.full
+++ b/ibm-semeru-runtimes_open-22-jre-jammy/Dockerfile.open.releases.full
@@ -23,34 +23,36 @@ RUN apt-get update \
...
-    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
-    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    curl -LfsSo /tmp/openjdk.tar.gz.sha256.txt ${ESUM_URL}; \
+    curl -OLJSks ${BINARY_URL}; \
+    sha256sum -c /tmp/openjdk.tar.gz.sha256.txt; \
+    mv ibm-semeru-*tar.gz /tmp/openjdk.tar.gz; \
```

**Comment by tianon** [comment]
Something I was thinking about while reviewing this: you might be able to combine some of the work of these images by specifying one variant of each version as the "donor" image and doing `COPY --from=ibm-semeru-runtimes:open-XX-YYY-ZZZZ ...` to get the downloaded/preprocessed copy more efficiently in the other variants (see https://github.com/docker-library/tomcat/blob/3ffa12959996cd955614a78ca73c68313245d57f/11.0/jre21/temurin-jammy/Dockerfile#L26 for a relevant example of this approach), since they're all downloading the same bytes from the same place.

To be clear though, I don't suggest making that part of this PR -- let's get this out and then you can consider something like this afterwards (if it's something you want to explore).

**Comment by jayasg12** [comment]
@tianon Semeru 22 files are updated with requested changes, thanks !!

**Review by yosifkit — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Pull request merged**
