### PR TITLE
Add Zulu Images from Azul systems

### PR DESCRIPTION
**Pull request by it-mak**
Documentation MR: https://github.com/docker-library/docs/pull/2320

### CODE REVIEW

**Comment by it-mak** [comment]
I kindly request your review @Tianon @Yosifkit

**Comment by it-mak** [comment]
PR was updated to last release version, still waiting for comments.

**Comment by gdams** [comment]
(an external contributor here so feel free to disregard my comments) but I'd suggest renaming this to `azul-zulu` to be more consistent with other OpenJDK vendors. It will cause confusion for users and could be considered misleading.

**Comment by it-mak** [comment]
Updated, for successful pass PR tests

**Comment by it-mak** [comment]
Still waiting for your review @tianon @yosifkit

**Comment by geertjanw** [comment]
Hi @tianon and @yosifkit, just like @it-mak I'm from Azul, and we'd really love for our Azul Zulu images to be official Docker images. We noticed there's quite a queue of similar requests (https://github.com/docker-library/official-images/issues?q=label%3Anew-image+) and maybe it's because of the time of the year, or some other reason, but can we do something or help, we'd be happy to be involved to expedite this and other similar requests.

**Comment by geertjanw** [comment]
@tianon and @yosifkit, sorry to ask again, but just wondering what the current status is of things.

**Comment by gdams** [comment]
I would like to reiterate my point that I don't feel that this image is appropriately named. I'd suggest renaming this to azul-zulu to be more consistent with other OpenJDK vendors. It will cause confusion for users and could be considered misleading.

**Comment by FDelporte** [comment]
> @tianon @yosifkit, see #16141.

#16141 replaces this pull request #14593

**Pull request closed without merging**
