### PR TITLE
Add mqtt.cool

### PR DESCRIPTION
**Pull request by gfinocchiaro**
# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[X] associated with or contacted upstream?
    - See
      * https://github/Lightstreamer
      * https://github/mqttcool 
-	[X] does it fit into one of the common categories? ("service", "language stack", "base distribution")
     - I would say service
-	[X] is it reasonably popular, or does it solve a particular use case well?
      -  See https://www.lightstreamer.com/mqttcool-features
-	[X] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long) 
     -  See docker-library/docs#1166
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[X] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
      - Using `openjdk:8-jre-alpine` and `openjdk:8-jre`
-	[X] ~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by gfinocchiaro** [comment]
@tianon  any news?

**Comment by tianon** [comment]
Your patience is appreciated!  A few initial thoughts:

Looking at https://lightstreamer.com/download/#mqtt11, this appears to officially request acceptance of a EULA before downloading -- how do you intend to capture that with the Docker image?  Is this the community edition, or the "enterprise" edition?  Is MQTT.Cool open-source? (I can't seem to find source for it, and https://mqtt.cool/ is pretty vague :smile:)

> ```dockerfile
> FROM openjdk:8-jre
> ```

Have you tried using `openjdk:8-jre-slim`?  It should be quite a bit smaller, and if MQTT.Cool works with it, it should result in a much slimmer image.

> ```dockerfile
> WORKDIR /mqtt.cool
> ```

This seems to only apply to the `RUN` line immediately following it -- why not simply use `cd` instead and avoid the extra image metadata change?

> ```dockerfile
> # Replace the fictitious jdk path with the JAVA_HOME environment variable in the launch script file
>         && sed -i -- 's/\/usr\/jdk1.8.0/$JAVA_HOME/' bin/unix-like/mc.sh \
> ```

This seems like something that ought to be pushed into the upstream tarball, right?  How are users expected to consume this script without Docker as-is?  Maybe even something like `${JAVA_HOME:-/usr/jdk1.8.0}` in the upstream version would make sense if that default value somehow has meaning somewhere that `JAVA_HOME` isn't set? (it seems like having that script upstream enforce users setting `JAVA_HOME` appropriately makes more sense, IMO)

> ```dockerfile
> # Addjust logging configurations in order to log only on standard output
>         && sed -i -e '123,$s/<appender-ref ref="LSDailyRolling" \/>/<appender-ref ref="LSConsole" \/>/' \
>                   -e '/<appender-ref ref="LSDailyRolling" \/>/ d' conf/lightstreamer_log_conf.xml \
>         && sed -i -e '67,$s/<appender-ref ref="MQTTCoolRolling" \/>/<appender-ref ref="LSConsole" \/>/' mqtt_connectors/mqtt_master_connector_log_conf.xml \
> ```

The intent of these lines is definitely :+1: :100:, but the implementation seems a bit fragile -- those are exact line numbers, aren't they?  Isn't this going to be a bit painful to maintain and ensure is correct in the future?

---

Given that this appears to be a service that users run, why do they care which JRE version it's using?  To put that another way, why is the JRE version relevant enough to include in the image tags here?  Wouldn't users interact with this container via the standard exposed APIs, which should be agnostic to JRE version?

**Comment by gfinocchiaro** [comment]
> Your patience is appreciated! A few initial thoughts:
> 
😄 
> Looking at https://lightstreamer.com/download/#mqtt11, this appears to officially request acceptance of a EULA before downloading -- how do you intend to capture that with the Docker image? Is this the community edition, or the "enterprise" edition? Is MQTT.Cool open-source? (I can't seem to find source for it, and https://mqtt.cool/ is pretty vague 😄)
> 
It is the Community Edition, even if the Enterprise Edition could be enabled by purchasing a license.
No, MQTT.Cool is not open-source.
https://mqtt.cool will be live in few days 😄 
> > ```dockerfile
> > FROM openjdk:8-jre
> > ```
> 
> Have you tried using `openjdk:8-jre-slim`? It should be quite a bit smaller, and if MQTT.Cool works with it, it should result in a much slimmer image.

Actually there is `open-jdk:8-jre-alpine` too. Tried with `openjdk:8-jre-slim`, but unfortunately it looks like that `gpg` is not included. Any tip?
> 
> > ```dockerfile
> > WORKDIR /mqtt.cool
> > ```
> 
> This seems to only apply to the `RUN` line immediately following it -- why not simply use `cd` instead and avoid the extra image metadata change?

Yes, right! Updated.
> 
> > ```dockerfile
> > # Replace the fictitious jdk path with the JAVA_HOME environment variable in the launch script file
> >         && sed -i -- 's/\/usr\/jdk1.8.0/$JAVA_HOME/' bin/unix-like/mc.sh \
> > ```
> 
> This seems like something that ought to be pushed into the upstream tarball, right? How are users expected to consume this script without Docker as-is? Maybe even something like `${JAVA_HOME:-/usr/jdk1.8.0}` in the upstream version would make sense if that default value somehow has meaning somewhere that `JAVA_HOME` isn't set? (it seems like having that script upstream enforce users setting `JAVA_HOME` appropriately makes more sense, IMO)

Very good observations, even if at this stage it is very hard for us getting back to this 1.1 version, considered that a brand new 1.2 package will be released in the next few days. That said, I'm going to update the upstream script as per your suggestion.
Anyway, here [our tips](https://lightstreamer.com/mqtt-docs/baseparent/MQTT.Cool%20Getting%20Started%20Guide.html#_configure) regarding JAVA_HOME.
> 
> > ```dockerfile
> > # Addjust logging configurations in order to log only on standard output
> >         && sed -i -e '123,$s/<appender-ref ref="LSDailyRolling" \/>/<appender-ref ref="LSConsole" \/>/' \
> >                   -e '/<appender-ref ref="LSDailyRolling" \/>/ d' conf/lightstreamer_log_conf.xml \
> >         && sed -i -e '67,$s/<appender-ref ref="MQTTCoolRolling" \/>/<appender-ref ref="LSConsole" \/>/' mqtt_connectors/mqtt_master_connector_log_conf.xml \
> > ```
> 
> The intent of these lines is definitely 👍 💯, but the implementation seems a bit fragile -- those are exact line numbers, aren't they? Isn't this going to be a bit painful to maintain and ensure is correct in the future?

Yes, right: just deeply simplified.
> 
> Given that this appears to be a service that users run, why do they care which JRE version it's using? To put that another way, why is the JRE version relevant enough to include in the image tags here? Wouldn't users interact with this container via the standard exposed APIs, which should be agnostic to JRE version?

JRE version is important too because of server-side development feature as illustrated [here](https://lightstreamer.com/mqtt-docs/baseparent/MQTT.Cool%20Getting%20Started%20Guide.html#_the_mqtt_cool_hook).

Let me know other thoughts.
Thanks

**Comment by gfinocchiaro** [comment]
Once again a lot of problems with pull/rebase stuff... Closing and opening a new one...

**Comment by tianon** [comment]
Ok, I've managed to close it.  In the future, please don't try rebasing or merging back to master anymore -- if you need that, let me know and I'll do the dance for you (because it takes a fair amount of effort to fix this when it does happen, not to mention the noise, so I'd rather just help you more hands-on doing the rebase to avoid this problem entirely instead). :heart:

**Comment by gfinocchiaro** [comment]
Thank you so much and apologize for bother you with that.

**Pull request closed without merging**
