### PR TITLE
Update Consul to 1.8.1/1.7.5/1.6.7

### PR DESCRIPTION
**Pull request by kyhavlov**

### CODE REVIEW

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

**Comment by mikemorris** [comment]
@tianon We migrated from what appeared to be a [deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) `MAINTAINER` in https://github.com/hashicorp/docker-consul/pull/149, should this is reverted or is there a preferred alternative?

**Comment by tianon** [comment]
From https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#pre-defined-annotation-keys:

> Keys SHOULD be named using a reverse domain notation - e.g. `com.example.myKey`.

If you want to use a standard well-defined label for this same bit of metadata, I'd suggest `org.opencontainers.image.authors` (but honestly, if it were me, I'd just remove the label entirely since I don't see the added value, and since it's auto-inherited by any image that's `FROM` this one and doesn't overwrite the value).

**Comment by mikemorris** [comment]
@tianon How's this look now?

**Comment by tianon** [comment]
Much better :+1:

**Pull request merged**
