### PR TITLE
SapMachine: Add missing JRE images

### PR DESCRIPTION
**Pull request by RealCLanger**
This adds the missing JRE images. Hopefully tests are all green now.

### CODE REVIEW

**Comment by RealCLanger** [comment]
Hm, tests still don't work - need to check what happens...

**Comment by yosifkit** [comment]
The Official Images build queue is still very full (https://doi-janky.infosiftr.net/) since all Debian images have been working though rebuilds since https://github.com/docker-library/official-images/pull/15395 was merged. So, it may be a little while longer before the `sapmachine:*-jdk` images are available. I'm happy to merge with failing builds, or we can wait for the jdk image builds (https://doi-janky.infosiftr.net/job/multiarch/view/images/view/sapmachine/).

**Comment by RealCLanger** [comment]
The required base images should be available now. Let's see if tests will be green now.

**Comment by RealCLanger** [comment]
Looks good now. :)

**Pull request merged**
