### PR TITLE
Rocky Linux updates for 9.0

### PR DESCRIPTION
**Pull request by NeilHanlon**
* Also drop legacy 8.5.x image

### CODE REVIEW

**Comment by NeilHanlon** [comment]
> Diff: https://gist.github.com/docker-library-bot/5086f6a11b91b9e52899825ae0a6ae9b
> 
> (Was this a draft just to test the CI, or because it's still a WIP and you don't want us to review it yet? pray)

Was just about to message you on IRC :) 

Still a WIP. Rocky 9 has not been officially released yet but I'm preparing the container images... plus I messed up the last PRs a few times so I figured I'd cross my T's

**Comment by tianon** [comment]
Ah, totally fair!  I'll keep going through the diff then and let you know if I come across anything unexpected. :+1:

**Comment by tianon** [comment]
Looks pretty vanilla to me! :+1: (nothing like `grub` sneaking in or anything :joy:)

I did notice you removed `rockylinux:latest` -- if that was intentional, we might want to consider deleting that specific alias from Hub as well (since normally it would stick around and just no longer be updated), but if that was an oversight you know what to do. :smile:

**Comment by NeilHanlon** [comment]
Thanks! Yeah it was intentional. What's the process for removing that tag from the repo? Especially with two majors around, I think it makes little sense to keep the latest tag explicitly added, as per the other PR.

**Comment by tianon** [comment]
Just remind us once we merge the final version of this PR and we'll go get rid of it manually. :innocent:

**Pull request merged**
