### PR TITLE
Update to Flink 1.15.2

### PR DESCRIPTION
**Pull request by zentol**

### CODE REVIEW

**Comment by zentol** [comment]
hmm, not really sure what to make of the naughty error message :/

**Comment by tianon** [comment]
That's unfortunately the downstream effect of https://github.com/docker-library/docs/pull/2162#issuecomment-1172781329 -- `openjdk:8*` and `openjdk:11*` are no longer maintained/supported.

See the top notice on https://hub.docker.com/_/openjdk for a list of alternative images/builds of OpenJDK 8 and 11 that might meet your needs.

**Comment by zentol** [comment]
Got it, unfortunate that none of us noticed your ping :/

We'll get right on that. 👍

**Comment by zentol** [comment]
@tianon We've updated the images to be based on eclipse-temurin. Would it be possible to merge this on Wednesday so we can give our users some notice beforehand?

**Comment by tianon** [comment]
Good to go now?  (or do you want to give it more time?)

**Comment by zentol** [comment]
@tianon Yes, we're good to go 👍

**Pull request merged**
