### PR TITLE
elixir 1.15.6

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Is skipping from 4 to 6 (and skipping over 5 intentional?

**Comment by getong** [comment]
> Is skipping from 4 to 6 (and skipping over 5 intentional?

No. I am busy with something, and cause something ignored by accident.

**Comment by LaurentGoderre** [comment]
@getong I don't think it's you, it seems the upstream repo did the skipping

**Comment by epinault** [comment]
@LaurentGoderre I did the upstream MR because nothing existed (neither .5 or .6 ) so I created the .6 cause I would like to get the latest . does it matter the .5 is not released?

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
