### PR TITLE
Remove deprecated "java" manifest (updating rapidoid and tomee to account for the deprecation)

### PR DESCRIPTION
**Pull request by tianon**
cc @nmihajlovski @lordofthejars (FYI)

### CODE REVIEW

**Comment by tianon** [comment]
(Had to patch `diff-pr.sh` locally to even generate this diff to work around similar assumptions to what we're seeing in that Travis failure :smile:)
```diff
error: failed fetching repo "java"
unable to find a manifest named "java" (in "/tmp/tmp.pvQeh5nrtt/oi/library" or as a remote URL)
diff --git a/java_openjdk-6-jre/Dockerfile b/java_openjdk-6-jre/Dockerfile
deleted file mode 100644
index 57b41df..0000000
diff --git a/java_openjdk-6/Dockerfile b/java_openjdk-6/Dockerfile
deleted file mode 100644
index bf7c655..0000000
diff --git a/java_openjdk-7-alpine/Dockerfile b/java_openjdk-7-alpine/Dockerfile
deleted file mode 100644
index c35f262..0000000
diff --git a/java_openjdk-7-jre-alpine/Dockerfile b/java_openjdk-7-jre-alpine/Dockerfile
deleted file mode 100644
index 492ee89..0000000
diff --git a/java_openjdk-7-jre/Dockerfile b/java_openjdk-7-jre/Dockerfile
deleted file mode 100644
index 0b5da5e..0000000
diff --git a/java_openjdk-7/Dockerfile b/java_openjdk-7/Dockerfile
deleted file mode 100644
index c7970a1..0000000
diff --git a/java_openjdk-8-alpine/Dockerfile b/java_openjdk-8-alpine/Dockerfile
deleted file mode 100644
index b4f4088..0000000
diff --git a/java_openjdk-8-jre-alpine/Dockerfile b/java_openjdk-8-jre-alpine/Dockerfile
deleted file mode 100644
index c4d75bc..0000000
diff --git a/java_openjdk-8-jre/Dockerfile b/java_openjdk-8-jre/Dockerfile
deleted file mode 100644
index 17d3d90..0000000
diff --git a/java_openjdk-8/Dockerfile b/java_openjdk-8/Dockerfile
deleted file mode 100644
index e87ddc1..0000000
diff --git a/java_openjdk-9-jre/Dockerfile b/java_openjdk-9-jre/Dockerfile
deleted file mode 100644
index 56d4ee6..0000000
diff --git a/java_openjdk-9/Dockerfile b/java_openjdk-9/Dockerfile
deleted file mode 100644
index ccbb58c..0000000
diff --git a/rapidoid_latest/Dockerfile b/rapidoid_latest/Dockerfile
index 377e3ea..a9c3f7e 100644
--- a/rapidoid_latest/Dockerfile
+++ b/rapidoid_latest/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 MAINTAINER Nikolche Mihajlovski
 
 # GPG key of Rapidoid's author/maintainer (616EF49C: Nikolche Mihajlovski <nikolce.mihajlovski@gmail.com>)
diff --git a/rapidoid_latest/entrypoint.sh b/rapidoid_latest/entrypoint.sh
index 9428b55..d8c06aa 100755
--- a/rapidoid_latest/entrypoint.sh
+++ b/rapidoid_latest/entrypoint.sh
@@ -5,7 +5,7 @@ if ! command -v -- "$1" >/dev/null 2>&1
 then
   set -- java \
     -Djava.io.tmpdir="$RAPIDOID_TMP" \
-    -cp "$RAPIDOID_JAR":/app/app.jar:/app/jars/*.jar org.rapidoid.standalone.Main \
+    -jar "$RAPIDOID_JAR" \
     "$@"
 fi
 
diff --git a/tomee_6-jre-1.7.4-jaxrs/Dockerfile b/tomee_6-jre-1.7.4-jaxrs/Dockerfile
index 4dcdee1..d5b682d 100644
--- a/tomee_6-jre-1.7.4-jaxrs/Dockerfile
+++ b/tomee_6-jre-1.7.4-jaxrs/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_6-jre-1.7.4-plume/Dockerfile b/tomee_6-jre-1.7.4-plume/Dockerfile
index 0587d8e..ac0a581 100644
--- a/tomee_6-jre-1.7.4-plume/Dockerfile
+++ b/tomee_6-jre-1.7.4-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_6-jre-1.7.4-plus/Dockerfile b/tomee_6-jre-1.7.4-plus/Dockerfile
index 649a379..7ced024 100644
--- a/tomee_6-jre-1.7.4-plus/Dockerfile
+++ b/tomee_6-jre-1.7.4-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_6-jre-1.7.4-webprofile/Dockerfile b/tomee_6-jre-1.7.4-webprofile/Dockerfile
index b90b395..25dc222 100644
--- a/tomee_6-jre-1.7.4-webprofile/Dockerfile
+++ b/tomee_6-jre-1.7.4-webprofile/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-jaxrs/Dockerfile b/tomee_7-jre-1.7.4-jaxrs/Dockerfile
index b733dff..0d2fdd0 100644
--- a/tomee_7-jre-1.7.4-jaxrs/Dockerfile
+++ b/tomee_7-jre-1.7.4-jaxrs/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-plume/Dockerfile b/tomee_7-jre-1.7.4-plume/Dockerfile
index d095a9e..48890bb 100644
--- a/tomee_7-jre-1.7.4-plume/Dockerfile
+++ b/tomee_7-jre-1.7.4-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-plus/Dockerfile b/tomee_7-jre-1.7.4-plus/Dockerfile
index b0eaa54..f0a5703 100644
--- a/tomee_7-jre-1.7.4-plus/Dockerfile
+++ b/tomee_7-jre-1.7.4-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-webprofile/Dockerfile b/tomee_7-jre-1.7.4-webprofile/Dockerfile
index 1b5eb74..6f122f4 100644
--- a/tomee_7-jre-1.7.4-webprofile/Dockerfile
+++ b/tomee_7-jre-1.7.4-webprofile/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jdk-7.0.1-plume/Dockerfile b/tomee_8-jdk-7.0.1-plume/Dockerfile
index f8a4548..ec5906b 100644
--- a/tomee_8-jdk-7.0.1-plume/Dockerfile
+++ b/tomee_8-jdk-7.0.1-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jdk
+FROM openjdk:8-jdk
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jdk-7.0.1-plus/Dockerfile b/tomee_8-jdk-7.0.1-plus/Dockerfile
index eb9e775..0bb9160 100644
--- a/tomee_8-jdk-7.0.1-plus/Dockerfile
+++ b/tomee_8-jdk-7.0.1-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jdk
+FROM openjdk:8-jdk
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-jaxrs/Dockerfile b/tomee_8-jre-1.7.4-jaxrs/Dockerfile
index f578061..833a031 100644
--- a/tomee_8-jre-1.7.4-jaxrs/Dockerfile
+++ b/tomee_8-jre-1.7.4-jaxrs/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-plume/Dockerfile b/tomee_8-jre-1.7.4-plume/Dockerfile
index d79d16c..c557773 100644
--- a/tomee_8-jre-1.7.4-plume/Dockerfile
+++ b/tomee_8-jre-1.7.4-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-plus/Dockerfile b/tomee_8-jre-1.7.4-plus/Dockerfile
index 197ab67..47c8243 100644
--- a/tomee_8-jre-1.7.4-plus/Dockerfile
+++ b/tomee_8-jre-1.7.4-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-webprofile/Dockerfile b/tomee_8-jre-1.7.4-webprofile/Dockerfile
index 54d6f5e..0e3f88a 100644
--- a/tomee_8-jre-1.7.4-webprofile/Dockerfile
+++ b/tomee_8-jre-1.7.4-webprofile/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_latest/Dockerfile b/tomee_latest/Dockerfile
index b4a72b6..0754167 100644
--- a/tomee_latest/Dockerfile
+++ b/tomee_latest/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jdk
+FROM openjdk:8-jdk
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
```

**Comment by tianon** [comment]
Arg, going to have to make similar patches to `test-pr.sh` for the same silly assumptions. :disappointed:

**Comment by tianon** [comment]
Went for an explicit image list instead to simply side-step the `test-pr.sh` issue.

Looks like TomEE 7.0.1 is failing to build:
```
$ bashbrew build tomee:8-jdk-7.0.1-webprofile
Building bashbrew/cache:fee087765028578b364c2f61722f255bf550aa7ed8c63269699af652af065d0c (tomee:8-jdk-7.0.1-webprofile)
error: failed building "tomee" (tags "8-jdk-7.0.1-webprofile, latest")
exit status 1
docker ["build" "-t" "bashbrew/cache:fee087765028578b364c2f61722f255bf550aa7ed8c63269699af652af065d0c" "--rm" "--force-rm" "-"] output:
Sending build context to Docker daemon 10.24 kB
Step 1/9 : FROM openjdk:8-jdk
 ---> 836f9fc9d5cd
Step 2/9 : ENV PATH /usr/local/tomee/bin:$PATH
 ---> Using cache
 ---> c2c5a720efd7
Step 3/9 : RUN mkdir -p /usr/local/tomee
 ---> Using cache
 ---> ff843d81624d
Step 4/9 : WORKDIR /usr/local/tomee
 ---> Using cache
 ---> 011e73d00011
Step 5/9 : ENV GPG_KEYS BDD0BBEB753192957EFC5F896A62FC8EF17D8FEF 	223D3A74B068ECA354DC385CE126833F9CF64915 	7A2744A8A9AAF063C23EB7868EBE7DBE8D050EEF 	82D8419BA697F0E7FB85916EE91287822FDB81B1 	9056B710F1E332780DE7AF34CBAEBE39A46C4CA1 	A57DAF81C1B69921F4BA8723A8DE0A4DB863A7C1 	B7574789F5018690043E6DD9C212662E12F3E1DD 	B8B301E6105DF628076BD92C5483E55897ABD9B9 	DBCCD103B8B24F86FFAAB025C8BB472CD297D428 	F067B8140F5DD80E1D3B5D92318242FE9A0B1183 	FAA603D58B1BA4EDF65896D0ED340E0E6D545F97
 ---> Using cache
 ---> eb05ba777c9c
Step 6/9 : RUN set -xe 	&& for key in $GPG_KEYS; do 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 	done
 ---> Using cache
 ---> 253abc223417
Step 7/9 : RUN set -x 	&& curl -fSL https://dist.apache.org/repos/dist/release/tomee/tomee-7.0.1/apache-tomee-7.0.1-webprofile.tar.gz.asc -o tomee.tar.gz.asc 	&& curl -fSL http://apache.rediris.es/tomee/tomee-7.0.1/apache-tomee-7.0.1-webprofile.tar.gz -o tomee.tar.gz 	&& gpg --batch --verify tomee.tar.gz.asc tomee.tar.gz 	&& tar -zxf tomee.tar.gz 	&& mv apache-tomee-webprofile-7.0.1/* /usr/local/tomee 	&& rm -Rf apache-tomee-webprofile-7.0.1 	&& rm bin/*.bat && rm tomee.tar.gz*
 ---> Running in 60c21efa4c9b
+ curl -fSL https://dist.apache.org/repos/dist/release/tomee/tomee-7.0.1/apache-tomee-7.0.1-webprofile.tar.gz.asc -o tomee.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Removing intermediate container 60c21efa4c9b
The command '/bin/sh -c set -x 	&& curl -fSL https://dist.apache.org/repos/dist/release/tomee/tomee-7.0.1/apache-tomee-7.0.1-webprofile.tar.gz.asc -o tomee.tar.gz.asc 	&& curl -fSL http://apache.rediris.es/tomee/tomee-7.0.1/apache-tomee-7.0.1-webprofile.tar.gz -o tomee.tar.gz 	&& gpg --batch --verify tomee.tar.gz.asc tomee.tar.gz 	&& tar -zxf tomee.tar.gz 	&& mv apache-tomee-webprofile-7.0.1/* /usr/local/tomee 	&& rm -Rf apache-tomee-webprofile-7.0.1 	&& rm bin/*.bat 	&& rm tomee.tar.gz*' returned a non-zero code: 22
```

**Comment by tianon** [comment]
I _think_ this is because TomEE 7.0.2 is out and Apache is pretty aggressive about removing old versions from their mirrors/dist.

**Comment by nmihajlovski** [comment]
@tianon Hi, please take a look at PR #2700, which I created just now. It includes the migration from "java" to "openjdk" and also the latest Rapidoid release (5.3.0).

**Comment by tianon** [comment]
Thanks @nmihajlovski -- I've removed `rapidoid` from this PR accordingly. :heart:

**Comment by tianon** [comment]
@lordofthejars is the `tomee` image still something you're interested in continuing to maintain?  Is there somewhere we could reach out to the community for co-maintainers?  Is there more I/we can do to help?  If things are _really_ dire we can deprecate the image (even temporarily until another maintainer can be found), but maybe we don't need to go to that extreme yet?

**Comment by tianon** [comment]
Updated again, given https://github.com/docker-library/official-images/pull/2698! :tada: :heart:

cc @otaviojava -- this now bumps the other tags of `tomee` too, and switches to the newer file format (which should make it easier to update in the future)

Getting an ACK or request for changes would be :+1: :heart: :pray:

**Comment by tianon** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/tomee_6-jre-1.7.4-jaxrs/Dockerfile b/tomee_6-jre-1.7.4-jaxrs/Dockerfile
index 4dcdee1..d5b682d 100644
--- a/tomee_6-jre-1.7.4-jaxrs/Dockerfile
+++ b/tomee_6-jre-1.7.4-jaxrs/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_6-jre-1.7.4-plume/Dockerfile b/tomee_6-jre-1.7.4-plume/Dockerfile
index 0587d8e..ac0a581 100644
--- a/tomee_6-jre-1.7.4-plume/Dockerfile
+++ b/tomee_6-jre-1.7.4-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_6-jre-1.7.4-plus/Dockerfile b/tomee_6-jre-1.7.4-plus/Dockerfile
index 649a379..7ced024 100644
--- a/tomee_6-jre-1.7.4-plus/Dockerfile
+++ b/tomee_6-jre-1.7.4-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_6-jre-1.7.4-webprofile/Dockerfile b/tomee_6-jre-1.7.4-webprofile/Dockerfile
index b90b395..25dc222 100644
--- a/tomee_6-jre-1.7.4-webprofile/Dockerfile
+++ b/tomee_6-jre-1.7.4-webprofile/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:6-jre
+FROM openjdk:6-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-jaxrs/Dockerfile b/tomee_7-jre-1.7.4-jaxrs/Dockerfile
index b733dff..0d2fdd0 100644
--- a/tomee_7-jre-1.7.4-jaxrs/Dockerfile
+++ b/tomee_7-jre-1.7.4-jaxrs/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-plume/Dockerfile b/tomee_7-jre-1.7.4-plume/Dockerfile
index d095a9e..48890bb 100644
--- a/tomee_7-jre-1.7.4-plume/Dockerfile
+++ b/tomee_7-jre-1.7.4-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-plus/Dockerfile b/tomee_7-jre-1.7.4-plus/Dockerfile
index b0eaa54..f0a5703 100644
--- a/tomee_7-jre-1.7.4-plus/Dockerfile
+++ b/tomee_7-jre-1.7.4-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_7-jre-1.7.4-webprofile/Dockerfile b/tomee_7-jre-1.7.4-webprofile/Dockerfile
index 1b5eb74..6f122f4 100644
--- a/tomee_7-jre-1.7.4-webprofile/Dockerfile
+++ b/tomee_7-jre-1.7.4-webprofile/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:7-jre
+FROM openjdk:7-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-jaxrs/Dockerfile b/tomee_8-jre-1.7.4-jaxrs/Dockerfile
index f578061..833a031 100644
--- a/tomee_8-jre-1.7.4-jaxrs/Dockerfile
+++ b/tomee_8-jre-1.7.4-jaxrs/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-plume/Dockerfile b/tomee_8-jre-1.7.4-plume/Dockerfile
index d79d16c..c557773 100644
--- a/tomee_8-jre-1.7.4-plume/Dockerfile
+++ b/tomee_8-jre-1.7.4-plume/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-plus/Dockerfile b/tomee_8-jre-1.7.4-plus/Dockerfile
index 197ab67..47c8243 100644
--- a/tomee_8-jre-1.7.4-plus/Dockerfile
+++ b/tomee_8-jre-1.7.4-plus/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
diff --git a/tomee_8-jre-1.7.4-webprofile/Dockerfile b/tomee_8-jre-1.7.4-webprofile/Dockerfile
index 54d6f5e..0e3f88a 100644
--- a/tomee_8-jre-1.7.4-webprofile/Dockerfile
+++ b/tomee_8-jre-1.7.4-webprofile/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:8-jre
+FROM openjdk:8-jre
 
 ENV PATH /usr/local/tomee/bin:$PATH
 RUN mkdir -p /usr/local/tomee
````

</details>

**Comment by tianon** [comment]
And just to show that this is indeed the final stretch:
```console
$ bashbrew children java
tomee:6-jre-1.7.4-jaxrs
tomee:6-jre-1.7.4-plume
tomee:6-jre-1.7.4-plus
tomee:6-jre-1.7.4-webprofile
tomee:7-jre-1.7.4-jaxrs
tomee:7-jre-1.7.4-plume
tomee:7-jre-1.7.4-plus
tomee:7-jre-1.7.4-webprofile
tomee:8-jre-1.7.4-jaxrs
tomee:8-jre-1.7.4-plume
tomee:8-jre-1.7.4-plus
tomee:8-jre-1.7.4-webprofile
```

**Comment by yosifkit** [comment]
Build test failure is irrelevant since it is not able to handle an image removal.

https://travis-ci.org/docker-library/official-images/builds/233406192#L302-L304

**Pull request merged**
