### PR TITLE
Update Ubuntu 2022-09-02

### PR DESCRIPTION
**Pull request by ROCKsBot**
Update Ubuntu to latest published rootfs tarballs as of 2022-09-02.

### CODE REVIEW

**Comment by woky** [comment]
This is only update of bionic to fix incorrect package introduced by mistake in previous build causing conflicts:
- https://bugs.launchpad.net/cloud-images/+bug/1988498
- https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1988523

**Comment by woky** [comment]
Not sure why the _Diff Comment_ job failed. We run `bashbrew` on the ubuntu library file before submitting PR and it run time.

**Comment by tianon** [comment]
I think what's happening is that diff-pr is trying to check out the old version (so it can generate a diff from old to new) and Launchpad's Git doesn't support the direct-SHA1-fetch to give us that older commit :grimacing:

**Comment by woky** [comment]
> I think what's happening is that diff-pr is trying to check out the old version (so it can generate a diff from old to new) and Launchpad's Git doesn't support the direct-SHA1-fetch to give us that older commit grimacing

I'm going to ask Launchpad to enable direct-SHA1-fetch. In the meantime, could we please merge this with diff created by me?

```diff
diff --git a/bionic-minimal-cloudimg-amd64-root.manifest b/bionic-minimal-cloudimg-amd64-root.manifest
index 08d31a6..43f27ca 100644
--- a/bionic-minimal-cloudimg-amd64-root.manifest
+++ b/bionic-minimal-cloudimg-amd64-root.manifest
@@ -64,10 +64,10 @@ libsepol1:amd64	2.7-1ubuntu0.1
 libsmartcols1:amd64	2.31.1-0.4ubuntu3.7
 libss2:amd64	1.44.1-1ubuntu1.4
 libstdc++6:amd64	8.4.0-1ubuntu1~18.04
-libsystemd0:amd64	237-3ubuntu10.54
+libsystemd0:amd64	237-3ubuntu10.53
 libtasn1-6:amd64	4.13-2
 libtinfo5:amd64	6.1-1ubuntu1.18.04
-libudev1:amd64	237-3ubuntu10.54
+libudev1:amd64	237-3ubuntu10.53
 libunistring2:amd64	0.9.9-0ubuntu2
 libuuid1:amd64	2.31.1-0.4ubuntu3.7
 libzstd1:amd64	1.3.3+dfsg-2ubuntu1.2
diff --git a/bionic-minimal-cloudimg-arm64-root.manifest b/bionic-minimal-cloudimg-arm64-root.manifest
index d7c83da..0e47f99 100644
--- a/bionic-minimal-cloudimg-arm64-root.manifest
+++ b/bionic-minimal-cloudimg-arm64-root.manifest
@@ -64,10 +64,10 @@ libsepol1:arm64	2.7-1ubuntu0.1
 libsmartcols1:arm64	2.31.1-0.4ubuntu3.7
 libss2:arm64	1.44.1-1ubuntu1.4
 libstdc++6:arm64	8.4.0-1ubuntu1~18.04
-libsystemd0:arm64	237-3ubuntu10.54
+libsystemd0:arm64	237-3ubuntu10.53
 libtasn1-6:arm64	4.13-2
 libtinfo5:arm64	6.1-1ubuntu1.18.04
-libudev1:arm64	237-3ubuntu10.54
+libudev1:arm64	237-3ubuntu10.53
 libunistring2:arm64	0.9.9-0ubuntu2
 libuuid1:arm64	2.31.1-0.4ubuntu3.7
 libzstd1:arm64	1.3.3+dfsg-2ubuntu1.2
diff --git a/bionic-minimal-cloudimg-armhf-root.manifest b/bionic-minimal-cloudimg-armhf-root.manifest
index da1d384..804c50b 100644
--- a/bionic-minimal-cloudimg-armhf-root.manifest
+++ b/bionic-minimal-cloudimg-armhf-root.manifest
@@ -64,10 +64,10 @@ libsepol1:armhf	2.7-1ubuntu0.1
 libsmartcols1:armhf	2.31.1-0.4ubuntu3.7
 libss2:armhf	1.44.1-1ubuntu1.4
 libstdc++6:armhf	8.4.0-1ubuntu1~18.04
-libsystemd0:armhf	237-3ubuntu10.54
+libsystemd0:armhf	237-3ubuntu10.53
 libtasn1-6:armhf	4.13-2
 libtinfo5:armhf	6.1-1ubuntu1.18.04
-libudev1:armhf	237-3ubuntu10.54
+libudev1:armhf	237-3ubuntu10.53
 libunistring2:armhf	0.9.9-0ubuntu2
 libuuid1:armhf	2.31.1-0.4ubuntu3.7
 libzstd1:armhf	1.3.3+dfsg-2ubuntu1.2
diff --git a/bionic-minimal-cloudimg-i386-root.manifest b/bionic-minimal-cloudimg-i386-root.manifest
index 7a465ae..3098dca 100644
--- a/bionic-minimal-cloudimg-i386-root.manifest
+++ b/bionic-minimal-cloudimg-i386-root.manifest
@@ -64,10 +64,10 @@ libsepol1:i386	2.7-1ubuntu0.1
 libsmartcols1:i386	2.31.1-0.4ubuntu3.7
 libss2:i386	1.44.1-1ubuntu1.4
 libstdc++6:i386	8.4.0-1ubuntu1~18.04
-libsystemd0:i386	237-3ubuntu10.54
+libsystemd0:i386	237-3ubuntu10.53
 libtasn1-6:i386	4.13-2
 libtinfo5:i386	6.1-1ubuntu1.18.04
-libudev1:i386	237-3ubuntu10.54
+libudev1:i386	237-3ubuntu10.53
 libunistring2:i386	0.9.9-0ubuntu2
 libuuid1:i386	2.31.1-0.4ubuntu3.7
 libzstd1:i386	1.3.3+dfsg-2ubuntu1.2
diff --git a/bionic-minimal-cloudimg-ppc64el-root.manifest b/bionic-minimal-cloudimg-ppc64el-root.manifest
index c411fb5..9da1017 100644
--- a/bionic-minimal-cloudimg-ppc64el-root.manifest
+++ b/bionic-minimal-cloudimg-ppc64el-root.manifest
@@ -64,10 +64,10 @@ libsepol1:ppc64el	2.7-1ubuntu0.1
 libsmartcols1:ppc64el	2.31.1-0.4ubuntu3.7
 libss2:ppc64el	1.44.1-1ubuntu1.4
 libstdc++6:ppc64el	8.4.0-1ubuntu1~18.04
-libsystemd0:ppc64el	237-3ubuntu10.54
+libsystemd0:ppc64el	237-3ubuntu10.53
 libtasn1-6:ppc64el	4.13-2
 libtinfo5:ppc64el	6.1-1ubuntu1.18.04
-libudev1:ppc64el	237-3ubuntu10.54
+libudev1:ppc64el	237-3ubuntu10.53
 libunistring2:ppc64el	0.9.9-0ubuntu2
 libuuid1:ppc64el	2.31.1-0.4ubuntu3.7
 libzstd1:ppc64el	1.3.3+dfsg-2ubuntu1.2
diff --git a/bionic-minimal-cloudimg-s390x-root.manifest b/bionic-minimal-cloudimg-s390x-root.manifest
index 2d47546..9d2a993 100644
--- a/bionic-minimal-cloudimg-s390x-root.manifest
+++ b/bionic-minimal-cloudimg-s390x-root.manifest
@@ -64,10 +64,10 @@ libsepol1:s390x	2.7-1ubuntu0.1
 libsmartcols1:s390x	2.31.1-0.4ubuntu3.7
 libss2:s390x	1.44.1-1ubuntu1.4
 libstdc++6:s390x	8.4.0-1ubuntu1~18.04
-libsystemd0:s390x	237-3ubuntu10.54
+libsystemd0:s390x	237-3ubuntu10.53
 libtasn1-6:s390x	4.13-2
 libtinfo5:s390x	6.1-1ubuntu1.18.04
-libudev1:s390x	237-3ubuntu10.54
+libudev1:s390x	237-3ubuntu10.53
 libunistring2:s390x	0.9.9-0ubuntu2
 libuuid1:s390x	2.31.1-0.4ubuntu3.7
 libzstd1:s390x	1.3.3+dfsg-2ubuntu1.2
```

**Comment by toabctl** [comment]
The current bionic image is broken (see https://bugs.launchpad.net/cloud-images/+bug/1988498) so please get this in and fix the diff afterwards.

**Comment by tianon** [comment]
> I'm going to ask Launchpad to enable direct-SHA1-fetch.

Our infrastructure relies on this, so please be sure to follow up on it - if it's not something they can/will resolve, we'll need to have the tarballs hosted/mirrored somewhere that does. :grimacing:

I happened to have a system that has the old commits cached, so I was able to run `diff-pr.sh` on it for the following:

<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-cat b/_bashbrew-cat
index 0e61156..b494468 100644
--- a/_bashbrew-cat
+++ b/_bashbrew-cat
@@ -1,19 +1,19 @@
-Maintainers: Tomáš Virtus <tomas.virtus@canonical.com> (@woky), Michael Hudson-Doyle <michael.hudson@ubuntu.com> (@mwhudson)
+Maintainers: Tomáš Virtus <tomas.virtus@canonical.com> (@woky), Tianon Gravi <tianon@debian.org> (@tianon), Michael Hudson-Doyle <michael.hudson@ubuntu.com> (@mwhudson)
 GitRepo: https://git.launchpad.net/cloud-images/+oci/ubuntu-base
 GitCommit: 42f91a1d38193121ecc9c3bf95a19c4ceed38f58
-amd64-GitCommit: 0b99ba2f4ec4dbe55b72c6b1c81eed4393b33346
+amd64-GitCommit: 67c49edefdf22f85b968f789723c71373e89f47d
 amd64-GitFetch: refs/heads/dist-amd64
-arm32v7-GitCommit: c1c74b7c7d3a868121c8ae5148524a720a08bcfb
+arm32v7-GitCommit: 9fd8dd8b63b291898b04b6e2d75a764973ad2c87
 arm32v7-GitFetch: refs/heads/dist-arm32v7
-arm64v8-GitCommit: 61d299eb91851e63d5f9b83deb2363f7520a904b
+arm64v8-GitCommit: 5794a1d22cc57a5dc3dc239db3e1bd0dd0e23d90
 arm64v8-GitFetch: refs/heads/dist-arm64v8
-i386-GitCommit: 593ab9e382c2142a2e86be9935a67ab6cbddb49d
+i386-GitCommit: 4e4a1f81dc8e4486b7b34c3fdf8bd0a555d7d545
 i386-GitFetch: refs/heads/dist-i386
-ppc64le-GitCommit: 593875aba76071397a2e2b5cc2c79ac3f129afbd
+ppc64le-GitCommit: 92acf4ac029c532a59f1df67650a647eec1cf05d
 ppc64le-GitFetch: refs/heads/dist-ppc64le
 riscv64-GitCommit: 0fb69a7b05d5a35fc6a2893d1fddc4945f6a8589
 riscv64-GitFetch: refs/heads/dist-riscv64
-s390x-GitCommit: 1802deb23dd5dbe15f52d9283a79d19fe966207b
+s390x-GitCommit: 09bab0f6d892ef80872e7305f9075f122a6eb0c8
 s390x-GitFetch: refs/heads/dist-s390x
 
 Tags: 14.04, trusty-20191217, trusty
@@ -24,7 +24,7 @@ Tags: 16.04, xenial-20210804, xenial
 Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
 Directory: xenial
 
-Tags: 18.04, bionic-20220829, bionic
+Tags: 18.04, bionic-20220902, bionic
 Architectures: amd64, arm32v7, arm64v8, i386, ppc64le, s390x
 Directory: bionic
 
diff --git a/_bashbrew-list b/_bashbrew-list
index 785636f..a793768 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -5,7 +5,7 @@ ubuntu:20.04
 ubuntu:22.04
 ubuntu:22.10
 ubuntu:bionic
-ubuntu:bionic-20220829
+ubuntu:bionic-20220902
 ubuntu:devel
 ubuntu:focal
 ubuntu:focal-20220826
diff --git a/ubuntu_bionic/build-info.txt b/ubuntu_bionic/build-info.txt
index d93680e..52c9624 100644
--- a/ubuntu_bionic/build-info.txt
+++ b/ubuntu_bionic/build-info.txt
@@ -1 +1 @@
-SERIAL=20220829
+SERIAL=20220902
diff --git a/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.manifest b/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.manifest
index 08d31a6..43f27ca 100644
--- a/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.manifest
+++ b/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.manifest
@@ -64,10 +64,10 @@ libsepol1:amd64	2.7-1ubuntu0.1
 libsmartcols1:amd64	2.31.1-0.4ubuntu3.7
 libss2:amd64	1.44.1-1ubuntu1.4
 libstdc++6:amd64	8.4.0-1ubuntu1~18.04
-libsystemd0:amd64	237-3ubuntu10.54
+libsystemd0:amd64	237-3ubuntu10.53
 libtasn1-6:amd64	4.13-2
 libtinfo5:amd64	6.1-1ubuntu1.18.04
-libudev1:amd64	237-3ubuntu10.54
+libudev1:amd64	237-3ubuntu10.53
 libunistring2:amd64	0.9.9-0ubuntu2
 libuuid1:amd64	2.31.1-0.4ubuntu3.7
 libzstd1:amd64	1.3.3+dfsg-2ubuntu1.2
diff --git a/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.tar.gz b/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.tar.gz
index 459b78a..7986ca0 100644
Binary files a/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.tar.gz and b/ubuntu_bionic/ubuntu-bionic-oci-amd64-root.tar.gz differ
```

</details>

(Which matches yours :+1: :heart:)

**Comment by woky** [comment]
@tianon I asked Launchpad to enable this, but I wonder, didn't it work only by accident with https://github.com/tianon/docker-brew-ubuntu-core/? Once you update branches there, the commit IDs in currently committed library file are no longer referenced by any ref in the repo, so Git server is free to garbage collect them. it seems to me that in case of GitHub this garbage collection (`git prune`) may be delayed and so far it only worked because we make PR shortly after updating branches. Does what I say make sense? I'm no Git expert.

I've made changes to our CI/CD to use ref structure similar to what you suggested here https://github.com/docker-library/official-images/pull/13010#issuecomment-1226307077, except it's tag-per-arch-suite. These refs will be immutable and will stay around as long as they are referenced in `library/ubuntu` in this repository. It looks like this: https://github.com/woky/official-images/pull/35/files. I've tried to build it with bashbrew and it works. Bashbrew can work without direct-SHA1-fetch capability seemingly by falling back to fetching `GitFetch` and finding the commit in the history. Can `diff-pr.sh` do the same or does it always do direct-SHA1-fetch?

**Comment by tianon** [comment]
> didn't it work only by accident with https://github.com/tianon/docker-brew-ubuntu-core/?

No, because GitHub doesn't garbage collect: https://github.com/tianon/docker-brew-ubuntu-core/commit/8c85eb1f0adfbcb99ac60402461d465f136ad441 :sweat_smile:
(note the date on that commit -- that's the first commit we used from that specific repository in `library/ubuntu`, still happily available even though it's long since unreferenced)

> It looks like this: https://github.com/woky/official-images/pull/35/files

This approach looks sane/workable :+1: :heart:

**Pull request merged**
