### PR TITLE
chore: release InfluxDB OSS v1.11.7

### PR DESCRIPTION
**Pull request by bnpfeife**

### CODE REVIEW

**Comment by yosifkit** [comment]
We don't yet use `ARG TARGETARCH` in official-images. We recommend using `apk --print-arch` or `dpkg --print-architecture` as the most reliable options to retrieve the userspace architecture of the image.

**Comment by tianon** [comment]
Generated a slightly more aggressive diff to try and get something easier to review the changes. :sweat_smile:

<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 45d7292..e85a97f 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,3 +1,2 @@
 amd64
-arm32v7
 arm64v8
diff --git a/_bashbrew-cat b/_bashbrew-cat
index 985934d..901dfcd 100644
--- a/_bashbrew-cat
+++ b/_bashbrew-cat
@@ -1,25 +1,6 @@
 Maintainers: Brandon Pfeifer <bpfeifer@influxdata.com> (@bnpfeife), Geoffrey Wossum <gwossum@influxdata.com> (@gwossum), Michael Gattozzi <mgattozzi@influxdata.com> (@mgattozzi), Trevor Hilton <thilton@influxdata.com> (@hiltontj)
 GitRepo: https://github.com/influxdata/influxdata-docker
-GitCommit: 652e8809eda9c7fa7f0ef81f26acb246bb935801
-
-Tags: 1.8, 1.8.10
-Architectures: amd64, arm32v7, arm64v8
-Directory: influxdb/1.8
-
-Tags: 1.8-alpine, 1.8.10-alpine
-Directory: influxdb/1.8/alpine
-
-Tags: 1.9-data, 1.9.13-data
-Directory: influxdb/1.9/data
-
-Tags: 1.9-data-alpine, 1.9.13-data-alpine
-Directory: influxdb/1.9/data/alpine
-
-Tags: 1.9-meta, 1.9.13-meta
-Directory: influxdb/1.9/meta
-
-Tags: 1.9-meta-alpine, 1.9.13-meta-alpine
-Directory: influxdb/1.9/meta/alpine
+GitCommit: aa5f51f7aa5d6ae4b3f236b8ed20105a5fe0b80d
 
 Tags: 1.10-data, 1.10.7-data
 Directory: influxdb/1.10/data
@@ -33,6 +14,14 @@ Directory: influxdb/1.10/meta
 Tags: 1.10-meta-alpine, 1.10.7-meta-alpine
 Directory: influxdb/1.10/meta/alpine
 
+Tags: 1.11, 1.11.7
+Architectures: amd64, arm64v8
+Directory: influxdb/1.11
+
+Tags: 1.11-alpine, 1.11.7-alpine
+Architectures: amd64, arm64v8
+Directory: influxdb/1.11/alpine
+
 Tags: 1.11-data, 1.11.7-data
 Directory: influxdb/1.11/data
 
diff --git a/_bashbrew-list b/_bashbrew-list
index c4827db..0029cf4 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -1,15 +1,3 @@
-influxdb:1.8
-influxdb:1.8-alpine
-influxdb:1.8.10
-influxdb:1.8.10-alpine
-influxdb:1.9-data
-influxdb:1.9-data-alpine
-influxdb:1.9-meta
-influxdb:1.9-meta-alpine
-influxdb:1.9.13-data
-influxdb:1.9.13-data-alpine
-influxdb:1.9.13-meta
-influxdb:1.9.13-meta-alpine
 influxdb:1.10-data
 influxdb:1.10-data-alpine
 influxdb:1.10-meta
@@ -18,10 +6,14 @@ influxdb:1.10.7-data
 influxdb:1.10.7-data-alpine
 influxdb:1.10.7-meta
 influxdb:1.10.7-meta-alpine
+influxdb:1.11
+influxdb:1.11-alpine
 influxdb:1.11-data
 influxdb:1.11-data-alpine
 influxdb:1.11-meta
 influxdb:1.11-meta-alpine
+influxdb:1.11.7
+influxdb:1.11.7-alpine
 influxdb:1.11.7-data
 influxdb:1.11.7-data-alpine
 influxdb:1.11.7-meta
diff --git a/_bashbrew-list-build-order b/_bashbrew-list-build-order
index fbf5c27..1748019 100644
--- a/_bashbrew-list-build-order
+++ b/_bashbrew-list-build-order
@@ -1,13 +1,9 @@
-influxdb:1.8.10
-influxdb:1.8.10-alpine
-influxdb:1.9.13-data
-influxdb:1.9.13-data-alpine
-influxdb:1.9.13-meta
-influxdb:1.9.13-meta-alpine
 influxdb:1.10.7-data
 influxdb:1.10.7-data-alpine
 influxdb:1.10.7-meta
 influxdb:1.10.7-meta-alpine
+influxdb:1.11.7
+influxdb:1.11.7-alpine
 influxdb:1.11.7-data
 influxdb:1.11.7-data-alpine
 influxdb:1.11.7-meta
diff --git a/influxdb_1.9-data-alpine/Dockerfile b/influxdb_1.11-alpine/Dockerfile
similarity index 15%
rename from influxdb_1.9-data-alpine/Dockerfile
rename to influxdb_1.11-alpine/Dockerfile
index 603c765..20ea4b3 100644
--- a/influxdb_1.9-data-alpine/Dockerfile
+++ b/influxdb_1.11-alpine/Dockerfile
@@ -1,35 +1,49 @@
-FROM alpine:3.17
+FROM alpine:3.20
 
-RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
-RUN apk add --no-cache tzdata bash ca-certificates && \
+RUN apk add --no-cache \
+      bash \
+      ca-certificates \
+      tzdata && \
     update-ca-certificates
 
-ENV INFLUXDB_VERSION 1.9.13-c1.9.13
-RUN set -ex && \
-    apk add --no-cache --virtual .build-deps wget gnupg tar && \
-    for key in \
-        9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E ; \
-    do \
-        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
-    done && \
-    wget --no-verbose https://dl.influxdata.com/enterprise/releases/influxdb-data-${INFLUXDB_VERSION}_linux_amd64.tar.gz.asc && \
-    wget --no-verbose https://dl.influxdata.com/enterprise/releases/influxdb-data-${INFLUXDB_VERSION}_linux_amd64.tar.gz && \
-    gpg --batch --verify influxdb-data-${INFLUXDB_VERSION}_linux_amd64.tar.gz.asc influxdb-data-${INFLUXDB_VERSION}_linux_amd64.tar.gz && \
-    mkdir -p /usr/src && \
-    tar -C /usr/src -xzf influxdb-data-${INFLUXDB_VERSION}_linux_amd64.tar.gz && \
-    rm -f /usr/src/influxdb-*/etc/influxdb/influxdb.conf && \
-    chmod +x /usr/src/influxdb-*/usr/bin/* && \
-    cp -a /usr/src/influxdb-*/usr/bin/. /usr/bin/ && \
-    gpgconf --kill all && \
-    rm -rf *.tar.gz* /usr/src /root/.gnupg && \
+ARG INFLUXDB_VERSION=1.11.7
+RUN apk add --no-cache --virtual .build-deps \
+      curl \
+      gnupg \
+      tar && \
+    gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E && \
+    case "$(apk --print-arch)" in \
+      x86_64)  ARCH=amd64 ;; \
+      aarch64) ARCH=arm64 ;; \
+      *) exit 1 ;; \
+    esac && \
+    export INFLUXDB_TAR=influxdb-${INFLUXDB_VERSION}-linux-${ARCH}.tar.gz && \
+    export INFLUXDB_ASC=influxdb-${INFLUXDB_VERSION}-linux-${ARCH}.tar.gz.asc && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_TAR}" && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_ASC}" && \
+    gpg --batch --verify "${INFLUXDB_ASC}" "${INFLUXDB_TAR}" && \
+    tar -xf "${INFLUXDB_TAR}" -C /usr/bin \
+      ./influx \
+      ./influx_inspect \
+      ./influxd && \
+    rm -rf "${INFLUXDB_TAR}" \
+           "${INFLUXDB_ASC}" && \
     apk del .build-deps
 COPY influxdb.conf /etc/influxdb/influxdb.conf
 
-EXPOSE 8086
+RUN addgroup influxdb && \
+    adduser -S -s /bin/false -h /var/lib/influxdb -G influxdb influxdb && \
+    mkdir -p /var/lib/influxdb && \
+    mkdir -p /var/log/influxdb && \
+    chown influxdb:influxdb /var/lib/influxdb && \
+    chown influxdb:influxdb /var/log/influxdb && \
+    chmod 0750 /var/lib/influxdb && \
+    chmod 0750 /var/log/influxdb
 
+EXPOSE 8086
 VOLUME /var/lib/influxdb
-
 COPY entrypoint.sh /entrypoint.sh
 COPY init-influxdb.sh /init-influxdb.sh
+USER influxdb
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["influxd"]
diff --git a/influxdb_1.8-alpine/entrypoint.sh b/influxdb_1.11-alpine/entrypoint.sh
similarity index 100%
rename from influxdb_1.8-alpine/entrypoint.sh
rename to influxdb_1.11-alpine/entrypoint.sh
diff --git a/influxdb_1.8-alpine/influxdb.conf b/influxdb_1.11-alpine/influxdb.conf
similarity index 100%
rename from influxdb_1.8-alpine/influxdb.conf
rename to influxdb_1.11-alpine/influxdb.conf
diff --git a/influxdb_1.8-alpine/init-influxdb.sh b/influxdb_1.11-alpine/init-influxdb.sh
similarity index 100%
rename from influxdb_1.8-alpine/init-influxdb.sh
rename to influxdb_1.11-alpine/init-influxdb.sh
diff --git a/influxdb_1.9-data/Dockerfile b/influxdb_1.11/Dockerfile
similarity index 18%
rename from influxdb_1.9-data/Dockerfile
rename to influxdb_1.11/Dockerfile
index e4d461f..af6f7b1 100644
--- a/influxdb_1.9-data/Dockerfile
+++ b/influxdb_1.11/Dockerfile
@@ -1,27 +1,29 @@
-FROM buildpack-deps:bullseye-curl
+FROM buildpack-deps:bookworm-curl
 
-RUN set -ex && \
-    mkdir ~/.gnupg; \
-    echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf; \
-    for key in \
-        9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E ; \
-    do \
-        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
-    done
-
-ENV INFLUXDB_VERSION 1.9.13-c1.9.13
-RUN wget --no-verbose https://dl.influxdata.com/enterprise/releases/influxdb-data_${INFLUXDB_VERSION}_amd64.deb.asc && \
-    wget --no-verbose https://dl.influxdata.com/enterprise/releases/influxdb-data_${INFLUXDB_VERSION}_amd64.deb && \
-    gpg --batch --verify influxdb-data_${INFLUXDB_VERSION}_amd64.deb.asc influxdb-data_${INFLUXDB_VERSION}_amd64.deb && \
-    dpkg -i influxdb-data_${INFLUXDB_VERSION}_amd64.deb && \
-    rm -f influxdb-data_${INFLUXDB_VERSION}_amd64.deb*
+ARG INFLUXDB_VERSION=1.11.7
+RUN gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E && \
+    export DEBIAN_FRONTEND=noninteractive && \
+    apt-get update && \
+    case "$(dpkg --print-architecture)" in \
+      *amd64) ARCH=amd64 ;; \
+      *arm64) ARCH=arm64 ;; \
+      *) exit 1 ;; \
+    esac && \
+    export INFLUXDB_DEB=influxdb-${INFLUXDB_VERSION}-${ARCH}.deb && \
+    export INFLUXDB_ASC=influxdb-${INFLUXDB_VERSION}-${ARCH}.deb.asc && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_DEB}" && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_ASC}" && \
+    gpg --batch --verify "${INFLUXDB_ASC}" "${INFLUXDB_DEB}" && \
+    apt-get install -y "./${INFLUXDB_DEB}" && \
+    rm -rf "${INFLUXDB_DEB}" \
+           "${INFLUXDB_ASC}" \
+	   /var/lib/apt/lists/*
 COPY influxdb.conf /etc/influxdb/influxdb.conf
 
 EXPOSE 8086
-
 VOLUME /var/lib/influxdb
-
 COPY entrypoint.sh /entrypoint.sh
 COPY init-influxdb.sh /init-influxdb.sh
+USER influxdb
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["influxd"]
diff --git a/influxdb_1.8/entrypoint.sh b/influxdb_1.11/entrypoint.sh
similarity index 79%
rename from influxdb_1.8/entrypoint.sh
rename to influxdb_1.11/entrypoint.sh
index 26e6bd7..832091c 100755
diff --git a/influxdb_1.8/influxdb.conf b/influxdb_1.11/influxdb.conf
similarity index 100%
rename from influxdb_1.8/influxdb.conf
rename to influxdb_1.11/influxdb.conf
diff --git a/influxdb_1.8/init-influxdb.sh b/influxdb_1.11/init-influxdb.sh
similarity index 100%
rename from influxdb_1.8/init-influxdb.sh
rename to influxdb_1.11/init-influxdb.sh
diff --git a/influxdb_1.8-alpine/Dockerfile b/influxdb_1.8-alpine/Dockerfile
deleted file mode 100644
index 984d9d8..0000000
diff --git a/influxdb_1.8/Dockerfile b/influxdb_1.8/Dockerfile
deleted file mode 100644
index 45b00aa..0000000
diff --git a/influxdb_1.9-data-alpine/entrypoint.sh b/influxdb_1.9-data-alpine/entrypoint.sh
deleted file mode 100755
index 83d12eb..0000000
diff --git a/influxdb_1.9-data-alpine/influxdb.conf b/influxdb_1.9-data-alpine/influxdb.conf
deleted file mode 100644
index f03c128..0000000
diff --git a/influxdb_1.9-data-alpine/init-influxdb.sh b/influxdb_1.9-data-alpine/init-influxdb.sh
deleted file mode 100755
index 3f7349a..0000000
diff --git a/influxdb_1.9-data/entrypoint.sh b/influxdb_1.9-data/entrypoint.sh
deleted file mode 100755
index 83d12eb..0000000
diff --git a/influxdb_1.9-data/influxdb.conf b/influxdb_1.9-data/influxdb.conf
deleted file mode 100644
index f03c128..0000000
diff --git a/influxdb_1.9-data/init-influxdb.sh b/influxdb_1.9-data/init-influxdb.sh
deleted file mode 100755
index 3f7349a..0000000
diff --git a/influxdb_1.9-meta-alpine/Dockerfile b/influxdb_1.9-meta-alpine/Dockerfile
deleted file mode 100644
index 9143fe8..0000000
diff --git a/influxdb_1.9-meta-alpine/entrypoint.sh b/influxdb_1.9-meta-alpine/entrypoint.sh
deleted file mode 100755
index ae61bda..0000000
diff --git a/influxdb_1.9-meta-alpine/influxdb-meta.conf b/influxdb_1.9-meta-alpine/influxdb-meta.conf
deleted file mode 100644
index 6491d8a..0000000
diff --git a/influxdb_1.9-meta/Dockerfile b/influxdb_1.9-meta/Dockerfile
deleted file mode 100644
index 6af7e67..0000000
diff --git a/influxdb_1.9-meta/entrypoint.sh b/influxdb_1.9-meta/entrypoint.sh
deleted file mode 100755
index ae61bda..0000000
diff --git a/influxdb_1.9-meta/influxdb-meta.conf b/influxdb_1.9-meta/influxdb-meta.conf
deleted file mode 100644
index 6491d8a..0000000
```

</details>

**Comment by tianon** [comment]
A few minor notes:

- _all_ invocations of `gpg` ought to include `--batch` (it's the flag to tell GnuPG to go into "API mode", essentially); I don't think that's a big problem though, certainly not a blocker

- you probably want to choose an explicit UID/GID for your new `influxdb` user in both Alpine _and_ Debian, and you probably want to do so before you install influxdb (especially on Debian where the `.deb` is presumably creating the user otherwise, and probably _not_ with a fixed UID/GID); if you're looking for numeric suggestions, I usually suggest going with the "well-known port" of the service, so in your case that'd be 8086, but any value will do (it's just in your best interest to choose something that's unlikely to have conflicts, which high port numbers like that are usually pretty safe bets :smile:)

- related to the above, this is going to cause a little bit of user pain as they now need to adjust the permissions on any storage they're providing to the container in order to upgrade, right?  (this is mostly an FYI / making sure you're aware of the user implications :heart:)

**Comment by bnpfeife** [comment]
Thanks for your feedback! I'll have an update shortly. 

The first two points seem like quick fixes to me. Fortunately, the debian package checks for the existence of the user before creating it. So, I'll create the user/group in the docker image with fixed UID/GID. 

I think I'm in a bit of a tug of war with security regarding executing programs in the container as root. I think for now we'll (InfluxData) handle the consequences of requiring different permissions the the volume mount.

**Comment by tianon** [comment]
Yeah, absolutely -- I like to call it the "security vs usability teeter-totter" :smile: :sob:

(that third item was just FYI so you know what you're getting into and are pre-prepared for the users that might be broken by it :heart:)

**Comment by tianon** [comment]
Having a fixed UID/GID makes it easier to help users fix it, though!  "`sudo chown -R XXX:YYY /your/volume/mount`"

(and helps make sure that future updates don't accidentally break them again when the UID changes)

**Comment by tianon** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 45d7292..e85a97f 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,3 +1,2 @@
 amd64
-arm32v7
 arm64v8
diff --git a/_bashbrew-cat b/_bashbrew-cat
index 985934d..dc373a1 100644
--- a/_bashbrew-cat
+++ b/_bashbrew-cat
@@ -1,25 +1,6 @@
 Maintainers: Brandon Pfeifer <bpfeifer@influxdata.com> (@bnpfeife), Geoffrey Wossum <gwossum@influxdata.com> (@gwossum), Michael Gattozzi <mgattozzi@influxdata.com> (@mgattozzi), Trevor Hilton <thilton@influxdata.com> (@hiltontj)
 GitRepo: https://github.com/influxdata/influxdata-docker
-GitCommit: 652e8809eda9c7fa7f0ef81f26acb246bb935801
-
-Tags: 1.8, 1.8.10
-Architectures: amd64, arm32v7, arm64v8
-Directory: influxdb/1.8
-
-Tags: 1.8-alpine, 1.8.10-alpine
-Directory: influxdb/1.8/alpine
-
-Tags: 1.9-data, 1.9.13-data
-Directory: influxdb/1.9/data
-
-Tags: 1.9-data-alpine, 1.9.13-data-alpine
-Directory: influxdb/1.9/data/alpine
-
-Tags: 1.9-meta, 1.9.13-meta
-Directory: influxdb/1.9/meta
-
-Tags: 1.9-meta-alpine, 1.9.13-meta-alpine
-Directory: influxdb/1.9/meta/alpine
+GitCommit: 4911d4bc6865973f4c91636da56239d140bc798d
 
 Tags: 1.10-data, 1.10.7-data
 Directory: influxdb/1.10/data
@@ -33,6 +14,14 @@ Directory: influxdb/1.10/meta
 Tags: 1.10-meta-alpine, 1.10.7-meta-alpine
 Directory: influxdb/1.10/meta/alpine
 
+Tags: 1.11, 1.11.7
+Architectures: amd64, arm64v8
+Directory: influxdb/1.11
+
+Tags: 1.11-alpine, 1.11.7-alpine
+Architectures: amd64, arm64v8
+Directory: influxdb/1.11/alpine
+
 Tags: 1.11-data, 1.11.7-data
 Directory: influxdb/1.11/data
 
diff --git a/_bashbrew-list b/_bashbrew-list
index c4827db..0029cf4 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -1,15 +1,3 @@
-influxdb:1.8
-influxdb:1.8-alpine
-influxdb:1.8.10
-influxdb:1.8.10-alpine
-influxdb:1.9-data
-influxdb:1.9-data-alpine
-influxdb:1.9-meta
-influxdb:1.9-meta-alpine
-influxdb:1.9.13-data
-influxdb:1.9.13-data-alpine
-influxdb:1.9.13-meta
-influxdb:1.9.13-meta-alpine
 influxdb:1.10-data
 influxdb:1.10-data-alpine
 influxdb:1.10-meta
@@ -18,10 +6,14 @@ influxdb:1.10.7-data
 influxdb:1.10.7-data-alpine
 influxdb:1.10.7-meta
 influxdb:1.10.7-meta-alpine
+influxdb:1.11
+influxdb:1.11-alpine
 influxdb:1.11-data
 influxdb:1.11-data-alpine
 influxdb:1.11-meta
 influxdb:1.11-meta-alpine
+influxdb:1.11.7
+influxdb:1.11.7-alpine
 influxdb:1.11.7-data
 influxdb:1.11.7-data-alpine
 influxdb:1.11.7-meta
diff --git a/_bashbrew-list-build-order b/_bashbrew-list-build-order
index fbf5c27..1748019 100644
--- a/_bashbrew-list-build-order
+++ b/_bashbrew-list-build-order
@@ -1,13 +1,9 @@
-influxdb:1.8.10
-influxdb:1.8.10-alpine
-influxdb:1.9.13-data
-influxdb:1.9.13-data-alpine
-influxdb:1.9.13-meta
-influxdb:1.9.13-meta-alpine
 influxdb:1.10.7-data
 influxdb:1.10.7-data-alpine
 influxdb:1.10.7-meta
 influxdb:1.10.7-meta-alpine
+influxdb:1.11.7
+influxdb:1.11.7-alpine
 influxdb:1.11.7-data
 influxdb:1.11.7-data-alpine
 influxdb:1.11.7-meta
diff --git a/influxdb_1.8-alpine/Dockerfile b/influxdb_1.11-alpine/Dockerfile
similarity index 15%
rename from influxdb_1.8-alpine/Dockerfile
rename to influxdb_1.11-alpine/Dockerfile
index 984d9d8..80cedd9 100644
--- a/influxdb_1.8-alpine/Dockerfile
+++ b/influxdb_1.11-alpine/Dockerfile
@@ -1,43 +1,49 @@
-FROM alpine:3.17
+FROM alpine:3.20
 
-RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
-RUN apk add --no-cache tzdata bash ca-certificates && \
+RUN apk add --no-cache \
+      bash \
+      ca-certificates \
+      tzdata && \
     update-ca-certificates
 
-ENV INFLUXDB_VERSION 1.8.10
-RUN set -ex && \
-    mkdir ~/.gnupg; \
-    echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf; \
-    apk add --no-cache --virtual .build-deps wget gnupg tar && \
-    for key in \
-        9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E ; \
-    do \
-        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
-    done && \
-    wget --no-verbose https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz.asc && \
-    wget --no-verbose https://dl.influxdata.com/influxdb/releases/influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
-    gpg --batch --verify influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz.asc influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
-    mkdir -p /usr/src && \
-    tar -C /usr/src -xzf influxdb-${INFLUXDB_VERSION}-static_linux_amd64.tar.gz && \
-    chmod +x /usr/src/influxdb-*/influx \
-             /usr/src/influxdb-*/influx_inspect \
-             /usr/src/influxdb-*/influx_stress \
-             /usr/src/influxdb-*/influxd &&\
-    mv /usr/src/influxdb-*/influx \
-       /usr/src/influxdb-*/influx_inspect \
-       /usr/src/influxdb-*/influx_stress  \
-       /usr/src/influxdb-*/influxd \
-       /usr/bin/ &&\
-    gpgconf --kill all && \
-    rm -rf *.tar.gz* /usr/src /root/.gnupg && \
+ARG INFLUXDB_VERSION=1.11.7
+RUN apk add --no-cache --virtual .build-deps \
+      curl \
+      gnupg \
+      tar && \
+    gpg --batch --keyserver hkp://keyserver.ubuntu.com --recv-keys 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E && \
+    case "$(apk --print-arch)" in \
+      x86_64)  ARCH=amd64 ;; \
+      aarch64) ARCH=arm64 ;; \
+      *) exit 1 ;; \
+    esac && \
+    export INFLUXDB_TAR=influxdb-${INFLUXDB_VERSION}-linux-${ARCH}.tar.gz && \
+    export INFLUXDB_ASC=influxdb-${INFLUXDB_VERSION}-linux-${ARCH}.tar.gz.asc && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_TAR}" && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_ASC}" && \
+    gpg --batch --verify "${INFLUXDB_ASC}" "${INFLUXDB_TAR}" && \
+    tar -xf "${INFLUXDB_TAR}" -C /usr/bin \
+      ./influx \
+      ./influx_inspect \
+      ./influxd && \
+    rm -rf "${INFLUXDB_TAR}" \
+           "${INFLUXDB_ASC}" && \
     apk del .build-deps
 COPY influxdb.conf /etc/influxdb/influxdb.conf
 
-EXPOSE 8086
+RUN addgroup --system --gid 1500 influxdb && \
+    adduser --system --uid 1500 --ingroup influxdb --home /var/lib/influxdb --shell /bin/false influxdb && \
+    mkdir -p /var/lib/influxdb && \
+    mkdir -p /var/log/influxdb && \
+    chown influxdb:influxdb /var/lib/influxdb && \
+    chown influxdb:influxdb /var/log/influxdb && \
+    chmod 0750 /var/lib/influxdb && \
+    chmod 0750 /var/log/influxdb
 
+EXPOSE 8086
 VOLUME /var/lib/influxdb
-
 COPY entrypoint.sh /entrypoint.sh
 COPY init-influxdb.sh /init-influxdb.sh
+USER influxdb
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["influxd"]
diff --git a/influxdb_1.8-alpine/entrypoint.sh b/influxdb_1.11-alpine/entrypoint.sh
similarity index 100%
rename from influxdb_1.8-alpine/entrypoint.sh
rename to influxdb_1.11-alpine/entrypoint.sh
diff --git a/influxdb_1.8-alpine/influxdb.conf b/influxdb_1.11-alpine/influxdb.conf
similarity index 100%
rename from influxdb_1.8-alpine/influxdb.conf
rename to influxdb_1.11-alpine/influxdb.conf
diff --git a/influxdb_1.8-alpine/init-influxdb.sh b/influxdb_1.11-alpine/init-influxdb.sh
similarity index 100%
rename from influxdb_1.8-alpine/init-influxdb.sh
rename to influxdb_1.11-alpine/init-influxdb.sh
diff --git a/influxdb_1.8/Dockerfile b/influxdb_1.11/Dockerfile
similarity index 17%
rename from influxdb_1.8/Dockerfile
rename to influxdb_1.11/Dockerfile
index 45b00aa..c54f15f 100644
--- a/influxdb_1.8/Dockerfile
+++ b/influxdb_1.11/Dockerfile
@@ -1,35 +1,32 @@
-FROM buildpack-deps:bullseye-curl
+FROM buildpack-deps:bookworm-curl
 
-RUN set -ex && \
-    mkdir ~/.gnupg; \
-    echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf; \
-    for key in \
-        9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E ; \
-    do \
-        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
-    done
+RUN addgroup --system --gid 1500 influxdb && \
+    adduser --system --uid 1500 --ingroup influxdb --home /var/lib/influxdb --shell /bin/false influxdb
 
-ENV INFLUXDB_VERSION 1.8.10
-RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" && \
-    case "${dpkgArch##*-}" in \
-      amd64) ARCH='amd64';; \
-      arm64) ARCH='arm64';; \
-      armhf) ARCH='armhf';; \
-      armel) ARCH='armel';; \
-      *)     echo "Unsupported architecture: ${dpkgArch}"; exit 1;; \
+ARG INFLUXDB_VERSION=1.11.7
+RUN gpg --batch --keyserver hkp://keyserver.ubuntu.com --recv-keys 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E && \
+    export DEBIAN_FRONTEND=noninteractive && \
+    apt-get update && \
+    case "$(dpkg --print-architecture)" in \
+      *amd64) ARCH=amd64 ;; \
+      *arm64) ARCH=arm64 ;; \
+      *) exit 1 ;; \
     esac && \
-    wget --no-verbose https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VERSION}_${ARCH}.deb.asc && \
-    wget --no-verbose https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VERSION}_${ARCH}.deb && \
-    gpg --batch --verify influxdb_${INFLUXDB_VERSION}_${ARCH}.deb.asc influxdb_${INFLUXDB_VERSION}_${ARCH}.deb && \
-    dpkg -i influxdb_${INFLUXDB_VERSION}_${ARCH}.deb && \
-    rm -f influxdb_${INFLUXDB_VERSION}_${ARCH}.deb*
+    export INFLUXDB_DEB=influxdb-${INFLUXDB_VERSION}-${ARCH}.deb && \
+    export INFLUXDB_ASC=influxdb-${INFLUXDB_VERSION}-${ARCH}.deb.asc && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_DEB}" && \
+    curl -fLO "https://dl.influxdata.com/influxdb/releases/${INFLUXDB_ASC}" && \
+    gpg --batch --verify "${INFLUXDB_ASC}" "${INFLUXDB_DEB}" && \
+    apt-get install -y "./${INFLUXDB_DEB}" && \
+    rm -rf "${INFLUXDB_DEB}" \
+           "${INFLUXDB_ASC}" \
+	   /var/lib/apt/lists/*
 COPY influxdb.conf /etc/influxdb/influxdb.conf
 
 EXPOSE 8086
-
 VOLUME /var/lib/influxdb
-
 COPY entrypoint.sh /entrypoint.sh
 COPY init-influxdb.sh /init-influxdb.sh
+USER influxdb
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["influxd"]
diff --git a/influxdb_1.8/entrypoint.sh b/influxdb_1.11/entrypoint.sh
similarity index 79%
rename from influxdb_1.8/entrypoint.sh
rename to influxdb_1.11/entrypoint.sh
index 26e6bd7..832091c 100755
diff --git a/influxdb_1.8/influxdb.conf b/influxdb_1.11/influxdb.conf
similarity index 100%
rename from influxdb_1.8/influxdb.conf
rename to influxdb_1.11/influxdb.conf
diff --git a/influxdb_1.8/init-influxdb.sh b/influxdb_1.11/init-influxdb.sh
similarity index 100%
rename from influxdb_1.8/init-influxdb.sh
rename to influxdb_1.11/init-influxdb.sh
diff --git a/influxdb_1.9-data-alpine/Dockerfile b/influxdb_1.9-data-alpine/Dockerfile
deleted file mode 100644
index 603c765..0000000
diff --git a/influxdb_1.9-data-alpine/entrypoint.sh b/influxdb_1.9-data-alpine/entrypoint.sh
deleted file mode 100755
index 83d12eb..0000000
diff --git a/influxdb_1.9-data-alpine/influxdb.conf b/influxdb_1.9-data-alpine/influxdb.conf
deleted file mode 100644
index f03c128..0000000
diff --git a/influxdb_1.9-data-alpine/init-influxdb.sh b/influxdb_1.9-data-alpine/init-influxdb.sh
deleted file mode 100755
index 3f7349a..0000000
diff --git a/influxdb_1.9-data/Dockerfile b/influxdb_1.9-data/Dockerfile
deleted file mode 100644
index e4d461f..0000000
diff --git a/influxdb_1.9-data/entrypoint.sh b/influxdb_1.9-data/entrypoint.sh
deleted file mode 100755
index 83d12eb..0000000
diff --git a/influxdb_1.9-data/influxdb.conf b/influxdb_1.9-data/influxdb.conf
deleted file mode 100644
index f03c128..0000000
diff --git a/influxdb_1.9-data/init-influxdb.sh b/influxdb_1.9-data/init-influxdb.sh
deleted file mode 100755
index 3f7349a..0000000
diff --git a/influxdb_1.9-meta-alpine/Dockerfile b/influxdb_1.9-meta-alpine/Dockerfile
deleted file mode 100644
index 9143fe8..0000000
diff --git a/influxdb_1.9-meta-alpine/entrypoint.sh b/influxdb_1.9-meta-alpine/entrypoint.sh
deleted file mode 100755
index ae61bda..0000000
diff --git a/influxdb_1.9-meta-alpine/influxdb-meta.conf b/influxdb_1.9-meta-alpine/influxdb-meta.conf
deleted file mode 100644
index 6491d8a..0000000
diff --git a/influxdb_1.9-meta/Dockerfile b/influxdb_1.9-meta/Dockerfile
deleted file mode 100644
index 6af7e67..0000000
diff --git a/influxdb_1.9-meta/entrypoint.sh b/influxdb_1.9-meta/entrypoint.sh
deleted file mode 100755
index ae61bda..0000000
diff --git a/influxdb_1.9-meta/influxdb-meta.conf b/influxdb_1.9-meta/influxdb-meta.conf
deleted file mode 100644
index 6491d8a..0000000
```

</details>

**Review by tianon — APPROVED** [review]

**Pull request merged**
