### PR TITLE
Update photon image

### PR DESCRIPTION
**Pull request by gerrit-photon**
Update photon image

### CODE REVIEW

**Comment by tianon** [comment]
So, what's the verdict on the discussion from https://github.com/docker-library/official-images/pull/4231?

**Comment by yosifkit** [comment]
Friendly ping, @frapposelli @YustasSwamp regarding older versions? :arrow_up:

**Comment by gerrit-photon** [comment]
Close the current pull request. Alexey has update the docker file and we will send an pull request for this update later.

**Comment by YustasSwamp** [comment]
Hi @yosifkit we changed our library file. Now it has only one date tag per version (one for 1.0 and one for 2.0) - 2 images total per build. All old images were dropped from library file.
Thanks.

**Pull request closed without merging**
