### PR TITLE
Bump Traefik to v2.4.3

### PR DESCRIPTION
**Pull request by rtribotte**
Hello,

This PR updates Traefik to [v2.4.3](https://github.com/traefik/traefik/releases/tag/v2.4.3).

/cc @ldez @SantoDE @kevinpollet

Cheers

### CODE REVIEW

**Review by kevinpollet — APPROVED** [review]
LGTM

**Review by ldez — APPROVED** [review]
LGTM

**Review by SantoDE — APPROVED** [review]
LGTM

**Comment by SantoDE** [comment]
Gently ping @yosifkit :=)

**Pull request merged**
