### PR TITLE
[Swift] Update to Swift 5.6.3

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
```
2022-09-02T17:13:59.1323919Z  - swift:5.6.3-windowsservercore-20H2 -- missing constraints (FROM mcr.microsoft.com/windows/servercore:20H2):
2022-09-02T17:13:59.1324477Z    - windowsservercore-20H2
2022-09-02T17:13:59.1325721Z 
2022-09-02T17:13:59.1361491Z ##[error]Process completed with exit code 1.
```

@yosifkit This is our first time adding support for Windows Docker image. Any suggestion on what's missing?

**Comment by yosifkit** [comment]
Two bits of feedback:
- the images should be `FROM` an "Long-Term Servicing Channel" release like `windowsservercore:ltsc2022` instead of the `20H2` "Semi-Annual Channel" (https://docs.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison, https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
- the library file requires a both the `Architectures: windows-amd64` and a `Contraints:` for the specific windows release, so `windowsservercore-ltsc2022` (or `windowsservercore-1809`, `nanoserver-ltsc2022` for other examples)

---

Here is an example in `golang`:
https://github.com/docker-library/official-images/blob/6998cd62932358a3e0ab798fa0aab257a82d56f1/library/golang#L29-L55

Optionally "plain" tags can be moved around to `SharedTags:` so that `docker pull swift:5.6` or `latest` on Linux or Windows would pull the right thing (see the full `golang` file for an example). `SharedTags` allow multiple versions of Windows along with one linux image to share a single tag via the manifest list (like a multi-arch image does, but Windows images are also kernel version dependent).

**Comment by tianon** [comment]
On the `Dockerfile`s, you'll also want to move down the versioned URLs as far as they reasonably can be for better cache.

The `LABEL` values aren't _new_ for `swift`, so I don't think we should make those a blocker for this PR, but you should see https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

**Comment by shahmishal** [comment]
@yosifkit @tianon How do I reproduce this locally? 

```
15s
[1](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:1)
Run set -- 'swift:5.6.3-windowsservercore-ltsc2022'
[2](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:2)
  set -- 'swift:5.6.3-windowsservercore-ltsc2022'
[3](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:3)
  if [ -s ./.test/config.sh ]; then set -- --config ~/oi/test/config.sh --config ./.test/config.sh "$@"; fi
[4](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:4)
  ./test/run.sh "$@"
[5](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:5)
  shell: C:\Program Files\Git\bin\bash.EXE -Eeuo pipefail -x {0}
[6](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:6)
  env:
[7](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:7)
    GIT_LFS_SKIP_SMUDGE: 1
[8](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:8)
    MSYS: winsymlinks:nativestrict
[9](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:10)
+ set -- swift:5.6.3-windowsservercore-ltsc2022
[10](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:11)
+ '[' -s ./.test/config.sh ']'
[11](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:12)
+ ./test/run.sh swift:5.6.3-windowsservercore-ltsc2022
[12](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:13)
testing swift:5.6.3-windowsservercore-ltsc2022
[13](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:14)
	'override-cmd' [1/2]...passed
[14](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:15)
<unknown>:0: error: could not load the swift standard library
[15](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:16)
	'swift-hello-world' [2/2]...failed
[16](https://github.com/docker-library/official-images/runs/8201997159?check_suite_focus=true#step:8:17)
Error: Process completed with exit code 1.
```

**Comment by compnerd** [comment]
The windows test failure seems to stem from the fact that the test script is a bash script.  The association due to the installation of git will force the creation of a bash shell instance.  This is observed in the logs:
```
shell: C:\Program Files\Git\bin\bash.EXE -Eeuo pipefail -x {0}
```

The problem is that environment is not setup for development with Swift - it does not have the proper `Path` and `SDKROOT` environment variables at the very least.  The default `RUN` setting for the Windows VM is configured for PowerShell as that is the shell that has been setup with the various environment variables and other pieces.

**Comment by yosifkit** [comment]
The test Windows hosts have bash, but bash is not run within the windows container. 

The test is just doing roughly the equivalent of this:
```console
$ output="$(docker run -v //path/to/container.swift://container.swft swift:5.6.3-windowsservercore-ltsc2022 swift ./container.swift)"
$ test "$output" = "$(cat expected-std-out.txt)"
```

From the failure output, `<unknown>:0: error: could not load the swift standard library`, I'd guess that the `USER ContainerUser` does not have enough access/permissions to run the swift binary (or maybe just something with dll's?).

---

You can run the test on a Windows machine with git bash (should come with Docker Desktop) while windows containers is active.
```console
$ # build the image
$ docker build -t swift:5.6.3-windowsservercore-ltsc2022 /path/to/5.6/windows/LTSC2022/
$ # from a checkout of the official-images repo
$ ./test/run.sh -t swift-hello-world swift:5.6.3-windowsservercore-ltsc2022
```

**Comment by compnerd** [comment]
> The test Windows hosts have bash, but bash is not run within the windows container.
> 
> The test is just doing roughly the equivalent of this:
> 
> ```
> $ output="$(docker run -v //path/to/container.swift://container.swft swift:5.6.3-windowsservercore-ltsc2022 swift ./container.swift)"
> $ test "$output" = "$(cat expected-std-out.txt)"
> ```
> 
> From the failure output, `<unknown>:0: error: could not load the swift standard library`, I'd guess that the `USER ContainerUser` does not have enough access/permissions to run the swift binary (or maybe just something with dll's?).

No, the user environment is not correct which is why it is failing.  At the very least, `SDKROOT` is not being configured due to the use of the bash shell.

> You can run the test on a Windows machine with git bash (should come with Docker Desktop) while windows containers is active.
> 
> ```
> $ # build the image
> $ docker build -t swift:5.6.3-windowsservercore-ltsc2022 /path/to/5.6/windows/LTSC2022/
> $ # from a checkout of the official-images repo
> $ ./test/run.sh -t swift-hello-world swift:5.6.3-windowsservercore-ltsc2022
> ```

Yes, except that environment is not able to run swift properly (this is a known limitation).

**Comment by tianon** [comment]
I think we're misunderstanding one another - the Windows-based image being added here does not seem to be able to successfully run Swift programs, which kind of defeats the purpose, doesn't it?  (If that's not what this new Windows-based image is for, maybe you can elaborate on the use case for it?)

(hopefully) more straightforward reproducer to try and help make this more clear:

```console
$ cat hello.swift
print("Hello, world!")

$ cat Dockerfile
FROM swift:5.6-windowsservercore-ltsc2022
COPY hello.swift ./
RUN swift hello.swift

$ docker build --pull --tag swift:5.6-windowsservercore-ltsc2022 https://github.com/apple/swift-docker.git#main:5.6/windows/LTSC2022
... (output removed for brevity) ...
Successfully tagged swift:5.6-windowsservercore-ltsc2022

$ docker build .
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM swift:5.6-windowsservercore-ltsc2022
 ---> 087ecdee2d49
Step 2/3 : COPY hello.swift ./
 ---> 41b37b7ccee2
Step 3/3 : RUN swift hello.swift
 ---> Running in 8ab5ab0d8e75
<unknown>:0: error: could not load the swift standard library
The command 'cmd /S /C swift hello.swift' returned a non-zero code: 1
```

Additionally, at a higher level, I'm _very_ concerned with just how big this new image is -- it's ~15GB on-disk. :grimacing:

Are Visual Studio's build tools (~4.62GB), Python (~927MB), _and_ Git (~787MB) all strictly necessary for a minimal Swift installation on Windows? (that's all on top of Swift itself which is ~3.6GB and the base image at ~5GB)

**Comment by compnerd** [comment]
> I think we're misunderstanding one another - the Windows-based image being added here does not seem to be able to successfully run Swift programs, which kind of defeats the purpose, doesn't it? (If that's not what this new Windows-based image is for, maybe you can elaborate on the use case for it?)
> 
> (hopefully) more straightforward reproducer to try and help make this more clear:
> 
> ```
> $ cat hello.swift
> print("Hello, world!")
> 
> $ cat Dockerfile
> FROM swift:5.6-windowsservercore-ltsc2022
> COPY hello.swift ./
> RUN swift hello.swift
> 
> $ docker build --pull --tag swift:5.6-windowsservercore-ltsc2022 https://github.com/apple/swift-docker.git#main:5.6/windows/LTSC2022
> ... (output removed for brevity) ...
> Successfully tagged swift:5.6-windowsservercore-ltsc2022
> 
> $ docker build .
> Sending build context to Docker daemon  3.072kB
> Step 1/3 : FROM swift:5.6-windowsservercore-ltsc2022
>  ---> 087ecdee2d49
> Step 2/3 : COPY hello.swift ./
>  ---> 41b37b7ccee2
> Step 3/3 : RUN swift hello.swift
>  ---> Running in 8ab5ab0d8e75
> <unknown>:0: error: could not load the swift standard library
> The command 'cmd /S /C swift hello.swift' returned a non-zero code: 1
> ```

Again, this is expected :).  You cannot simply do `cmd /S /C swift` and expect this to work.  You **must** use this as `docker run -it ...` as the docker image does not re-create the environment properly otherwise.  The problem is that there are a number of environment variables (including but not limited to `SDKROOT` which is the error that shows up here).  I _think_ that you might be able to get away with:

```
FROM swift:5.6-windowsservercore-ltsc2022
COPY hello.swift ./
RUN swiftc -sdk C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk -emit-executable -o hello.exe hello.swift && .\hello.exe
```

The `swift` command is not supported on Windows - that is the interpreter, which is not yet available.

> Additionally, at a higher level, I'm _very_ concerned with just how big this new image is -- it's ~15GB on-disk. 😬
> 
> Are Visual Studio's build tools (~4.62GB), Python (~927MB), _and_ Git (~787MB) all strictly necessary for a minimal Swift installation on Windows? (that's all on top of Swift itself which is ~3.6GB and the base image at ~5GB)

Yes, this is the minimal image that can be used for development.  The Visual Studio Build Tools are mandatory to provide the vcruntime headers (and linker) and the Windows SDK for the system SDK, Python is a dependency for lldb, and Git is required for use of SPM.  The Swift tools provide the tools needed to build and run Swift code and is pretty close to minimal (there can be ~20M removed if you remove the LSP support).

FWIW, I do share the concern over the distribution size.

**Comment by compnerd** [comment]
@tianon - btw, from a local setup:

```
S:\SourceCache\swift-docker\5.6\windows\20H2>docker image build --compress -t swift:5.6 .
...
S:\SourceCache\swift-docker\5.6\windows\20H2>docker run -t swift:5.6 swift --version
compnerd.org Swift version 5.6.3 (swift-5.6.3-RELEASE)
Target: x86_64-unknown-windows-msvc
```

I need to run 20H2 as otherwise the kernel versions don't match on my local host.

**Comment by shahmishal** [comment]
Removing Windows Docker config for now, so we can get Linux Docker images released.

**Comment by shahmishal** [comment]
@yosifkit @tianon Can we merge this PR?

**Pull request merged**
