### PR TITLE
Upgrade SonarQube to 10.0

### PR DESCRIPTION
**Pull request by carminevassallo**
Dear team,

we just released SonarQube 10.0. Please merge this PR to have it released as Docker image.

### CODE REVIEW

**Comment by yosifkit** [comment]
```diff
+LABEL org.opencontainers.image.url=https://github.com/SonarSource/sonar-scanner-cli-docker
```
Seems fine to add a label:+1:. Should this be pointing to `https://github.com/SonarSource/docker-sonarqube` instead?

One caveat of using a label is that they are inherited by images `FROM` this one; we hope to be able to provide this information in annotations automatically for official images, but that is still a todo.

**Comment by tianon** [comment]
See also https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

(for further context/consideration, not because it's necessarily a blocker)

**Comment by carminevassallo** [comment]
> Seems fine to add a label👍. Should this be pointing to `https://github.com/SonarSource/docker-sonarqube` instead?

Thanks for spotting this guys! We are gonna fix it shortly...

**Comment by carminevassallo** [comment]
> Thanks for spotting this guys! We are gonna fix it shortly...

and that's fixed. Please let us know if you have other comments, otherwise feel free to merge :)

**Pull request merged**
