### PR TITLE
Add a simple initial "bashbrew" Dockerfile

### PR DESCRIPTION
**Pull request by tianon**
cc @md5 :wink:

It's got a ways to go before it's really, really useful, but it's at least good enough for a lot of stuff as-is. :+1:

### CODE REVIEW

**Comment by md5** [comment]
Shouldn't it `apk add --update bash`?

**Comment by md5** [comment]
Nevermind my inattention!

**Comment by md5** [comment]
Nice start!

**Comment by md5** [comment]
While I think this is an interesting approach, it doesn't really solve the problem with running tests in the Docker Machine scenario encountered on OS X, which is the main hurdle I encounter when working with official images.

Since I need to make the Docker socket available to the container with `-v /var/run/docker.sock:/var/run/docker.sock` in order to get access to a Docker daemon, that daemon is still running outside the image. This works fine for `bashbrew build`, but as soon as I need to run tests that use mounted volumes themselves, everything breaks. The reason for this is that the paths inside the container don't match the paths that the Docker daemon attempts to mount for the (sibling) test containers.

The workaround I normally use for this is to do `-v "$(pwd):$(pwd)" -w "$(pwd)"`, which makes the test file paths inside the container the same as outside the container. Since I'm running these tests from my home directory under `/Users`, which is mounted as a shared folder into the Docker VM, this ends up working, but it's a bit of a pain in the ass.

**Comment by tianon** [comment]
Right!  I have some crazy ideas for that problem too that give us other
nice features, but I need to play a little first to see if they'll actually
work. :smiling_imp:

Thanks for looking and thinking over this. :heart:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
