### PR TITLE
Add Presto image

### PR DESCRIPTION
**Pull request by martint**
This adds an image for Presto, a distributed SQL engine for big data (https://prestosql.io)

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream?
    - https://github.com/prestosql
-	[ ] does it fit into one of the common categories? ("service", "language stack", "base distribution")
    - service
-	[x] is it reasonably popular, or does it solve a particular use case well?
    - over 1.5k stars on GitHub
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/pull/1759
-	[ ] official-images maintainer dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ official-images maintainer dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by martint** [comment]
@tianon, please let me know if there's anything I can do to help move this forward.

**Comment by findepi** [comment]
I am willing to help. @tianon please let me know what can I do to help move this forward.

**Comment by electrum** [comment]
@yosifkit @tianon Is there any way I can help to get this merged?

**Comment by bitsondatadev** [comment]
@yosifkit @tianon I can help too if anything is needed here.

**Comment by bitsondatadev** [comment]
Just checking in!

**Comment by bitsondatadev** [comment]
@yosifkit and @tianon checking in.

**Comment by findepi** [comment]
can i do anything to help move this forward?

**Comment by tianon** [comment]
Sorry for the delay (and thanks for your patience).

> considered openjdk:11-jdk due to the dependency on the Java JDK, but it results in a bigger image than using centos:centos7 as a base

It sounds like you probably want to look instead at `openjdk:11-jre`, `openjdk:11-jre-slim`, or even more explicitly `openjdk:11-jre-slim-buster` depending on the needs of your application (I don't imagine Presto actually needs the JDK installed at runtime?).

Additionally, there are several alternative Java implementations available in the official images that are worth considering as a base (`amazoncorretto`, `adoptopenjdk`, `sapmachine`) if the stock/vanilla OpenJDK builds provided in `openjdk` don't suit your needs for one reason or another.

> ```diff
> +LABEL maintainer="Presto community <https://prestosql.io/community.html>"
> ```

See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

> ```diff
> +ENV PRESTO_VERSION 337
> ```
> 

You should move as much as is reasonably version-independent above this line to ensure that rebuilds can make the best use of Docker build cache as possible.

> ```diff
> +    yum -y -q update && \
> ```
> 

This is essentially the same as `apt-get upgrade`, which is covered here: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

We prefer instead to have the base image maintainers push an updated base image if packages in the base layers need to be updated (especially so that users don't have to deal with the duplicated bandwidth/storage for the same dependencies twice).

> ```diff
> +COPY --chown=presto:presto default /usr/lib/presto/default
> ```

I'm confused by a bit of the contents of this directory -- some of this seems like sane defaults that should probably be distributed with the upstream releases?

**Comment by yosifkit** [comment]
Closing given absence of activity. We apologize for the delays with our responses. :bowing_man: Not to excuse our slow or missing replies, we often have to prioritize maintaining the current images over adding new images. Thanks for your contribution.

If you'd still like to propose a new image, let us know here and we'll try to help it move along. If you've since moved on to other endeavors, we wish you the best. :heart:

**Comment by bitsondatadev** [comment]
@findepi @martint are we still interested in getting a Trino (formerly PrestoSQL) image added?

**Comment by bitsondatadev** [comment]
@findepi yeah. I'll do this next week when I get back from PTO and add in the changes requested.

**Pull request closed without merging**
