### PR TITLE
Update clojure

### PR DESCRIPTION
**Pull request by Quantisan**
Automated pull request to update `library/clojure` generated by
GitHub Actions on the Quantisan/docker-clojure repo.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Apologies, I had misunderstood the situation in #16572. The missing upstream images were older distro versions that will never get new JDK versions. This PR should only build on valid upstream images.

**Comment by alexander-yakushev** [comment]
Apparently, `eclipse-temurin:22-jdk-jammy` doesn't have `curl` (while `eclipse-temurin:21-jdk-jammy` had it). Nice.

**Comment by cap10morgan** [comment]
> Apparently, `eclipse-temurin:22-jdk-jammy` doesn't have `curl` (while `eclipse-temurin:21-jdk-jammy` had it). See https://github.com/adoptium/containers/issues/255.

I'm working on a fix on our end.

**Comment by alexander-yakushev** [comment]
Here's my solution, you may consider taking it if you aren't too far ahead with yours yet https://github.com/Quantisan/docker-clojure/pull/221

**Comment by tianon** [comment]
I would suggest also adding `-f`/`--fail` to all these `curl` invocations, but given they're all immediately followed by a checksum validation, I don't think it's a blocking concern (just something to keep in mind for the next update). :+1:

**Comment by tianon** [comment]
(While you're at it, you might want to add `-S`/`--show-error` as well, which updates `-s`/`--silent`'s behavior to actually print error messages :sob:)

**Review by tianon — APPROVED** [review]

**Comment by cap10morgan** [comment]
Great suggestions, thanks @tianon!

**Pull request merged**
