### PR TITLE
[security] Updated nginx to 1.22.1 and 1.23.2.

### PR DESCRIPTION
**Pull request by thresheek**
This also adds a new image variant, alpine-slim.

Apologies for not notifying earlier.

### CODE REVIEW

**Comment by tianon** [comment]
The addition of `alpine-slim` is a little strange and I'd like to discuss that one more before we merge - would you mind removing that from here for now and putting it in a separate PR so we can get the security release through ASAP? :innocent:

**Comment by tianon** [comment]
(To be clear, I'm also happy to help split if that would be helpful!)

**Comment by tianon** [comment]
To be extra clear, what I'm proposing is making the contents of this PR the following, and the current contents in a new follow-up PR so we can review `alpine-slim` separately:

```yaml
# this file is generated via https://github.com/nginxinc/docker-nginx/blob/1dca42f99b3f032d862a1d35e8a5b951d629dc98/generate-stackbrew-library.sh

Maintainers: NGINX Docker Maintainers <docker-maint@nginx.com> (@nginxinc)
GitRepo: https://github.com/nginxinc/docker-nginx.git

Tags: 1.23.2, mainline, 1, 1.23, latest
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: mainline/debian

Tags: 1.23.2-perl, mainline-perl, 1-perl, 1.23-perl, perl
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: mainline/debian-perl

Tags: 1.23.2-alpine, mainline-alpine, 1-alpine, 1.23-alpine, alpine
Architectures: arm64v8, arm32v6, arm32v7, ppc64le, s390x, i386, amd64
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: mainline/alpine

Tags: 1.23.2-alpine-perl, mainline-alpine-perl, 1-alpine-perl, 1.23-alpine-perl, alpine-perl
Architectures: arm64v8, arm32v6, arm32v7, ppc64le, s390x, i386, amd64
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: mainline/alpine-perl

Tags: 1.22.1, stable, 1.22
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: stable/debian

Tags: 1.22.1-perl, stable-perl, 1.22-perl
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: stable/debian-perl

Tags: 1.22.1-alpine, stable-alpine, 1.22-alpine
Architectures: arm64v8, arm32v6, arm32v7, ppc64le, s390x, i386, amd64
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: stable/alpine

Tags: 1.22.1-alpine-perl, stable-alpine-perl, 1.22-alpine-perl
Architectures: arm64v8, arm32v6, arm32v7, ppc64le, s390x, i386, amd64
GitCommit: fef51235521d1cdf8b05d8cb1378a526d2abf421
Directory: stable/alpine-perl
```

**Comment by thresheek** [comment]
Sure.  Would you like a separate commit on top removing the slim variant, or a force-push with a new fixed commit?

**Comment by thresheek** [comment]
Let's not pollute the repo history. I've force-pushed the amended variant. Many thanks!

**Comment by tianon** [comment]
Thank you :bow:

**Pull request merged**
