### PR TITLE
Bump SBOM indexer to 1.9.3

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by tianon** [comment]
```diff
-			"org.opencontainers.image.version": "1.7.1-doi"
+			"org.opencontainers.image.version": "1.9.1"
```

Is this still a DOI-specific image (and this is just a metadata quirk) or should we adjust the tag we're pointing to back to the general image so the DOI tag doesn't need to be maintained anymore? (no opinion either way, just checking to make sure we're not doing more effort than we need to for something only used by DOI :+1:)

```diff
+		"User": "docker-scout",
...
 		{
 			"comment": "buildkit.dockerfile.v0",
-			"created": "2024-04-17T14:18:59.653995821Z",
+			"created": "2024-05-24T17:26:28.73658959Z",
+			"created_by": "USER docker-scout",
+			"empty_layer": true
+		},
```

Isn't it possible this causes the scanner to fail to read some of the files from the image?  (maybe the BuildKit integration already provides the appropriate capability to the SBOM scanner so that it can ignore filesystem permissions?  `CAP_DAC_OVERRIDE`, IIRC?)

**Comment by tianon** [comment]
`docker/scout-sbom-indexer:1.9-doi` and `docker/scout-sbom-indexer:1.9` have separate digests, but they aren't functionally different anymore -- the only difference is the attestation objects:

```diff
$ diff -u <(crane manifest docker/scout-sbom-indexer:1.9) <(crane manifest docker/scout-sbom-indexer:1.9-doi)
--- /dev/fd/63	2024-05-24 13:15:32.204281763 -0700
+++ /dev/fd/62	2024-05-24 13:15:32.208281807 -0700
@@ -78,7 +78,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:69cd9eea315867f6da4cfee6d2f49d251bf5634a857ed91c601c92b081197ccb",
+      "digest": "sha256:1ad667203b44d41ecd46dda782fea9debcfcfa078833c49aceeb3a616eac1dfe",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:be45afbabe212504408643f7f88d6b7749b6bb684cdad7a1e6d93673a8bd4f96",
@@ -91,7 +91,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:f1ef0c1acaf6a1f75cc8be22fedcc890c3b339fce78aae1cf55de260370e8af2",
+      "digest": "sha256:6a214ccbfe2b3c3591f6406121c037a1731ed2624d192069fa056dbc95c85b1a",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:9d1f08934f42d77d990a598e3ccab573b39e30eb304395f3a30df152c2a4d9ce",
@@ -104,7 +104,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:760d86c316f9bb0f9c2348cb93657bf847e1ea6e6e23b6c2ff1861e4a1a90e23",
+      "digest": "sha256:c01aa6ef9ee4bd68521d9b794bc658fe667e9b8292eba43dbba8be9c28cc1b80",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:b160fcabf08fac83a59101152783e9154241c43215dc8473489dc9b2a3564c31",
@@ -117,7 +117,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:367ec26c21fc075009641f11bd723372baf91e4f5c0dfc9eddab99ddc773db8b",
+      "digest": "sha256:2d9d5b86682f8f71fe584461779e8a2043d20e37166c48b972bd4647be46657a",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:289dcb1c4c7a964f1cae585334c6bf19735f6f4e9a37c7ff6f1fe8b1e4c30da4",
@@ -130,7 +130,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:cf1d3acaa36447787f8fbdbbb284e3dc0315d5fd66b9b818c3d1e82009f73ef7",
+      "digest": "sha256:a3735008eb6a35bf8d70e588e6af22ab1d93232912c70926b162c3b0859e04a3",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:2702933ca2043f233bbaef354123ff06795097858a17e0cd217d6d89a8c5af3c",
@@ -143,7 +143,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:bc1260ea9118d48487a47cc3c37edda6cc9c1cfbbfbff0d64ed1e4d0c9a5f145",
+      "digest": "sha256:0d32afb80a059fe5226cb275fa20f9dfaa3f09760f791c457b8d2c6e9f580be9",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:959c7f87533089fce640849924e0693f1cea1ff4c6ddf0455f5f4cd3a018ee16",
@@ -156,7 +156,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:f7c424b6cb3efc064563e04ce0ffb7ecf7a4f808700853846ad4859d97815b88",
+      "digest": "sha256:0683556e3fb5da148c3c253df2f0d285c54d650772a19d98aa98392b6ab4125c",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:87e05b317a2c89055200aabfb41a5ba63be8ed3486e9bc7f8f02e20779573979",
@@ -169,7 +169,7 @@
     },
     {
       "mediaType": "application/vnd.oci.image.manifest.v1+json",
-      "digest": "sha256:6ecb885bfe4409a9bb008cd622f3a83618f69308df472c496a238a885bb95abb",
+      "digest": "sha256:98f283af950a252d663b150b24f3f539cb7ec36bb76008a2dd12c620fa8767e1",
       "size": 840,
       "annotations": {
         "vnd.docker.reference.digest": "sha256:d9ca36be3fd41215ba0cda678f52fc80a544a1128ec4b84df566362f318f9cee",
```

again with a bit of `jq` to make it easier to see what's happening:

```diff
$ diff -u <(crane manifest docker/scout-sbom-indexer:1.9 | jq -r '.manifests[] | ([.platform["os","architecture","variant"]//empty] | join("/")) + " " + .digest') <(crane manifest docker/scout-sbom-indexer:1.9-doi | jq -r '.manifests[] | ([.platform["os","architecture","variant"]//empty] | join("/")) + " " + .digest')
--- /dev/fd/63	2024-05-24 13:18:30.978194670 -0700
+++ /dev/fd/62	2024-05-24 13:18:30.978194670 -0700
@@ -6,11 +6,11 @@
 linux/ppc64le sha256:959c7f87533089fce640849924e0693f1cea1ff4c6ddf0455f5f4cd3a018ee16
 linux/riscv64 sha256:87e05b317a2c89055200aabfb41a5ba63be8ed3486e9bc7f8f02e20779573979
 linux/s390x sha256:d9ca36be3fd41215ba0cda678f52fc80a544a1128ec4b84df566362f318f9cee
-unknown/unknown sha256:69cd9eea315867f6da4cfee6d2f49d251bf5634a857ed91c601c92b081197ccb
-unknown/unknown sha256:f1ef0c1acaf6a1f75cc8be22fedcc890c3b339fce78aae1cf55de260370e8af2
-unknown/unknown sha256:760d86c316f9bb0f9c2348cb93657bf847e1ea6e6e23b6c2ff1861e4a1a90e23
-unknown/unknown sha256:367ec26c21fc075009641f11bd723372baf91e4f5c0dfc9eddab99ddc773db8b
-unknown/unknown sha256:cf1d3acaa36447787f8fbdbbb284e3dc0315d5fd66b9b818c3d1e82009f73ef7
-unknown/unknown sha256:bc1260ea9118d48487a47cc3c37edda6cc9c1cfbbfbff0d64ed1e4d0c9a5f145
-unknown/unknown sha256:f7c424b6cb3efc064563e04ce0ffb7ecf7a4f808700853846ad4859d97815b88
-unknown/unknown sha256:6ecb885bfe4409a9bb008cd622f3a83618f69308df472c496a238a885bb95abb
+unknown/unknown sha256:1ad667203b44d41ecd46dda782fea9debcfcfa078833c49aceeb3a616eac1dfe
+unknown/unknown sha256:6a214ccbfe2b3c3591f6406121c037a1731ed2624d192069fa056dbc95c85b1a
+unknown/unknown sha256:c01aa6ef9ee4bd68521d9b794bc658fe667e9b8292eba43dbba8be9c28cc1b80
+unknown/unknown sha256:2d9d5b86682f8f71fe584461779e8a2043d20e37166c48b972bd4647be46657a
+unknown/unknown sha256:a3735008eb6a35bf8d70e588e6af22ab1d93232912c70926b162c3b0859e04a3
+unknown/unknown sha256:0d32afb80a059fe5226cb275fa20f9dfaa3f09760f791c457b8d2c6e9f580be9
+unknown/unknown sha256:0683556e3fb5da148c3c253df2f0d285c54d650772a19d98aa98392b6ab4125c
+unknown/unknown sha256:98f283af950a252d663b150b24f3f539cb7ec36bb76008a2dd12c620fa8767e1
```

**Comment by whalelines** [comment]
So that means the non-doi one also sets `"DOCKER_SCOUT_SBOM_CATALOGERS=php-composer-lock,erlang-otp-application"`, which may be problematic. @eunomie reported some issues with the 1.9.0 build. Perhaps there were some issues with this build too?

**Comment by LaurentGoderre** [comment]
The erlang one is what will make the `elixir` image work. I just tested locally. I forget which image needed the composer one

**Comment by yosifkit** [comment]
Can you update to the newer `1.9.3-doi`? It looks like they fixed it so that the non-doi build doesn't set the extra environment variables again (and the `-doi` is no longer claiming to be non-doi in the image labels).

`sha256:bd120478dfb979a8d27e2a6e0e9d985f752bcd0a1806a6e4213f341084cabda1` [oci-dag-dev](https://oci.dag.dev/?image=docker/scout-sbom-indexer@sha256:bd120478dfb979a8d27e2a6e0e9d985f752bcd0a1806a6e4213f341084cabda1&mt=application%2Fvnd.oci.image.index.v1%2Bjson&size=6175)

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
