### PR TITLE
Scientific Linux reached end of life

### PR DESCRIPTION
**Pull request by sl-team**

### CODE REVIEW

**Comment by jcpunk** [comment]
Starting July 1 2024 Scientific Linux no longer recieves updates.

**Comment by jcpunk** [comment]
Sure, do you have an example I should copy?

**Comment by whalelines** [comment]
Typically the deprecation notice is prefixed to the description in the `README-short.txt` file.

https://github.com/docker-library/docs/blob/master/centos/README-short.txt
https://github.com/docker-library/docs/blob/master/express-gateway/README-short.txt

More extensive guidance can be placed at the top of the `content.md` file, e.g., https://hub.docker.com/_/openjdk (the java directory in the docs has since been removed).

**Comment by jcpunk** [comment]
Is https://github.com/docker-library/docs/pull/2459 what you're looking for?

**Comment by whalelines** [comment]
Yes, thanks!

**Comment by tianon** [comment]
Ok, https://github.com/docker-library/docs/pull/2459 has now successfully propagated to both https://hub.docker.com/_/sl _and_ https://hub.docker.com/r/amd64/sl so we should be good to go. :bow: :heart:

**Review by yosifkit — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Pull request merged**
