### PR TITLE
Call out explicitly that Git tags are discouraged

### PR DESCRIPTION
**Pull request by tianon**
Also, clarified some of the language around the file format itself, including concrete real-world examples of how it looks/works in practice, and the recommendation to go browse other existing files too.

### CODE REVIEW

**Comment by tianon** [comment]
Of course, https://github.com/docker-library/official-images/pull/511/files?w=1 is easier to look at. :+1:

**Comment by md5** [comment]
:+1: I was wondering about this recently. Glad to see it clarified, though I'd be gladder to see tags banned.

Would you guys consider banning tags for any new images going forward and grandfathering the ones currently using tags?

**Comment by tianon** [comment]
That's effectively what this commit was intended to be. :+1:

I realized somewhat recently that even if we trust the maintainer of the image not to change a tag, that doesn't mean someone else with access to that repo (or someone who maliciously gains access) isn't going to change that tag either inadvertently or maliciously.

Also, a full Git commit reference is a hash of the contents it represents, further solidifying the repeatability in the same way we use full GPG fingerprints and embedded hash verification in our `Dockerfile`s wherever possible.  Once I fully realized the implications of this, it was clear that we needed to make tags no longer acceptable.

**Comment by md5** [comment]
:metal:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
