### PR TITLE
Update joomla

### PR DESCRIPTION
**Pull request by zero-24**
Changes

- https://github.com/joomla-docker/docker-joomla/commit/33ce005: Joomla 3.9.22 (https://github.com/joomla-docker/docker-joomla/pull/101)
- https://github.com/joomla-docker/docker-joomla/commit/2c5c804: APCu 5.1.19 (https://github.com/joomla-docker/docker-joomla/pull/105)
- https://github.com/joomla-docker/docker-joomla/commit/6874f56: update missing maintainer line to @HLeithner (https://github.com/joomla-docker/docker-joomla/pull/103)

### CODE REVIEW

**Comment by zero-24** [comment]
The latest changes from the bot have been merged I have just updated the description as requested. This should now be ready.

PS is there any documentation on that bot thing and how to use it correctly? Pulling the branch and push it to my branch and copy the text from the dif that i'm not allowed to merge does not seem right to me?

Would it be possible to appoint one or two trusted maintainer per project to be added to that `docker-library-bot` repo so we can actually use the code pushed to that repo directly?

Or can we allow that bot to push the branche to somewhere we can actually take his work directly?

**Comment by tianon** [comment]
> PS is there any documentation on that bot thing and how to use it correctly? Pulling the branch and push it to my branch and copy the text from the dif that i'm not allowed to merge does not seem right to me?
> 
> Would it be possible to appoint one or two trusted maintainer per project to be added to that `docker-library-bot` repo so we can actually use the code pushed to that repo directly?
> 
> Or can we allow that bot to push the branche to somewhere we can actually take his work directly?

Unfortunately we never intended @docker-library-bot to be a real tool outside our own usage, but having it push somewhere you can open PRs from is a great idea!  If you've got a particular repo in mind, just give me and @docker-library-bot access and I'll see what I can rig up. :smile:

**Comment by zero-24** [comment]
Thanks @tianon I have invited him to: https://github.com/joomla-docker/official-images with write permission. When that bot could create the branch there too a update of that repo is just `on click away` as we can add the people that should do the update.

Just one more questions when / how often does that bot run?

**Comment by zero-24** [comment]
I have just added you to that repo too I'm not sure what permissions you need? feel free to reach out to me at tobias.zulauf[at]community.joomla.org so we can setup all we need together. Thanks for your help!

**Comment by tianon** [comment]
Perfect, all set up!

Currently, each `update.sh` job runs roughly once every six hours (so four times a day).

**Comment by zero-24** [comment]
Awesome thanks for this 👍 Will document how to use that new repo for our update workflow.

**Pull request merged**
