### PR TITLE
haxe: add windowsservercore-1809 variants

### PR DESCRIPTION
**Pull request by andyli**

### CODE REVIEW

**Comment by tianon** [comment]
Isn't 1809 a more specific alias for this currently which is less likely to break, especially if we don't update the build server for the next release immediately for example?

**Comment by andyli** [comment]
I thought they are different images, but looks like ltsc images are just aliases?

Should I add both ltsc2019 and 1809 or only 1809? There are both in the python official image.

**Comment by tianon** [comment]
I think Python has 1809 and ltsc2016 which is the older release.

**Comment by yosifkit** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index ee0e07e..9c6727f 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -3,6 +3,7 @@ haxe:3.1-stretch @ amd64
 haxe:3.1-stretch @ arm32v7
 haxe:3.1-stretch @ arm64v8
 haxe:3.1-windowsservercore-1803 @ windows-amd64
+haxe:3.1-windowsservercore-1809 @ windows-amd64
 haxe:3.1-windowsservercore-ltsc2016 @ windows-amd64
 haxe:3.2-alpine3.7 @ amd64
 haxe:3.2-alpine3.7 @ arm64v8
@@ -20,6 +21,7 @@ haxe:3.2-stretch @ amd64
 haxe:3.2-stretch @ arm32v7
 haxe:3.2-stretch @ arm64v8
 haxe:3.2-windowsservercore-1803 @ windows-amd64
+haxe:3.2-windowsservercore-1809 @ windows-amd64
 haxe:3.2-windowsservercore-ltsc2016 @ windows-amd64
 haxe:3.3-alpine3.7 @ amd64
 haxe:3.3-alpine3.7 @ arm64v8
@@ -37,6 +39,7 @@ haxe:3.3-stretch @ amd64
 haxe:3.3-stretch @ arm32v7
 haxe:3.3-stretch @ arm64v8
 haxe:3.3-windowsservercore-1803 @ windows-amd64
+haxe:3.3-windowsservercore-1809 @ windows-amd64
 haxe:3.3-windowsservercore-ltsc2016 @ windows-amd64
 haxe:3.4-alpine3.7 @ amd64
 haxe:3.4-alpine3.7 @ arm64v8
@@ -54,6 +57,7 @@ haxe:3.4-stretch @ amd64
 haxe:3.4-stretch @ arm32v7
 haxe:3.4-stretch @ arm64v8
 haxe:3.4-windowsservercore-1803 @ windows-amd64
+haxe:3.4-windowsservercore-1809 @ windows-amd64
 haxe:3.4-windowsservercore-ltsc2016 @ windows-amd64
 haxe:4.0-alpine3.7 @ amd64
 haxe:4.0-alpine3.7 @ arm64v8
@@ -71,4 +75,5 @@ haxe:4.0-stretch @ amd64
 haxe:4.0-stretch @ arm32v7
 haxe:4.0-stretch @ arm64v8
 haxe:4.0-windowsservercore-1803 @ windows-amd64
+haxe:4.0-windowsservercore-1809 @ windows-amd64
 haxe:4.0-windowsservercore-ltsc2016 @ windows-amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index 4702d4e..ff6e67f 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -3,12 +3,14 @@ haxe:3.1-jessie
 haxe:3.1-stretch
 haxe:3.1-windowsservercore
 haxe:3.1-windowsservercore-1803
+haxe:3.1-windowsservercore-1809
 haxe:3.1-windowsservercore-ltsc2016
 haxe:3.1.3
 haxe:3.1.3-jessie
 haxe:3.1.3-stretch
 haxe:3.1.3-windowsservercore
 haxe:3.1.3-windowsservercore-1803
+haxe:3.1.3-windowsservercore-1809
 haxe:3.1.3-windowsservercore-ltsc2016
 haxe:3.2
 haxe:3.2-alpine
@@ -21,6 +23,7 @@ haxe:3.2-jessie
 haxe:3.2-stretch
 haxe:3.2-windowsservercore
 haxe:3.2-windowsservercore-1803
+haxe:3.2-windowsservercore-1809
 haxe:3.2-windowsservercore-ltsc2016
 haxe:3.2.1
 haxe:3.2.1-alpine
@@ -33,6 +36,7 @@ haxe:3.2.1-jessie
 haxe:3.2.1-stretch
 haxe:3.2.1-windowsservercore
 haxe:3.2.1-windowsservercore-1803
+haxe:3.2.1-windowsservercore-1809
 haxe:3.2.1-windowsservercore-ltsc2016
 haxe:3.3
 haxe:3.3-alpine
@@ -45,6 +49,7 @@ haxe:3.3-jessie
 haxe:3.3-stretch
 haxe:3.3-windowsservercore
 haxe:3.3-windowsservercore-1803
+haxe:3.3-windowsservercore-1809
 haxe:3.3-windowsservercore-ltsc2016
 haxe:3.3.0
 haxe:3.3.0-alpine
@@ -65,10 +70,12 @@ haxe:3.3.0-rc.1-jessie
 haxe:3.3.0-rc.1-stretch
 haxe:3.3.0-rc.1-windowsservercore
 haxe:3.3.0-rc.1-windowsservercore-1803
+haxe:3.3.0-rc.1-windowsservercore-1809
 haxe:3.3.0-rc.1-windowsservercore-ltsc2016
 haxe:3.3.0-stretch
 haxe:3.3.0-windowsservercore
 haxe:3.3.0-windowsservercore-1803
+haxe:3.3.0-windowsservercore-1809
 haxe:3.3.0-windowsservercore-ltsc2016
 haxe:3.4
 haxe:3.4-alpine
@@ -81,6 +88,7 @@ haxe:3.4-jessie
 haxe:3.4-stretch
 haxe:3.4-windowsservercore
 haxe:3.4-windowsservercore-1803
+haxe:3.4-windowsservercore-1809
 haxe:3.4-windowsservercore-ltsc2016
 haxe:3.4.7
 haxe:3.4.7-alpine
@@ -93,6 +101,7 @@ haxe:3.4.7-jessie
 haxe:3.4.7-stretch
 haxe:3.4.7-windowsservercore
 haxe:3.4.7-windowsservercore-1803
+haxe:3.4.7-windowsservercore-1809
 haxe:3.4.7-windowsservercore-ltsc2016
 haxe:4.0
 haxe:4.0-alpine
@@ -105,6 +114,7 @@ haxe:4.0-jessie
 haxe:4.0-stretch
 haxe:4.0-windowsservercore
 haxe:4.0-windowsservercore-1803
+haxe:4.0-windowsservercore-1809
 haxe:4.0-windowsservercore-ltsc2016
 haxe:4.0.0
 haxe:4.0.0-alpine
@@ -125,9 +135,11 @@ haxe:4.0.0-rc.3-jessie
 haxe:4.0.0-rc.3-stretch
 haxe:4.0.0-rc.3-windowsservercore
 haxe:4.0.0-rc.3-windowsservercore-1803
+haxe:4.0.0-rc.3-windowsservercore-1809
 haxe:4.0.0-rc.3-windowsservercore-ltsc2016
 haxe:4.0.0-stretch
 haxe:4.0.0-windowsservercore
 haxe:4.0.0-windowsservercore-1803
+haxe:4.0.0-windowsservercore-1809
 haxe:4.0.0-windowsservercore-ltsc2016
 haxe:latest
diff --git a/_bashbrew-shared-tags b/_bashbrew-shared-tags
index 1acc565..bd19b37 100644
--- a/_bashbrew-shared-tags
+++ b/_bashbrew-shared-tags
@@ -1,25 +1,25 @@
-haxe:3.1 -- haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
-haxe:3.1-windowsservercore -- haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
-haxe:3.1.3 -- haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
-haxe:3.1.3-windowsservercore -- haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
-haxe:3.2 -- haxe:3.2-buster, haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
-haxe:3.2-windowsservercore -- haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
-haxe:3.2.1 -- haxe:3.2-buster, haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
-haxe:3.2.1-windowsservercore -- haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
-haxe:3.3 -- haxe:3.3-buster, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
-haxe:3.3-windowsservercore -- haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
-haxe:3.3.0 -- haxe:3.3-buster, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
-haxe:3.3.0-rc.1 -- haxe:3.3-buster, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
-haxe:3.3.0-rc.1-windowsservercore -- haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
-haxe:3.3.0-windowsservercore -- haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
-haxe:3.4 -- haxe:3.4-buster, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
-haxe:3.4-windowsservercore -- haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
-haxe:3.4.7 -- haxe:3.4-buster, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
-haxe:3.4.7-windowsservercore -- haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
-haxe:4.0 -- haxe:4.0-buster, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
-haxe:4.0-windowsservercore -- haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
-haxe:4.0.0 -- haxe:4.0-buster, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
-haxe:4.0.0-rc.3 -- haxe:4.0-buster, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
-haxe:4.0.0-rc.3-windowsservercore -- haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
-haxe:4.0.0-windowsservercore -- haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
-haxe:latest -- haxe:3.4-buster, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
+haxe:3.1 -- haxe:3.1-windowsservercore-1809, haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
+haxe:3.1-windowsservercore -- haxe:3.1-windowsservercore-1809, haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
+haxe:3.1.3 -- haxe:3.1-windowsservercore-1809, haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
+haxe:3.1.3-windowsservercore -- haxe:3.1-windowsservercore-1809, haxe:3.1-windowsservercore-1803, haxe:3.1-windowsservercore-ltsc2016
+haxe:3.2 -- haxe:3.2-buster, haxe:3.2-windowsservercore-1809, haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
+haxe:3.2-windowsservercore -- haxe:3.2-windowsservercore-1809, haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
+haxe:3.2.1 -- haxe:3.2-buster, haxe:3.2-windowsservercore-1809, haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
+haxe:3.2.1-windowsservercore -- haxe:3.2-windowsservercore-1809, haxe:3.2-windowsservercore-1803, haxe:3.2-windowsservercore-ltsc2016
+haxe:3.3 -- haxe:3.3-buster, haxe:3.3-windowsservercore-1809, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
+haxe:3.3-windowsservercore -- haxe:3.3-windowsservercore-1809, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
+haxe:3.3.0 -- haxe:3.3-buster, haxe:3.3-windowsservercore-1809, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
+haxe:3.3.0-rc.1 -- haxe:3.3-buster, haxe:3.3-windowsservercore-1809, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
+haxe:3.3.0-rc.1-windowsservercore -- haxe:3.3-windowsservercore-1809, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
+haxe:3.3.0-windowsservercore -- haxe:3.3-windowsservercore-1809, haxe:3.3-windowsservercore-1803, haxe:3.3-windowsservercore-ltsc2016
+haxe:3.4 -- haxe:3.4-buster, haxe:3.4-windowsservercore-1809, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
+haxe:3.4-windowsservercore -- haxe:3.4-windowsservercore-1809, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
+haxe:3.4.7 -- haxe:3.4-buster, haxe:3.4-windowsservercore-1809, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
+haxe:3.4.7-windowsservercore -- haxe:3.4-windowsservercore-1809, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
+haxe:4.0 -- haxe:4.0-buster, haxe:4.0-windowsservercore-1809, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
+haxe:4.0-windowsservercore -- haxe:4.0-windowsservercore-1809, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
+haxe:4.0.0 -- haxe:4.0-buster, haxe:4.0-windowsservercore-1809, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
+haxe:4.0.0-rc.3 -- haxe:4.0-buster, haxe:4.0-windowsservercore-1809, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
+haxe:4.0.0-rc.3-windowsservercore -- haxe:4.0-windowsservercore-1809, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
+haxe:4.0.0-windowsservercore -- haxe:4.0-windowsservercore-1809, haxe:4.0-windowsservercore-1803, haxe:4.0-windowsservercore-ltsc2016
+haxe:latest -- haxe:3.4-buster, haxe:3.4-windowsservercore-1809, haxe:3.4-windowsservercore-1803, haxe:3.4-windowsservercore-ltsc2016
diff --git a/haxe_3.1-windowsservercore-1803/Dockerfile b/haxe_3.1-windowsservercore-1809/Dockerfile
similarity index 98%
copy from haxe_3.1-windowsservercore-1803/Dockerfile
copy to haxe_3.1-windowsservercore-1809/Dockerfile
index 54cfa26..0f5bb06 100644
--- a/haxe_3.1-windowsservercore-1803/Dockerfile
+++ b/haxe_3.1-windowsservercore-1809/Dockerfile
@@ -4,7 +4,7 @@
 # PLEASE DO NOT EDIT IT DIRECTLY.
 #
 
-FROM mcr.microsoft.com/windows/servercore:1803
+FROM mcr.microsoft.com/windows/servercore:1809
 
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
 
diff --git a/haxe_3.2-windowsservercore-1803/Dockerfile b/haxe_3.2-windowsservercore-1809/Dockerfile
similarity index 98%
copy from haxe_3.2-windowsservercore-1803/Dockerfile
copy to haxe_3.2-windowsservercore-1809/Dockerfile
index b67172d..6d1a493 100644
--- a/haxe_3.2-windowsservercore-1803/Dockerfile
+++ b/haxe_3.2-windowsservercore-1809/Dockerfile
@@ -4,7 +4,7 @@
 # PLEASE DO NOT EDIT IT DIRECTLY.
 #
 
-FROM mcr.microsoft.com/windows/servercore:1803
+FROM mcr.microsoft.com/windows/servercore:1809
 
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
 
diff --git a/haxe_3.3-windowsservercore-1803/Dockerfile b/haxe_3.3-windowsservercore-1809/Dockerfile
similarity index 98%
copy from haxe_3.3-windowsservercore-1803/Dockerfile
copy to haxe_3.3-windowsservercore-1809/Dockerfile
index cd3007c..375d52d 100644
--- a/haxe_3.3-windowsservercore-1803/Dockerfile
+++ b/haxe_3.3-windowsservercore-1809/Dockerfile
@@ -4,7 +4,7 @@
 # PLEASE DO NOT EDIT IT DIRECTLY.
 #
 
-FROM mcr.microsoft.com/windows/servercore:1803
+FROM mcr.microsoft.com/windows/servercore:1809
 
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
 
diff --git a/haxe_3.4-windowsservercore-1803/Dockerfile b/haxe_3.4-windowsservercore-1809/Dockerfile
similarity index 98%
copy from haxe_3.4-windowsservercore-1803/Dockerfile
copy to haxe_3.4-windowsservercore-1809/Dockerfile
index f425ac0..d303bb6 100644
--- a/haxe_3.4-windowsservercore-1803/Dockerfile
+++ b/haxe_3.4-windowsservercore-1809/Dockerfile
@@ -4,7 +4,7 @@
 # PLEASE DO NOT EDIT IT DIRECTLY.
 #
 
-FROM mcr.microsoft.com/windows/servercore:1803
+FROM mcr.microsoft.com/windows/servercore:1809
 
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
 
diff --git a/haxe_4.0-windowsservercore-1803/Dockerfile b/haxe_4.0-windowsservercore-1809/Dockerfile
similarity index 98%
copy from haxe_4.0-windowsservercore-1803/Dockerfile
copy to haxe_4.0-windowsservercore-1809/Dockerfile
index c088b70..e88d7d1 100644
--- a/haxe_4.0-windowsservercore-1803/Dockerfile
+++ b/haxe_4.0-windowsservercore-1809/Dockerfile
@@ -4,7 +4,7 @@
 # PLEASE DO NOT EDIT IT DIRECTLY.
 #
 
-FROM mcr.microsoft.com/windows/servercore:1803
+FROM mcr.microsoft.com/windows/servercore:1809
 
 SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
 
```

</details>

**Pull request merged**
