### PR TITLE
Updated mageia 7 images, added cauldron

### PR DESCRIPTION
**Pull request by juanluisbaptiste**
Hi,

Updated images for mageia 7 and added new ones for cauldron version.

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi @tianon , could you tell me what's wrong here ? what I'm missing ?

**Comment by tianon** [comment]
You're good!  It just happens that diff is too large for our bot to auto-comment on the PR - we'll create it out-of-band and post it to a gist instead. :+1:

**Comment by tianon** [comment]
Diff: https://gist.github.com/docker-library-bot/8040168a1e850f9a838f089c0481f7e3

**Comment by tianon** [comment]
LGTM :+1:

**Comment by juanluisbaptiste** [comment]
Excellent, thanks !!

**Pull request merged**
