### PR TITLE
Add support for Semeru 23 container images and update tomcat version.

### PR DESCRIPTION
**Pull request by ramachandrabolisetti**
This update contains:

- Semeru 23 container images added.
- Tomcat version update.

### CODE REVIEW

**Comment by tianon** [comment]
22 is now EOL as well, right? (and thus should be removed?) :eyes:

As a reminder, removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by ramachandrabolisetti** [comment]
I will discuss on the EOS and I will remove 22 tag once the timeline is confirmed. Thanks !!

**Comment by tianon** [comment]
```
+FROM ubuntu:23.04
```

The images tagged "jammy" aren't from jammy :sweat_smile:

(FWIW, these _could_ be `FROM ubuntu:jammy` so it's easier to keep them in sync correctly)

**Review by tianon — APPROVED** [review]

**Comment by yosifkit** [comment]
`ibm-semeru-runtimes` images are failing to rebuild after base image updates (Ubuntu rebuilds) because the "old" tomcat is no longer available through the CDN. Can you provide some updated Dockerfiles? Perhaps they could fallback to `https://archive.apache.org/dist/` when it is no longer available on the primary Apache CDN? It is up to you if you want to add the archive fallback. (We have a block that does this for our [`cassandra` images](https://github.com/docker-library/cassandra/blob/1e3d5732f34ceb9e77870d0be9501515f917cc60/5.0/Dockerfile#L107-L118)).
```console
+ curl -LfsSo /tmp/tomcat/tomcat.tar.gz https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.95/bin/apache-tomcat-9.0.95.tar.gz
curl: (22) The requested URL returned error: 404 
```

**Pull request merged**
