### PR TITLE
Friendica Release 2022.02

### PR DESCRIPTION
**Pull request by nupplaphil**
- Release 2022.02
- Bugfix memory_limit

### CODE REVIEW

**Comment by tianon** [comment]
Managed to get `git` to generate a slightly better diff:

<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-cat b/_bashbrew-cat
index 558e2fe..22e6eaf 100644
--- a/_bashbrew-cat
+++ b/_bashbrew-cat
@@ -2,47 +2,47 @@ Maintainers: Friendica <info@friendi.ca> (@friendica), Philipp Holzer <admin@phi
 GitRepo: https://github.com/friendica/docker.git
 GitFetch: refs/heads/stable
 
-Tags: 2021.09-apache, apache, stable-apache, 2021.09, latest, stable
+Tags: 2021.09-apache, 2021.09
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
-GitCommit: 9f8658cf5372dc4ac75a9d5d330d7f35a83ddbdf
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
 Directory: 2021.09/apache
 
-Tags: 2021.09-fpm, fpm, stable-fpm
+Tags: 2021.09-fpm
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
-GitCommit: 9f8658cf5372dc4ac75a9d5d330d7f35a83ddbdf
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
 Directory: 2021.09/fpm
 
-Tags: 2021.09-fpm-alpine, fpm-alpine, stable-fpm-alpine
+Tags: 2021.09-fpm-alpine
 Architectures: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x
-GitCommit: 9f8658cf5372dc4ac75a9d5d330d7f35a83ddbdf
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
 Directory: 2021.09/fpm-alpine
 
-Tags: 2021.12-dev-apache, dev-apache, 2021.12-dev, dev
+Tags: 2022.02-apache, apache, stable-apache, 2022.02, latest, stable
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
-GitCommit: 933e3c5604ff01fe6a2a4d3a23b92effe5e152b0
-Directory: 2021.12-dev/apache
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
+Directory: 2022.02/apache
 
-Tags: 2021.12-dev-fpm, dev-fpm
+Tags: 2022.02-fpm, fpm, stable-fpm
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
-GitCommit: 933e3c5604ff01fe6a2a4d3a23b92effe5e152b0
-Directory: 2021.12-dev/fpm
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
+Directory: 2022.02/fpm
 
-Tags: 2021.12-dev-fpm-alpine, dev-fpm-alpine
+Tags: 2022.02-fpm-alpine, fpm-alpine, stable-fpm-alpine
 Architectures: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x
-GitCommit: 933e3c5604ff01fe6a2a4d3a23b92effe5e152b0
-Directory: 2021.12-dev/fpm-alpine
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
+Directory: 2022.02/fpm-alpine
 
-Tags: 2021.12-rc-apache, rc-apache, 2021.12-rc, rc
+Tags: 2022.05-dev-apache, dev-apache, 2022.05-dev, dev
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
-GitCommit: 933e3c5604ff01fe6a2a4d3a23b92effe5e152b0
-Directory: 2021.12-rc/apache
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
+Directory: 2022.05-dev/apache
 
-Tags: 2021.12-rc-fpm, rc-fpm
+Tags: 2022.05-dev-fpm, dev-fpm
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, s390x
-GitCommit: 933e3c5604ff01fe6a2a4d3a23b92effe5e152b0
-Directory: 2021.12-rc/fpm
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
+Directory: 2022.05-dev/fpm
 
-Tags: 2021.12-rc-fpm-alpine, rc-fpm-alpine
+Tags: 2022.05-dev-fpm-alpine, dev-fpm-alpine
 Architectures: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x
-GitCommit: 933e3c5604ff01fe6a2a4d3a23b92effe5e152b0
-Directory: 2021.12-rc/fpm-alpine
+GitCommit: c277360de4dd812801a297e07cccd94e86dc9a04
+Directory: 2022.05-dev/fpm-alpine
diff --git a/_bashbrew-list b/_bashbrew-list
index 61cf2c1..c89de0f 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -2,14 +2,14 @@ friendica:2021.09
 friendica:2021.09-apache
 friendica:2021.09-fpm
 friendica:2021.09-fpm-alpine
-friendica:2021.12-dev
-friendica:2021.12-dev-apache
-friendica:2021.12-dev-fpm
-friendica:2021.12-dev-fpm-alpine
-friendica:2021.12-rc
-friendica:2021.12-rc-apache
-friendica:2021.12-rc-fpm
-friendica:2021.12-rc-fpm-alpine
+friendica:2022.02
+friendica:2022.02-apache
+friendica:2022.02-fpm
+friendica:2022.02-fpm-alpine
+friendica:2022.05-dev
+friendica:2022.05-dev-apache
+friendica:2022.05-dev-fpm
+friendica:2022.05-dev-fpm-alpine
 friendica:apache
 friendica:dev
 friendica:dev-apache
@@ -18,10 +18,6 @@ friendica:dev-fpm-alpine
 friendica:fpm
 friendica:fpm-alpine
 friendica:latest
-friendica:rc
-friendica:rc-apache
-friendica:rc-fpm
-friendica:rc-fpm-alpine
 friendica:stable
 friendica:stable-apache
 friendica:stable-fpm
diff --git a/friendica_stable-fpm-alpine/Dockerfile b/friendica_2021.09-fpm-alpine/Dockerfile
similarity index 96%
copy from friendica_stable-fpm-alpine/Dockerfile
copy to friendica_2021.09-fpm-alpine/Dockerfile
index 2e893ee..6d5668a 100644
--- a/friendica_stable-fpm-alpine/Dockerfile
+++ b/friendica_2021.09-fpm-alpine/Dockerfile
@@ -81,8 +81,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install APCu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -120,9 +120,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
diff --git a/friendica_rc-fpm-alpine/config/00apcu.config.php b/friendica_2021.09-fpm-alpine/config/00apcu.config.php
similarity index 100%
rename from friendica_rc-fpm-alpine/config/00apcu.config.php
rename to friendica_2021.09-fpm-alpine/config/00apcu.config.php
diff --git a/friendica_rc-fpm-alpine/config/01redis.config.php b/friendica_2021.09-fpm-alpine/config/01redis.config.php
similarity index 100%
rename from friendica_rc-fpm-alpine/config/01redis.config.php
rename to friendica_2021.09-fpm-alpine/config/01redis.config.php
diff --git a/friendica_rc-fpm-alpine/config/zz-docker.config.php b/friendica_2021.09-fpm-alpine/config/zz-docker.config.php
similarity index 100%
rename from friendica_rc-fpm-alpine/config/zz-docker.config.php
rename to friendica_2021.09-fpm-alpine/config/zz-docker.config.php
diff --git a/friendica_rc-fpm-alpine/cron.sh b/friendica_2021.09-fpm-alpine/cron.sh
similarity index 100%
rename from friendica_rc-fpm-alpine/cron.sh
rename to friendica_2021.09-fpm-alpine/cron.sh
diff --git a/friendica_rc-fpm-alpine/entrypoint.sh b/friendica_2021.09-fpm-alpine/entrypoint.sh
similarity index 100%
rename from friendica_rc-fpm-alpine/entrypoint.sh
rename to friendica_2021.09-fpm-alpine/entrypoint.sh
diff --git a/friendica_rc-fpm-alpine/setup_msmtp.sh b/friendica_2021.09-fpm-alpine/setup_msmtp.sh
similarity index 100%
rename from friendica_rc-fpm-alpine/setup_msmtp.sh
rename to friendica_2021.09-fpm-alpine/setup_msmtp.sh
diff --git a/friendica_rc-fpm-alpine/upgrade.exclude b/friendica_2021.09-fpm-alpine/upgrade.exclude
similarity index 100%
rename from friendica_rc-fpm-alpine/upgrade.exclude
rename to friendica_2021.09-fpm-alpine/upgrade.exclude
diff --git a/friendica_stable-fpm/Dockerfile b/friendica_2021.09-fpm/Dockerfile
similarity index 96%
copy from friendica_stable-fpm/Dockerfile
copy to friendica_2021.09-fpm/Dockerfile
index 1d7d79b..a687f81 100644
--- a/friendica_stable-fpm/Dockerfile
+++ b/friendica_2021.09-fpm/Dockerfile
@@ -95,8 +95,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install apcu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -139,9 +139,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
diff --git a/friendica_rc-fpm/config/00apcu.config.php b/friendica_2021.09-fpm/config/00apcu.config.php
similarity index 100%
rename from friendica_rc-fpm/config/00apcu.config.php
rename to friendica_2021.09-fpm/config/00apcu.config.php
diff --git a/friendica_rc-fpm/config/01redis.config.php b/friendica_2021.09-fpm/config/01redis.config.php
similarity index 100%
rename from friendica_rc-fpm/config/01redis.config.php
rename to friendica_2021.09-fpm/config/01redis.config.php
diff --git a/friendica_rc-fpm/config/zz-docker.config.php b/friendica_2021.09-fpm/config/zz-docker.config.php
similarity index 100%
rename from friendica_rc-fpm/config/zz-docker.config.php
rename to friendica_2021.09-fpm/config/zz-docker.config.php
diff --git a/friendica_rc-fpm/cron.sh b/friendica_2021.09-fpm/cron.sh
similarity index 100%
rename from friendica_rc-fpm/cron.sh
rename to friendica_2021.09-fpm/cron.sh
diff --git a/friendica_rc-fpm/entrypoint.sh b/friendica_2021.09-fpm/entrypoint.sh
similarity index 100%
rename from friendica_rc-fpm/entrypoint.sh
rename to friendica_2021.09-fpm/entrypoint.sh
diff --git a/friendica_rc-fpm/setup_msmtp.sh b/friendica_2021.09-fpm/setup_msmtp.sh
similarity index 100%
rename from friendica_rc-fpm/setup_msmtp.sh
rename to friendica_2021.09-fpm/setup_msmtp.sh
diff --git a/friendica_rc-fpm/upgrade.exclude b/friendica_2021.09-fpm/upgrade.exclude
similarity index 100%
rename from friendica_rc-fpm/upgrade.exclude
rename to friendica_2021.09-fpm/upgrade.exclude
diff --git a/friendica_stable/Dockerfile b/friendica_2021.09/Dockerfile
similarity index 97%
copy from friendica_stable/Dockerfile
copy to friendica_2021.09/Dockerfile
index 15a622d..2191133 100644
--- a/friendica_stable/Dockerfile
+++ b/friendica_2021.09/Dockerfile
@@ -95,8 +95,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install apcu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -139,9 +139,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
diff --git a/friendica_rc/config/00apcu.config.php b/friendica_2021.09/config/00apcu.config.php
similarity index 100%
rename from friendica_rc/config/00apcu.config.php
rename to friendica_2021.09/config/00apcu.config.php
diff --git a/friendica_rc/config/01redis.config.php b/friendica_2021.09/config/01redis.config.php
similarity index 100%
rename from friendica_rc/config/01redis.config.php
rename to friendica_2021.09/config/01redis.config.php
diff --git a/friendica_rc/config/zz-docker.config.php b/friendica_2021.09/config/zz-docker.config.php
similarity index 100%
rename from friendica_rc/config/zz-docker.config.php
rename to friendica_2021.09/config/zz-docker.config.php
diff --git a/friendica_rc/cron.sh b/friendica_2021.09/cron.sh
similarity index 100%
rename from friendica_rc/cron.sh
rename to friendica_2021.09/cron.sh
diff --git a/friendica_rc/entrypoint.sh b/friendica_2021.09/entrypoint.sh
similarity index 100%
rename from friendica_rc/entrypoint.sh
rename to friendica_2021.09/entrypoint.sh
diff --git a/friendica_rc/setup_msmtp.sh b/friendica_2021.09/setup_msmtp.sh
similarity index 100%
rename from friendica_rc/setup_msmtp.sh
rename to friendica_2021.09/setup_msmtp.sh
diff --git a/friendica_rc/upgrade.exclude b/friendica_2021.09/upgrade.exclude
similarity index 100%
rename from friendica_rc/upgrade.exclude
rename to friendica_2021.09/upgrade.exclude
diff --git a/friendica_dev-fpm-alpine/Dockerfile b/friendica_dev-fpm-alpine/Dockerfile
index 879413a..2969104 100644
--- a/friendica_dev-fpm-alpine/Dockerfile
+++ b/friendica_dev-fpm-alpine/Dockerfile
@@ -81,8 +81,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install APCu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -120,9 +120,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
@@ -134,8 +134,8 @@ VOLUME /var/www/html
 
 # 39 = LOG_PID | LOG_ODELAY | LOG_CONS | LOG_PERROR
 ENV FRIENDICA_SYSLOG_FLAGS 39
-ENV FRIENDICA_VERSION "2021.12-dev"
-ENV FRIENDICA_ADDONS "2021.12-dev"
+ENV FRIENDICA_VERSION "2022.05-dev"
+ENV FRIENDICA_ADDONS "2022.05-dev"
 
 RUN set -ex; \
      apk add --no-cache --virtual .fetch-deps \
diff --git a/friendica_dev-fpm/Dockerfile b/friendica_dev-fpm/Dockerfile
index adca04b..2550d35 100644
--- a/friendica_dev-fpm/Dockerfile
+++ b/friendica_dev-fpm/Dockerfile
@@ -95,8 +95,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install apcu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -139,9 +139,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
@@ -153,8 +153,8 @@ VOLUME /var/www/html
 
 # 39 = LOG_PID | LOG_ODELAY | LOG_CONS | LOG_PERROR
 ENV FRIENDICA_SYSLOG_FLAGS 39
-ENV FRIENDICA_VERSION "2021.12-dev"
-ENV FRIENDICA_ADDONS "2021.12-dev"
+ENV FRIENDICA_VERSION "2022.05-dev"
+ENV FRIENDICA_ADDONS "2022.05-dev"
 
 RUN set -ex; \
     fetchDeps=" \
diff --git a/friendica_dev/Dockerfile b/friendica_dev/Dockerfile
index d088a56..6bc2e83 100644
--- a/friendica_dev/Dockerfile
+++ b/friendica_dev/Dockerfile
@@ -95,8 +95,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install apcu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -139,9 +139,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
@@ -162,8 +162,8 @@ RUN set -ex;\
 
 # 39 = LOG_PID | LOG_ODELAY | LOG_CONS | LOG_PERROR
 ENV FRIENDICA_SYSLOG_FLAGS 39
-ENV FRIENDICA_VERSION "2021.12-dev"
-ENV FRIENDICA_ADDONS "2021.12-dev"
+ENV FRIENDICA_VERSION "2022.05-dev"
+ENV FRIENDICA_ADDONS "2022.05-dev"
 
 RUN set -ex; \
     fetchDeps=" \
diff --git a/friendica_rc-fpm-alpine/Dockerfile b/friendica_rc-fpm-alpine/Dockerfile
deleted file mode 100644
index ba5d553..0000000
diff --git a/friendica_rc-fpm-alpine/entrypoint-dev.sh b/friendica_rc-fpm-alpine/entrypoint-dev.sh
deleted file mode 100755
index 8b34c21..0000000
diff --git a/friendica_rc-fpm/Dockerfile b/friendica_rc-fpm/Dockerfile
deleted file mode 100644
index 868ba61..0000000
diff --git a/friendica_rc-fpm/entrypoint-dev.sh b/friendica_rc-fpm/entrypoint-dev.sh
deleted file mode 100755
index 8b34c21..0000000
diff --git a/friendica_rc/Dockerfile b/friendica_rc/Dockerfile
deleted file mode 100644
index 66952d4..0000000
diff --git a/friendica_rc/entrypoint-dev.sh b/friendica_rc/entrypoint-dev.sh
deleted file mode 100755
index 8b34c21..0000000
diff --git a/friendica_stable-fpm-alpine/Dockerfile b/friendica_stable-fpm-alpine/Dockerfile
index 2e893ee..f0e1038 100644
--- a/friendica_stable-fpm-alpine/Dockerfile
+++ b/friendica_stable-fpm-alpine/Dockerfile
@@ -81,8 +81,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install APCu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -120,9 +120,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
@@ -134,10 +134,10 @@ VOLUME /var/www/html
 
 # 39 = LOG_PID | LOG_ODELAY | LOG_CONS | LOG_PERROR
 ENV FRIENDICA_SYSLOG_FLAGS 39
-ENV FRIENDICA_VERSION "2021.09"
-ENV FRIENDICA_ADDONS "2021.09"
-ENV FRIENDICA_DOWNLOAD_SHA256 "3f33f5a63c4e9d8ea55b21a33d46663f4b1d636a6546fa3603a244583d3b6faf"
-ENV FRIENDICA_DOWNLOAD_ADDONS_SHA256 "1910e732b3ca3fc35e57835f217746d6e1fbed1f76d8da1c989742ac2237090d"
+ENV FRIENDICA_VERSION "2022.02"
+ENV FRIENDICA_ADDONS "2022.02"
+ENV FRIENDICA_DOWNLOAD_SHA256 "032be1a8c7e1a82d34eebc95b5bd2f2564a9114834eff45e6b4daa240eab22e8"
+ENV FRIENDICA_DOWNLOAD_ADDONS_SHA256 "146240e7215d15d743bee4e0d3c084315b5a1778493f400284e80ff84e3cd1ce"
 
 RUN set -ex; \
      apk add --no-cache --virtual .fetch-deps \
diff --git a/friendica_stable-fpm/Dockerfile b/friendica_stable-fpm/Dockerfile
index 1d7d79b..de49d15 100644
--- a/friendica_stable-fpm/Dockerfile
+++ b/friendica_stable-fpm/Dockerfile
@@ -95,8 +95,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install apcu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -139,9 +139,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
@@ -153,10 +153,10 @@ VOLUME /var/www/html
 
 # 39 = LOG_PID | LOG_ODELAY | LOG_CONS | LOG_PERROR
 ENV FRIENDICA_SYSLOG_FLAGS 39
-ENV FRIENDICA_VERSION "2021.09"
-ENV FRIENDICA_ADDONS "2021.09"
-ENV FRIENDICA_DOWNLOAD_SHA256 "3f33f5a63c4e9d8ea55b21a33d46663f4b1d636a6546fa3603a244583d3b6faf"
-ENV FRIENDICA_DOWNLOAD_ADDONS_SHA256 "1910e732b3ca3fc35e57835f217746d6e1fbed1f76d8da1c989742ac2237090d"
+ENV FRIENDICA_VERSION "2022.02"
+ENV FRIENDICA_ADDONS "2022.02"
+ENV FRIENDICA_DOWNLOAD_SHA256 "032be1a8c7e1a82d34eebc95b5bd2f2564a9114834eff45e6b4daa240eab22e8"
+ENV FRIENDICA_DOWNLOAD_ADDONS_SHA256 "146240e7215d15d743bee4e0d3c084315b5a1778493f400284e80ff84e3cd1ce"
 
 RUN set -ex; \
     fetchDeps=" \
diff --git a/friendica_stable/Dockerfile b/friendica_stable/Dockerfile
index 15a622d..73f2ed2 100644
--- a/friendica_stable/Dockerfile
+++ b/friendica_stable/Dockerfile
@@ -95,8 +95,8 @@ RUN set -ex; \
 # pecl will claim success even if one install fails, so we need to perform each install separately
     pecl install apcu-5.1.21; \
     pecl install memcached-3.1.5; \
-    pecl install redis-5.3.5; \
-    pecl install imagick-3.5.1; \
+    pecl install redis-5.3.6; \
+    pecl install imagick-3.7.0; \
     \
     docker-php-ext-enable \
         apcu \
@@ -139,9 +139,9 @@ RUN set -ex; \
     echo 'apc.enable_cli=1' >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini; \
     \
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
     \
     mkdir /var/www/data; \
@@ -162,10 +162,10 @@ RUN set -ex;\
 
 # 39 = LOG_PID | LOG_ODELAY | LOG_CONS | LOG_PERROR
 ENV FRIENDICA_SYSLOG_FLAGS 39
-ENV FRIENDICA_VERSION "2021.09"
-ENV FRIENDICA_ADDONS "2021.09"
-ENV FRIENDICA_DOWNLOAD_SHA256 "3f33f5a63c4e9d8ea55b21a33d46663f4b1d636a6546fa3603a244583d3b6faf"
-ENV FRIENDICA_DOWNLOAD_ADDONS_SHA256 "1910e732b3ca3fc35e57835f217746d6e1fbed1f76d8da1c989742ac2237090d"
+ENV FRIENDICA_VERSION "2022.02"
+ENV FRIENDICA_ADDONS "2022.02"
+ENV FRIENDICA_DOWNLOAD_SHA256 "032be1a8c7e1a82d34eebc95b5bd2f2564a9114834eff45e6b4daa240eab22e8"
+ENV FRIENDICA_DOWNLOAD_ADDONS_SHA256 "146240e7215d15d743bee4e0d3c084315b5a1778493f400284e80ff84e3cd1ce"
 
 RUN set -ex; \
     fetchDeps=" \
```

</details>

**Comment by tianon** [comment]
```diff
     { \
-        echo 'memory_limit=${PHP_MEMORY_LIMIT}'; \
-        echo 'upload_max_filesize=${PHP_UPLOAD_LIMIT}'; \
-        echo 'post_max_size=${PHP_UPLOAD_LIMIT}'; \
+        echo "memory_limit=${PHP_MEMORY_LIMIT}"; \
+        echo "upload_max_filesize=${PHP_UPLOAD_LIMIT}"; \
+        echo "post_max_size=${PHP_UPLOAD_LIMIT}"; \
     } > /usr/local/etc/php/conf.d/friendica.ini; \
```

I think this change was probably unintentional - it's different in a very subtle way.  The old version puts literally `${XXX}` into the `php.ini` file, which is then evaluated by PHP itself at runtime.  The new version puts the current values of those variables into the configuration instead, which breaks the ability to modify them at runtime.

**Comment by tianon** [comment]
To demonstrate with the existing images:

```console
$ docker run --rm friendica php -i | grep memory_limit
memory_limit => 512M => 512M

$ docker run --rm --env PHP_MEMORY_LIMIT=1G friendica php -i | grep memory_limit
memory_limit => 1G => 1G
```

**Comment by nupplaphil** [comment]
Ah damn, I "had" this issue https://github.com/friendica/docker/issues/185 and thought I fixed it because of the wrong apostrophes. But you're right, now the env variable doesn't matter anymore.

Do you have a hint for me why the old way throws a memory exception even for a fresh very basic install like described at https://github.com/friendica/docker/issues/185 ?

**Comment by yosifkit** [comment]
The problem is that when the entrypoint is running stuff as the `www-data` user, the environment is scrubbed by `su` (https://github.com/friendica/docker/blob/7157ae6ac9ced8fa1c0b186993ab578092ce3cb1/docker-entrypoint.sh#L4-L12). So when that `php` runs, it doesn't have a value set for `PHP_MEMORY_LIMIT` (or access to any of the user supplied values).

**Comment by nupplaphil** [comment]
Thank you!

**Pull request merged**
