### PR TITLE
Add Jetty

### PR DESCRIPTION
**Pull request by md5**
Please review. I'll open a docs PR shortly.

Closes docker-library/official-images#203

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM
Build test of #469; 7523911829e8da387dc1af27da4a1147e1a76bda (`jetty`):

```console
$ url="https://raw.githubusercontent.com/docker-library/official-images/7523911829e8da387dc1af27da4a1147e1a76bda/library/jetty"
$ bashbrew build "$url"
Cloning jetty (git://github.com/md5/docker-jetty) ...
Processing jetty:7.6.16-jre7 ...
Processing jetty:7.6-jre7 ...
Processing jetty:7-jre7 ...
Processing jetty:7.6.16 ...
Processing jetty:7.6 ...
Processing jetty:7 ...
Processing jetty:7.6.16-jre8 ...
Processing jetty:7.6-jre8 ...
Processing jetty:7-jre8 ...
Processing jetty:8.1.16-jre7 ...
Processing jetty:8.1-jre7 ...
Processing jetty:8-jre7 ...
Processing jetty:8.1.16 ...
Processing jetty:8.1 ...
Processing jetty:8 ...
Processing jetty:8.1.16-jre8 ...
Processing jetty:8.1-jre8 ...
Processing jetty:8-jre8 ...
Processing jetty:9.2.7-jre7 ...
Processing jetty:9.2-jre7 ...
Processing jetty:9-jre7 ...
Processing jetty:jre7 ...
Processing jetty:9.2.7 ...
Processing jetty:9.2 ...
Processing jetty:9 ...
Processing jetty:latest ...
Processing jetty:9.2.7-jre8 ...
Processing jetty:9.2-jre8 ...
Processing jetty:9-jre8 ...
Processing jetty:jre8 ...
$ bashbrew list "$url" | xargs test/run.sh
testing jetty:7.6.16-jre7
	'utc' [1/1]...passed
testing jetty:7.6-jre7
	'utc' [1/1]...passed
testing jetty:7-jre7
	'utc' [1/1]...passed
testing jetty:7.6.16
	'utc' [1/1]...passed
testing jetty:7.6
	'utc' [1/1]...passed
testing jetty:7
	'utc' [1/1]...passed
testing jetty:7.6.16-jre8
	'utc' [1/1]...passed
testing jetty:7.6-jre8
	'utc' [1/1]...passed
testing jetty:7-jre8
	'utc' [1/1]...passed
testing jetty:8.1.16-jre7
	'utc' [1/1]...passed
testing jetty:8.1-jre7
	'utc' [1/1]...passed
testing jetty:8-jre7
	'utc' [1/1]...passed
testing jetty:8.1.16
	'utc' [1/1]...passed
testing jetty:8.1
	'utc' [1/1]...passed
testing jetty:8
	'utc' [1/1]...passed
testing jetty:8.1.16-jre8
	'utc' [1/1]...passed
testing jetty:8.1-jre8
	'utc' [1/1]...passed
testing jetty:8-jre8
	'utc' [1/1]...passed
testing jetty:9.2.7-jre7
	'utc' [1/1]...passed
testing jetty:9.2-jre7
	'utc' [1/1]...passed
testing jetty:9-jre7
	'utc' [1/1]...passed
testing jetty:jre7
	'utc' [1/1]...passed
testing jetty:9.2.7
	'utc' [1/1]...passed
testing jetty:9.2
	'utc' [1/1]...passed
testing jetty:9
	'utc' [1/1]...passed
testing jetty:latest
	'utc' [1/1]...passed
testing jetty:9.2.7-jre8
	'utc' [1/1]...passed
testing jetty:9.2-jre8
	'utc' [1/1]...passed
testing jetty:9-jre8
	'utc' [1/1]...passed
testing jetty:jre8
	'utc' [1/1]...passed
```

**Comment by tianon** [comment]
So many tags, like all our Java-based images. :stuck_out_tongue_closed_eyes:

LGTM

**Comment by tianon** [comment]
Welcome to the club, @md5 :heart:

**Comment by tianon** [comment]
You're willing to pass the baton if upstream becomes interested in maintaining this, right? :+1:

**Comment by md5** [comment]
@tianon Of course.

**Comment by tianon** [comment]
:heart:

Figured as much, but better to be sure, right? :smile:

**Comment by md5** [comment]
@tianon Thanks for checking.

FWIW, I'll mention that I've signed up for [`jetty-announce`](https://dev.eclipse.org/mailman/listinfo/jetty-announce) and signed a CLA with the Eclipse Foundation to smooth the path for any patches I may need to make.

I'll also make an effort to be on `#docker-library` on Freenode. My registered nick is "mdillon" on Freenode if you want to `+v` me on the IRC channel.

**Pull request merged**
