### PR TITLE
Update Debian

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Bleh, nope, this needs to be rebuilt for glibc 2.36-9+deb12u4 (https://lists.debian.org/debian-security-announce/2024/msg00018.html)

**Comment by tianon** [comment]
... on the plus side, snapshot already picked it up: https://snapshot.debian.org/package/glibc/2.36-9%2Bdeb12u4/#libc6_2.36-9:2b:deb12u4

**Comment by tianon** [comment]
I'm re-triggering builds against `@1706643859`, which maps to `Tue 30 Jan 2024 07:44:19 PM UTC` and should give us https://snapshot.debian.org/archive/debian-security/20240130T194419Z/ and https://snapshot.debian.org/archive/debian/20240130T152810Z/ both of which should be new enough to include https://snapshot.debian.org/package/glibc/2.36-9%2Bdeb12u4/#libc6_2.36-9:2b:deb12u4

**Review by whalelines — APPROVED** [review]
```diff
-libc-bin	2.36-9+deb12u3
-libc6:amd64	2.36-9+deb12u3
+libc-bin	2.36-9+deb12u4
+libc6:amd64	2.36-9+deb12u4
```

Release the hounds!

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
