### PR TITLE
AlmaLinux: update to 8.5 release

### PR DESCRIPTION
**Pull request by ezamriy**
Release notes are available here: https://wiki.almalinux.org/release-notes/8.5.html

### CODE REVIEW

**Review by srbala — COMMENTED** [review]
LGTM

**Comment by yosifkit** [comment]
While it is not a big problem since we can just "Squash and Merge", we would appreciate if you could rebase plus force push your fork's branch rather than just pull/merge upstream master for a cleaner git commit history.

If we keep using `Squash and Merge" and your branch keeps adding "￼Merge branch 'master' into master", then the list of commits in each successive PR will grow indefinitely. One best practice is to always create a new branch based on the upstream target so that is it always up-to-date; the other is to ensure that a single re-used branch is rebased on upstream master to ensure that there is just a single (or couple) commits added for the PR.

**Comment by srbala** [comment]
Thank you @yosifkit, we will keep in mind going forward

**Comment by ezamriy** [comment]
Oh yes, sorry for that. We will do it in a different way next time. Thanks!

**Comment by srbala** [comment]
@yosifkit @tianon  repo is updated for documentation 5 hours ago, new tags were created but images were not published yet. How long usually it would take to publish images (after documentation updated)?

**Comment by srbala** [comment]
Packages updated now, looks like picked up on daily check

**Pull request merged**
