### PR TITLE
Add new "sid" variant of buildpack-deps

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by yosifkit** [comment]
Do you want to combine this with updates to golang and java to use micro?

**Comment by tianon** [comment]
Oh, I suppose I could do that.

**Comment by tianon** [comment]
"... and switch java to use buildpack-deps:*-micro"

**Comment by tianon** [comment]
Build test of #401; 47c1395f4581be9195ce3d0d6fdfd5dc73ad5eaf (`buildpack-deps`, `java`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/47c1395f4581be9195ce3d0d6fdfd5dc73ad5eaf/library/buildpack-deps
Processing buildpack-deps:jessie-micro ...
Processing buildpack-deps:micro ...
Processing buildpack-deps:jessie ...
Processing buildpack-deps:latest ...
Processing buildpack-deps:sid-micro ...
Processing buildpack-deps:sid ...
Processing buildpack-deps:wheezy-micro ...
Processing buildpack-deps:wheezy ...
```

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/47c1395f4581be9195ce3d0d6fdfd5dc73ad5eaf/library/java
Fetching java (git://github.com/docker-library/java) ...
Processing java:openjdk-6b33-jdk ...
Processing java:openjdk-6b33 ...
Processing java:openjdk-6-jdk ...
Processing java:openjdk-6 ...
Processing java:6b33-jdk ...
Processing java:6b33 ...
Processing java:6-jdk ...
Processing java:6 ...
Processing java:openjdk-6b33-jre ...
Processing java:openjdk-6-jre ...
Processing java:6b33-jre ...
Processing java:6-jre ...
Processing java:openjdk-7u71-jdk ...
Processing java:openjdk-7u71 ...
Processing java:openjdk-7-jdk ...
Processing java:openjdk-7 ...
Processing java:7u71-jdk ...
Processing java:7u71 ...
Processing java:7-jdk ...
Processing java:7 ...
Processing java:jdk ...
Processing java:latest ...
Processing java:openjdk-7u71-jre ...
Processing java:openjdk-7-jre ...
Processing java:7u71-jre ...
Processing java:7-jre ...
Processing java:jre ...
Processing java:openjdk-8u40-b09-jdk ...
Processing java:openjdk-8u40-b09 ...
Processing java:openjdk-8u40-jdk ...
Processing java:openjdk-8u40 ...
Processing java:openjdk-8-jdk ...
Processing java:openjdk-8 ...
Processing java:8u40-b09-jdk ...
Processing java:8u40-b09 ...
Processing java:8u40-jdk ...
Processing java:8u40 ...
Processing java:8-jdk ...
Processing java:8 ...
Processing java:openjdk-8u40-b09-jre ...
Processing java:openjdk-8u40-jre ...
Processing java:openjdk-8-jre ...
Processing java:8u40-b09-jre ...
Processing java:8u40-jre ...
Processing java:8-jre ...
```

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Sizes, for reference: (with some duplicates weeded out to make it easier to read)
```console
$ docker images buildpack-deps
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
buildpack-deps      sid                 791d137b3d74        About an hour ago   732.2 MB
buildpack-deps      sid-micro           5d88036e88d8        About an hour ago   392.2 MB
buildpack-deps      wheezy              9211530a699c        2 weeks ago         560.4 MB
buildpack-deps      wheezy-micro        9cb126bc1b2b        2 weeks ago         244.4 MB
buildpack-deps      jessie              46c3f54a0542        2 weeks ago         728.8 MB
buildpack-deps      jessie-micro        c8e506fcb72c        2 weeks ago         390.9 MB
```
```console
$ docker images java
REPOSITORY          TAG                    IMAGE ID            CREATED             VIRTUAL SIZE
java                openjdk-8-jre          2156ebeb5173        31 minutes ago      611.6 MB
java                openjdk-8-jdk          9bd75a64c742        33 minutes ago      670.3 MB
java                openjdk-7-jre          51e3a9471fe2        37 minutes ago      575.8 MB
java                openjdk-7-jdk          b3a6c99d8d35        39 minutes ago      615.6 MB
java                openjdk-6-jre          617646b542a9        44 minutes ago      413.6 MB
java                openjdk-6-jdk          2c97811c4cf6        47 minutes ago      453.5 MB
```

**Comment by yosifkit** [comment]
I think they are too big. We should fix that. Current sizes:
```console
$ docker images java | grep -e 'openjdk-[0-9]-'
java                openjdk-8-jre          0ab7ad256ec0        2 weeks ago         313.3 MB
java                openjdk-8-jdk          aec8201c9d63        2 weeks ago         662.1 MB
java                openjdk-7-jre          b797b3ba124d        2 weeks ago         342.4 MB
java                openjdk-7-jdk          2853fadead12        2 weeks ago         607.7 MB
java                openjdk-6-jre          5e56022e8a88        2 weeks ago         202.7 MB
java                openjdk-6-jdk          293b3977972c        2 weeks ago         352.6 MB
```

**Pull request merged**
