### PR TITLE
Updated mageia images

### PR DESCRIPTION
**Pull request by juanluisbaptiste**

### CODE REVIEW

**Comment by yosifkit** [comment]
Diff: https://gist.github.com/docker-library-bot/959446b693a86734656c1385a7af76a5

**Comment by juanluisbaptiste** [comment]
Hi @tianon , yes, you are right, I will try to push updated images this week.

**Comment by juanluisbaptiste** [comment]
@tianon We are having issues building the aarch64 images, so this update will take longer than expected.

**Comment by tianon** [comment]
Ouch, thanks for the update! :heart:

I hope you get it figured out. :crossed_fingers:

**Pull request merged**
