### PR TITLE
Upgrade to XWiki 11.5

### PR DESCRIPTION
**Pull request by mflorea**

### CODE REVIEW

**Comment by tianon** [comment]
This has some overlap with https://github.com/docker-library/official-images/pull/5990, doesn't it?

**Comment by tianon** [comment]
(cc @vmassol)

**Comment by vmassol** [comment]
yes I'm back to it, let me check #5990 and take a decision. I'll post back here. Thanks

**Comment by vmassol** [comment]
Superseded by https://github.com/docker-library/official-images/pull/5990

**Pull request closed without merging**
