### PR TITLE
bump version: Elixir 1.3.0 on top of Erlang 19.0

### PR DESCRIPTION
**Pull request by c0b**
as well as the new 2822-based manifest file format.

### CODE REVIEW

**Comment by c0b** [comment]
c0b/docker-elixir#11

**Comment by c0b** [comment]
it's weird why the travis-ci failure?

```console
$ bashbrew list --build-order elixir
error: failed sorting entries list for "elixir"
exit status 128
command: git ["rev-parse" "033f8f8015a012cbb84cf4df4c3bcdbdd1c017af^{commit}"]
fatal: ambiguous argument '033f8f8015a012cbb84cf4df4c3bcdbdd1c017af^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

but this one has no problem run locally: and this commit is available on c0b/docker-elixir@master

```console
➸ git rev-parse '033f8f8015a012cbb84cf4df4c3bcdbdd1c017af^{commit}'
033f8f8015a012cbb84cf4df4c3bcdbdd1c017af
```

**Comment by chatgris** [comment]
@c0b I think it is not the right `GitRepo` here.

**Comment by c0b** [comment]
@chatgris that's brilliant; I have updated

**Comment by tianon** [comment]
Full diff:
```diff
diff --git a/elixir_1.2-onbuild/Dockerfile b/elixir_1.2.6-onbuild/Dockerfile
similarity index 100%
copy from elixir_1.2-onbuild/Dockerfile
copy to elixir_1.2.6-onbuild/Dockerfile
diff --git a/elixir_1.2.3/Dockerfile b/elixir_1.2.6-slim/Dockerfile
similarity index 83%
copy from elixir_1.2.3/Dockerfile
copy to elixir_1.2.6-slim/Dockerfile
index 6a09b77..d6e32aa 100644
--- a/elixir_1.2.3/Dockerfile
+++ b/elixir_1.2.6-slim/Dockerfile
@@ -2,12 +2,12 @@
 FROM erlang:18-slim
 
 # elixir expects utf8.
-ENV ELIXIR_VERSION=v1.2.3 \
+ENV ELIXIR_VERSION="v1.2.6" \
 	LANG=C.UTF-8
 
 RUN set -xe \
 	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/releases/download/${ELIXIR_VERSION#*@}/Precompiled.zip" \
-	&& ELIXIR_DOWNLOAD_SHA256="948483f0b14630851b9cee3332fdb3467943ed4881672ac41dc562e77cd3c785" \
+	&& ELIXIR_DOWNLOAD_SHA256="bb4324eb7c9568fa30f0f2ed3c1b86ebbd5251f7c820f1beb0e5eed5fb8a9729" \
 	&& buildDeps=' \
 		ca-certificates \
 		curl \
diff --git a/elixir_1.2.3/Dockerfile b/elixir_1.2.6/Dockerfile
similarity index 77%
copy from elixir_1.2.3/Dockerfile
copy to elixir_1.2.6/Dockerfile
index 6a09b77..1b5086c 100644
--- a/elixir_1.2.3/Dockerfile
+++ b/elixir_1.2.6/Dockerfile
@@ -1,16 +1,14 @@
 
-FROM erlang:18-slim
+FROM erlang:18
 
 # elixir expects utf8.
-ENV ELIXIR_VERSION=v1.2.3 \
+ENV ELIXIR_VERSION="v1.2.6" \
 	LANG=C.UTF-8
 
 RUN set -xe \
 	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/releases/download/${ELIXIR_VERSION#*@}/Precompiled.zip" \
-	&& ELIXIR_DOWNLOAD_SHA256="948483f0b14630851b9cee3332fdb3467943ed4881672ac41dc562e77cd3c785" \
+	&& ELIXIR_DOWNLOAD_SHA256="bb4324eb7c9568fa30f0f2ed3c1b86ebbd5251f7c820f1beb0e5eed5fb8a9729" \
 	&& buildDeps=' \
-		ca-certificates \
-		curl \
 		unzip \
 	' \
 	&& apt-get update \
diff --git a/elixir_1.3.0-onbuild/Dockerfile b/elixir_1.3.0-onbuild/Dockerfile
new file mode 100644
index 0000000..e288422
--- /dev/null
+++ b/elixir_1.3.0-onbuild/Dockerfile
@@ -0,0 +1,3 @@
+
+FROM elixir:1.3
+
diff --git a/elixir_1.3.0/Dockerfile b/elixir_1.3.0/Dockerfile
new file mode 100644
index 0000000..2084daa
--- /dev/null
+++ b/elixir_1.3.0/Dockerfile
@@ -0,0 +1,21 @@
+
+FROM erlang:19
+
+# elixir expects utf8.
+ENV ELIXIR_VERSION="v1.3.0" \
+	LANG=C.UTF-8
+
+RUN set -xe \
+	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/${ELIXIR_VERSION}.tar.gz" \
+	&& ELIXIR_DOWNLOAD_SHA256="66cb8448dd60397cad11ba554c2613f732192c9026468cff55e8347a5ae4004a" \
+	&& curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL \
+	&& echo "$ELIXIR_DOWNLOAD_SHA256 elixir-src.tar.gz" | sha256sum -c - \
+	&& mkdir -p /usr/src/elixir-src \
+	&& tar -xzf elixir-src.tar.gz -C /usr/src/elixir-src --strip-components=1 \
+	&& rm elixir-src.tar.gz \
+	&& cd /usr/src/elixir-src \
+	&& make -j$(nproc) \
+	&& make install \
+	&& rm -rf /usr/src/elixir-src
+
+CMD ["iex"]
```

**Comment by tianon** [comment]
The new `elixir:1.3-onbuild` is the same as `elixir:1.2-onbuild` (so I don't think it's worth holding up this PR for), but I'm curious what the point of having the `onbuild` variant is if it doesn't actually do anything additional -- can you elaborate on that?

I think more interestingly is that we're switching from `Precompiled.zip` over to compiling from source.  Is there a particular reason for that? (maybe a discussion with or recommendation from upstream you could point to?)

**Comment by c0b** [comment]
it's more effect of carried over from a developing version, when 1.3 was not there, we were doing the master build from source similar like c0b/docker-elixir#12 because there was no pre-compiled version; When it actually came out, somebody made immediate PRs (c0b/docker-elixir#8 c0b/docker-elixir#9 c0b/docker-elixir#10) and I took one of them, didn't realize the switching till today;

but it's good or bad? maybe fine to recompile at docker build time, good to have more votes from upstream; I'll repost

**Comment by edevil** [comment]
I didn't notice the difference as well... I'm not going to be building this package so the extra build time won't affect me. But maybe it would be a good idea to use the precompiled version if available.

**Comment by tuvistavie** [comment]
In a normal dev environment, Elixir should be quite fast to compile (~ 1min on my 4 years old laptop) but I still agree using the precompiled version is probably better, as I don't see any benefits for compiling from source.

**Comment by nathany** [comment]
My vote is for precompiled.

**Comment by tianon** [comment]
Based on the original discussion we had in https://github.com/docker-library/official-images/pull/1398 (which included Elixir upstream), the preference was in favor of precompiled, which is why I brought it up. :smile:

**Pull request closed without merging**
