### PR TITLE
Update ELK images

### PR DESCRIPTION
**Pull request by tianon**
elasticsearch:
- https://github.com/docker-library/elasticsearch/commit/7a4ec49: Update to 7.12.0
- https://github.com/docker-library/elasticsearch/commit/e1bc20d: Update to 6.8.15

logstash:
- https://github.com/docker-library/logstash/commit/5cbbe44: Update to 7.12.0
- https://github.com/docker-library/logstash/commit/3640745: Update to 6.8.15

kibana:
- https://github.com/docker-library/kibana/commit/357513f: Update to 7.12.0
- https://github.com/docker-library/kibana/commit/d6759ae: Update to 6.8.15

### CODE REVIEW

**Comment by tianon** [comment]
Upstream diffs:

- https://github.com/elastic/dockerfiles/compare/v6.8.14...v6.8.15
- https://github.com/elastic/dockerfiles/compare/v7.11.2...v7.12.0

**Comment by tianon** [comment]
@pugnascotia friendly reminder of https://github.com/docker-library/official-images/pull/9758#issuecomment-793838618 :smile:

(It looks like that checked-in compiled binary got updated in this 7.12.0 release instead of removed. :sweat_smile:)

Otherwise, this looks OK to me -- seems we're getting ready for arm64 Kibana too? :smile:
(Or is that included here and we need to update our scripts to account for it?)

**Comment by Conky5** [comment]
> Otherwise, this looks OK to me -- seems we're getting ready for arm64 Kibana too? smile

Yes :smile: 

>  (Or is that included here and we need to update our scripts to account for it?)

No, not yet.

**Comment by pugnascotia** [comment]
@tianon sorry, I haven't forgotten about this but I ended up having to do some refactoring to how we build our contexts and images first.

**Comment by pugnascotia** [comment]
@tianon from 7.13.0 there won't be a binary in the context. It'll still be there in any 7.12 patch releases, I hope that's OK (I was hoping to avoid some thorny backports 😅)

**Comment by tianon** [comment]
Sounds great to me!  I just wanted to make sure it didn't fall off the radar. :smile:

**Pull request merged**
