### PR TITLE
feat: update to CouchDB 3.2.2

### PR DESCRIPTION
**Pull request by janl**
we published a new CouchDB release just now, thanks!

### CODE REVIEW

**Review by big-r81 — COMMENTED** [review]
+1

**Comment by yosifkit** [comment]
It seems that the `3.2.2` Dockerfile still [references `3.2.1-1` ](https://github.com/apache/couchdb-docker/blob/d861e435acb35e191aaacaf12d6c1f148557d8ec/3.2.2/Dockerfile#L57).

**Comment by janl** [comment]
@yosifkit oh duh, thanks for the heads up. It is fixed now on `main` o/

**Comment by yosifkit** [comment]
Just an FYI that this build will be slow since the build queue is very full from the Debian update that was merged yesterday (https://github.com/docker-library/official-images/pull/12257).

**Comment by janl** [comment]
thanks!

**Pull request merged**
