### PR TITLE
version bump: otp-19.1

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by c0b** [comment]
it looks good as I see :+1:; usually @yosifkit will take it in a same work day or next.

**Comment by yosifkit** [comment]
```diff
diff --git a/erlang_latest/Dockerfile b/erlang_latest/Dockerfile
index 017abb1..18ea8c1 100644
--- a/erlang_latest/Dockerfile
+++ b/erlang_latest/Dockerfile
@@ -1,12 +1,12 @@
 FROM buildpack-deps:jessie
 
-ENV OTP_VERSION="19.0.7"
+ENV OTP_VERSION="19.1"
 
 # We'll install the build dependencies for erlang-odbc along with the erlang
 # build process:
 RUN set -xe \
 	&& OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz" \
-	&& OTP_DOWNLOAD_SHA256="584e08c7d810204163247dd2187bfc44175bac60d3e2577a0ea55a6a898c8dce" \
+	&& OTP_DOWNLOAD_SHA256="caf320c07bdd4c6e11831a0b0d25645a29112007077dbf11eec22437f8b041ed" \
 	&& runtimeDeps='libodbc1 \
 			libsctp1' \
 	&& buildDeps='unixodbc-dev \
diff --git a/erlang_onbuild/Dockerfile b/erlang_onbuild/Dockerfile
index c3e568a..739e439 100644
--- a/erlang_onbuild/Dockerfile
+++ b/erlang_onbuild/Dockerfile
@@ -1,4 +1,4 @@
-FROM erlang:19.0
+FROM erlang:19.1
 
 RUN mkdir -p /usr/src/app
 WORKDIR /usr/src/app
diff --git a/erlang_slim/Dockerfile b/erlang_slim/Dockerfile
index 2a41bbe..55b7db3 100644
--- a/erlang_slim/Dockerfile
+++ b/erlang_slim/Dockerfile
@@ -1,12 +1,12 @@
 FROM debian:jessie
 
-ENV OTP_VERSION="19.0.7"
+ENV OTP_VERSION="19.1"
 
 # We'll install the build dependencies, and purge them on the last step to make
 # sure our final image contains only what we've just built:
 RUN set -xe \
 	&& OTP_DOWNLOAD_URL="https://github.com/erlang/otp/archive/OTP-${OTP_VERSION}.tar.gz" \
-	&& OTP_DOWNLOAD_SHA256="584e08c7d810204163247dd2187bfc44175bac60d3e2577a0ea55a6a898c8dce" \
+	&& OTP_DOWNLOAD_SHA256="caf320c07bdd4c6e11831a0b0d25645a29112007077dbf11eec22437f8b041ed" \
 	&& runtimeDeps=' \
 		libodbc1 \
 		libssl1.0.0 \
```

Build test in progress :smile:

**Comment by aaronjensen** [comment]
Thanks for the quick merge @yosifkit! About how long does it take to show up on docker hub?

**Comment by yosifkit** [comment]
Should be very shortly.  We've built and pushed them; they are in Docker's signing and scanning queue.

**Pull request merged**
