### PR TITLE
Update photon image

### PR DESCRIPTION
**Pull request by gerrit-photon**
Update photon image

### CODE REVIEW

**Comment by tianon** [comment]
Are `curl` and all those `ca-certificates` files being added to the base image intentionally?

**Comment by yosifkit** [comment]
Friendly ping: @YustasSwamp or @frapposelli

> Are `curl` and all those `ca-certificates` files being added to the base image intentionally?

**Comment by frapposelli** [comment]
I believe it was intentional but I'll let @YustasSwamp reply as I'm no longer in charge of the photon image.

**Comment by YustasSwamp** [comment]
Hi @yosifkit and @tianon. Thanks for the attention to these extra files.

There was a regression, where curl and certs were removed from photon docker image accidentally:
https://github.com/docker-library/official-images/pull/10399
Tags photon:3.0-20210621 and photon:3.0-20210625 are affected by this regression.

Curl binaries and certificates are supposed to be in the image.
We intentionally restored it back by:
https://github.com/vmware/photon/commit/591c9847dffb25b62aae9f0521f9ca5436dda25d

Thanks!

**Pull request merged**
