### PR TITLE
Convert "bashbrew" to Go and add a new RFC 2822 manifest file format

### PR DESCRIPTION
**Pull request by tianon**
To satisfy both Windows (https://github.com/docker-library/golang/pull/92) building and "non-AUFS" (https://github.com/docker-library/official-images/pull/1612, https://github.com/docker-library/official-images/pull/1537) building ("build machine" constraints, if you will), an update to the manifest file format is necessary.

To this end, we're introducing a new format which uses RFC 2822, allowing much more expressivity (especially for additional metadata like `Constraints`) and readability.  The new tool also includes backwards compatibility for the older line-based manifest file format, but its usage is discouraged (and we will be slowly converting at least the `docker-library` repos to use the new format in their `generate-stackbrew-library.sh` scripts).

One of the tangential benefits of this conversion is a massive increase in the speed of the tool (`bashbrew list --all` on a very fast system with an SSD and a flaming hot cache used to take ~5s and now takes ~0.012s).

Closes #1612

### CODE REVIEW

**Comment by tianon** [comment]
Massive shout-out to @paultag for writing several useful Go libraries that were really useful for building this (RFC 2822 parser and topological sorter). :+1:

**Comment by paultag** [comment]
:us: happy to do my part! Awesome change, speedups look huge!

**Comment by tianon** [comment]
@flavio @cyphar: this includes an update to `library/opensuse`:
```
Maintainers: Flavio Castelli <fcastelli@suse.com> (@flavio)
GitRepo: https://github.com/openSUSE/docker-containers-build.git
Directory: docker
Constraints: !aufs

Tags: 13.2, harlequin
GitFetch: refs/heads/openSUSE-13.1
GitCommit: 0d21bc58cd26da2a0a59588affc506b977d6a846

Tags: 42.1, leap, latest
GitFetch: refs/heads/openSUSE-42.1
GitCommit: d529ec4ff604e41997fd98b6ade9715ab20cf75c

Tags: tumbleweed
GitFetch: refs/heads/openSUSE-Tumbleweed
GitCommit: c87d6edb440b0165c07f3e3f474f0effd6f5ba8d
```

**Comment by tianon** [comment]
@maxamillion @puiterwijk: this includes an update to `library/fedora`:
```
Maintainers: Adam Miller <maxamillion@fedoraproject.org> (@maxamillion),
             Patrick Uiterwijk <puiterwijk@gmail.com> (@puiterwijk)
GitRepo: https://github.com/fedora-cloud/docker-brew-fedora.git
Constraints: !aufs

Tags: latest, 23
GitFetch: refs/heads/23
GitCommit: 3677613e2c32eea7f6dc4d5e9a297b7e7f73dc6e

Tags: 22
GitFetch: refs/heads/22
GitCommit: bccd42bf4e9102ef10eff372488167948fdd0430

Tags: 21
GitFetch: refs/heads/21
GitCommit: e32493b9601c3535cd6e0d0a8ff61d8fa95afb83

Tags: rawhide
GitFetch: refs/heads/rawhide
GitCommit: d28b4d3e1c4d613a12701557b0d686c28490af69

Tags: 20, heisenbug
GitFetch: refs/heads/20
GitCommit: 10ada29063147fde9e39190f4c2344b6e6e659e6
```

**Comment by tianon** [comment]
Here's a fun example of why `bashbrew cat` has a `-f` flag:
```diff
diff --git a/.template-helpers/generate-dockerfile-links-partial.sh b/.template-helpers/generate-dockerfile-links-partial.sh
index f081a58..7bb5347 100755
--- a/.template-helpers/generate-dockerfile-links-partial.sh
+++ b/.template-helpers/generate-dockerfile-links-partial.sh
@@ -8,67 +8,31 @@ if [ -z "$repo" ]; then
 	exit 1
 fi
 
-IFS=$'\n'
-lines=( $(curl -fsSL 'https://raw.githubusercontent.com/docker-library/official-images/master/library/'"$repo" | grep -vE '^$|^#') )
-unset IFS
-
-if [ "${#lines[@]}" -eq 0 ]; then
-	echo >&2 "Failed to read manifest file for $repo"
-	exit 1
-fi
-
-repoDirs=()
-declare -A repoDirTags=()
-
-latest=
-uniqImages=()
-for line in "${lines[@]}"; do
-	tag="$(echo "$line" | awk -F ': +' '{ print $1 }')"
-	if [ -z "$latest" -o "$tag" = 'latest' ]; then
-		latest="$tag"
-	fi
-	repoDir="$(echo "$line" | awk -F ': +' '{ print $2 }')"
-	if [ -z "${repoDirTags[$repoDir]}" ]; then
-		repoDirs+=( "$repoDir" )
-		uniqImages+=( "$repo:$tag" )
-	else
-		repoDirTags["$repoDir"]+=', '
-	fi
-	repoDirTags["$repoDir"]+='`'"$tag"'`'
-done
-
-IFS=','
-imageLayers="https://imagelayers.io/?images=${uniqImages[*]}"
-unset IFS
-
-for repoDir in "${repoDirs[@]}"; do
-	if [[ "$repoDir" != *github.com* ]]; then
-		# skip non-github.com for now
-		continue
-	fi
-	
-	# split out some data
-	gitUrl="${repoDir%%@*}"
-	commitDir="${repoDir#*@}"
-	commit="${commitDir%% *}"
-	dir="${commitDir#* }"
-	if [ "$dir" = "$commitDir" ]; then
-		dir=''
-	fi
-	
-	# sanitize some data
-	gitUrl="${gitUrl#git://}"
-	gitUrl="${gitUrl%/}"
-	gitUrl="${gitUrl%.git}"
-	dir="${dir#/}"
-	dir="${dir%/}"
-	[ -z "$dir" ] || dir="$dir/"
-	
-	url="https://$gitUrl/blob/$commit/${dir}Dockerfile"
-	
-	echo $'-\t['"${repoDirTags["$repoDir"]}"' (*'"${dir}Dockerfile"'*)]('"$url"')'
-done
-
-echo
-echo "[![](https://badge.imagelayers.io/$repo:$latest.svg)]($imageLayers)"
-echo
+bashbrew cat -f '
+	{{- range $i, $e := .Entries -}}
+		{{- $from := $.DockerFrom $e -}}
+		{{- if $i -}}
+			{{- "\n" -}}
+		{{- end -}}
+		- {{- "\t" -}}
+			[`{{- join $e.Tags "`, `" -}}` (*{{if ne $e.Directory "."}}{{$e.Directory}}/{{end}}Dockerfile*)]({{$e.GitRepo}}/blob/{{$e.GitCommit}}/{{$e.Directory}}/Dockerfile)
+	{{- end -}}
+	{{- "\n\n" -}}
+	[![](https://badge.imagelayers.io/
+	{{- .RepoName}}:
+	{{- if .Manifest.GetTag "latest" -}}
+		latest
+	{{- else -}}
+		{{- index (index .Entries 0).Tags 0 -}}
+	{{- end -}}
+	.svg)](https://imagelayers.io/?images=
+	{{- range $i, $e := .Entries -}}
+		{{- if $i}},{{end -}}
+		{{- $.RepoName}}:{{index $e.Tags 0 -}}
+	{{- end -}}
+	)
+' "https://github.com/docker-library/official-images/raw/master/library/$repo" \
+	| (grep -E '//github.com/|^$|//imagelayers.io/' || true) \
+	| sed -r \
+		-e 's![a-z]+://!https://!g' \
+		-e 's![.]git/!/!g'
```

**Comment by cyphar** [comment]
@tianon Thanks. Can you also answer a question about automated updates of `library/opensuse`? We currently use OBS and Jenkins to create new images at regular intervals (as well as when we detect pending security updates using `zypper-docker`). Is there a way for us to auto-submit changes without having to create a bot that auto-creates pull requests?

**Comment by md5** [comment]
Nice work @tianon!

I'm curious whether you considered having the source code live outside the `docker-library/official-images` repository (e.g. in `docker-library/bashbrew`).

I haven't had a chance to play with this too much yet, but it would be cool if `bashbrew cat` could take another flag (perhaps `-F`) that lets the template be in a file instead of passed directly as a string.

**Comment by tianon** [comment]
@cyphar afraid not :disappointed:

However, depending on the planned frequency of bumps, I'm willing to add the following script to my own local checkout and make the actual bump PRs based on the repo contents for you on a periodic basis (or on request/as-needed). :+1:

```bash
#!/bin/bash
set -e

repo='https://github.com/openSUSE/docker-containers-build.git'

cat <<-EOH
	Maintainers: Flavio Castelli <fcastelli@suse.com> (@flavio),
	             Aleksa Sarai <asarai@suse.de> (@cyphar)
	GitRepo: $repo
	Directory: docker
	Constraints: !aufs
EOH

func() {
	local ref="$1"
	local tags="$2"
	cat <<-EOE
		
		Tags: $tags
		GitFetch: $ref
		GitCommit: $(git ls-remote "$repo" "$ref" | cut -d$'\t' -f1)
	EOE
}

func refs/heads/openSUSE-42.1 '42.1, leap, latest'
func refs/heads/openSUSE-13.1 '13.2, harlequin'
func refs/heads/openSUSE-Tumbleweed 'tumbleweed'
```

Which currently outputs:
```
Maintainers: Flavio Castelli <fcastelli@suse.com> (@flavio),
             Aleksa Sarai <asarai@suse.de> (@cyphar)
GitRepo: https://github.com/openSUSE/docker-containers-build.git
Directory: docker
Constraints: !aufs

Tags: 42.1, leap, latest
GitFetch: refs/heads/openSUSE-42.1
GitCommit: d529ec4ff604e41997fd98b6ade9715ab20cf75c

Tags: 13.2, harlequin
GitFetch: refs/heads/openSUSE-13.1
GitCommit: 0d21bc58cd26da2a0a59588affc506b977d6a846

Tags: tumbleweed
GitFetch: refs/heads/openSUSE-Tumbleweed
GitCommit: c87d6edb440b0165c07f3e3f474f0effd6f5ba8d
```

**Comment by tianon** [comment]
@md5 yeah, @yosifkit and I discussed doing that for a bit (it has some nice properties like being able to actually create versioned releases and push out binaries for use), but decided that for now, we should keep them together and reconsider splitting it out entirely as a separate discussion :+1:

Regarding `-F`, I think that's a fabulous idea, and I'm going to go implement it. :smile:

**Comment by md5** [comment]
@tianon On second thought, `-t`/`--template` might be a better flag than `-F` to avoid any possible confusion with `-f`/`--format`.

**Comment by tianon** [comment]
I was thinking `--format-file`/`-F`, especially since it explicitly overrides `--format` (so the parallel felt appropriate)

**Comment by tianon** [comment]
Thanks to @md5, the example I pasted above is now way better (and more fun to edit, since vim-go has highlighting for `.tmpl` files):
```bash
#!/bin/bash
set -eo pipefail

repo="$1"
if [ -z "$repo" ]; then
	echo >&2 "usage: $0 repo"
	echo >&2 "   ie: $0 hylang"
	exit 1
fi

bashbrew cat \
		-F "$(dirname "$BASH_SOURCE")/$(basename "$BASH_SOURCE" .sh).tmpl" \
		"https://github.com/docker-library/official-images/raw/master/library/$repo"
```
```tmpl
{{- /*

This template defines the "Supported tags and Dockerfile links" portion of an image description.

*/ -}}

{{- define "dockerfilePath" -}}
	{{- if ne .Directory "." -}}
		{{- .Directory -}}
		/
	{{- end -}}
	Dockerfile
{{- end -}}

{{- range $i, $e := $.Entries -}}
	{{- /* force bashbrew to "fetch" the GitCommit so that it is fully resolved */ -}}
	{{- $from := $.DockerFrom $e -}}

	{{- $repoUrlBase := concat "https://" (trimPrefix (trimSuffix (trimPrefix $e.GitRepo "git://") ".git") "https://") -}}
	{{- $isGitHub := hasPrefix $repoUrlBase "https://github.com/" -}}

	{{- if $i -}}
		{{- "\n" -}}
	{{- end -}}

	- {{- "\t" -}}
	{{- if $isGitHub -}} [ {{- end -}}
	` {{- join $e.Tags "`, `" -}} ` (* {{- template "dockerfilePath" $e -}} *)
	{{- if $isGitHub -}} ]( {{- $repoUrlBase -}} /blob/ {{- $e.GitCommit -}} / {{- template "dockerfilePath" $e -}} ) {{- end -}}
	{{- /* TODO decide what to do (if anything) about non-GitHub repos with respect to URL */ -}}
{{- end -}}

{{- "\n\n" -}}

[![](https://badge.imagelayers.io/
{{- /* either "repo:latest" or "repo:first-tag" */ -}}
{{- .RepoName -}} : {{- if .Manifest.GetTag "latest" -}} latest {{- else -}} {{- index (index .Entries 0).Tags 0 -}} {{- end -}}
.svg)](https://imagelayers.io/?images=
{{- /* list all "repo:tag" combinations, comma separated */ -}}
{{- range $i, $e := $.Entries -}}
	{{- if $i -}} , {{- end -}}
	{{- $.RepoName -}} : {{- index $e.Tags 0 -}}
{{- end -}}
)

{{- "\n\n" -}}
```

**Comment by flavio** [comment]
> However, depending on the planned frequency of bumps, I'm willing to add the following script to my own local checkout and make the actual bump PRs based on the repo contents for you on a periodic basis (or on request/as-needed). :+1:

That would be fantastic!

**Comment by tianon** [comment]
Ok @yosifkit, I think I'm happy with where this is at now. :+1: :pray:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
