### PR TITLE
Update clojure tools-deps to 1.10.3.833

### PR DESCRIPTION
**Pull request by cap10morgan**
Upstream release

### CODE REVIEW

**Comment by tekacs** [comment]
After this update, it appears that `clj` no longer executes in the container:

```clojure
~> docker run --rm -it clojure:openjdk-11-tools-deps bash
root@31e78425c7f3:/tmp# clj
rlwrap: error: Cannot execute /usr/local/lib/clojure/bin/clojure: No such file or directory 
```

I've found this to be the case on multiple systems.

**Comment by yosifkit** [comment]
Turns out the installer has a bug:
>1.10.3.839 (May 12, 2021)
> - Fix Linux installer breakage in 1.10.3.833
>
> \- https://clojure.org/releases/tools#v1.10.3.839

**Comment by cap10morgan** [comment]
I’ll get an update PR up shortly

**Comment by cap10morgan** [comment]
New PR: https://github.com/docker-library/official-images/pull/10186

**Pull request merged**
