### PR TITLE
Update mediawiki to 1.35.1 and 1.31.12

### PR DESCRIPTION
**Pull request by pesc**
Update Mediawiki to the latest releases:
https://lists.wikimedia.org/pipermail/mediawiki-announce/2020-December/000268.html
https://lists.wikimedia.org/pipermail/mediawiki-announce/2020-December/000269.html﻿

Closes wikimedia/mediawiki-docker#89

### CODE REVIEW

**Comment by davidbarratt** [comment]
@pesc looks like `1.31` has to have it's base upgraded.

**Comment by pesc** [comment]
> @pesc looks like `1.31` has to have it's base upgraded.

What do you mean? Because PHP 7.2 got removed?

**Comment by pesc** [comment]
@davidbarratt it seems fine now...

**Comment by davidbarratt** [comment]
I don't have permission to this repo, but looks good to me!

**Pull request merged**
