### PR TITLE
Remove all tags of CentOS (now fully EOL)

### PR DESCRIPTION
**Pull request by tianon**
https://www.redhat.com/en/topics/linux/centos-linux-eol

### CODE REVIEW

**Comment by tianon** [comment]
FYI affected maintainers for the CentOS EOL/removal:

- `eclipse-temurin`: @gdams @sxa
- `ibm-semeru-runtimes`: @jayasg12
- `percona`: @EvgeniyPatlan @hors @vorsel @adivinho @surbhat1595
- `swift`: @tkremenek @shahmishal @tomerd @hamin @swizzlr

Please either drop the affected tags from the supported list (by removing them from your `library/` file) or update them to a supported release.

(Also, if you're not supposed to be in this list, or you're getting this forwarded to you and you *are* supposed to be in this list, please update the `Maintainers:` section of the relevant `library/` file appropriately! :sweat_smile:)

**Comment by tianon** [comment]
(See also https://github.com/docker-library/official-images/issues/11679 and https://github.com/docker-library/docs/pull/2205 -- namely, this image hasn't actually been maintained for a _long_ time now, but the upstream distro is now explicitly EOL.)

**Review by yosifkit — APPROVED** [review]

**Comment by tianon** [comment]
Hmm, looking at the deprecation notice, we should probably make some slight tweaks for the new "fully EOL" state.

**Comment by gdams** [comment]
> FYI affected maintainers for the CentOS EOL/removal:
> 
> * `eclipse-temurin`: @gdams @sxa
> * `ibm-semeru-runtimes`: @jayasg12
> * `percona`: @EvgeniyPatlan @hors @vorsel @adivinho @surbhat1595
> * `swift`: @tkremenek @shahmishal @tomerd @hamin @swizzlr
> 
> Please either drop the affected tags from the supported list (by removing them from your `library/` file) or update them to a supported release.
> 
> (Also, if you're not supposed to be in this list, or you're getting this forwarded to you and you _are_ supposed to be in this list, please update the `Maintainers:` section of the relevant `library/` file appropriately! 😅)

Thanks for the heads up! I would refer back to my original ask here https://github.com/docker-library/official-images/issues/12587. This would be very useful for maintainers to have better insights

**Comment by hron84** [comment]
I am very confused. You talking about removing all tags on CentOS image, however the linked documentation talks about just CentOS 7, as it says on the very beginning (even at Dec 2025, one year later of the issue was closed):

> CentOS Linux 7 reached end of life (EOL) on June 30, 2024. This article will cover what that means, how you can prepare, and how Red Hat can help ease your migration.

This sentence reads me CentOS Linux 7 reached end of life and not the entire distribution. And literally no one mentioned it on this ticket. I am ever doubting if anyone bothered to read the linked documentation.

This communication both from Docker and RedHat side is misleading to people coming from the DockerHub page of the image to this issue and not being able to find answers or solutions. 

I think I am not requesting too much considering how popular CentOS is/was and how essential could be this **official** base image. Also, on the DockerHub page of the project, there is no actual direction what could be a recommended replacement for this image which could be also an essential for deprecating an **official** Docker image from my opinion.

What I ask for is a consistent and helpful communication about this deprecation and a read-through of a page you refer to as a base information. At least in the case if you still value your community.

**Comment by sxa** [comment]
> This sentence reads me CentOS Linux 7 reached end of life and not the entire distribution.

CentOS7 was the last version that was still supported so it's not (IMHO) misleading to say that the whole CentOS distribution is now EOL. [CentOS8 was already made EOL in 2021](https://www.centos.org/centos-linux-eol/). No later versions were produced.

CentOS Stream is the currently maintained distribution from the project as indicated in the redhat.com article:

> In 2020, The CentOS Project, in coordination with Red Hat, announced that it would shift full investment to CentOS Stream,

**Comment by tianon** [comment]
Sorry yes, to be more clear/explicit: CentOS is fully EOL within the Docker Official Images program (where previously it was only CentOS > 7 which was, because Stream never made it here).  Additionally, even though it was "supported", it was not receiving image updates, so it wasn't really even accurate to say it was supported.

**Comment by hron84** [comment]
Ahh, I understand now, it was a bit confusing to me understanding what CentOS Stream is, as I am not using these CentOS images on everyday manner, just maintaining a handful of (very important) images inside our company to provide ability to build and sign RPM packages.

**Comment by davidof120** [comment]
wsl.exe --list --online

**Pull request merged**
