### PR TITLE
maven: JDK 23

### PR DESCRIPTION
**Pull request by carlossg**

### CODE REVIEW

**Comment by patpatpat123** [comment]
Thank you Carlos for this

**Comment by tianon** [comment]
Not a blocker, and I plan to merge in a moment in spite of it (because it'll be a trivial follow-up if it's an issue), but this discrepancy in the list of packages installed between these different Alpine variants is expected/intentional, right?

```diff
-FROM eclipse-temurin:8-jdk-alpine
+FROM amazoncorretto:17-alpine
 
-RUN apk add --no-cache bash procps curl tar openssh-client
+RUN apk add --no-cache bash openssh-client
```

**Review by tianon — APPROVED** [review]

**Comment by carlossg** [comment]
> Not a blocker, and I plan to merge in a moment in spite of it (because it'll be a trivial follow-up if it's an issue), but this discrepancy in the list of packages installed between these different Alpine variants is expected/intentional, right?

thanks for checking, yes it is fine, different distros have different packages for backwards compatibility

**Comment by tianon** [comment]
FYI, JDK 23 is now EOL, so these should all be removed again :sweat_smile:

**Pull request merged**
