### PR TITLE
Release of GeoNetwork 4.0.0-alpha.2

### PR DESCRIPTION
**Pull request by juanluisrp**
Release of GeoNetwork 4.0.0-alpha.2
https://github.com/geonetwork/docker-geonetwork/pull/53

### CODE REVIEW

**Comment by yosifkit** [comment]
You definitely still need `exec` to apply to the resident server process so that the shell doesn't stay resident.

```diff
-  java $JAVA_OPTIONS -jar /usr/local/jetty/start.jar
+  exec java $JAVA_OPTIONS -jar /usr/local/jetty/start.jar
```

Also, the change from `JAVA_OPTS` to `JAVA_OPTIONS` might cause some user problems on upgrade if they are overriding it?

**Comment by juanluisrp** [comment]
For these new versions we have switched from Tomcat to Jetty. The option for settings JVM options in Jetty based images is to use `JAVA_OPTIONS`. 
What have other projects in this case?
Should we keep `JAVA_OPTS` and assign its value to `JAVA_OPTIONS` in the entrypoint?

**Comment by yosifkit** [comment]
> For these new versions we have switched from Tomcat to Jetty. The option for settings JVM options in Jetty based images is to use `JAVA_OPTIONS`.
> What have other projects in this case?
> Should we keep `JAVA_OPTS` and assign its value to `JAVA_OPTIONS` in the entrypoint?

You can use whichever variable you want, I was just concerned for breaking users.  On the other hand, I don't see a need to use/support the one from jetty, since you aren't using their scripts.

**Comment by tianon** [comment]
(IMO, it seems a little odd to be `FROM jetty` at all if you're not going to use their scripts :sweat_smile:)

**Comment by juanluisrp** [comment]
> (IMO, it seems a little odd to be `FROM jetty` at all if you're not going to use their scripts 😅)

We could install Jetty ourselves but I would like to get the image rebuilt when base Jetty image is updated.

**Comment by yosifkit** [comment]
closing in favor of https://github.com/docker-library/official-images/pull/8969

**Pull request closed without merging**
