### PR TITLE
add trickster

### PR DESCRIPTION
**Pull request by jranson**
The Trickster team at Comcast is very pleased to submit Trickster to the Docker Official Images library. Trickster is used and contributed to by users all around the globe at places like Adobe, DigitalOcean, InfluxDB, Hostinger, GitLab and beyond.

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream?
    - I am the creator and primary maintainer of Trickster
-	[x] does it fit into one of the common categories? ("**service**", "language stack", "base distribution")
    - Trickster is an HTTP proxy service that fronts prometheus, influxdb, a static website, etc.
-	[x] is it reasonably popular, or does it solve a particular use case well?
    - Trickster has just crossed 900K downloads on Docker Hub (and accelerating) in under 2 years of availability, and is widely used throughout the technology industry. Also, we bought some stickers on sticker mule.
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/pull/1755
-	[ ] official-images maintainer dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ official-images maintainer dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by jranson** [comment]
Hi folks, it looks like one of the tests has timed out, and there is not a lot of info as to why in the github actions log, so I am not sure if I need to do anything to assist. Thanks for any assistance!

**Comment by tianon** [comment]
I haven't taken a look at the `Dockerfile`/Dockerization yet, but that usually means an issue with `ENTRYPOINT` (https://github.com/docker-library/official-images#consistency), since it looks like it's hanging in the `override-cmd` test.

**Comment by tianon** [comment]
Friendly ping -- is this still something you're interested in pursuing? :pray:

**Comment by yosifkit** [comment]
Closing given absence of activity. We apologize for the delays with our responses. :bowing_man: Not to excuse our slow or missing replies, we often have to prioritize maintaining the current images over adding new images. Thanks for your contribution.

If you'd still like to propose a new image, let us know here and we'll try to help it move along. If you've since moved on to other endeavors, we wish you the best. :heart:

**Pull request closed without merging**
