### PR TITLE
chore: remove powersj as maintainer

### PR DESCRIPTION
**Pull request by powersj**
Thanks for the help over the past few years! I am moving on from InfluxData so I am removing myself as a maintainer.

### CODE REVIEW

**Review by yosifkit — APPROVED** [review]
Thanks! And enjoy your future endeavors.

**Comment by tianon** [comment]
With apologies to powersj for the notification, looks like we're due for some image updates. :bow: :heart:

- https://github.com/influxdata/influxdata-docker/issues/782

**Comment by powersj** [comment]
@tianon thanks for the nudge, I've pinged @srebhan privately to figure out who the right person is.

**Comment by tianon** [comment]
Going above and beyond; we appreciate it, @powersj :heart:

**Pull request merged**
