### PR TITLE
Update for jetty repo move

### PR DESCRIPTION
**Pull request by md5**

### CODE REVIEW

**Comment by md5** [comment]
It looks like Travis is trying to use `Dockerfile` in the directory root instead of in the specified directory. I can't see what the issue here is...

**Comment by md5** [comment]
The file had extra `\r` characters in it... https://github.com/docker/docker/issues/8513 strikes again!

**Comment by md5** [comment]
I opened a PR to make bashbrew be less chokey about `CR` characters: https://github.com/docker-library/official-images/pull/645

**Comment by tianon** [comment]
LGTM

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
