### PR TITLE
Remove dangling children of Debian Buster

### PR DESCRIPTION
**Pull request by tianon**
Debian Buster is EOL, and as such these images need to be either upated or removed (they are not receiving meaningful rebuilds anymore).

(see https://github.com/docker-library/official-images/pull/17091#issuecomment-2201099734)

I'm happy to accept these back if they are updated with a suitably supported base image.

### CODE REVIEW

**Comment by tianon** [comment]
Also FYI @getong (`erlang`, `elixir`)

**Review by whalelines — APPROVED** [review]
LGTM

**Review by yosifkit — APPROVED** [review]

**Comment by yarikoptic** [comment]
Is there some effort to archive such older/EOLed images?
For the use cases of "reproducible science" it might be desired/critical to be able to access such old bases.

**Comment by tianon** [comment]
Oh sorry, I should've included my standard blurb!

> Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by yarikoptic** [comment]
oh, thanks!  I will to remember!

**Pull request merged**
