### PR TITLE
Update amazoncorretto maintainers

### PR DESCRIPTION
**Pull request by rgithubli**
Add new corretto team member into maintainer list.

### CODE REVIEW

**Comment by rgithubli** [comment]
It seems one of the test builds complained deprecated alpine 3.17 is in use: https://github.com/docker-library/official-images/actions/runs/12320281298/job/34389187124?pr=18094.

We have a separate task to deprecate alpine 3.17. Actually @minschoi that's added as a new maintainer in this change is working on it. Should we first deprecate alpine 3.17 before any changes can go through in this repo, or it's fine to let this administrative change pass?

**Review by yosifkit — DISMISSED** [review]

**Comment by yosifkit** [comment]
This is fine when just adjusting the maintainer list 👍

**Comment by yosifkit** [comment]
Also, welcome to the new maintainers!
Daniel Hu (@costmuch), 
Michael De Vera (@mldevera),
Min Choi (@minschoi),
Satyen Subramaniam (@satyenme)

(it looks like maybe Michael's GitHub handle might be misspelled or not created yet?)

**Comment by lutkerd** [comment]
Michael should be @midver

**Comment by mmm-choi** [comment]
Hi, sorry my GitHub is @mmm-choi

**Comment by rgithubli** [comment]
Sorry. Messed up with the github alias. Fixed at here: https://github.com/docker-library/official-images/pull/18094/commits/3dd5e31d0346b594e7b51f03cdecb0affccddea1.

**Review by yosifkit — APPROVED** [review]

**Comment by yosifkit** [comment]
Thanks everyone and welcome!

**Pull request merged**
