### PR TITLE
[8.13.2] Update ELK images

### PR DESCRIPTION
**Pull request by navyau09**
Update elk images

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@navyau09  there is still the issue that using the `arch` commands gives the kernel architecture and not the container. It should be switched to using `dpkg --print-architecture` or `apk --print-arch`. As mentioned here: https://github.com/docker-library/official-images/pull/16520#issuecomment-2043738623

**Comment by navyau09** [comment]
@LaurentGoderre Could you please verify again, if this looks good?

**Review by LaurentGoderre — APPROVED** [review]

**Comment by LaurentGoderre** [comment]
Can we close #16697 in favor of this?

**Comment by tianon** [comment]
This is good for now, but please do revisit https://github.com/elastic/logstash/pull/16063#discussion_r1577000627 (adding at the very least `set -e` to all semi-colon-using `RUN` lines, if not the full `set -eux` I suggest there).

**Comment by tianon** [comment]
```diff
-RUN \
- curl -Lo - https://artifacts.elastic.co/downloads/logstash/logstash-8.13.0-linux-$(arch).tar.gz | \
+RUN curl -Lo - https://artifacts.elastic.co/downloads/logstash/logstash-8.13.3-linux-$(arch).tar.gz | \
```

Wait a minute, this is 8.13.3 but the tags are 8.13.2 - I think that's a mistake?

(We should also apply the same "avoiding `arch` in favor of querying the image userspace environment" logic to these lines, but they're pre-existing usage so I feel less strongly about enforcing that for now.)

**Comment by LaurentGoderre** [comment]
Good catch @tianon . It seems only logstash got the bump.

**Pull request closed without merging**
