### PR TITLE
Add Swift 3.1.1

### PR DESCRIPTION
**Pull request by rymcol**
Adds Hash for Swift 3.1.1 Support

### CODE REVIEW

**Comment by tianon** [comment]
:disappointed: 

<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 225660c..4a9ae06 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,3 +1,4 @@
 swift:3 @ amd64
 swift:3.0 @ amd64
+swift:3.1 @ amd64
 swift:latest @ amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index b3d1f05..5788d32 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -3,6 +3,7 @@ swift:3.0
 swift:3.0.2
 swift:3.1
 swift:3.1.0
+swift:3.1.1
 swift:4
 swift:4.0
 swift:latest
diff --git a/swift_3/Dockerfile b/swift_3.1/Dockerfile
similarity index 100%
copy from swift_3/Dockerfile
copy to swift_3.1/Dockerfile
diff --git a/swift_3/Dockerfile b/swift_3/Dockerfile
index 464c7b7..3389e6f 100644
--- a/swift_3/Dockerfile
+++ b/swift_3/Dockerfile
@@ -6,7 +6,7 @@ RUN apt-get -q update && \
     apt-get -q install -y \
     make \
     libc6-dev \
-    clang-3.6 \
+    clang-3.8 \
     curl \
     libedit-dev \
     python2.7 \
@@ -17,14 +17,14 @@ RUN apt-get -q update && \
     git \
     libcurl4-openssl-dev \
     pkg-config \
-    && update-alternatives --quiet --install /usr/bin/clang clang /usr/bin/clang-3.6 100 \
-    && update-alternatives --quiet --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 100 \
+    && update-alternatives --quiet --install /usr/bin/clang clang /usr/bin/clang-3.8 100 \
+    && update-alternatives --quiet --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100 \
     && rm -r /var/lib/apt/lists/*
 
 # Everything up to here should cache nicely between Swift versions, assuming dev dependencies change little
 ARG SWIFT_PLATFORM=ubuntu16.04
-ARG SWIFT_BRANCH=swift-3.1-release
-ARG SWIFT_VERSION=swift-3.1-RELEASE
+ARG SWIFT_BRANCH=swift-3.1.1-release
+ARG SWIFT_VERSION=swift-3.1.1-RELEASE
 
 ENV SWIFT_PLATFORM=$SWIFT_PLATFORM \
     SWIFT_BRANCH=$SWIFT_BRANCH \
@@ -56,5 +56,9 @@ RUN SWIFT_URL=https://swift.org/builds/$SWIFT_BRANCH/$(echo "$SWIFT_PLATFORM" |
     && tar -xzf swift.tar.gz --directory / --strip-components=1 \
     && rm -r "$GNUPGHOME" swift.tar.gz.sig swift.tar.gz
 
+# Post cleanup for binaries orthogonal to swift runtime, but was used to download and install. 
+RUN apt-get -y remove --purge \ 
+    python2.7
+
 # Print Installed Swift Version
 RUN swift --version
````

</details>

**Comment by yosifkit** [comment]
Seems this one got lost. I think @tianon was trying to point out the same issue as the previous PR: https://github.com/docker-library/official-images/pull/3485#issuecomment-331935914. So, a similar fix as https://github.com/swiftdocker/docker-swift/pull/84 to drop the `--purge  python2.7` run line.

**Comment by rymcol** [comment]
I think we now have Swift 4.0.2 to deal with as well, so we should probably update that too before we proceed

cc: @lgaches

**Comment by yosifkit** [comment]
Looks like this was superseded by https://github.com/docker-library/official-images/pull/3693.

**Pull request closed without merging**
