### PR TITLE
Update "no-root-password" to test all users

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
I wonder if we should relax the "locked" restriction too, since "locked" is generally OK (and anyone "unlocking" will likely be changing the password, not just unlocking).

**Comment by tianon** [comment]
(It's already just a warning for that reason, but I'm wondering if even the warning is warranted.)

**Comment by tianon** [comment]
Example:
```console
$ bashbrew list --uniq centos | xargs ./test/run.sh -t no-hard-coded-passwords
testing centos:latest
	'no-hard-coded-passwords' [1/1]...error: crypt password detected for 'root': '$1$UKLtvLuY$kka6S665oCFmU7ivSDZzU.'
failed
testing centos:centos6
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'vcsa': '!!'
warning: locked password detected for 'root': '!!$6$tXwgMDTb$13.6vsXO0Do0/lTNBc8leO5BqzTRspVNfB3qAnhHTztu7UYFJiqA/KfbYQmLcbUs9JFdL6S3THSJNoz7L6gEg1'
passed
testing centos:centos5
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'vcsa': '!!'
warning: locked password detected for 'root': '!!$1$9OTGZASO$LQZppGKFwHHQU3l7v8qrm/'
passed
testing centos:centos7.1.1503
	'no-hard-coded-passwords' [1/1]...error: crypt password detected for 'root': '$1$UKLtvLuY$kka6S665oCFmU7ivSDZzU.'
failed
testing centos:centos7.0.1406
	'no-hard-coded-passwords' [1/1]...error: crypt password detected for 'root': '$1$UKLtvLuY$kka6S665oCFmU7ivSDZzU.'
failed
testing centos:centos6.6
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'vcsa': '!!'
warning: locked password detected for 'root': '!!$6$Bj6gWbwf$T/i4LnqdnzwbnBXSDExUNhDGiZ0fnrvXoKoywrao322ianPjatAR1Vz0cPjHEo3rOv9FN6FMmsCcwaDRdkr7Z.'
passed
testing centos:centos5.11
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'vcsa': '!!'
warning: locked password detected for 'root': '!!$1$n81CmQ4b$ZclidDChoxQmcPBt49NLW.'
passed
```

**Comment by tianon** [comment]
Example:
```console
$ bashbrew list --uniq fedora | xargs ./test/run.sh -t no-hard-coded-passwords
testing fedora:latest
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'systemd-resolve': '!!'
warning: locked password detected for 'systemd-network': '!!'
warning: locked password detected for 'dbus': '!!'
warning: garbage password detected for 'root': 'locked'
warning: locked password detected for 'systemd-bus-proxy': '!!'
warning: locked password detected for 'systemd-timesync': '!!'
passed
testing fedora:21
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'systemd-resolve': '!!'
warning: locked password detected for 'systemd-network': '!!'
warning: locked password detected for 'dbus': '!!'
warning: garbage password detected for 'root': 'locked'
warning: locked password detected for 'systemd-bus-proxy': '!!'
warning: locked password detected for 'systemd-timesync': '!!'
passed
testing fedora:rawhide
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'systemd-resolve': '!!'
warning: locked password detected for 'systemd-network': '!!'
warning: locked password detected for 'dbus': '!!'
warning: garbage password detected for 'root': 'locked'
warning: locked password detected for 'systemd-bus-proxy': '!!'
warning: locked password detected for 'systemd-timesync': '!!'
passed
testing fedora:20
	'no-hard-coded-passwords' [1/1]...warning: locked password detected for 'dbus': '!!'
warning: garbage password detected for 'root': 'locked'
passed
```

**Comment by yosifkit** [comment]
Yeah... should probably ignore locked passwords since it just clutters the output and is still safe.

**Comment by tianon** [comment]
Ok, updated examples:
```console
$ bashbrew list --uniq centos | xargs ./test/run.sh -t no-hard-cod
ed-passwords
testing centos:latest
	'no-hard-coded-passwords' [1/1]...error: crypt password detected for 'root': '$1$UKLtvLuY$kka6S665oCFmU7ivSDZzU.'
failed
testing centos:centos6
	'no-hard-coded-passwords' [1/1]...passed
testing centos:centos5
	'no-hard-coded-passwords' [1/1]...passed
testing centos:centos7.1.1503
	'no-hard-coded-passwords' [1/1]...error: crypt password detected for 'root': '$1$UKLtvLuY$kka6S665oCFmU7ivSDZzU.'
failed
testing centos:centos7.0.1406
	'no-hard-coded-passwords' [1/1]...error: crypt password detected for 'root': '$1$UKLtvLuY$kka6S665oCFmU7ivSDZzU.'
failed
testing centos:centos6.6
	'no-hard-coded-passwords' [1/1]...passed
testing centos:centos5.11
	'no-hard-coded-passwords' [1/1]...passed
```
```console
$ bashbrew list --uniq fedora | xargs ./test/run.sh -t no-hard-coded-passwords
testing fedora:latest
	'no-hard-coded-passwords' [1/1]...warning: garbage password detected for 'root': 'locked'
passed
testing fedora:21
	'no-hard-coded-passwords' [1/1]...warning: garbage password detected for 'root': 'locked'
passed
testing fedora:rawhide
	'no-hard-coded-passwords' [1/1]...warning: garbage password detected for 'root': 'locked'
passed
testing fedora:20
	'no-hard-coded-passwords' [1/1]...warning: garbage password detected for 'root': 'locked'
passed
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
