### PR TITLE
[varnish] drop alpine tag

### PR DESCRIPTION
**Pull request by gquintard**
see https://github.com/docker-library/official-images/pull/15852#issuecomment-1845912882

### CODE REVIEW

**Comment by whalelines** [comment]
Seems you are updating the base images used in the alpine tag, not dropping it, no?

**Comment by gquintard** [comment]
@whalelines , sorry, I don't understand what you mean, we are doing this:

```
-FROM alpine:3.15
+FROM alpine
```

which is dropping the tag of the base images

**Comment by tianon** [comment]
I would still recommend pinning that to a specific base image -- sorry, I think my message must've been unclear.  I meant either remove the `varnish` tag that uses that image or update it, and updating it is totally valid.  I'd suggest pinning simply so that you don't get unexpected build failures when the "square wheel" moves and Alpine updates (so as of yesterday, that'd be `FROM alpine:3.19`).

**Comment by whalelines** [comment]
@gquintard , I read the title of this PR as removing the alpine tag from the varnish image, not removing the tag on the alpine base image, which, as @tianon mentions, is not a good idea.

**Comment by gquintard** [comment]
ah, thanks @whalelines , I see how my title was confusing, sorry about that.

I've updated the PR to use `3.19` now.

By the way, I'm stealing the square wheel image, it's brilliant.

**Pull request merged**
