### PR TITLE
Update photon image

### PR DESCRIPTION
**Pull request by gerrit-photon**
Update photon image

### CODE REVIEW

**Comment by tianon** [comment]
Just to double check, Python 3.5 was added to 1.0 here on purpose, right?

**Comment by yosifkit** [comment]
> Just to double check, Python 3.5 was added to 1.0 here on purpose, right?

Ping @frapposelli or @YustasSwamp

**Comment by YustasSwamp** [comment]
Hi @tianon and @yosifkit thanks for the catch!
This is not on purpose. Please hold on with this change.

**Comment by YustasSwamp** [comment]
We are going to stop automatic image push, until we fix extra stuff that got added. Will update you once it's ready. Please ignore above commits.

**Comment by YustasSwamp** [comment]
Hi @tianon and @yosifkit , we fixed content of our images. Please consider latest commit (1 hour ago) for merging. Thanks.

**Pull request merged**
