### PR TITLE
Update couchdb, add new couchdb-nouveau fulltext search addon

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Review by nickva — COMMENTED** [review]
-1

This fails for me at least:

```
Starting buildx build at Fri Sep 27 03:50:08 EDT 2024...
[+] Building 3.1s (6/6) FINISHED                                                                                                                                             docker-container:apache-couchdb
 => [internal] load build definition from Dockerfile                                                                                                                                                    0.0s
 => => transferring dockerfile: 4.46kB                                                                                                                                                                  0.0s
 => CANCELED [linux/arm64 internal] load metadata for docker.io/library/debian:bullseye-slim                                                                                                            3.0s
 => CANCELED [linux/amd64 internal] load metadata for docker.io/library/debian:bullseye-slim                                                                                                            3.0s
 => ERROR [linux/s390x internal] load metadata for docker.io/library/debian:bullseye-slim                                                                                                               3.0s
 => ERROR [linux/ppc64le internal] load metadata for docker.io/library/debian:bullseye-slim                                                                                                             3.0s
 => [auth] library/debian:pull token for registry-1.docker.io                                                                                                                                           0.0s
------
 > [linux/s390x internal] load metadata for docker.io/library/debian:bullseye-slim:
------
------
 > [linux/ppc64le internal] load metadata for docker.io/library/debian:bullseye-slim:
------
Dockerfile:13
--------------------
  11 |     # the License.
  12 |     
  13 | >>> FROM debian:bullseye-slim
  14 |     
  15 |     LABEL maintainer="CouchDB Developers dev@couchdb.apache.org"
--------------------
ERROR: failed to solve: debian:bullseye-slim: failed to resolve source metadata for docker.io/library/debian:bullseye-slim: no match for platform in manifest: not found
```

**Comment by tianon** [comment]
From the CI:

> Invalid 'FROM' + 'Architectures' combinations detected:
>
>  - couchdb:3.3.3 (FROM debian:bullseye-slim) [ppc64le, s390x]

Debian Bullseye is officially in LTS now, so the set of supported architectures is limited and you'll need to either drop the now-unsupported ones or update to Bookworm.

I think you'll also want to remove 3.2, right?  (I understand it's EOL now?)  As a reminder, removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

Also, unfortunately we won't likely accept nouveau as a _new_ image (new repo namespace) -- I would suggest using a tag naming scheme like `couchdb:3.4-nouveau` if nouveau is simply an optional add-on to couchdb, or `couchdb:nouveau-3.4` if nouveau is a wholly separate tool (and the version numbers are only coincidentally the same).  Relevant to the former, would it be possible/reasonable for the new nouveau images to be `FROM couchdb:3.4` so they can share layers?  One major benefit of doing so is that it's then less "expensive" for users to swap back and forth between them.

**Comment by nickva** [comment]
@tianon Thank you for your guidance. We'll use bookworm for the base, remove 3.2 and use a tagging scheme for nouveau

**Comment by janl** [comment]
> Relevant to the former, would it be possible/reasonable for the new nouveau images to be FROM couchdb:3.4 so they can share layers? One major benefit of doing so is that it's then less "expensive" for users to swap back and forth between them.

Nouveau needs a Java runtime environment and CouchDB needs an Erlang runtime environment, so stacking them on top of each other does not make too much sense.

The other points I have addressed with the latest commit. Am I missing anything?

**Comment by janl** [comment]
OH! does the CI error mean we have to bump 3.3.3 to bookworm as well? Sorry if I misunderstood that.

**Comment by janl** [comment]
finally, all checks green ✅✅✅

thanks for the help!

**Comment by yosifkit** [comment]
One comment for change and a few others for thought:
A few of the new/modified `apt-get install` lines are missing a corresponding `rm -rf /var/lib/apt/lists/*` in the same layer. 

I don't know what the `-server` argument does for `/usr/bin/java`, but I guess if it runs, it is probably fine. You could get away with just `java` for the `CMD` instead of the whole path (since container runtimes use `PATH` for resolution), but it is fine either way.

**Comment by janl** [comment]
@yosifkit thanks for the additional notes. We’re happy to address those in future releases unless anyone here thinks these are showstoppers? Nouveau is marked as a beta feature for this release.

We’d love to get the new CouchDB release onto the official library. If the new Nouveau image is holding that up, we can also split this out into a separate PR.

**Comment by yosifkit** [comment]
I guess they are fine this time. It will make the nouveau image a little bit larger (20 MB or more).

---

Something to consider for later: are any of the other Docker official images a suitable base instead of `apt` installing the OpenJDK? It is fine either way to us. Here they are in alphabetical order:
- [amazoncorretto](https://hub.docker.com/_/amazoncorretto)
- [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin)
- [ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes)
- [ibmjava](https://hub.docker.com/_/ibmjava)
- [sapmachine](https://hub.docker.com/_/sapmachine)

**Review by yosifkit — APPROVED** [review]

**Review by yosifkit — DISMISSED** [review]
Sorry, 🙇 one more thing and this is a blocker for me.
```dockerfile
RUN chown -R nouveau:nouveau /opt/nouveau
```
```console
<missing>      About a minute ago   RUN /bin/sh -c chown -R nouveau:nouveau /opt…   38.5MB    buildkit.dockerfile.v0
```
This `chown` layer is inflating the image size. Because this is changing ownership of files from an earlier layer, there is now an extra copy of everything in `/opt/nouveau` for this `chown` layer. Any permissions (or mode) changes need to be done in the same layer in which the files originate.

If you'd like to open a separate PR that is just the couchdb bump I can merge that while we continue iterating here for `couchdb:*-nouveau`.

**Comment by janl** [comment]
@yosifkit there you go, threw in the cleanup as well

**Review by nickva — COMMENTED** [review]
+1 from me

For commit on 1c0ff3713acf5f5cb2c0dc0229dce3325557bb4f on https://github.com/apache/couchdb-docker

Used buildx to push `3.4.1`, 3.4`, `3` and `latest` to https://hub.docker.com/repository/docker/apache/couchdb/tags

**Comment by nickva** [comment]
@big-r81 had noticed we missed another cleanup and we just merged it fix: https://github.com/apache/couchdb-docker/pull/270

**Comment by janl** [comment]
+1, anything else to get this merged? :)

**Review by big-r81 — COMMENTED** [review]
+1

Added the corresponding `rm -rf /var/lib/apt/lists/*` lines and removed the layer bloating of the separate `chown` command.

All is ✅.

**Review by tianon — APPROVED** [review]

**Pull request merged**
