### PR TITLE
Update Joomla! to 3.9.2

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by tianon** [comment]
This was included in https://github.com/docker-library/official-images/pull/5306 -- would you like me to stop including `joomla` in those bumps? (it would certainly make my life simpler not to have to worry about `joomla` bumps there :sweat_smile:)

**Comment by tianon** [comment]
(cc @mbabker)

**Comment by J0WI** [comment]
Oops, I've overseen this! Thanks for keeping Joomla! up to date!

**Comment by tianon** [comment]
You should be able to run it in a Docker container (as long as you can get the `bashbrew` binary and the repo source in there, which isn't too difficult), if that helps. :smile: :heart:

**Pull request closed without merging**
