### PR TITLE
mariadb entrypoint fix

### PR DESCRIPTION
**Pull request by grooverdan**
I made a mistake and caused #MariaDB/mariadb-docker/issues/460

Correct fails to set password with MARIADB_ROOT_HOST=localhost,

Now includes test case.

### CODE REVIEW

**Comment by yosifkit** [comment]
Shouldn't https://github.com/MariaDB/mariadb-docker/blob/661429797fe3bbbb2aac6d0dc842a333c8782e5b/docker-entrypoint.sh#L353 also have the possibility of being set with `MARIADB_ROOT_PASSWORD_HASH`?

**Comment by grooverdan** [comment]
quite right, fixing now. Thanks.

**Comment by grooverdan** [comment]
I'm working on a solution for `/docker-entrypoint-initdb.d/` with `$MARIADB_ROOT_PASSWORD_HASH`, but I don't want to rush it too much. For now this fixes the regression and some other parts of PASSWORD_HASH.

**Comment by grooverdan** [comment]
Thank you.

**Pull request merged**
