### PR TITLE
Update r-base with apt-pinning

### PR DESCRIPTION
**Pull request by cboettig**
This commit resolves potential dependency problems that could occur in building the r-base image.  The previous strategy used the Debian sources from CRAN to build the latest R image, but these reflect dependencies on Wheezy.  We use Debian apt-pinning now to avoid this issue.

### CODE REVIEW

**Comment by tianon** [comment]
Just to simplify review: https://gist.github.com/tianon/5969b752837142352db8

I kept looking this over and thinking that this problem felt very, very familiar (like we'd discussed it before).  Turns out we did: https://github.com/rocker-org/rocker/pull/88#issuecomment-63678256 and https://github.com/rocker-org/rocker/pull/88#issuecomment-63690821

**Comment by cboettig** [comment]
@tianon Thanks for the diff. 

Yup, and apologies for that, at the time we'd forgotten about `apt-pinning` as a way to best address that issue.  We feel this approach should provide the best of both worlds (robust builds without rolling back to ancient wheezy).

**Comment by yosifkit** [comment]
That sounds reasonable to me.

**Comment by tianon** [comment]
Why not just use `APT::Default-Release` instead of having a whole new file used with `COPY`?
```Dockerfile
# make sure "stable" is preferred for otherwise unspecified installs
RUN echo 'APT::Default-Release "stable";' > /etc/apt/apt.conf.d/default
```

**Comment by tianon** [comment]
Also, since you're already `FROM debian:jessie` and aren't adding any other suites except `sid`, it seems a little strange to have such a verbose and explicit `preferences` file.

**Comment by tianon** [comment]
To illustrate what I mean:
```console
$ docker run -it --rm debian:jessie
root@a3962efb7c49:/# echo 'deb http://http.debian.net/debian sid main' > /etc/apt/sources.list.d/sid.list
root@a3962efb7c49:/# apt-get update
...
root@a3962efb7c49:/# apt-cache policy erlang
erlang:
  Installed: (none)
  Candidate: 1:17.3-dfsg-3
  Version table:
     1:17.3-dfsg-3 0
        500 http://http.debian.net/debian/ jessie/main amd64 Packages
        500 http://http.debian.net/debian/ sid/main amd64 Packages
root@a3962efb7c49:/# echo 'APT::Default-Release "jessie";' > /etc/apt/apt.conf.d/default
root@a3962efb7c49:/# apt-cache policy erlang
erlang:
  Installed: (none)
  Candidate: 1:17.3-dfsg-3
  Version table:
     1:17.3-dfsg-3 0
        990 http://http.debian.net/debian/ jessie/main amd64 Packages
        500 http://http.debian.net/debian/ sid/main amd64 Packages
root@a3962efb7c49:/# 
```

**Comment by eddelbuettel** [comment]
I acknowledge that the two commands shown above by @tianon are "lighter-weight", but I would like to point out that we will end up with the exact same packages from sid as before: `r-base`, `littler`.  Nothing really changes so this, and please pardon my French here, seems like like bike shedding to me.

I may be missing something more fundamental. If so, please feel free to set me straight.

**Comment by eddelbuettel** [comment]
But if this is what it takes to move forward we will adjust Dockerfiles, have'em built and will PR again.

**Comment by tianon** [comment]
COPY has very irritating Docker cache behavior (thanks to mtimes being
significant) and thus should be avoided whenever possible.

**Comment by eddelbuettel** [comment]
Ohhh, I see.  Instead of copying the preferences file in, get the same effect via the two echos you showed?  

I buy that.  Thanks for waving the cluebat.  Will change.

**Comment by tianon** [comment]
:+1: :heart:

**Comment by tianon** [comment]
(if I really wanted to just bikeshed, you'd be changing whitespace right now too -- I try to keep the unnecessary bike-shedding to a minimum :smile:)

**Comment by eddelbuettel** [comment]
Hehe -- get yourself a :100:   ;-)

**Comment by eddelbuettel** [comment]
Guess it must be passed my bedtime here in flyover country if I put markdown into git comments.  Oh boy.

**Comment by tianon** [comment]
Hah, you even did the totally over-the-top whitespace changes. :heart:  I feel buttered. :smile:

Once this PR is updated I'll run a test build and I think we're good to go. :+1:

**Comment by eddelbuettel** [comment]
My pal and co-conspirator @cboettig is much more on top of these issues, but was too polite to trample over the r-base Dockerfile I had worked on last ;-)

**Comment by cboettig** [comment]
Thanks for the feedback, PR updated.

**Comment by eddelbuettel** [comment]
Looks we're good.  Freshly built and pulled:

```{.bash}
edd@max:~$ docker run --rm -ti rocker/r-base /bin/bash
root@f2ba3bf7ab40:/# R --version
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

root@f2ba3bf7ab40:/# r --version
r ('littler') version 0.2.2

git revision 8df31e5 as of Thu Jan 29 17:43:21 2015 -0800
built at 12:53:44 on Jan 30 2015
using GNU R Version 3.1.2 (2014-10-31)

Copyright (C) 2006 - 2014  Jeffrey Horner and Dirk Eddelbuettel

r is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License.  For more information about
these matters, see http://www.gnu.org/copyleft/gpl.html.

root@f2ba3bf7ab40:/# exit
edd@max:~$ docker images | grep r-base
rocker/r-base                latest              64f4276cbb9f        4 minutes ago       500 MB
r-base                       3.1.2               0ca81a0d7240        4 weeks ago         500.3 MB
r-base                       latest              0ca81a0d7240        4 weeks ago         500.3 MB
edd@max:~$ 
```

**Comment by tianon** [comment]
You guys are swell. :heart:

Thanks for being so easy to work with.

LGTM

Build test of #444; bad6eba14b06f08b60845b8d152c0a7c784cc6f5 (`r-base`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/bad6eba14b06f08b60845b8d152c0a7c784cc6f5/library/r-base
Fetching r-base (git://github.com/rocker-org/rocker) ...
Processing r-base:latest ...
Processing r-base:3.1.2 ...
```

**Comment by tianon** [comment]
cc @yosifkit

**Comment by yosifkit** [comment]
LGTM

**Comment by eddelbuettel** [comment]
Yay!  Thanks for the patience and repeated cluebat waves.  Have a cookies.

**Comment by eddelbuettel** [comment]
You win, again :)

**Pull request merged**
