### PR TITLE
caddy: v2.8.0 release

### PR DESCRIPTION
**Pull request by francislavoie**
https://github.com/caddyserver/caddy/releases/tag/v2.8.0

### CODE REVIEW

**Comment by tianon** [comment]
Sure!  Currently, the only "meaningful" versions to support are really only the two you've got (LTSC2022 and 1809) -- we don't officially support anything beyond that here (yet).  It's important to support both if you want users to be able to use the images effectively because they essentially have to match the image OS version to their host OS version (or at least "level of compatibility").  In newer versions of Windows, Microsoft _is_ working to relax this (see https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility for example), but it's going to take a bit before that work hits Windows Server versions in a meaningful way, and even then there'll always be a transition period. :smile:

(1809 is effectively Windows Server 2019)

**Review by tianon — APPROVED** [review]

**Comment by francislavoie** [comment]
Okay, thanks, good to know. Dependabot has been annoying us about bumping it up but I wasn't comfortable with doing it without knowing the implications. Glad we didn't then!

**Comment by tianon** [comment]
Oh interesting -- I guess I'll go check your recent PRs to see for myself, but I'm curious what it's suggesting you bump _to_ :sweat_smile:

**Comment by tianon** [comment]
Oh man, https://github.com/caddyserver/caddy-docker/pull/344 is so hilariously wrong I can't believe it's recommending it with a straight face -- Windows is popular enough that I think they need to rush to implement some special cases for those recommendations! :grimacing:

**Comment by francislavoie** [comment]
We might just have it configured incorrectly, I dunno. But yeah :grimacing:

**Comment by tianon** [comment]
https://github.com/caddyserver/caddy-docker/blob/31e47e815d156068674d986aa64fa03998df952a/.github/dependabot.yml looks pretty vanilla to me!  Those other two PRs are _also_ probably not what you want (you've chosen to "pin" to `golang:1.22` on purpose -- switching to something [more](https://github.com/caddyserver/caddy-docker/pull/346) or [less](https://github.com/caddyserver/caddy-docker/pull/345) specific, it can't seem to make up its mind, is definitely also unhelpful :joy:)

**Pull request merged**
