### PR TITLE
Fedora 20 is EOL, remove fedora:{20,heisenbug}

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by lsm5** [comment]
umm, please put this on hold for now, I'll get back when we're ready to get rid of version 20. (waiting to hear from people if this will break things for them)

**Comment by tianon** [comment]
Does it help to know that the tag will still exist and be pullable, it just won't get rebuilt or be listed in the "supported" list on the image description?

**Comment by lsm5** [comment]
@tianon yup, that sounds much better than just deleting them! Do I just update this file with a comment saying it won't be supported anymore, or is there a better place to mention this?

**Comment by yosifkit** [comment]
You could just update the [content.md](https://github.com/docker-library/docs/blob/master/fedora/content.md) in the docs to mention the EOL. If that is reasonable, I give this a LGTM.

**Comment by tianon** [comment]
LGTM +1

Agree with adding a note to `content.md` if you want to explicitly call this out. :+1:

**Comment by tianon** [comment]
@lsm5 so, we'll wait to merge until you confirm that you agree :wink:

**Comment by tianon** [comment]
ping @lsm5, we good to merge?

**Comment by lsm5** [comment]
umm, not yet ... guess I still gotta send an f20 update with openssl fix if we're going to keep f20 around :|

**Comment by yosifkit** [comment]
ping @lsm5.  status of this PR?  Now that f20 is updated in #866, are we dropping it soon?

**Comment by lsm5** [comment]
I'm gonna close this. Let's keep f20 in there.  f20 logjam update https://github.com/docker-library/official-images/commit/3336cb2c59e665e0e6575bf556cad286c9d66da5 and the docs mentioning f20 EOL have been merged.

Copying @maxamillion to keep him in the loop. He (or someone else from fedora rel-eng) will soon be owning fedora updates.

**Pull request closed without merging**
