### PR TITLE
kong: bump to 0.14.0rc1

### PR DESCRIPTION
**Pull request by thibaultcha**
* 0.14.0rc1 points to alpine
* 0.14.0rc1-alpine
* 0.14.0rc1-centos

### CODE REVIEW

**Comment by tianon** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 266ffa6..dbceb1a 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -3,4 +3,6 @@ kong:0.11.2-alpine @ amd64
 kong:0.12.3 @ amd64
 kong:0.12.3-alpine @ amd64
 kong:0.13-centos @ amd64
+kong:0.14.0rc1 @ amd64
+kong:0.14.0rc1-centos @ amd64
 kong:latest @ amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index d879e08..133b6f2 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -13,4 +13,7 @@ kong:0.13-centos
 kong:0.13.1
 kong:0.13.1-alpine
 kong:0.13.1-centos
+kong:0.14.0rc1
+kong:0.14.0rc1-alpine
+kong:0.14.0rc1-centos
 kong:latest
diff --git a/kong_0.13-centos/Dockerfile b/kong_0.14.0rc1-centos/Dockerfile
similarity index 94%
copy from kong_0.13-centos/Dockerfile
copy to kong_0.14.0rc1-centos/Dockerfile
index 37b9fc4..fd56b1a 100644
--- a/kong_0.13-centos/Dockerfile
+++ b/kong_0.14.0rc1-centos/Dockerfile
@@ -1,7 +1,7 @@
 FROM centos:7
 MAINTAINER Marco Palladino, marco@mashape.com
 
-ENV KONG_VERSION 0.13.1
+ENV KONG_VERSION 0.14.0rc1
 
 RUN yum install -y wget https://bintray.com/kong/kong-community-edition-rpm/download_file?file_path=centos/7/kong-community-edition-$KONG_VERSION.el7.noarch.rpm && \
     yum clean all
diff --git a/kong_0.11.2-alpine/docker-entrypoint.sh b/kong_0.14.0rc1-centos/docker-entrypoint.sh
similarity index 100%
copy from kong_0.11.2-alpine/docker-entrypoint.sh
copy to kong_0.14.0rc1-centos/docker-entrypoint.sh
diff --git a/kong_latest/Dockerfile b/kong_0.14.0rc1/Dockerfile
similarity index 72%
copy from kong_latest/Dockerfile
copy to kong_0.14.0rc1/Dockerfile
index d40f1c5..b17d12e 100644
--- a/kong_latest/Dockerfile
+++ b/kong_0.14.0rc1/Dockerfile
@@ -1,10 +1,11 @@
 FROM alpine:3.6
 LABEL maintainer Marco Palladino, marco@mashape.com
 
-ENV KONG_VERSION 0.13.1
-ENV KONG_SHA256 caf119ce7a367b9d9cd1ace55c4b6a499ff3c4693f80ea25129ebf2da0373fcc 
+ENV KONG_VERSION 0.14.0rc1
+ENV KONG_SHA256 e8a7e8be0f98a936f72237e878dc1644e9d7b8aea666bc5e6c4d023545b619f3 
 
-RUN apk add --no-cache --virtual .build-deps wget tar ca-certificates \
+RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories \
+	&& apk add --no-cache --virtual .build-deps wget tar ca-certificates \
 	&& apk add --no-cache libgcc openssl pcre perl tzdata curl \
 	&& wget -O kong.tar.gz "https://bintray.com/kong/kong-community-edition-alpine-tar/download_file?file_path=kong-community-edition-$KONG_VERSION.apk.tar.gz" \
 	&& echo "$KONG_SHA256 *kong.tar.gz" | sha256sum -c - \
diff --git a/kong_0.11.2-alpine/docker-entrypoint.sh b/kong_0.14.0rc1/docker-entrypoint.sh
similarity index 100%
copy from kong_0.11.2-alpine/docker-entrypoint.sh
copy to kong_0.14.0rc1/docker-entrypoint.sh
````

</details>

**Comment by tianon** [comment]
```diff
+RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories \
```

Can you elaborate on the reasoning/logic behind this change? :pray:

**Comment by tianon** [comment]
Looks like it was https://github.com/Kong/docker-kong/pull/159, but I don't see the "why?" included there -- what's the value added by doing so? (There's active harm caused by preventing folks like our servers that build this from being able to transparently apply caching for all Alpine package downloads, but maybe there's some innate benefit we're not seeing. :+1:)

**Comment by thibaultcha** [comment]
@gszr Can you give a hand and help me answer @tianon's question? Thanks!

**Comment by tianon** [comment]
Can you please elaborate more on the reasons that went into that decision?  The APK packages that `apk add` downloads and installs are cryptographically signed and verified, as are the package lists, so privacy is the only real benefit provided by using https, and that benefit is a bit dubious in this case IMO.

Keeping the default http-based repository allows us to have our build servers transparently hijack that domain via DNS to provide a download cache, which helps a lot with speeding up our builds.

**Comment by gszr** [comment]
@tianon, both the packages and lists are downloaded from the same repository, over http, or are there signatures carried over in the base system?

**Comment by tianon** [comment]
The public keys exist in the base system (see `/etc/apk/keys`), very similar to APT in Debian (`/etc/apt/trusted.gpg.d`).  The package signatures from the mirrors are verified against those (which prevents tampering).

**Comment by gszr** [comment]
Thank you @tianon - I reverted that commit in Kong Docker. New PR incoming.

**Pull request closed without merging**
