### PR TITLE
[security] Update golang

### PR DESCRIPTION
**Pull request by tianon**
Changes:

- https://github.com/docker-library/golang/commit/539882f: Update 1.22 to 1.22.5
- https://github.com/docker-library/golang/commit/4e6e435: Update 1.21 to 1.21.12

### CODE REVIEW

**Review by yosifkit — APPROVED** [review]

**Comment by ldemailly** [comment]
thanks! I wonder if this could be automated based on trusting go.dev/dl/ ?

**Comment by tianon** [comment]
It is; that's how https://github.com/docker-library/golang/commit/539882f and https://github.com/docker-library/golang/commit/4e6e435 were created.  This PR (and the review of it) are the only manual steps involved (and opening the PR itself is only manual because we often have scraping issues with various upstreams where the automated updates are flaky and thus "flap" between versions occasionally and we don't want to open PRs/create noise for those frivolous commits).

See also https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what

**Comment by ldemailly** [comment]
oh, awesome, thanks for having answered with the details!
so I see (I think all green/done on https://doi-janky.infosiftr.net/job/multiarch/view/images/view/golang/

yet

https://hub.docker.com/v2/repositories/library/golang/tags/1.22.5 is still 404 - where else can see the progress?

**Comment by ldemailly** [comment]
this is probably the wrong spot to ask (where is the right one) but any ETA/issue with

https://hub.docker.com/layers/library/golang/1.22.5/images/sha256-c8715e797d0705204fdeeaf791773c80d5a036c021779984b4c817d84f9b19cb?context=explore

to get the rest of the architectures? (arm etc missing)

**Comment by ldemailly** [comment]
filled https://github.com/docker-library/golang/issues/525 in case it'd help visibility

**Pull request merged**
