### PR TITLE
Update Clear Linux OS to 33760

### PR DESCRIPTION
**Pull request by clrbuilder**
Update Clear Linux OS latest+base images to release 33760

@bryteise @gtkramer

### CODE REVIEW

**Comment by yosifkit** [comment]
Just to double check, are these new elfutils files (like the following) on purpose?

```diff
+usr/bin/debuginfod-find
+usr/bin/eu-addr2line
+usr/bin/eu-ar
+usr/bin/eu-elfclassify
+usr/bin/eu-elfcmp
+usr/bin/eu-elfcompress
+usr/bin/eu-elflint
+usr/bin/eu-findtextrel
+usr/bin/eu-make-debug-archive
+usr/bin/eu-nm
+usr/bin/eu-objdump
+usr/bin/eu-ranlib
+usr/bin/eu-readelf
+usr/bin/eu-size
+usr/bin/eu-stack
+usr/bin/eu-strings
+usr/bin/eu-strip
+usr/bin/eu-unstrip
```

**Comment by phmccarty** [comment]
@yosifkit No, those additions were unintentional... thanks for catching that. We will investigate the issue.

**Comment by phmccarty** [comment]
There was an update to `elfutils` package last week, and the packaging changes had some unexpected side effects that led to unwanted changes in various low-level bundles.

We have fixed the issue in 33790 and newer.

**Comment by yosifkit** [comment]
Should we merge this one and have the fix on the next PR, update this one with the fix, or close this and wait for the next PR?

**Comment by phmccarty** [comment]
I would prefer to close this one and wait for the next PR. Thanks!

**Pull request closed without merging**
