### PR TITLE
Gradle 7.1

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by tianon** [comment]
(Naughty failure is our good ol' AdoptOpenJDK flip-flopping architectures :see_no_evil:)

**Comment by keeganwitt** [comment]
@tianon Yep. You heard any update on whether that's gonna improve? Wasn't there an issue for that?

**Comment by TheSRK** [comment]
Hello, my project is on Gradle 7.1 but I don't see an official docker image for 7.1 in the docker hub. So, is it mandatory to update now? Or my 7.1 gradle will be compatible with gradle:7.5-jdk8?

**Comment by yosifkit** [comment]
None of the old tags are deleted, so there are still `7.1` based images: [hub.docker.com](https://hub.docker.com/_/gradle/tags?page=1&name=7.1). But they are no longer updated. As far as compatibility, you could check the [release notes](https://gradle.org/releases/) or just trust that they are following their policy: https://docs.gradle.org/current/userguide/feature_lifecycle.html#backwards_compatibility

**Pull request merged**
