### PR TITLE
Update Ubuntu 2023-06-01

### PR DESCRIPTION
**Pull request by ROCKsBot**
Update Ubuntu to the latest published OCI tarballs as of 2023-06-01.

### CODE REVIEW

**Comment by woky** [comment]
Could you please re-run the check? It appears Launchpad is not healthy today.

**Comment by tianon** [comment]
I don't think it's worth over-cycling for _this_ update, but the next one can probably drop me from `Maintainers:` here too (matching the docs PR) :eyes: :heart:

**Comment by woky** [comment]
@tianon Will do. You don't want to be /cc-ed in the bot comment either, right?

**Comment by tianon** [comment]
Naw, I'm good - I'll see it either way :smile:

**Pull request merged**
