### PR TITLE
Add apk test for Alpine

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Is this actually useful for you?
@tianon @yosifkit

**Comment by tianon** [comment]
Doh, sorry!

If I were maintaining the Alpine image, I would want a test like this (verifies repository urls, etc), but I'll have to defer to @ncopa here: is this something you'd like having us run on each Alpine update to do a rough smoke test?

**Comment by J0WI** [comment]
@ncopa FYI, there is a similar check for Debian/APT: https://github.com/docker-library/official-images/tree/master/test/tests/debian-apt-get

**Comment by J0WI** [comment]
:ping_pong: @ncopa

**Comment by yosifkit** [comment]
No response; closing old PR.

(@ncopa, you are still welcome to open a similar PR if this is something you want us to test)

**Pull request closed without merging**
