### PR TITLE
Update php

### PR DESCRIPTION
**Pull request by tianon**
Changes:

- https://github.com/docker-library/php/commit/f936910: Merge pull request https://github.com/docker-library/php/pull/1096 from infosiftr/pear-8.0
- https://github.com/docker-library/php/commit/deb4a80: Keep "pecl update-channels" for 8.0 also
- https://github.com/docker-library/php/commit/6944008: Merge pull request https://github.com/docker-library/php/pull/1090 from infosiftr/8-ga
- https://github.com/docker-library/php/commit/8dfb458: Update to 8.0.0 (GA)
- https://github.com/docker-library/php/commit/26e65d3: Update 7.3 to 7.3.25
- https://github.com/docker-library/php/commit/0274f58: Update 7.4 to 7.4.13

(:turkey:...)

### CODE REVIEW

**Comment by tianon** [comment]
Hmm, the email announcement said it was a security fix, but https://www.php.net/index.php#id2020-11-26-1 does not. :confused:

**Comment by tianon** [comment]
Fixing the missed `pecl update-channels` bits in https://github.com/docker-library/php/pull/1096

**Comment by enumag** [comment]
https://hub.docker.com/layers/php/library/php/8.0-alpine/images/sha256-3033d69f2670fe716c4932109d8c3d1c3724c6f55db829f9993a764f5ec1777e

In OS/ARCH there is no `linux/amd64`, leading to `no matching manifest for linux/amd64 in the manifest list entries` error. What's going on?

**Comment by WyriHaximus** [comment]
Looks like it's only pushed to `amd64/php` and for some reason failed/forgot/didn't try to push to `php`: https://hub.docker.com/r/amd64/php/tags?page=1&ordering=last_updated&name=8.0-

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/1098 and https://github.com/docker-library/php/pull/1090, especially https://github.com/docker-library/php/pull/1090#issuecomment-736639641:

> What happened here is that ARM managed to build and push faster than amd64 did, then we hit Docker's rate limits while trying to update the manifest lists for a while.

**Comment by enumag** [comment]
Okay, indeed that explains how it happened. What now? How can we fix it?

**Comment by tianon** [comment]
In this case, patience did the trick and it should be fixed and working.

**Comment by tom-pryor** [comment]
Does docker not provide free pro/team docker hub accounts for community members who maintain official images that don't have the new rate limits?

**Pull request merged**
