### PR TITLE
Actually update ZNC to 1.8.1

### PR DESCRIPTION
**Pull request by DarthGandalf**
I forgot one important detail in #8141

### CODE REVIEW

**Comment by IceBear2k** [comment]
#8225 should be merged before this, unless there is some other process to fix currently wrong tags `1.8.0` and `1.8.0-slim`.

**Comment by DarthGandalf** [comment]
I don't think reverting that commit as is is a good idea: that would mean that tags `latest`, `1.8-slim`, etc would refer to the version 1.8.0 again, instead of 1.8.1, even if temporarily.

**Comment by tianon** [comment]
Indeed, if fixing the older tags is important, they should be added as new entries to the existing file (temporarily) next to the existing version.

This LGTM :+1:

**Comment by tianon** [comment]
(If fixing the old tags is desirable to you, @DarthGandalf, that can be a separate PR. :+1:)

**Comment by DarthGandalf** [comment]
@IceBear2k wanna add the separate entry temporarily?

**Pull request merged**
