### PR TITLE
Update php

### PR DESCRIPTION
**Pull request by tianon**
Changes:

- https://github.com/docker-library/php/commit/cc901e9: Add PHP 8.2.0 (https://github.com/docker-library/php/pull/1353)
- https://github.com/docker-library/php/commit/b8abf7a: Update 8.2-rc

### CODE REVIEW

**Comment by PheRum** [comment]
@tianon 

```
➜  8.2 git:(master) docker build -t ipherum/gitlab-ci:8.2 .
Sending build context to Docker daemon   2.56kB
Step 1/7 : FROM --platform=linux/amd64 php:8.2-cli-alpine
manifest for php:8.2-cli-alpine not found: manifest unknown: manifest unknown
```

**Comment by yosifkit** [comment]
See steps 5-6 in our [FAQ](https://github.com/docker-library/faq/tree/4f51e1b995017ab10dab85fed304bce60fb7fa37#an-images-source-changed-in-git-now-what) entry for "An image's source changed in Git, now what?".  You can see all the jobs for PHP at the bottom of the docker-library/php repo: https://github.com/docker-library/php/#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by heddn** [comment]
https://hub.docker.com/layers/library/php/8.2-apache/images/sha256-85629e9f9581782231fc7f5cdecbe7678579d3d6468d64eacbf5a7c8f62f4a05?context=explore doesn't seem to have a manifest for `linux/amd64`. Do I just need to be patient or is that an unexpected thing?

**Comment by yosifkit** [comment]
I see an image for `amd64` for `php:8.2-apache`. It is expected that new tags only have the architectures that were ready when the OCI index was updated. The job for updating that index happens to be running right now and so they will be as complete as they can be.

**Pull request merged**
