### PR TITLE
change default --namespaces '_'

### PR DESCRIPTION
**Pull request by psftw**
motivation: I don't want to have to specify this to avoid additional namespace tags.

### CODE REVIEW

**Comment by yosifkit** [comment]
:cake: :tada: LGTM

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/404#issuecomment-70316179

> ... as long as we have a sane way to configure the official build server in the other direction.

So, what ideas do you have? :wink:

**Comment by yosifkit** [comment]
Configure? Isn't it just: `./bashbrew.sh build --namespaces='_ library stackbrew' ...`

**Comment by tianon** [comment]
For every time we run it?

**Comment by tianon** [comment]
I suppose we could just keep the opposite of this patch as an unstaged change in Git on the server.  That'll make updates to this script more annoying to apply (since we'll have to do the `stash`, `pull`, `stash pop` dance), but I'm OK with that if you are.

**Comment by yosifkit** [comment]
What do you have in mind?  Would we really want an ENV or config file to change it?

**Comment by tianon** [comment]
Definitely not an environment variable.  I was thinking about a config file, but that feels like overkill for now.  Maybe we go with this for now and revisit the debate later when/if it turns out to be annoying? :smile:

**Comment by yosifkit** [comment]
That works :+1:

**Comment by tianon** [comment]
:smiling_imp:

LGTM

**Pull request merged**
