### PR TITLE
fedora container update

### PR DESCRIPTION
**Pull request by siddharthvipul**
+ Link to newer images
+ add maintainer
+ change latest image to f32 from f31
Signed-off-by: siddharthvipul <siddharthvipul1@gmail.com>

### CODE REVIEW

**Comment by yosifkit** [comment]
```console
failed fetching/scraping FROM for "fedora" (tags "rawhide, 33", arch "arm64v8")
failed "git show" for "aarch64/Dockerfile" from commit "69c5d5652550f1ba0e51c1510bf8d5ecd5a6bea4"
file not found
```

**Comment by siddharthvipul** [comment]
@yosifkit 
hey, I have updated the container (excluded the builds that were failing (data center move problem)

@cverna, FYI, rawhide has just 2 build x86_64 and arm64.

**Comment by tianon** [comment]
Diff: https://gist.github.com/docker-library-bot/b65cdf1e27801e5c9c82c8b771a6ce15

**Comment by tianon** [comment]
Any particular reason to keep versions 26 - 30 listed here?  Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by cverna** [comment]
> Any particular reason to keep versions 26 - 30 listed here? Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them. (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

+1 to remove them from the file :-)

**Comment by siddharthvipul** [comment]
> > Any particular reason to keep versions 26 - 30 listed here? Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them. (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)
> 
> +1 to remove them from the file :-)

Thank you for a green check :)
@tianon, does it look okay now? - removed EOL versions

**Pull request merged**
