### PR TITLE
Release Couchbase Server EE 6.6.4 and 7.0.3 with log4j remediation

### PR DESCRIPTION
**Pull request by ceejatec**
Proposing this now to get it in the queue and reviewed. If possible, please wait for a comment from me before actually submitting the change - we should be posting a blog today about the log4j remediation.

### CODE REVIEW

**Comment by ceejatec** [comment]
Also, we would like to have the Category "Databases" applied to our official image. It appears there isn't a way for us to do that ourselves (https://github.com/docker/roadmap/issues/76 ) - can you do it?

**Comment by tianon** [comment]
Build test of #11500; 9bd05907b; `amd64` (`couchbase:6.6.4`, `couchbase:latest`):

```console

$ bashbrew build couchbase:6.6.4
Building bashbrew/cache:deb8850304389e7a4d042c252a14d20b34f2331e0ad7a6f9a38293016cffbf3e (couchbase:6.6.4)
Tagging couchbase:6.6.4
Tagging couchbase:enterprise-6.6.4

$ test/run.sh couchbase:6.6.4
testing couchbase:6.6.4
	'utc' [1/3]...passed
	'no-hard-coded-passwords' [2/3]...passed
	'override-cmd' [3/3]...passed

```

```console

$ bashbrew build couchbase:latest
Building bashbrew/cache:86e26dbdbc464f39dd5f7d7e1833f589e57bebe09c3fa3aa52f9b0c13270f1a8 (couchbase:latest)
Tagging couchbase:latest
Tagging couchbase:enterprise
Tagging couchbase:7.0.3
Tagging couchbase:enterprise-7.0.3

$ test/run.sh couchbase:latest
testing couchbase:latest
	'utc' [1/3]...passed
	'no-hard-coded-passwords' [2/3]...passed
	'override-cmd' [3/3]...passed

```

**Comment by tianon** [comment]
That log line is very cute :joy:

**Comment by tianon** [comment]
> Also, we would like to have the Category "Databases" applied to our official image. It appears there isn't a way for us to do that ourselves ([docker/roadmap#76](https://github.com/docker/roadmap/issues/76) ) - can you do it?

We can't do this, but I'll ask the Docker folks. :+1:

**Pull request merged**
