### PR TITLE
Update golang

### PR DESCRIPTION
**Pull request by yosifkit**
Changes:

- https://github.com/docker-library/golang/commit/1373933: Merge pull request https://github.com/docker-library/golang/pull/373 from techknowlogick/alpine3.14
- https://github.com/docker-library/golang/commit/f300e60: Update to Alpine 3.14

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I saw these tags on https://hub.docker.com/_/golang:

- **1.16.5-alpine3.14**, **1.16-alpine3.14**, **1-alpine3.14**, alpine3.14, 1.16.5-alpine, 1.16-alpine, 1-alpine, alpine

but looks like not really available?

image

1.16.5-alpine3.13 looks different

image

and also can't pull them with success, not sure is something went wrong?

```
$ docker pull golang:1.16-alpine3.14
1.16-alpine3.14: Pulling from library/golang
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by tyranron** [comment]
Same here:

Screenshot 2021-06-17 at 13 46 03
Screenshot 2021-06-17 at 13 46 21

ping @yosifkit

**Comment by yosifkit** [comment]
`amd64` is failing to build because of https://github.com/opencontainers/runc/pull/2750.  We're working to update `docker` + `runc` on the builder.

**Comment by tianon** [comment]
Builders are updated and builds are either queued or in progress --
sorry for the delay!

**Pull request merged**
