### PR TITLE
archlinux: Release 20210829.0.32635

### PR DESCRIPTION
**Pull request by archlinux-github**
This is an automated release [1].

[1] https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/master/.gitlab-ci.yml

---

Maintainers: @SantiagoTorres @shibumi @hashworks

### CODE REVIEW

**Comment by DasSkelett** [comment]
Looks like this one never arrived at Docker Hub, and PRs for 2021-09-05 and 2021-09-12 haven't been opened either.
screenshot

@SantiagoTorres @shibumi @hashworks  (pinging you as maintainers)

**Comment by yosifkit** [comment]
The tags are there and pull just fine. Not sure why the Docker Hub interface isn't showing them.

```console
$ docker manifest inspect archlinux:base-20210829.0.32635
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:12bd35ad6ea47a827433ad0c5cc5659e74f451bd92bc526bc12f19905d95f97d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
$ docker pull archlinux:base-20210829.0.32635
base-20210829.0.32635: Pulling from library/archlinux
adb45d044f8e: Pull complete 
97dcbf6a4ad1: Pull complete 
Digest: sha256:91d8f255a6f8944bb15725ed97180f8dbda877919f05cd97ebde033d7217ec39
Status: Downloaded newer image for archlinux:base-20210829.0.32635
docker.io/library/archlinux:base-20210829.0.32635
```

**Comment by tianon** [comment]
There's some folks on the Docker Inc team looking into the UI mismatch. 🙂

**Comment by DasSkelett** [comment]
Nice to hear! Now there's only the question why there hasn't been any automated PR to update the image so far this month, but that's probably on the Arch team to investigate.

**Comment by hashworks** [comment]
Thanks for the ping, small problem on our end. Automated PR will continue soon :)

**Pull request merged**
