### PR TITLE
[nats] Release v2.10.16

### PR DESCRIPTION
**Pull request by bruth**
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.10.16)

### CODE REVIEW

**Comment by bruth** [comment]
@yosifkit reviewers used to automatically get assigned. Has the workflow changed for anyone on the Docker team to review and merge the PRs? If so, understood and I will not ping you :)

**Comment by tianon** [comment]
(I wish the teams themselves could be public, _especially_ when their existence is already public due to being part of the appropriate file: https://github.com/docker-library/official-images/blob/6a521d5304d3fbb1fe4f7e4f08c8aef76d5e3478/.github/CODEOWNERS#L1 :upside_down_face:)

**Comment by bruth** [comment]
@tianon Ah missed that, thanks. I see `a team` was assigned.

**Comment by tianon** [comment]
I think it's probably fine to leave it, but I'd just note the warning that `setcap` might not round-trip the graph drivers successfully (so I'd consider the `setcap` addition to the `Dockerfile` mostly best-effort).

I'm guessing that's probably to be able to bind to "privileged" ports, which is already enabled by default for containers in recent Docker versions (since in a private network namespace, the concept of "privileged ports" doesn't really hold much meaning), so there's other mitigations in place already. :+1:

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
You might also enjoy https://github.com/moby/moby/issues/8460 and https://github.com/moby/moby/pull/41030 (which is the PR that finally fixed this for the engine :partying_face:).

**Comment by bruth** [comment]
@tianon It turns out that adding this setcap change broke a few people when pulling the image for more restrictive environments. We reverted the change in the Dockerfile. The NATS binary did not change of course, so we are safe to open a new PR with an update to the GitCommit to the new nats-docker version to re-build/push the image for 2.10.16?

**Comment by yosifkit** [comment]
Yeah, that's fine.

**Pull request merged**
