### PR TITLE
Remove latest tag from official Vault images

### PR DESCRIPTION
**Pull request by mladlow**
Per https://github.com/docker-library/docs/pull/2283#issuecomment-1449158801, could I also request that the latest tag be deleted please?

### CODE REVIEW

**Comment by tianon** [comment]
As requested:

```console
$ docker pull vault:latest
Error response from daemon: manifest for vault:latest not found: manifest unknown: manifest unknown
```

:+1: :heart:

**Comment by drewfish** [comment]
I can see how this is a good idea, but FYI this was a surprise and broke my CI builds.

The `latest` tag appears to documented as officially supported:
Screen Shot 2023-06-26 at 15 16 22

**Comment by drewfish** [comment]
Ack... I just saw this notice... I will do as it suggets.

> DEPRECATION NOTICE
Upcoming in Vault 1.14, we will stop publishing official Dockerhub images and publish only our Verified Publisher images. Users of Docker images should pull from [hashicorp/vault](https://hub.docker.com/r/hashicorp/vault) instead of [vault](https://hub.docker.com/_/vault). Verified Publisher images can be found at https://hub.docker.com/r/hashicorp/vault.

**Comment by mladlow** [comment]
Hey @drewfish I'm sorry this change broke your CI but glad that you can make the update. Thanks for adding the instructions here! I bet they will be helpful for future readers. Thanks @tianon for all your help over the years ❤️

**Comment by tianon** [comment]
For sure!  We'll be here, ready to help if you ever decide you want to resurrect this image. :heart:

**Pull request merged**
