### PR TITLE
Updated nginx to 1.13.6 and introduced a new variant with amplify age…

### PR DESCRIPTION
**Pull request by thresheek**
…nt installed.

### CODE REVIEW

**Comment by tianon** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 01c27a8..f6809f4 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -14,6 +14,7 @@ nginx:1.12-perl @ ppc64le
 nginx:1.12-perl @ s390x
 nginx:alpine @ amd64
 nginx:alpine-perl @ amd64
+nginx:amplify @ amd64
 nginx:latest @ amd64
 nginx:latest @ arm32v7
 nginx:latest @ arm64v8
diff --git a/_bashbrew-list b/_bashbrew-list
index 896b170..f7dceba 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -1,6 +1,7 @@
 nginx:1
 nginx:1-alpine
 nginx:1-alpine-perl
+nginx:1-amplify
 nginx:1-perl
 nginx:1.12
 nginx:1.12-alpine
@@ -13,17 +14,21 @@ nginx:1.12.1-perl
 nginx:1.13
 nginx:1.13-alpine
 nginx:1.13-alpine-perl
+nginx:1.13-amplify
 nginx:1.13-perl
-nginx:1.13.5
-nginx:1.13.5-alpine
-nginx:1.13.5-alpine-perl
-nginx:1.13.5-perl
+nginx:1.13.6
+nginx:1.13.6-alpine
+nginx:1.13.6-alpine-perl
+nginx:1.13.6-amplify
+nginx:1.13.6-perl
 nginx:alpine
 nginx:alpine-perl
+nginx:amplify
 nginx:latest
 nginx:mainline
 nginx:mainline-alpine
 nginx:mainline-alpine-perl
+nginx:mainline-amplify
 nginx:mainline-perl
 nginx:perl
 nginx:stable
diff --git a/nginx_alpine-perl/Dockerfile b/nginx_alpine-perl/Dockerfile
index 2579b27..c2746ac 100644
--- a/nginx_alpine-perl/Dockerfile
+++ b/nginx_alpine-perl/Dockerfile
@@ -2,7 +2,7 @@ FROM alpine:3.5
 
 LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-ENV NGINX_VERSION 1.13.5
+ENV NGINX_VERSION 1.13.6
 
 RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
 	&& CONFIG="\
diff --git a/nginx_alpine/Dockerfile b/nginx_alpine/Dockerfile
index fa6c012..8868666 100644
--- a/nginx_alpine/Dockerfile
+++ b/nginx_alpine/Dockerfile
@@ -2,7 +2,7 @@ FROM alpine:3.5
 
 LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-ENV NGINX_VERSION 1.13.5
+ENV NGINX_VERSION 1.13.6
 
 RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
 	&& CONFIG="\
@@ -118,11 +118,10 @@ RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
 	&& mv /usr/bin/envsubst /tmp/ \
 	\
 	&& runDeps="$( \
-		scanelf --needed --nobanner /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
-			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-			| sort -u \
-			| xargs -r apk info --installed \
+		scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
+			| tr ',' '\n' \
 			| sort -u \
+			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
 	)" \
 	&& apk add --no-cache --virtual .nginx-rundeps $runDeps \
 	&& apk del .build-deps \
diff --git a/nginx_amplify/Dockerfile b/nginx_amplify/Dockerfile
new file mode 100644
index 0000000..f020604
--- /dev/null
+++ b/nginx_amplify/Dockerfile
@@ -0,0 +1,80 @@
+FROM debian:stretch-slim
+
+LABEL maintainer="NGINX Amplify Engineering"
+
+ENV NGINX_VERSION         1.13.6-1~stretch
+ENV NJS_VERSION           1.13.6.0.1.14-1~stretch
+ENV AMPLIFY_AGENT_VERSION 0.46-2~stretch
+
+RUN set -x \
+    && deps="apt-transport-https apt-utils gnupg1 ca-certificates" \
+    && apt-get update \
+    && apt-get install --no-install-recommends --no-install-suggests -y $deps \
+    && echo "deb https://packages.amplify.nginx.com/debian/ stretch amplify-agent" > /etc/apt/sources.list.d/nginx-amplify.list \
+    && echo "deb http://nginx.org/packages/mainline/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
+    && \
+    NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+    found=''; \
+    for server in \
+        ha.pool.sks-keyservers.net \
+        hkp://keyserver.ubuntu.com:80 \
+        hkp://p80.pool.sks-keyservers.net:80 \
+        pgp.mit.edu \
+    ; do \
+        echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+        apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+    apt-get update \
+    && nginxPackages=" \
+        nginx=${NGINX_VERSION} \
+        nginx-module-xslt=${NGINX_VERSION} \
+        nginx-module-geoip=${NGINX_VERSION} \
+        nginx-module-image-filter=${NGINX_VERSION} \
+        nginx-module-njs=${NJS_VERSION} \
+        nginx-amplify-agent=${AMPLIFY_AGENT_VERSION} \
+    " \
+    && apt-get install --no-install-recommends --no-install-suggests -y \
+        $nginxPackages \
+        gettext-base \
+        procps \
+    && apt-get remove --purge --auto-remove -y $deps \
+    && rm -rf /etc/apt/sources.list.d/nginx-amplify.list \
+    && rm -rf /etc/apt/sources.list.d/nginx-amplify.list \
+    && rm -rf /var/lib/apt/lists/*
+
+# Copy nginx stub_status config
+COPY ./conf.d/stub_status.conf /etc/nginx/conf.d
+
+# API_KEY is required for configuring the NGINX Amplify Agent.
+# It could be your real API key for NGINX Amplify here if you wanted
+# to build your own image to host it in a private registry.
+# However, including private keys in the Dockerfile is not recommended.
+# Use the environment variables at runtime as described below.
+
+#ENV API_KEY 1234567890
+
+# If AMPLIFY_IMAGENAME is set, the startup wrapper script will use it to
+# generate the 'imagename' to put in the /etc/amplify-agent/agent.conf
+# If several instances use the same 'imagename', the metrics will
+# be aggregated into a single object in NGINX Amplify. Otherwise Amplify
+# will create separate objects for monitoring (an object per instance).
+# AMPLIFY_IMAGENAME can also be passed to the instance at runtime as
+# described below.
+
+#ENV AMPLIFY_IMAGENAME my-docker-instance-123
+
+# The /entrypoint.sh script will launch nginx and the Amplify Agent.
+# The script honors API_KEY and AMPLIFY_IMAGENAME environment
+# variables, and updates /etc/amplify-agent/agent.conf accordingly.
+
+COPY ./entrypoint.sh /entrypoint.sh
+
+# TO set/override API_KEY and AMPLIFY_IMAGENAME when starting an instance:
+# docker run --name my-nginx1 -e API_KEY='..effc' -e AMPLIFY_IMAGENAME="service-name" -d nginx-amplify
+
+EXPOSE 80
+
+STOPSIGNAL SIGTERM
+
+ENTRYPOINT ["/entrypoint.sh"]
diff --git a/nginx_amplify/conf.d/stub_status.conf b/nginx_amplify/conf.d/stub_status.conf
new file mode 100644
index 0000000..e9bea0c
--- /dev/null
+++ b/nginx_amplify/conf.d/stub_status.conf
@@ -0,0 +1,9 @@
+server {
+        listen 127.0.0.1:80;
+        server_name 127.0.0.1;
+        location /nginx_status {
+            stub_status on;
+            allow 127.0.0.1;
+            deny all;
+        }
+    }
diff --git a/nginx_amplify/entrypoint.sh b/nginx_amplify/entrypoint.sh
new file mode 100755
index 0000000..2b5afa8
--- /dev/null
+++ b/nginx_amplify/entrypoint.sh
@@ -0,0 +1,77 @@
+#!/bin/sh
+#
+# This script launches nginx and the NGINX Amplify Agent.
+#
+# Unless already baked in the image, a real API_KEY is required for the
+# NGINX Amplify Agent to be able to connect to the backend.
+#
+# If AMPLIFY_IMAGENAME is set, the script will use it to generate
+# the 'imagename' to put in the /etc/amplify-agent/agent.conf
+#
+# If several instances use the same imagename, the metrics will
+# be aggregated into a single object in Amplify. Otherwise NGINX Amplify
+# will create separate objects for monitoring (an object per instance).
+#
+
+# Variables
+agent_conf_file="/etc/amplify-agent/agent.conf"
+agent_log_file="/var/log/amplify-agent/agent.log"
+nginx_status_conf="/etc/nginx/conf.d/stub_status.conf"
+api_key=""
+amplify_imagename=""
+
+# Launch nginx
+echo "starting nginx ..."
+nginx -g "daemon off;" &
+
+nginx_pid=$!
+
+test -n "${API_KEY}" && \
+    api_key=${API_KEY}
+
+test -n "${AMPLIFY_IMAGENAME}" && \
+    amplify_imagename=${AMPLIFY_IMAGENAME}
+
+if [ -n "${api_key}" -o -n "${amplify_imagename}" ]; then
+    echo "updating ${agent_conf_file} ..."
+
+    if [ ! -f "${agent_conf_file}" ]; then
+	test -f "${agent_conf_file}.default" && \
+	cp -p "${agent_conf_file}.default" "${agent_conf_file}" || \
+	{ echo "no ${agent_conf_file}.default found! exiting."; exit 1; }
+    fi
+
+    test -n "${api_key}" && \
+    echo " ---> using api_key = ${api_key}" && \
+    sh -c "sed -i.old -e 's/api_key.*$/api_key = $api_key/' \
+	${agent_conf_file}"
+
+    test -n "${amplify_imagename}" && \
+    echo " ---> using imagename = ${amplify_imagename}" && \
+    sh -c "sed -i.old -e 's/imagename.*$/imagename = $amplify_imagename/' \
+	${agent_conf_file}"
+
+    test -f "${agent_conf_file}" && \
+    chmod 644 ${agent_conf_file} && \
+    chown nginx ${agent_conf_file} > /dev/null 2>&1
+
+    test -f "${nginx_status_conf}" && \
+    chmod 644 ${nginx_status_conf} && \
+    chown nginx ${nginx_status_conf} > /dev/null 2>&1
+fi
+
+if ! grep '^api_key.*=[ ]*[[:alnum:]].*' ${agent_conf_file} > /dev/null 2>&1; then
+    echo "no api_key found in ${agent_conf_file}! exiting."
+fi
+
+echo "starting amplify-agent ..."
+service amplify-agent start > /dev/null 2>&1 < /dev/null
+
+if [ $? != 0 ]; then
+    echo "couldn't start the agent, please check ${agent_log_file}"
+    exit 1
+fi
+
+wait ${nginx_pid}
+
+echo "nginx master process has stopped, exiting."
diff --git a/nginx_latest/Dockerfile b/nginx_latest/Dockerfile
index b39ab33..fbfc09e 100644
--- a/nginx_latest/Dockerfile
+++ b/nginx_latest/Dockerfile
@@ -2,8 +2,8 @@ FROM debian:stretch-slim
 
 LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-ENV NGINX_VERSION 1.13.5-1~stretch
-ENV NJS_VERSION   1.13.5.0.1.13-1~stretch
+ENV NGINX_VERSION 1.13.6-1~stretch
+ENV NJS_VERSION   1.13.6.0.1.14-1~stretch
 
 RUN set -x \
 	&& apt-get update \
diff --git a/nginx_perl/Dockerfile b/nginx_perl/Dockerfile
index 7860ae7..5a9e590 100644
--- a/nginx_perl/Dockerfile
+++ b/nginx_perl/Dockerfile
@@ -2,8 +2,8 @@ FROM debian:stretch-slim
 
 LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-ENV NGINX_VERSION 1.13.5-1~stretch
-ENV NJS_VERSION   1.13.5.0.1.13-1~stretch
+ENV NGINX_VERSION 1.13.6-1~stretch
+ENV NJS_VERSION   1.13.6.0.1.14-1~stretch
 
 RUN set -x \
 	&& apt-get update \
````

</details>

**Comment by tianon** [comment]
The 1.13.6 version bump looks fine (and I'd be happy to merge that right away if you wanted to split it out), but I do have some concerns about the amplify-agent Dockerization that need to be discussed.

That startup script is going to be very, very fragile -- if anything goes wrong with the amplify-agent (presumably the whole reason someone would be running this image variant), there will be _no_ indication of why, nor even that a failure has occurred, because nothing is monitoring that agent process (it's running in the background, likely logging to `/var/log/...`, and there's no init system monitoring it).  I'm not suggesting adding an init system to monitor that separate process (please, please don't), but I am curious whether there's a way to run the agent as a separate container so that each of NGINX and the agent can be run separately, and Docker can properly track each of their lifecycles individually?  Even if it requires going to the level of `--network container:some-nginx`, a two-container deployment for this is going to be preferable, unless NGINX itself can be convinced to launch and monitor that agent process directly.

**Comment by gshulegaard** [comment]
Hey!  Amplify agent contributor here...

You bring up some excellent points.

At the moment the Amplify agent is intentionally designed to work very closely with a running NGINX instance.  We track NGINX workers, system metrics, parse the NGINX config, detect config changes, detect NGINX events such as reloads/restarts, etc.  A year or so ago, I investigated various ways to deploy in a Docker environment and came up with more or less three possibilities:

* Privileged external container
* Networked external container
* Process within the same container

Running as a privileged container would give us the access to the NGINX container's resources that we require in order to replicate our functionality, but we would have to engineer an orthogonal workflow to accommodate and ask users to allow our agent's to run with elevated access to their underlying container hosts (at least last I checked).

We thought a bit about running a networked container that could support an orthogonal workflow where agents could be pre-configured and rely only on syslog and `stub_status`/`status` pages...but this would involve more configuration complexity as well as hamstring more advanced Amplify features such as NGINX event messaging and automatic/parallel reconfiguration.

At the time, running an agent within the same container seemed to be the most feature complete and least divergent workflow from our typical agent deployment.  When considering other container ecosystems such as LXD and OpenVZ, the availability of init systems within the container made this style of deployment less un-desirable.  So in the interest of preserving Amplify features and existing workflow we opted to go this route.

Like I said at start, you raise very good points and I am open to exploring any and all ideas for improving this situation.  But so far I haven't thought of any reasonable solution that doesn't involve serious workflow and/or feature caveats.

**Comment by tianon** [comment]
Would it be possible to change Amplify to launch and monitor the NGINX process directly (either failing when it fails, or restarting it as might be appropriate)?  That would allow both to be shut down cleanly upon `docker stop` (`SIGTERM`), among other benefits.  That also seems to me to be more in line with what Amplify's function, and would solve the concerns for making this an official image.  (I do realize that will be a non-trivial amount of development work in Amplify itself, but I cannot see another way to structure this in order to make it acceptable for the official images program otherwise -- every generic process supervisor we've evaluated falls short of providing a consistent, stable, and clean experience.)

**Comment by gshulegaard** [comment]
I must admit, having the Amplify agent manage the NGINX process is not something I have thought about personally to any great detail.  It's something I think worth examining with the rest of the team.  Is it appropriate to consider such a management feature as acceptance criteria here?  It would substantially impact prioritization from a product feature stand point if it is.

Thanks!

**Comment by tianon** [comment]
Yes, definitely -- running two separate unmanaged processes in a single
container in the current manner is going to be a blocker for an official
image. 👍

**Comment by thresheek** [comment]
Let's scrap this PR then; I'll provide another one to bump nginx versions.  Thanks a lot @tianon!

**Pull request closed without merging**
