### PR TITLE
Add mqttcool

### PR DESCRIPTION
**Pull request by gfinocchiaro**
# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[X] associated with or contacted upstream?
    - See
      * https://github/Lightstreamer
      * https://github/mqttcool 
-	[X] does it fit into one of the common categories? ("service", "language stack", "base distribution")
     - I would say service
-	[X] is it reasonably popular, or does it solve a particular use case well?
      -  See https://www.lightstreamer.com/mqttcool-features
-	[X] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long) 
     -  See docker-library/docs#1166
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[X] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
      - Using `openjdk:8-jre-alpine` and `openjdk:8-jre`
-	[X] ~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by gfinocchiaro** [comment]
# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[X] associated with or contacted upstream?
* https://github/Lightstreamer
* https://github/mqttcool 
-	[X] does it fit into one of the common categories? ("service", "language stack", "base distribution")
* service
-	[X] is it reasonably popular, or does it solve a particular use case well?
* See https://www.lightstreamer.com/mqttcool-features
-	[X] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long) 
* See docker-library/docs#1166
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[X] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[ ] if `FROM scratch`, tarballs only exist in a single commit within the associated history?
-	[X] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

**Comment by gfinocchiaro** [comment]
Added Checklist for Review

**Comment by gfinocchiaro** [comment]
Is there anything else I can do from my side to go on with this PR?
Thanks a lot!

**Comment by tianon** [comment]
Thanks @docker-library-bot :heart:

1. Just as an offer, would it be more upstream-accurate to call this new image `mqtt.cool`? (we already have precedence for a period with `rocket.chat`, so I wanted to just double check that `mqttcool` is the preferred image name)

1. looking at `jre8-alpine/Dockerfile` (on both `1.0` and `1.1`), I think you meant `apk del .deps` instead of `apk del gnupg tar openssl`, right? (to remove all the runtime deps that were added?)

**Comment by gfinocchiaro** [comment]
Hi!

1. Yes, actually the preffered image name is `mqtt.cool`
2. Oh, you're right.

I'm going to make the required changes.

**Comment by gfinocchiaro** [comment]
Lots of labels, not sure what happened.

**Comment by tianon** [comment]
I think something went wrong with your rebase, because instead of just your commits, you now have over 250 in here.

I'd suggest trying `git pull --rebase https://github.com/docker-library/official-images.git master`, then doing a force push if that's successful.

It looks like your docs PR suffered from the same issue.

**Comment by gfinocchiaro** [comment]
I could not manage to successfully rebase. I believe that a new PR from scratch is the best option now. What do you think?

**Comment by tianon** [comment]
I've just done the rebase myself successfully and got it down to 7 commits, but force pushing didn't seem to update the PR properly so it's probably true that this has gotten into a bad enough state that it can't be repaired directly and a new PR is likely warranted. :disappointed:

**Comment by gfinocchiaro** [comment]
Ok, I'm going to close this and opening a new one.
Thanks.

**Comment by tianon** [comment]
This PR didn't actually get closed. :smile:

The new PR (https://github.com/docker-library/official-images/pull/4658) looks good though. :+1:

(For future PRs, I would recommend not using your fork's `master` branch and instead creating a topical branch based on the latest from https://github.com/docker-library/official-images's `master` branch.  https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github appears to have some decent tips on that sort of thing.)

**Pull request closed without merging**
