### PR TITLE
Add "Table of Contents" of README.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Let's improve the README.md readability by adding "Table of Contents" so that we don't need to scroll down and up.

### CODE REVIEW

**Comment by yosifkit** [comment]
This is a great idea, but I'd like to ensure it doesn't get out of sync with any changes in the future.  We'll need to add this to an automated task. Did you use a specific tool to generate this?

**Comment by PeterDaveHello** [comment]
Can use https://npmjs.com/package/doctoc but will need nodejs, acceptable?

**Comment by PeterDaveHello** [comment]
@yosifkit would you like me to integrate with `doctoc`? Thanks.

**Comment by PeterDaveHello** [comment]
@yosifkit ?

**Comment by yosifkit** [comment]
Sorry for the long tail, I don't often take time for non-image related issues.  I'd rather not add a dependency on a new language (even though it could just be dropped into another docker image).  I did look at https://github.com/ekalinin/github-markdown-toc, but it could quickly exhaust github api limits.

Given that we always use `#` style headers we don't need a full markdown parser; I think we could whip up something that would generate it with just bash and awk.

**Comment by PeterDaveHello** [comment]
Oops, was doing it, never mind.

**Pull request closed without merging**
