### PR TITLE
Plone: Fix zeo shared blob env

### PR DESCRIPTION
**Pull request by avoinea**
Refs https://github.com/plone/plone.docker/pull/167

### CODE REVIEW

**Comment by tianon** [comment]
Just to be clear, this change is needed for those two older tags too? (Looking at https://github.com/docker-library/official-images/pull/11795, it appears you're up to three concurrent versions only temporarily? :sweat_smile:)

Also, that CI failure is a little weird -- it appears there's some extra unexpected whitespace in the output?  Do you think that's just a fluke that we should restart for, or something the test needs to be updated for?

**Comment by avoinea** [comment]
> Just to be clear, this change is needed for those two older tags too? (Looking at #11795, it appears you're up to three concurrent versions only temporarily? sweat_smile)

True, we can skip the older tags.

> Also, that CI failure is a little weird -- it appears there's some extra unexpected whitespace in the output? Do you think that's just a fluke that we should restart for, or something the test needs to be updated for?

It seems a thing. I'll look into it :wink:

**Comment by tianon** [comment]
It's probably been a minute since we shared our standard "copypasta" about older tags with you, so just for reference/reminder:

> Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

:+1:

**Comment by tianon** [comment]
Hopefully https://www.githubstatus.com/incidents/fpk08rxnqjz2 is resolved soon :see_no_evil:

**Comment by tianon** [comment]
(Rebased to trigger GitHub Actions :+1:)

**Pull request merged**
