### PR TITLE
Fix spurious "bad file descriptor" errors in bashbrew by using "exec.Cmd" objects more appropriately while streaming

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
GREEN CI YAY

**Comment by nathanleclaire** [comment]
You know the saying -- "If you're going to vendor a @paultag lib, might as well vendor it all"

**Comment by yosifkit** [comment]
LGTM

**Comment by paultag** [comment]
Bwahahahaha

**Pull request merged**
