### PR TITLE
Add latest-modular tag to be used like the 'latest' one

### PR DESCRIPTION
**Pull request by Fale**

### CODE REVIEW

**Comment by tianon** [comment]
This is alright, but should simply be `modular`, not `latest-modular` (see https://github.com/docker-library/official-images#tags-and-aliases).

cc @maxamillion @puiterwijk (`fedora` image maintainers)

**Comment by Fale** [comment]
Thanks tianon! Fixed it as for the reference

**Comment by maxamillion** [comment]
@tianon +1 from me, I'm good with the change.

**Comment by tianon** [comment]
Thanks for confirming @maxamillion :+1:

LGTM

<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-list b/_bashbrew-list
index bf3471a..c55e02d 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -2,4 +2,5 @@ fedora:25
 fedora:26
 fedora:26-modular
 fedora:latest
+fedora:modular
 fedora:rawhide
````

</details>

**Pull request merged**
