### PR TITLE
Add infinit.

### PR DESCRIPTION
**Pull request by Dimrok**
We wish to add Infinit to the list of official images.
The Git repostitory associated is [https://github.com/infinit/infinit-docker](https://github.com/infinit/infinit-docker), the upstream of the project (which is still closed-source) can be found here [https://github.com/infinit/infinit](https://github.com/infinit/infinit) and is, by definition, empty.

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream ?
    - https://github.com/infinit
-	[x] does it fit into one of the common categories? ("service", "language stack", "base distribution")
    - distributed file system service
-	[ ] is it reasonably popular, or does it solve a particular use case well?
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/issues/919
-	[x] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[x] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
    - downloads pre-compiled release binaries/packages from upstream
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tianon** [comment]
This looks pretty good to me -- I think @yosifkit might have had some questions on the docs/usage, but I think the Dockerization is probably in good shape; @yosifkit?  (shameless ping :heart:)

**Comment by tianon** [comment]
Just to be clear, this is usable as a standalone data store without using the FUSE driver, right?  The FUSE driver is simply a filesystem-based client for accessing an existing storage cluster?

**Comment by yosifkit** [comment]
I made some comments in the docs PR (https://github.com/docker-library/docs/pull/919#pullrequestreview-49357814).

**Comment by yosifkit** [comment]
Closing given absence of progress. We apologize for the delays with our responses. :bowing_man: Not to excuse our slow or missing replies, we often have to prioritize maintaining the current images over adding new images. Thanks for your contribution.

If you'd still like to propose a new image, let us know here and we'll try to help it move along. If you've since moved on to other endeavors, we wish you the best. :heart:

**Comment by HazCod** [comment]
@yosifkit Is there any official news about this?
[People are starting to get worried about infinit.](https://www.reddit.com/r/docker/comments/an8h51/whatever_happened_to_infinit_distributed_storage/)

**Comment by tianon** [comment]
Sorry, we don't have any insight there (we're an external team).

**Pull request closed without merging**
