### PR TITLE
Release of GeoNetwork v3.10.7 and v3.12.1

### PR DESCRIPTION
**Pull request by juanluisrp**

### CODE REVIEW

**Comment by yosifkit** [comment]
I am a bit confused by the addition of a `SHELL` of `bash` with `pipefail`. I'm not certain what failure case this is trying to catch since the only pipe is an `echo | md5sum`. This will be inherited (likely unexpectedly) by any users building an image `FROM geonetwork`.

**Comment by juanluisrp** [comment]
I was just trying to remove [this warning](
https://github.com/hadolint/hadolint/wiki/DL4006), but I can revert the
`SHELL` command if you think it isn't needed.

**Comment by tianon** [comment]
Yeah, it doesn't appear to be necessary, and it does have potential for
breaking users since it persists and is inherited.

**Comment by juanluisrp** [comment]
I've removed the `SHELL` with `pipefail` from the `Dockerfile` files

**Pull request merged**
