### PR TITLE
[nats] Adding Windows variants

### PR DESCRIPTION
**Pull request by kozlovic**
This PR is following the work done by @sixeyed
on this [PR](https://github.com/nats-io/nats-docker/pull/5)

### CODE REVIEW

**Comment by kozlovic** [comment]
@tianon @yosifkit By the way, assuming that this PR is ok and merged, is the doc's README.md (https://github.com/docker-library/docs/tree/master/nats) automatically regenerated to update the valid tags without me submitting a PR (I have nothing to change in content.md though)?

**Comment by yosifkit** [comment]
Yeah, it will get updated with links to the new windows versions.

```diff
diff --git a/nats_nanoserver/Dockerfile b/nats_nanoserver/Dockerfile
new file mode 100644
index 0000000..043563a
--- /dev/null
+++ b/nats_nanoserver/Dockerfile
@@ -0,0 +1,20 @@
+# escape=`
+FROM microsoft/nanoserver
+SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
+
+ENV NATS_VERSION="v0.9.6"
+
+# Download and expand released version
+RUN Invoke-WebRequest -OutFile gnatsd.zip "https://github.com/nats-io/gnatsd/releases/download/$($env:NATS_VERSION)/gnatsd-$($env:NATS_VERSION)-windows-amd64.zip" -UseBasicParsing ; `
+    Expand-Archive gnatsd.zip -DestinationPath C:\ ; `
+    Move-Item "C:/gnatsd-$($env:NATS_VERSION)-windows-amd64" 'c:/gnatsd'; `
+    Remove-Item gnatsd.zip
+
+WORKDIR c:/gnatsd
+COPY gnatsd.conf gnatsd.conf
+
+# Expose client, management, and cluster ports
+EXPOSE 4222 8222 6222
+
+ENTRYPOINT ["gnatsd"]
+CMD ["-c", "gnatsd.conf"]
diff --git a/nats_latest/gnatsd.conf b/nats_nanoserver/gnatsd.conf
similarity index 100%
copy from nats_latest/gnatsd.conf
copy to nats_nanoserver/gnatsd.conf
diff --git a/nats_windowsservercore/Dockerfile b/nats_windowsservercore/Dockerfile
new file mode 100644
index 0000000..b904e1f
--- /dev/null
+++ b/nats_windowsservercore/Dockerfile
@@ -0,0 +1,20 @@
+# escape=`
+FROM microsoft/windowsservercore
+SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
+
+ENV NATS_VERSION="v0.9.6"
+
+# Download and expand released version
+RUN Invoke-WebRequest -OutFile gnatsd.zip "https://github.com/nats-io/gnatsd/releases/download/$($env:NATS_VERSION)/gnatsd-$($env:NATS_VERSION)-windows-amd64.zip" -UseBasicParsing ; `
+    Expand-Archive gnatsd.zip -DestinationPath C:\ ; `
+    Move-Item "C:/gnatsd-$($env:NATS_VERSION)-windows-amd64" 'c:/gnatsd'; `
+    Remove-Item gnatsd.zip
+
+WORKDIR c:/gnatsd
+COPY gnatsd.conf gnatsd.conf
+
+# Expose client, management, and cluster ports
+EXPOSE 4222 8222 6222
+
+ENTRYPOINT ["gnatsd"]
+CMD ["-c", "gnatsd.conf"]
diff --git a/nats_latest/gnatsd.conf b/nats_windowsservercore/gnatsd.conf
similarity index 100%
copy from nats_latest/gnatsd.conf
copy to nats_windowsservercore/gnatsd.conf
```

**Comment by tianon** [comment]
```console
$ bashbrew build 2>/dev/null https://github.com/nats-io/official-images/raw/master/library/nats
Building bashbrew/cache:b7995fc972fef835a780fabc392434c1f1957c48ebf1a03b2c1ba3d2d7b341d6 (nats:0.9.6-nanoserver)
Tagging nats:0.9.6-nanoserver
Tagging nats:nanoserver
Building bashbrew/cache:bbd022367e3c917dfdddad4ea68b62bc31ceba1cfcade9d8728c9360762127f2 (nats:0.9.6-windowsservercore)
Tagging nats:0.9.6-windowsservercore
Tagging nats:windowsservercore
```

The image builds successfully, although I just realized this new image isn't `FROM scratch`, so that `ENTRYPOINT` goes a bit afoul of https://github.com/docker-library/official-images#consistency. :disappointed:

However, I don't think Windows (either PowerShell _or_ `cmd`) has a concept of the POSIX `exec`, so I don't think we can really enforce an entrypoint script, and might have to just adapt our current `scratch` exception to also apply to Windows-based images. :cry:

(In summary, this is fine for now and we'll give you a prod if we figure out a solution in the future.)

**Comment by kozlovic** [comment]
@tianon Ok thanks!

**Pull request merged**
