### PR TITLE
rebar3 3.12.0, erlang/otp 21.3.8.7, erlang/otp 22.1

### PR DESCRIPTION
**Pull request by getong**
erlang/docker-erlang-otp#241  erlang/docker-erlang-otp#242

### CODE REVIEW

**Comment by getong** [comment]
How about I change the dockerfile like below:
```
-LABEL otp.version=$OTP_VERSION
-LABEL rebar3.version=$REBAR3_VERSION
+LABEL org.opencontainers.image.version=$OTP_VERSION \
+ rebar3.version=$REBAR3_VERSION
```
@yosifkit

**Comment by getong** [comment]
How do you think of this:
```
LABEL org.opencontainers.image.version=$OTP_VERSION \
 rebar3.version=$REBAR3_VERSION \
 alpine.version=3.10
```
If no problem, I will merge the erlang/docker-erlang-otp#234 and update this pr.
@tianon  @yosifkit

**Comment by tianon** [comment]
`org.opencontainers.image.version=$OTP_VERSION` is fine, but both of `rebar3.version=$REBAR3_VERSION` and `alpine.version=3.10` are not compliant with the OCI standard (reverse DNS syntax).

What's the intended goal of these labels?  Is there a particular product that's looking for / consuming them?

**Comment by tianon** [comment]
(In my experience, human-maintained metadata like labels is a poor replacement for real image introspection, especially because it has a tendency to be inaccurate or out of date.)

**Comment by tsloughter** [comment]
The labels are set to the same variables used to install the software that they are the version for. Meaning they can not be out of date, they will be in sync with whatever is installed in that image.

The added labels are meant to make it easier to know what version of tools (like rebar3) is included in the image. I don't know how this would be done with inspecting the image besides running it and calling `rebar3 version`.

The only other option I know of would be to include all versions in the tag, resulting in `erlang:22.1-3.10-3.12`.

**Comment by tianon** [comment]
If the point is introspection, why not introspect the environment variables directly? (which are as accessible as labels, and are extracted in exactly the same way, just under a different key)

```console
$ docker image inspect --format '{{- range .Config.Env -}}{{- . -}}{{- "\n" -}}{{- end -}}' erlang
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OTP_VERSION=22.0.7
REBAR_VERSION=2.6.4
REBAR3_VERSION=3.11.1
```

**Comment by getong** [comment]
@tsloughter If you agree, I will update the  erlang/docker-erlang-otp#243 , and then update this pr.

**Comment by tsloughter** [comment]
Yea, that is fine.

**Pull request closed without merging**
