### PR TITLE
Update Ubuntu September 2020

### PR DESCRIPTION
**Pull request by philroche**

### CODE REVIEW

**Comment by tianon** [comment]
This should probably be regenerated to account for https://github.com/tianon/docker-brew-ubuntu-core/pull/187 :innocent: (cc @mwhudson)

**Comment by philroche** [comment]
@tianon Images and were built and official-images update generated after https://github.com/tianon/docker-brew-ubuntu-core/pull/187 PR merge

**Comment by philroche** [comment]
Converted to draft until I understand @tianon's request.

**Comment by yosifkit** [comment]
Generated Dockerfiles referenced by this PR, like [amd64](https://github.com/tianon/docker-brew-ubuntu-core/blob/388819d55fb76130ebada339583524096a038c2e/bionic/Dockerfile), don't reflect the change from https://github.com/tianon/docker-brew-ubuntu-core/pull/187 (likely because it was merged after the Jenkins job was complete).

**Comment by philroche** [comment]
@tianon @yosifkit request understood and new PR created @ https://github.com/docker-library/official-images/pull/8730

**Pull request closed without merging**
