### PR TITLE
[security] Update Node.js for November 2018 security releases

### PR DESCRIPTION
**Pull request by rvagg**
* 6.15.0
* 8.14.0
* 10.14.0
* 11.3.0

Ref: https://nodejs.org/en/blog/vulnerability/november-2018-security-releases/

ping @yosifkit & @tianon

### CODE REVIEW

**Comment by tianon** [comment]
(Just to thread the needle -- Travis is failing here because https://github.com/nodejs/docker-node/pull/938 isn't merged yet.)

**Comment by rvagg** [comment]
nodejs/docker-node#938 merged now

**Comment by yosifkit** [comment]
Waiting on https://github.com/nodejs/docker-node/pull/939

**Comment by SimenB** [comment]
#5116

**Comment by larister** [comment]
Thanks for all the work on this. Any ideas why the check is still failing? Looks like conflict resolution is needed...

**Comment by SimenB** [comment]
@larister conflict because #5116 has been merged, the updated images are available as soon as the build completes

**Comment by larister** [comment]
Ok thanks @SimenB; forgive me ignorance but which build are you talking about? The one triggered by #5116 has already completed a while ago but I still can't seem to build `FROM node:8.14.0`

**Comment by SimenB** [comment]
https://doi-janky.infosiftr.net/job/multiarch/view/images/view/node/

**Comment by tianon** [comment]
Closing given https://github.com/docker-library/official-images/pull/5116 (which replaced this).

**Pull request closed without merging**
