### PR TITLE
caddy: v2.7.5 release

### PR DESCRIPTION
**Pull request by hairyhenderson**
https://github.com/caddyserver/caddy/releases/tag/v2.7.5

### CODE REVIEW

**Comment by francislavoie** [comment]
From https://github.com/docker-library/official-images/actions/runs/6489066259/job/17622689391?pr=15525 :thinking: what the heck:
```
# github.com/docker-library/bashbrew/cmd/bashbrew
C:\hostedtoolcache\windows\go\1.18.10\x64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2040567454\000008.o: in function `_cgo_preinit_init':
\\_\_\runtime\cgo/gcc_libinit_windows.c:30: undefined reference to `__imp___iob_func'
C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2040567454\000008.o: in function `x_cgo_sys_thread_create':
\\_\_\runtime\cgo/gcc_libinit_windows.c:60: undefined reference to `__imp___iob_func'
C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2040567454\000008.o: in function `x_cgo_notify_runtime_init_done':
\\_\_\runtime\cgo/gcc_libinit_windows.c:101: undefined reference to `__imp___iob_func'
C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2040567454\000009.o: in function `x_cgo_thread_start':
\\_\_\runtime\cgo/gcc_util.c:18: undefined reference to `__imp___iob_func'
C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-2040567454\000010.o: in function `_cgo_sys_thread_start':
\\_\_\runtime\cgo/gcc_windows_amd64.c:31: undefined reference to `__imp___iob_func'
collect2.exe: error: ld returned 1 exit status
```

**Comment by yosifkit** [comment]
😞 Don't worry about those go `github.com/docker-library/bashbrew/cmd/bashbrew` windows failures. I've made a fix, but haven't gotten a release with the changes done yet.

**Review by yosifkit — APPROVED** [review]

**Comment by francislavoie** [comment]
@yosifkit just wondering, 3 weeks ago you wrote that the build queue is very full https://github.com/docker-library/official-images/issues/15404#issuecomment-1728270522 due to a debian update. Is that still the case today? It seems like the Caddy release for amd64 has still not been built, and we have users complaining about that (and explaining to them that it's out of our control is hard for some of them to hear). Just want to know if there's anything we can do to push this along or if we just need to continue being patient. Is the build queue stuck on something that might need to be cancelled to let the rest continue, etc?

**Comment by yosifkit** [comment]
Yeah, you happened to hit the Debian rebuild timing again (https://github.com/docker-library/official-images/pull/15508). I've pushed the queued architecture-specific caddy builds to the front of the queue, so they'll build next.

**Comment by francislavoie** [comment]
Thank you 🙏

**Pull request merged**
