### PR TITLE
erlang/otp 23.2.2

### PR DESCRIPTION
**Pull request by getong**
erlang/docker-erlang-otp#323 , erlang/docker-erlang-otp#322

### CODE REVIEW

**Comment by yosifkit** [comment]
Alpine 3.9 is no longer supported (https://github.com/docker-library/official-images/pull/9424#issuecomment-760584591), so any images based on them need to be updated to a newer Alpine or dropped.

**Comment by tianon** [comment]
You might also be interested in https://github.com/erlang/otp/pull/2954, which is now part of 23.2.3, 22.3.4.15, and 21.3.8.19. :partying_face: :smile:

**Comment by getong** [comment]
The erlang/otp 21 branch can not be compiled under alpine docker image due to the erlang/otp#2693.
Just wait for this to be merged into erlang 21 branch. 
Also see erlang/docker-erlang-otp#322

**Comment by getong** [comment]
@yosifkit @tianon 
The pr is ready to be merged.

**Pull request merged**
