### PR TITLE
Update for Ubuntu Jammy 22.04 LTS release

### PR DESCRIPTION
**Pull request by woky**
Also update other suites with latest release.

### CODE REVIEW

**Comment by toabctl** [comment]
LGTM. Thanks!

**Comment by toabctl** [comment]
@tianon please merge this one. TIA

**Comment by darkdragon-001** [comment]
Probably someone first needs to run the workflow and scripts in the other repository in order to produce up to date tarballs if I read the [README](https://github.com/tianon/docker-brew-ubuntu-core#scripts-to-prepare-updates-to-the-ubuntu-official-docker-images) correctly?

**Comment by woky** [comment]
@darkdragon-001 The tarballs are already committed, see https://github.com/tianon/docker-brew-ubuntu-core/actions/runs/2202118654. This library file is generated from the committed tarballs.

**Comment by heliocastro** [comment]
Hi. This new image is not updated on docker main registry ?

**Comment by woky** [comment]
> Hi. This new image is not updated on docker main registry ?

Hello @heliocastro. We update Ubuntu images on Docker Hub monthly. I'm going to submit next update this week, hopefully today. You should still be able to pull `kinetic` from this update.

**Comment by heliocastro** [comment]
@woky Thanks. I just checked today, and seen like is not there yet.
Anyway, i will need wait for this then wait for maven images be updated on topf of it

**Pull request merged**
