### PR TITLE
Official Convertigo 8.3.1 release

### PR DESCRIPTION
**Pull request by nicolas-albert**
Thx!

### CODE REVIEW

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
Oh no :sob: :joy: :heart:

```console
Step 13/20 : RUN export GNUPGHOME="$(mktemp -d)"     && ( gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$CONVERTIGO_GPG_KEYS"     || gpg --batch --keyserver keyserver.pgp.com --recv-keys "$CONVERTIGO_GPG_KEYS" )     && curl -fSL -o /tmp/convertigo.war $CONVERTIGO_WAR_URL     && curl -fSL -o /tmp/convertigo.war.asc $CONVERTIGO_WAR_URL.asc     && gpg --batch --verify /tmp/convertigo.war.asc /tmp/convertigo.war     && mkdir -p webapps/ROOT webapps/convertigo     && mkdir /certs && chmod 777 /certs     && (cd webapps/convertigo         && unzip -q /tmp/convertigo.war         && chmod 777 WEB-INF/web.xml WEB-INF/lib WEB-INF/classes         && rm -rf /tmp/*)
 ---> Running in 350ac108326c
gpg: keybox '/tmp/tmp.0HhbyUG0mK/pubring.kbx' created
gpg: /tmp/tmp.0HhbyUG0mK/trustdb.gpg: trustdb created
gpg: key D4DA8FBEB64BF75F: public key "Convertigo (mBaaS and Enterprise Mobility Platform) <info@convertigo.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
 ---> Removed intermediate container 350ac108326c
The command '/bin/sh -c export GNUPGHOME="$(mktemp -d)"     && ( gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$CONVERTIGO_GPG_KEYS"     || gpg --batch --keyserver keyserver.pgp.com --recv-keys "$CONVERTIGO_GPG_KEYS" )     && curl -fSL -o /tmp/convertigo.war $CONVERTIGO_WAR_URL     && curl -fSL -o /tmp/convertigo.war.asc $CONVERTIGO_WAR_URL.asc     && gpg --batch --verify /tmp/convertigo.war.asc /tmp/convertigo.war     && mkdir -p webapps/ROOT webapps/convertigo     && mkdir /certs && chmod 777 /certs     && (cd webapps/convertigo         && unzip -q /tmp/convertigo.war         && chmod 777 WEB-INF/web.xml WEB-INF/lib WEB-INF/classes         && rm -rf /tmp/*)' returned a non-zero code: 22
```

**Comment by nicolas-albert** [comment]
Nightmare, the release was published with -beta ...
I think I have to relaunch it!

**Comment by tianon** [comment]
Just to be clear, you need the CI here restarted, or you need to do more upstream work (re-release, etc)? :bow:

**Comment by nicolas-albert** [comment]
It should be good now.
Files exist now:
https://github.com/convertigo/convertigo/releases/download/8.3.1/convertigo-8.3.1.war
https://github.com/convertigo/convertigo/releases/download/8.3.1/convertigo-8.3.1.war.asc

(was 8.3.1/convertigo-8.3.1-beta.war due to a mistake)

I have prepared the **build.gradle** to release (8.3.1-beta -> 8.3.1), make and push the tag then the CI push the release on GitHub. I realized the **build.gradle** wasn't commit ... so I retag, double release on GitHub and ... delete the good release and let the `-beta`!

Sad story 😭 

Thx you again for your work 🙏

**Pull request merged**
