### PR TITLE
Adding Couchbase Server EE 6.6.3

### PR DESCRIPTION
**Pull request by ceejatec**

### CODE REVIEW

**Comment by yosifkit** [comment]
Both `community-6.6.0` and `6.6.3` also fail to build locally (Debian Bullseye host, docker 20.10.8)

```console
+ apt-get install -y ./couchbase-server-community_6.6.0-ubuntu18.04_amd64.deb
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  couchbase-server-community
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/209 MB of archives.
After this operation, 541 MB of additional disk space will be used.
Get:1 /couchbase-server-community_6.6.0-ubuntu18.04_amd64.deb couchbase-server-community amd64 6.6.0-7909-1 [209 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package couchbase-server-community.
(Reading database ... 7204 files and directories currently installed.)
Preparing to unpack .../couchbase-server-community_6.6.0-ubuntu18.04_amd64.deb ...
Warning: Transparent hugepages looks to be active and should not be.
Please look at https://developer.couchbase.com/documentation/server/current/install/thp-disable.html as for how to PERMANENTLY alter this setting.
Warning: Swappiness is not set to 0.
Please look at https://developer.couchbase.com/documentation/server/current/install/install-swap-space.html as for how to PERMANENTLY alter this setting.
Minimum RAM required  : 4 GB
System RAM configured : 62.45 GB

Minimum number of processors required : 4 cores
Number of processors on the system    : 16 cores
Unpacking couchbase-server-community (6.6.0-7909-1) ...
Setting up couchbase-server-community (6.6.0-7909-1) ...
/opt/couchbase/bin/install/systemd-ctl: line 26: systemctl: command not found
dpkg: error processing package couchbase-server-community (--configure):
 installed couchbase-server-community package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 couchbase-server-community
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
```console
+ apt-get install -y ./couchbase-server-enterprise_6.6.3-ubuntu20.04_amd64.deb
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  couchbase-server
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 0 B/359 MB of archives.
After this operation, 898 MB of additional disk space will be used.
Get:1 /couchbase-server-enterprise_6.6.3-ubuntu20.04_amd64.deb couchbase-server amd64 6.6.3-9808-1 [359 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package couchbase-server.
(Reading database ... 6748 files and directories currently installed.)
Preparing to unpack .../couchbase-server-enterprise_6.6.3-ubuntu20.04_amd64.deb ...
Warning: Transparent hugepages looks to be active and should not be.
Please look at https://docs.couchbase.com/server/6.6/install/thp-disable.html as for how to PERMANENTLY alter this setting.
Warning: Swappiness is not set to 0.
Please look at https://docs.couchbase.com/server/6.6/install/install-swap-space.html as for how to PERMANENTLY alter this setting.
Minimum RAM required  : 4 GB
System RAM configured : 62.45 GB

Minimum number of processors required : 4 cores
Number of processors on the system    : 16 cores
Unpacking couchbase-server (6.6.3-9808-1) ...
Setting up couchbase-server (6.6.3-9808-1) ...
/opt/couchbase/bin/install/systemd-ctl: line 26: systemctl: command not found
dpkg: error processing package couchbase-server (--configure):
 installed couchbase-server package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 couchbase-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ceejatec** [comment]
It's the same issue we've had with Docker detection when running in GitHub actions. It's fixed in our 7.x releases but the 6.x line still has it. The images build and run fine in a normal Docker environment.

**Comment by tianon** [comment]
That's what @yosifkit is contesting though -- he tried a build test in his _local_ environment and it failed with that output. :confused:

I did a build test on a server that's roughly the same as what the official server will build on and it succeeded, so I guess we can keep rolling the dice here, but @yosifkit's local isn't _that_ much further updated from our official build environments, meaning this is potentially something that will bite them eventually too (especially given that Bullseye is going to be officially released this weekend, so updating our infra to it will be officially on the TODO list, although it won't happen right away), so if the 6.x series is going to continue to be maintained/supported, I'd strongly recommend backporting whatever the fix for 7.x was. :grimacing:

---

Build test of #10708; 94d024de0; `amd64` (`couchbase:6.6.3`):

```console

$ bashbrew build couchbase:6.6.3
Building bashbrew/cache:babb0392d0637de5c8e33d7a5d5dee58c250b5f60ad924e168980e3f433fde18 (couchbase:6.6.3)
Tagging couchbase:6.6.3
Tagging couchbase:enterprise-6.6.3

$ test/run.sh couchbase:6.6.3
testing couchbase:6.6.3
	'utc' [1/3]...passed
	'no-hard-coded-passwords' [2/3]...passed
	'override-cmd' [3/3]...passed

```

**Comment by ceejatec** [comment]
Thanks for the merge. I will see if I can merge it back for 6.6.4. I can't update any already-released versions, like 6.0.0, but if I don't update the git commit in the library/couchbase file for those versions then you shouldn't need to rebuild them anymore, correct?

Although, I guess you do rebuild official images when the base Ubuntu image is updated, right? Hmm, I guess that may be a problem for us in future if your infrastructure changes sufficiently...

**Comment by tianon** [comment]
Yep -- I'd argue you should probably just drop 6.0.0 from the "supported"
list here if it can't be updated (the tag will remain on Docker Hub, but we
won't try building it anymore and it won't be listed in the image
description).

**Pull request merged**
