### PR TITLE
Update XWiki to 13.10

### PR DESCRIPTION
**Pull request by surli**

### CODE REVIEW

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

(I'd personally just drop the `maintainer` metadata entirely since it's inherited by any image that's `FROM` this one, but it's your call.)

**Comment by tianon** [comment]
I guess I'd also recommend using a tag that's a _little_ more specific than `tomcat:9`, since that one is likely to change things like the JDK version pretty willy-nilly, but that's also up to you. :sweat_smile:

**Comment by vmassol** [comment]
@tianon Thanks for your pieces of advices, much appreciated.

About:

> (I'd personally just drop the maintainer metadata entirely since it's inherited by any image that's FROM this one, but it's your call.)

I'm not sure I understand. I wanted to let users of the xwiki docker image know who are the maintainers. If I remove this metadata, how can anyone find that info by looking at the docker image?

Thanks

**Comment by vmassol** [comment]
@tianon I had replaced the `MAINTAINER` command by a `LABEL`  one because the former is deprecated https://docs.docker.com/engine/reference/builder/#maintainer-deprecated and the recommendation is to use a `LABEL`.

I couldn't find what `We don't actively recommend using labels` actually means. Could you elaborate and explain what are the problems/consequences of using `LABEL maintainer="XWiki Development Team <committers@xwiki.org>"`?

Thanks a lot

**Comment by yosifkit** [comment]
> Could you elaborate and explain what are the problems/consequences of using `LABEL maintainer="XWiki Development Team <committers@xwiki.org>"`?

The largest drawback is that any user that creates an image `FROM` it inherits all labels so it can incorrectly attribute maintainership to dependent images. This is also true of the `MAINTAINER` instruction. For images we directly maintain, we rely on users knowing where they pulled an image from so that they can find help by looking at the readme content hosted on Docker Hub and GitHub rather that relying on metadata in the image.

The XWiki image is welcome to move from the deprecated `MAINTAINER` Dockerfile instruction to using `LABEL`, but image label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md. I think `org.opencontainers.image.authors` is the equivalent to maintaner.

**Comment by vmassol** [comment]
@yosifkit Thanks a lot for the explanation. I've now updated the LABELs to follow the opencontainers conventions. Waiting for @surli to update this PR with sha1 `1d2ea57cbe91d8eff11f19d1ca8ddd378a3b871b`  for XWiki 13.10.

**Pull request merged**
