### PR TITLE
Update for Node.js 0.10.36

### PR DESCRIPTION
**Pull request by chorrell**

### CODE REVIEW

**Comment by yosifkit** [comment]
Can we squash out that merge commit please?

**Comment by chorrell** [comment]
Shoot. Yeah. Um, what's the best way to do that?

**Comment by tianon** [comment]
I think the easiest one-liner solution will be `git pull --rebase https://github.com/docker-library/official-images.git master` :+1:

**Comment by chorrell** [comment]
Hmm, that seem to do what I expected...

**Comment by tianon** [comment]
```console
$ git clone -b master https://github.com/chorrell/official-images.git
Cloning into 'official-images'...
remote: Counting objects: 2966, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 2966 (delta 9), reused 0 (delta 0)
Receiving objects: 100% (2966/2966), 455.39 KiB | 404.00 KiB/s, done.
Resolving deltas: 100% (1706/1706), done.
Checking connectivity... done.
$ cd official-images/
$ git pull --rebase https://github.com/docker-library/official-images.git master
From https://github.com/docker-library/official-images
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: update for Node.js 0.10.36
Applying: update for Node.js 0.10.36
Using index info to reconstruct a base tree...
M	library/node
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
$ git log # only one extra commit shown here
$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 4 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean
```

**Comment by tianon** [comment]
(and then `git push -f`, of course, but I can't do that on your fork's `master` :wink:)

**Comment by chorrell** [comment]
Done.

**Comment by yosifkit** [comment]
LGTM. Build test of #426; 283eb833c8eb56b83d00732499c7487b1f96752e (`node`):

```console
$ ./bashbrew/bashbrew.sh build https://raw.githubusercontent.com/docker-library/official-images/283eb833c8eb56b83d00732499c7487b1f96752e/library/node
Fetching node (git://github.com/joyent/docker-node) ...
Processing node:0.10.36 ...
Processing node:0.10 ...
Processing node:0 ...
Processing node:latest ...
Processing node:0.10.36-onbuild ...
Processing node:0.10-onbuild ...
Processing node:0-onbuild ...
Processing node:onbuild ...
Processing node:0.10.36-slim ...
Processing node:0.10-slim ...
Processing node:0-slim ...
Processing node:slim ...
Processing node:0.11.15 ...
Processing node:0.11 ...
Processing node:0.11.15-onbuild ...
Processing node:0.11-onbuild ...
Processing node:0.11.15-slim ...
Processing node:0.11-slim ...
Processing node:0.8.28 ...
Processing node:0.8 ...
Processing node:0.8.28-onbuild ...
Processing node:0.8-onbuild ...
Processing node:0.8.28-slim ...
Processing node:0.8-slim ...
```

**Comment by tianon** [comment]
LGTM

**Pull request merged**
