### PR TITLE
[nats-streaming] Release v0.25.2

### PR DESCRIPTION
**Pull request by kozlovic**
Details can be found [here](https://github.com/nats-io/nats-streaming-server/releases/tag/v0.25.2)

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
Doc PR: https://github.com/docker-library/docs/pull/2217

**Comment by yosifkit** [comment]
It looks like the image is called `-alpine3.16`, but the Dockerfile still seems to be `FROM alpine:3.15`.

**Comment by kozlovic** [comment]
@yosifkit Thank you so much! I was replacing occurrences of alpine3.15 to 3.16, but obviously missed the `FROM` one. I need to update the repo and will update this PR and push force. Is that ok or you prefer closing this PR and me making a new one?

**Comment by kozlovic** [comment]
@yosifkit I have updated and force-pushed the changes. Thank you again for catching this error!

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
