### PR TITLE
erlang 19.3.6.6

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by c0b** [comment]
hold on this one before I fix the generate-stackbrew-library.sh
https://github.com/docker-library/official-images/pull/3957#issuecomment-370173068

**Comment by c0b** [comment]
@getong you don't have to wait if you could manually add the `arm64v8, i386, s390x, ppc64le` back for 20-alpine
 from https://github.com/docker-library/official-images/pull/4009/files#diff-c9976a31b54be88c19792313c6647e6eL17

while I am fixing the generate-stackbrew-library.sh today.

**Comment by c0b** [comment]
the new script generate a diff like this:

```diff
--- ./library/erlang	2018-03-01 20:47:17.826621629 -0800
+++ ./library/erlang.new	2018-03-03 15:18:14.786302946 -0800
@@ -14,18 +14,18 @@ GitCommit: 83a747afba739592bb4d3f8a01b5d
 Directory: 20/slim
 
 Tags: 20.2.4-alpine, 20.2-alpine, 20-alpine, alpine
-Architectures: amd64
+Architectures: amd64, arm64v8, i386, s390x, ppc64le
 GitCommit: 83a747afba739592bb4d3f8a01b5d535c1f2c8dd
 Directory: 20/alpine
 
-Tags: 19.3.6.5, 19.3.6, 19.3, 19
+Tags: 19.3.6.6, 19.3.6, 19.3, 19
 Architectures: amd64, arm32v7, arm64v8, i386, s390x
-GitCommit: f6606389b995d24dce8933e4ca4d6d46fce8612b
+GitCommit: bede8199e3263e936687542a0492774b3512296a
 Directory: 19
 
-Tags: 19.3.6.5-slim, 19.3.6-slim, 19.3-slim, 19-slim
+Tags: 19.3.6.6-slim, 19.3.6-slim, 19.3-slim, 19-slim
 Architectures: amd64, arm32v7, arm64v8, i386, s390x
-GitCommit: 6e2088d493e6f50b82c0e416c72a2dd914e84fd2
+GitCommit: bede8199e3263e936687542a0492774b3512296a
 Directory: 19/slim
 
 Tags: 18.3.4.7, 18.3.4, 18.3, 18
```

**Comment by getong** [comment]
@c0b I will look at it later today or tomorrow

**Comment by c0b** [comment]
if you haven't done so, may be ok to give up this one;  I'll open another PR to include c0b/docker-erlang-otp#108 together

**Comment by getong** [comment]
erlang 18.3.4.8 is released, you can open a new pr with this too. @c0b

**Pull request closed without merging**
