### PR TITLE
[oraclelinux]: Release Oracle Linux 9

### PR DESCRIPTION
**Pull request by amsteinb-orcl**
https://docs.oracle.com/en/operating-systems/oracle-linux/9/index.html
Signed-off-by: Alan Steinberg <alan.steinberg@oracle.com>

### CODE REVIEW

**Comment by amsteinb-orcl** [comment]
Can someone explain what the Diff Comment failure means and how it was caused?

**Comment by Djelibeybi** [comment]
There is no diff because there was no previous release of `9` or `9-slim`.

@tianon @yosifkit could we get a manual review and merge, please?

**Comment by tianon** [comment]
Yeah, unfortunately there's a limit to comment length, and new major releases typically go over it :sweat_smile:

Diff: https://gist.github.com/docker-library-bot/4314a147736889616aa13a8b8665017b

**Comment by tianon** [comment]
I'm really impressed that even though `systemd` appears to have forced itself into the minimum set (which is totally understandable), the overall image sizes are still pretty respectable!

- `oraclelinux:8`: ~226MB
- `oraclelinux:9`: ~217MB
- `oraclelinux:8-slim`: ~101MB
- `oraclelinux:9-slim`: ~126MB

(I believe it's only `slim` that _didn't_ have `systemd` previously but now does, which makes sense from the image size bump :sweat_smile:)

**Pull request merged**
