### PR TITLE
Add amazonlinux releases

### PR DESCRIPTION
**Pull request by sktomer**
Updated Packages for Amazon Linux 2023:
- python3-libs-3.9.20-1.amzn2023.0.2
- amazon-linux-repo-cdn-2023.6.20241212-0.amzn2023
- system-release-2023.6.20241212-0.amzn2023
- python3-3.9.20-1.amzn2023.0.2

(update other releases to not rely on EOL alpine:3.17)

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
I'm not sure that using the `latest` for alpine is a good idea. It would be better to pin it to 3.21 instead.

**Comment by sktomer** [comment]
I can make that change if you insist. We discussed that it would be low risk and the pre-checks would inform us if anything is broken.

**Comment by tianon** [comment]
Do you mean you have proactive CI that would notice when `:latest` changes and notify you of any breakage?  (as long as you've got that, I think `:latest` is probably mostly OK here)

**Comment by sktomer** [comment]
yes please merge this. also please close this as a duplicate: https://github.com/docker-library/official-images/pull/18139 (the author, my colleague is out of office today).

**Review by tianon — APPROVED** [review]

**Pull request merged**
