### PR TITLE
Add arm32v7 support to Eclipse Mosquitto.

### PR DESCRIPTION
**Pull request by ralight**

### CODE REVIEW

**Comment by yosifkit** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index bd134e6..86f7445 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,5 +1,6 @@
 eclipse-mosquitto:latest @ amd64
 eclipse-mosquitto:latest @ arm32v6
+eclipse-mosquitto:latest @ arm32v7
 eclipse-mosquitto:latest @ arm64v8
 eclipse-mosquitto:latest @ i386
 eclipse-mosquitto:latest @ ppc64le
```

</details>

**Comment by yosifkit** [comment]
Alpine 3.8 doesn't support `arm32v7`. https://github.com/docker-library/official-images/blob/c9ff9d5eff80491ca2594db11bfcd7547d3fa96a/library/alpine#L29

You'll need to update to alpine:3.9 if you want that.

**Comment by ralight** [comment]
Ah, thanks, that'll be why it wasn't there in the first place. I'll see about checking that.

**Comment by tianon** [comment]
Closing for now -- feel free to open a new PR once you get this sorted (perhaps with a bump to Alpine 3.9). :+1:

**Pull request closed without merging**
