### PR TITLE
Update golang to 1.4.1

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Build test of #402; 6f0da1da0f5b52fd966241f15789624ded51f166 (`golang`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/6f0da1da0f5b52fd966241f15789624ded51f166/library/golang
Fetching golang (git://github.com/docker-library/golang) ...
Processing golang:1.3.3 ...
Processing golang:1.3 ...
Processing golang:1.3.3-onbuild ...
Processing golang:1.3-onbuild ...
Processing golang:1.3.3-cross ...
Processing golang:1.3-cross ...
Processing golang:1.3.3-wheezy ...
Processing golang:1.3-wheezy ...
Processing golang:1.4.1 ...
Processing golang:1.4 ...
Processing golang:1 ...
Processing golang:latest ...
Processing golang:1.4.1-onbuild ...
Processing golang:1.4-onbuild ...
Processing golang:1-onbuild ...
Processing golang:onbuild ...
Processing golang:1.4.1-cross ...
Processing golang:1.4-cross ...
Processing golang:1-cross ...
Processing golang:cross ...
Processing golang:1.4.1-wheezy ...
Processing golang:1.4-wheezy ...
Processing golang:1-wheezy ...
Processing golang:wheezy ...
```

**Comment by yosifkit** [comment]
Do we want to hold off on this to get the `buildpack:micro` stuff sorted out so that `golang:1.4.0` can get the changes?

**Comment by tianon** [comment]
Naw, 1.4.1 is such a minor update that everyone should just use it: https://github.com/golang/go/issues?q=milestone%3AGo1.4.1

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
