### PR TITLE
haskell: add 9.6.6 bullseye images

### PR DESCRIPTION
**Pull request by jhrcek**

### CODE REVIEW

**Comment by develop7** [comment]
#17347 :)

**Comment by develop7** [comment]
Closed mine

**Comment by jhrcek** [comment]
You beat me to it :-) but let's keep this one as it introduces more "simplified" tags, the way they were called before, e.g. https://github.com/docker-library/official-images/commit/a826215c0792669249ecdde85c036f450b57c589#diff-9bff1cee7662d0039e3defd259d228fde8ab01e742742e37112eb16fdba76cecL45

**Comment by tianon** [comment]
To answer:

> aarch64 images use deb10 bindists, hope that's not a problem

As long as they work, that seems fine to me! :smile: :heart:

**Review by tianon — APPROVED** [review]

**Comment by develop7** [comment]
> but let's keep this one as it introduces more "simplified" tags

yup yup yup

**Pull request merged**
