### PR TITLE
Add spiped-basics test

### PR DESCRIPTION
**Pull request by TimWolla**
This test is based on the existing haproxy-basics test and [the Travis configuration in the origin repository](https://github.com/TimWolla/docker-spiped/blob/master/.travis.yml).

On my local machine it worked on the first attempt. Something's fishy there. Please carefully review for dumbness.

### CODE REVIEW

**Comment by TimWolla** [comment]
It appears that GH Actions is not terribly happy with a test only PR: https://github.com/docker-library/official-images/actions/runs/184869600 and I also received an email about that.

**Comment by tianon** [comment]
The easy fix would be to make this part of #8439 :sweat_smile:

**Comment by tianon** [comment]
(Then it'll actually test those updates)

**Comment by TimWolla** [comment]
> The easy fix would be to make this part of #8439

I did this now, but I like creating a single PR per distinct change :innocent:

**Pull request closed without merging**
