### PR TITLE
Update mongo to 3.0.3

### PR DESCRIPTION
**Pull request by w0mbat**

### CODE REVIEW

**Comment by tianon** [comment]
Nice!  Would you mind force pushing an amend to your commit that replaces this file with the full output of `./generate-stackbrew-library.sh` from the `mongo` repository so all the references are updated appropriately?

**Comment by w0mbat** [comment]
sure, what do I need to do? Can´t find the `generate-stackbrew-library.sh` file anywhere :/

**Comment by tianon** [comment]
It's in the "mongo" repo:
https://github.com/docker-library/mongo/blob/master/generate-stackbrew-library.sh
(since it uses Git metadata from that repo to generate the proper commits
for here)

:+1:

**Comment by tianon** [comment]
Alternatively, here's what I get when I run it here:
```console
$ ./generate-stackbrew-library.sh
# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)

2.2.7: git://github.com/docker-library/mongo@c9a1b066a0f35f679c2f8e1854a21e025867d938 2.2
2.2: git://github.com/docker-library/mongo@c9a1b066a0f35f679c2f8e1854a21e025867d938 2.2

2.4.14: git://github.com/docker-library/mongo@b7630a1644d934c4c4d57a121e2ca42a50e99c44 2.4
2.4: git://github.com/docker-library/mongo@b7630a1644d934c4c4d57a121e2ca42a50e99c44 2.4

2.6.9: git://github.com/docker-library/mongo@c9a1b066a0f35f679c2f8e1854a21e025867d938 2.6
2.6: git://github.com/docker-library/mongo@c9a1b066a0f35f679c2f8e1854a21e025867d938 2.6
2: git://github.com/docker-library/mongo@c9a1b066a0f35f679c2f8e1854a21e025867d938 2.6

3.0.3: git://github.com/docker-library/mongo@65491bce9f2b6941dbde4ddaf16171dad5fe50d1 3.0
3.0: git://github.com/docker-library/mongo@65491bce9f2b6941dbde4ddaf16171dad5fe50d1 3.0
3: git://github.com/docker-library/mongo@65491bce9f2b6941dbde4ddaf16171dad5fe50d1 3.0
latest: git://github.com/docker-library/mongo@65491bce9f2b6941dbde4ddaf16171dad5fe50d1 3.0
```

**Comment by tianon** [comment]
If you'd prefer, I can take over and make a new PR for this too. :+1:  (we've got several that need updates at this point)

(but if you want the "fame and glory", by all means! :dancer: :fire:)

**Comment by w0mbat** [comment]
Hmm, well it tells me this:

```
./generate-stackbrew-library.sh
./generate-stackbrew-library.sh: line 4: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

So, i´m ok if you would take over ;)

**Pull request closed without merging**
