### PR TITLE
bump kong to 3.7

### PR DESCRIPTION
**Pull request by kikito**

### CODE REVIEW

**Comment by tianon** [comment]
```diff
-      && curl -fL https://download.konghq.com/gateway-${KONG_VERSION%%.*}.x-ubuntu-${UBUNTU_CODENAME}/pool/all/k/kong/kong_${KONG_VERSION}_$arch.deb -o /tmp/kong.deb \
+      && KONG_REPO=$(echo ${KONG_VERSION%.*} | sed 's/\.//') \
+      && curl -fL https://packages.konghq.com/public/gateway-$KONG_REPO/deb/ubuntu/pool/$UBUNTU_CODENAME/main/k/ko/kong_$KONG_VERSION/kong_${KONG_VERSION}_$arch.deb \
```

Looks like this `curl` lost `-o` so it's curling the deb file straight to stdout :sob:

I'd suggest moving the `-o` to the beginning of the command so this is less likely to be missed in the future:

```diff
+      && curl -fL -o /tmp/kong.deb https://packages.konghq.com/public/gateway-$KONG_REPO/deb/ubuntu/pool/$UBUNTU_CODENAME/main/k/ko/kong_$KONG_VERSION/kong_${KONG_VERSION}_$arch.deb \
```

Also, I'd suggest setting up some automated GitHub Actions CI to do a rough smoke test/build before you submit to us so that you can catch things like this sooner. :eyes:

**Comment by tianon** [comment]
One more thought to consider: is 3.3 now EOL, or have I misread? :eyes:

**Comment by kikito** [comment]
Hi, I don't understand how that diff is generated, but it looks incorrect. I have checked both commit [6c5f89989720f9dd97db3a1a1483fe651d990d0a](https://github.com/Kong/docker-kong/commit/6c5f89989720f9dd97db3a1a1483fe651d990d0a) and our [3.7.0 release source code](https://github.com/Kong/docker-kong/releases/tag/3.7.0) and in both the code looks different, like this:

```
      && KONG_REPO=$(echo ${KONG_VERSION%.*} | sed 's/\.//') \
      && DOWNLOAD_URL="https://packages.konghq.com/public/gateway-$KONG_REPO/deb/debian/pool/$CODENAME/main/k/ko/kong_$KONG_VERSION/kong_${KONG_VERSION}_amd64.deb" \
      && curl -fL $DOWNLOAD_URL -o /tmp/kong.deb \
```

The code that appears on the diff seems to belong to an older never-released development branch also called 3.7.0, located here:

https://github.com/Kong/docker-kong/tree/3.7.0

It might be that the script is prioritizing that branch over the tag. I'll delete the branch and retry a push.

If this issue still happens afterwards, we'll have to consider caching issues.

> Also, I'd suggest setting up some automated GitHub Actions CI to do a rough smoke test/build before you submit to us so that you can catch things like this sooner. 👀

Indeed. I am afraid we don't release major versions often enough to justify the investment in time. We do manual tests instead. An automated test would not have caught this on our end I'm afraid.

> One more thought to consider: is 3.3 now EOL, or have I misread?

You are [essentially correct](https://docs.konghq.com/gateway/latest/support-policy/). We just sunsetted support for 3.3 Enterprise Edition. This PR is about the Community / Open Source version of Kong, but it makes sense to align the two. I will remove it on my next push.

**Comment by kikito** [comment]
The diff above still shows the incorrect code. Would it be possible to delete the cache for this PR?

I can also close this pr and open a new one if that helps.

**Comment by LaurentGoderre** [comment]
@kikito looks like it was missed here: https://github.com/Kong/docker-kong/commit/6c5f89989720f9dd97db3a1a1483fe651d990d0a#diff-e304c5deec3cba4179562dff6dccf270afde0ea5fadb12be3c4026d9f666e93aR29-R30

**Comment by kikito** [comment]
@LaurentGoderre my apologies, I did not notice that other Dockerfile hidden inside our ubuntu folder.

We have fixed the missing targetfile option and retagged the 3.7.0 release so that it includes the fix. I have personally tested that ubuntu/Dockerfile doesn't have the problem any more. Let me close this PR and open a new one so that the build is run again.

**Comment by tianon** [comment]
> Let me close this PR and open a new one so that the build is run again.

In the future, please just force push to the existing PR branch -- that will automatically update the PR, and CI will re-run (and if it does not, close and reopen will usually retrigger without issue).  This avoids creating extra noise/cruft for maintainers and their inboxes.

**Pull request closed without merging**
