### PR TITLE
Update Joomla!

### PR DESCRIPTION
**Pull request by Llewellynvdm**
Changes:

- joomla-docker/docker-joomla@6407e1b: Updated all the images with the permission fix.
- joomla-docker/docker-joomla@d90c4f6: Fix [joomla-docker/docker-joomla#174](https://github.com/joomla-docker/docker-joomla/issues/174) to correct the `configuration.php` ownership and permissions.

### CODE REVIEW

**Comment by tianon** [comment]
You'll probably want at _least_ an "are we root?" check around this, like you've got further up in the entrypoint:

```bash
                if [ "$uid" = '0' ] && [ "$(stat -c '%u:%g' .)" = '0:0' ]; then
                        chown "$user:$group" .
                fi
```

You might also want to consider what you'll do if the `chmod` or `chown` fails, since that'll be a common scenario for setups using SELinux (in our experience).

I'm also not sure how we didn't catch it before (I blame long scripts :sweat_smile: :innocent:), but your `$?` check will probably never trigger since the script uses `set -e` -- I would suggest moving whatever command you're testing straight into the `if`, like this:

```bash
if php ...; then
```

**Comment by Llewellynvdm** [comment]
Thank you for your insightful feedback, especially regarding the checks and error handling in the script. I understand your concern about the `$?` check potentially not triggering due to the `set -e` configuration. However, from my testing, it seems that `[ $? -eq 0 ]` does reliably trigger as expected. I believe this might be due to the specific context in which it's used, but I'll revisit this to ensure there's no oversight.

Regarding the file ownership issue, I agree that directly addressing the root cause is more effective. Instead of changing file permissions post-creation, running the PHP command as the intended user seems to be a cleaner solution:

```bash
sudo -u "$user" php installation/joomla.php install "${installJoomlaArgs[@]}"
```

This approach should prevent the configuration file from being created with root ownership in the first place. Of course, I'll be mindful of any security implications and compatibility issues this change might introduce, especially in diverse Docker environments.

I plan to conduct thorough testing on this and would appreciate any additional insights or concerns you might have, particularly regarding compatibility with SELinux or other specific Docker setups. Your experience in these matters is extremely valuable.

Looking forward to your thoughts on this approach.

**Comment by Llewellynvdm** [comment]
Hmm the sudo option is not working for me... painful. I will continue down the initial path with the suggested changes.

**Comment by Llewellynvdm** [comment]
Okay here is what seems to work as expected:
```
if [ "$uid" = '0' ] && [ "$(stat -c '%u:%g' configuration.php)" != "$user:$group" ]; then
    chown "$user:$group" configuration.php
    chmod 444 configuration.php
fi
```
Unless I am still missing something.... I will push out this update, let me know.

**Review by yosifkit — APPROVED** [review]
It all looks good to me!

**Pull request merged**
