### PR TITLE
One commit (per branch) to rule them all. 

### PR DESCRIPTION
**Pull request by Djelibeybi**
This is also to check that we don't fail @tianon's naughty commit automation. Note the tarballs themselves are unchanged from the current publish, so this PR could be closed without merging assuming the commits are all good.

Signed-off-by: Avi Miller <avi.miller@oracle.com>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Seems like there's a possible script issue though: `../naughty-commits.sh: line 47: potentiallyNaughtyCommits[@]: unbound variable`

**Comment by tianon** [comment]
Bahhh, of course Travis uses Bash 4.3 :man_facepalming:

**Comment by tianon** [comment]
Fixed in https://github.com/docker-library/official-images/pull/7460.

**Comment by tianon** [comment]
If you rebase that warning should go away too :smile:

**Comment by Djelibeybi** [comment]
Which warning? And rebase what? The repo now has a single commit per branch, so I'm not sure what else I can do. :D

**Comment by tianon** [comment]
Sorry, I mean rebase this PR against master (we just merged #7460 to fix the Bash 4.3 error you found right away :smile:)

**Comment by Djelibeybi** [comment]
Ugh, I suspect I just stuffed it up. Not sure I rebased properly. 🤦‍♂

**Pull request closed without merging**
