### PR TITLE
alpine: bump alpine 3.18.0 as latest, drop EOL 3.14

### PR DESCRIPTION
**Pull request by ncopa**

### CODE REVIEW

**Comment by yosifkit** [comment]
FYI affected maintainers. `alpine:3.14` is being removed from "Supported Images" since it has reached end of life, so official images `FROM` it need to be updated (like to a newer Alpine release) or should be removed as well.

- `amazoncorretto`: @corretto @lutkerd @benty-amzn @caojoshua @alvdavi @rgithubli @mrserb @Rudometov
- `arangodb`: @fceller @dothebart @KVS85
- `eclipse-mosquitto`: @ralight
- `haxe`: @andyli
- `kapacitor`: @bnpfeife
- `traefik`: @ldez @juliens @rtribotte @mmatur @kevinpollet @tommoulard
- `vault`: @mladlow @calvn @ncabatoff

> Removing an image from the `library/[image]` files will remove it from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding it on the official build server), but the tag will still be available to users who want it.

**Comment by ldez** [comment]
Hello, we will remove [Traefik v1](https://github.com/traefik/traefik-library-image/blob/4434758cf14bbd1ec9511b3f2a37b0a6ce846db6/alpine/Dockerfile) image.

**Comment by KVS85** [comment]
Hello, we moved Alpine to 3.15 for ArangoDB 3.9: https://github.com/docker-library/official-images/pull/14621.

**Comment by ralight** [comment]
eclipse-mosquitto is fixed as per #14645

**Pull request merged**
