### PR TITLE
Bump Rust to 1.72.0

### PR DESCRIPTION
**Pull request by sfackler**

### CODE REVIEW

**Comment by sfackler** [comment]
Oh, should we not be building Trixie images yet?

**Comment by yosifkit** [comment]
We haven't added Trixie to `buildpack-deps` just yet. I can't remember how early we do that since Trixie is still equivalent to `unstable`.

**Comment by kristof-mattei** [comment]
See https://github.com/docker-library/buildpack-deps/pull/149

**Comment by sfackler** [comment]
Updated to remove the trixie images.

**Pull request merged**
