### PR TITLE
Telegraf v1.30.0

### PR DESCRIPTION
**Pull request by powersj**
Thank you! Includes a fix to ensure user provided groups are also passed on.

### CODE REVIEW

**Comment by tianon** [comment]
That `sed` seems really fragile/brittle (very easy for something to go wrong and not notice) :grimacing:

I think I've deducted correctly that https://github.com/influxdata/influxdata-docker/issues/724#issuecomment-1960860373 is the underlying issue it's solving? (`--user root:something` and wanting to keep `something` after dropping privileges?)

It's not a blocker by any means (we're fine with merging the `sed` as-is), but maybe an approach like this would be more maintainable for you?

```bash
    # honor groups supplied via 'docker run --group-add ...' but drop 'root'
    # (also removes 'telegraf' since we unconditionally add it and don't want it listed twice)
    # see https://github.com/influxdata/influxdata-docker/issues/724
    groups="telegraf"
    extra_groups="$(id -Gn)"
    for group in $extra_groups; do
        case "$group" in
            root | telegraf) ;;
            *) groups="$groups,$group" ;;
        esac
    done
    exec setpriv --reuid telegraf --regid telegraf --groups "$groups" "$@"
```

**Comment by powersj** [comment]
> I think I've deducted correctly that https://github.com/influxdata/influxdata-docker/issues/724#issuecomment-1960860373 is the underlying issue it's solving? (--user root:something and wanting to keep something after dropping privileges?)

yep exactly!

> It's not a blocker by any means (we're fine with merging the sed as-is), but maybe an approach like this would be more maintainable for you?

I like this, @jdstrand, thoughts?

**Comment by jdstrand** [comment]
> > It's not a blocker by any means (we're fine with merging the sed as-is), but maybe an approach like this would be more maintainable for you?
> 
> I like this, @jdstrand, thoughts?

LGTM. Cleaner, thanks!

**Review by yosifkit — APPROVED** [review]

**Comment by wz2b** [comment]
I mentioned this is the other issue - and this is already merged - but if the intent here is to always use the TELEGRAF user, then I think this needs to be:

`extra_groups="$(id -Gn telegraf || true)"`

A more flexible approach would probably be to honor UID.

**Comment by tianon** [comment]
The intent is to add the groups of the user we're running as (minus `root`) to the process running as the `telegraf` user (so that `docker run --group-add foo` with the implied root user actually works and adds `foo` to the eventual telegraf process).

**Comment by tianon** [comment]
Also, this whole section of code only runs (and only even _could_ work) if we're running as root, so `docker run --user` will already "do the right thing" here :+1:

**Pull request merged**
