### PR TITLE
Add graalvm image

### PR DESCRIPTION
**Pull request by cap10morgan**
This adds a [GraalVM](https://www.graalvm.org) image for building native executables from JVM-based languages. [Their license](https://github.com/oracle/graal/blob/master/LICENSE) permits redistribution of the community edition, which is what this is packaging up.

I asked if the upstream packagers could publish their Docker images as official images, [but they don't seem receptive to that idea](https://github.com/graalvm/container/issues/21). I am already one of the maintainers of the official clojure image, so I'm happy to take this on too. I need it at work anyway.

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[ ] associated with or contacted upstream?
-	[ ] does it fit into one of the common categories? ("service", "language stack", "base distribution")
-	[ ] is it reasonably popular, or does it solve a particular use case well?
-	[ ] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
-	[ ] official-images maintainer dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ official-images maintainer dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[ ] if `FROM scratch`, tarballs only exist in a single commit within the associated history?
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tianon** [comment]
Reading https://github.com/graalvm/container/issues/21, they don't sound very interested in being part of our program -- unfortunately, them not wanting this to move forward is going to be a blocker for us (the last thing we want to do is misrepresent their project).

**Comment by Djelibeybi** [comment]
Is there a reason why you created a different Dockerfile instead of using one of the official ones from https://github.com/graalvm/container? If this is supposed to be the Docker Hub official image, it should be at least structually identical to the actual official image.

**Comment by cap10morgan** [comment]
@Djelibeybi Because they said they were uninterested in making that a Docker Official Image, and if I'm going to maintain it, I'd rather it be Debian-based.

However, if using that Dockerfile gets upstream's blessing to make this an official image, I'll do it. Is that something you can help with?

**Comment by Djelibeybi** [comment]
I've sent an email to the GraalVM team for more info so I can understand their reasoning. Once I've got that info, I'll be able to better determine whether or not an official supported-by-Oracle image is possible.

**Comment by cap10morgan** [comment]
@Djelibeybi Awesome, thank you!

**Comment by Djelibeybi** [comment]
@cap10morgan sure, my pleasure.

**Comment by Djelibeybi** [comment]
I've found a new person to ping, which I've just done.

**Comment by Djelibeybi** [comment]
I haven't forgotten about this PR. I am going higher up the org chart.

**Comment by cap10morgan** [comment]
> I haven't forgotten about this PR. I am going higher up the org chart.

Thank you @Djelibeybi! I keep running into use cases for a clojure+graalvm image that I've haven't pursued just b/c I didn't have time to build the hybrid image. If this existed though... :)

**Comment by Djelibeybi** [comment]
Sorry for the long delay in responding. Unfortunately, it looks like the GraalVM team is not currently able to support the creation of an official GraalVM image on Docker Hub.

**Comment by cap10morgan** [comment]
> Sorry for the long delay in responding. Unfortunately, it looks like the GraalVM team is not currently able to support the creation of an official GraalVM image on Docker Hub.

OK, yeah, that is unfortunate. Is there anything we in the community can do to help change that?

**Comment by Djelibeybi** [comment]
The only thing I can recommend is opening an issue in the GraalVM org/repo and getting as much community support as possible.

**Comment by cap10morgan** [comment]
> The only thing I can recommend is opening an issue in the GraalVM org/repo and getting as much community support as possible.

I have this opened up over there: https://github.com/graalvm/container/issues/22

I'll see if I can drum up some community activity and support around it. Thanks!

**Pull request closed without merging**
