### PR TITLE
Update docker/scout-sbom-indexer:1 …

### PR DESCRIPTION
**Pull request by tianon**
…to `sha256:660cc838b79f712369273e91c985b547026bb750a371a027a2a24a771cc02620`

### CODE REVIEW

**Comment by tianon** [comment]
@LaurentGoderre this one is good to take, right? (no reason we should wait on it?)

**Comment by LaurentGoderre** [comment]
which tag does that point to?

**Comment by yosifkit** [comment]
Looks to be `1.5.0`.

**Review by LaurentGoderre — APPROVED** [review]

**Comment by LaurentGoderre** [comment]
LGTM

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
