### PR TITLE
library/perl: 5.41.3 -> 5.41.4

### PR DESCRIPTION
**Pull request by zakame**
- http://nntp.perl.org/group/perl.perl5.porters/268800
- https://github.com/Perl/docker-perl/pull/172

### CODE REVIEW

**Review by tianon — APPROVED** [review]

**Comment by zakame** [comment]
Thanks @tianon! 👍

**Comment by yosifkit** [comment]
We're getting a failure when running the tests while building the i386 images: https://github.com/docker-library/meta/actions/runs/10966085457/job/30453269226. Can you take a look?

Not sure what the relevant bit is, but here is part of the log:
```console
#12 161.2 cd t && (rm -f perl; /usr/bin/ln -s ../perl perl)
#12 161.2 TESTFILE=harness LD_LIBRARY_PATH=/usr/src/perl ./runtests choose
#12 161.3 No saved state, selection will be empty
#12 161.3 No saved state, selection will be empty
#12 163.9 base/cond.t .......................................................... ok
#12 163.9 base/if.t ............................................................ ok
...
#12 484.7 ../lib/perl5db.t ..................................................... ok
#12 488.0 ../lib/Unicode/UCD.t ................................................. ok
#12 488.0 
#12 488.0 Test Summary Report
#12 488.0 -------------------
#12 488.0 op/pack.t                                                          (Wstat: 512 (exited 2) Tests: 247 Failed: 0)
#12 488.0   Non-zero exit status: 2
#12 488.0   Parse errors: Bad plan.  You planned 14724 tests but ran 247.
#12 488.0 Files=2889, Tests=1182807, 327 wallclock secs (89.56 usr 10.93 sys + 740.73 cusr 86.74 csys = 927.96 CPU)
#12 488.0 Result: FAIL
#12 488.2 Finished test run at Fri Sep 20 20:57:45 2024.
#12 488.2 make: *** [makefile:866: test_harness] Error 1

**Comment by zakame** [comment]
Thanks @yosifkit 🙏 Looks like there were recent `pack()` changes that are causing this - will forward to perlbug.

**Comment by zakame** [comment]
Perhaps something changed in base `debian:bookworm-slim` image? https://github.com/Perl/docker-perl/actions/runs/10963019337/job/30443596763#step:4:4036 passed ok prior...

**Comment by mauke** [comment]
That thing you linked looks like a 64-bit platform build, not 32-bit.

**Comment by zakame** [comment]
@mauke right, thanks - I think docker-perl could probably enable 32-bit builds at least for perldevel to catch this in future.

**Comment by zakame** [comment]
Now fixed in https://github.com/Perl/perl5/pull/22619, will see in the next 5.41.5 release (or maybe sooner) 🙏

**Pull request merged**
