### PR TITLE
Updated nginx-mainline to 1.11.2.

### PR DESCRIPTION
**Pull request by thresheek**

### CODE REVIEW

**Comment by tianon** [comment]
```diff
warning: insecure protocol git:// detected: git://github.com/nginxinc/docker-nginx
diff --git a/nginx_1.11.1-alpine/Dockerfile b/nginx_1.11.2-alpine/Dockerfile
similarity index 58%
rename from nginx_1.11.1-alpine/Dockerfile
rename to nginx_1.11.2-alpine/Dockerfile
index 39918a5..899c1a6 100644
--- a/nginx_1.11.1-alpine/Dockerfile
+++ b/nginx_1.11.2-alpine/Dockerfile
@@ -1,56 +1,54 @@
-FROM alpine:3.3
+FROM alpine:3.4
 
 MAINTAINER NGINX Docker Maintainers "docker-maint@nginx.com"
 
-ENV NGINX_VERSION 1.11.1
+ENV NGINX_VERSION 1.11.2
 
-ENV GPG_KEYS B0F4253373F8F6F510D42178520A9993A1C052F8
-ENV CONFIG "\
-	--prefix=/etc/nginx \
-	--sbin-path=/usr/sbin/nginx \
-	--modules-path=/usr/lib/nginx/modules \
-	--conf-path=/etc/nginx/nginx.conf \
-	--error-log-path=/var/log/nginx/error.log \
-	--http-log-path=/var/log/nginx/access.log \
-	--pid-path=/var/run/nginx.pid \
-	--lock-path=/var/run/nginx.lock \
-	--http-client-body-temp-path=/var/cache/nginx/client_temp \
-	--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
-	--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
-	--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
-	--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
-	--user=nginx \
-	--group=nginx \
-	--with-http_ssl_module \
-	--with-http_realip_module \
-	--with-http_addition_module \
-	--with-http_sub_module \
-	--with-http_dav_module \
-	--with-http_flv_module \
-	--with-http_mp4_module \
-	--with-http_gunzip_module \
-	--with-http_gzip_static_module \
-	--with-http_random_index_module \
-	--with-http_secure_link_module \
-	--with-http_stub_status_module \
-	--with-http_auth_request_module \
-	--with-http_xslt_module=dynamic \
-	--with-http_image_filter_module=dynamic \
-	--with-http_geoip_module=dynamic \
-	--with-http_perl_module=dynamic \
-	--with-threads \
-	--with-stream \
-	--with-stream_ssl_module \
-	--with-http_slice_module \
-	--with-mail \
-	--with-mail_ssl_module \
-	--with-file-aio \
-	--with-http_v2_module \
-	--with-ipv6 \
-	"
-
-RUN \
-	addgroup -S nginx \
+RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
+	&& CONFIG="\
+		--prefix=/etc/nginx \
+		--sbin-path=/usr/sbin/nginx \
+		--modules-path=/usr/lib/nginx/modules \
+		--conf-path=/etc/nginx/nginx.conf \
+		--error-log-path=/var/log/nginx/error.log \
+		--http-log-path=/var/log/nginx/access.log \
+		--pid-path=/var/run/nginx.pid \
+		--lock-path=/var/run/nginx.lock \
+		--http-client-body-temp-path=/var/cache/nginx/client_temp \
+		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
+		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
+		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
+		--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
+		--user=nginx \
+		--group=nginx \
+		--with-http_ssl_module \
+		--with-http_realip_module \
+		--with-http_addition_module \
+		--with-http_sub_module \
+		--with-http_dav_module \
+		--with-http_flv_module \
+		--with-http_mp4_module \
+		--with-http_gunzip_module \
+		--with-http_gzip_static_module \
+		--with-http_random_index_module \
+		--with-http_secure_link_module \
+		--with-http_stub_status_module \
+		--with-http_auth_request_module \
+		--with-http_xslt_module=dynamic \
+		--with-http_image_filter_module=dynamic \
+		--with-http_geoip_module=dynamic \
+		--with-http_perl_module=dynamic \
+		--with-threads \
+		--with-stream \
+		--with-stream_ssl_module \
+		--with-http_slice_module \
+		--with-mail \
+		--with-mail_ssl_module \
+		--with-file-aio \
+		--with-http_v2_module \
+		--with-ipv6 \
+	" \
+	&& addgroup -S nginx \
 	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
 	&& apk add --no-cache --virtual .build-deps \
 		gcc \
@@ -99,17 +97,26 @@ RUN \
 	&& ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \
 	&& strip /usr/sbin/nginx* \
 	&& strip /usr/lib/nginx/modules/*.so \
+	&& rm -rf /usr/src/nginx-$NGINX_VERSION \
+	\
+	# Bring in gettext so we can get `envsubst`, then throw
+	# the rest away. To do this, we need to install `gettext`
+	# then move `envsubst` out of the way so `gettext` can
+	# be deleted completely, then move `envsubst` back.
+	&& apk add --no-cache --virtual .gettext gettext \
+	&& mv /usr/bin/envsubst /tmp/ \
+	\
 	&& runDeps="$( \
-		scanelf --needed --nobanner /usr/sbin/nginx /usr/lib/nginx/modules/*.so \
+		scanelf --needed --nobanner /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
 			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
 			| sort -u \
 			| xargs -r apk info --installed \
 			| sort -u \
 	)" \
-	&& apk add --virtual .nginx-rundeps $runDeps \
+	&& apk add --no-cache --virtual .nginx-rundeps $runDeps \
 	&& apk del .build-deps \
-	&& rm -rf /usr/src/nginx-$NGINX_VERSION \
-	&& apk add --no-cache gettext \
+	&& apk del .gettext \
+	&& mv /tmp/envsubst /usr/bin/ \
 	\
 	# forward request and error logs to docker log collector
 	&& ln -sf /dev/stdout /var/log/nginx/access.log \
diff --git a/nginx_1.11.1-alpine/nginx.conf b/nginx_1.11.2-alpine/nginx.conf
similarity index 100%
rename from nginx_1.11.1-alpine/nginx.conf
rename to nginx_1.11.2-alpine/nginx.conf
diff --git a/nginx_1.11.1-alpine/nginx.vh.default.conf b/nginx_1.11.2-alpine/nginx.vh.default.conf
similarity index 100%
rename from nginx_1.11.1-alpine/nginx.vh.default.conf
rename to nginx_1.11.2-alpine/nginx.vh.default.conf
diff --git a/nginx_1.11.1/Dockerfile b/nginx_1.11.2/Dockerfile
similarity index 96%
rename from nginx_1.11.1/Dockerfile
rename to nginx_1.11.2/Dockerfile
index 80ae322..e50e74b 100644
--- a/nginx_1.11.1/Dockerfile
+++ b/nginx_1.11.2/Dockerfile
@@ -2,7 +2,7 @@ FROM debian:jessie
 
 MAINTAINER NGINX Docker Maintainers "docker-maint@nginx.com"
 
-ENV NGINX_VERSION 1.11.1-1~jessie
+ENV NGINX_VERSION 1.11.2-1~jessie
 
 RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 \
 	&& echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list \
```

**Comment by tianon** [comment]
For that `envsubst` hack, it's probably less likely to break in dependent images if you put it into `/usr/local/bin` when you move it back (as opposed to `/usr/bin`) since `apk` won't install there.

**Comment by md5** [comment]
@tianon Doesn't that mean that the one in `/usr/local/bin` will take precedence in `$PATH`?

**Comment by md5** [comment]
(which is only a problem if they aren't the same)

**Comment by tianon** [comment]
Yeah, but IMO that's not a huge issue (especially since `rm /usr/local/bin/envsubst` is pretty trivial).

**Comment by ziggythehamster** [comment]
I think you guys might have forgotten about this PR. You may as well make this 1.11.3 now that nginx has released it :)

**Comment by ziggythehamster** [comment]
@tianon any chance of getting this image updated? :)

**Comment by thresheek** [comment]
Closing this PR as I will send a newer one.  Thanks.

**Pull request closed without merging**
