### PR TITLE
erlang/otp 25.2

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by tianon** [comment]
Are you sure you don't want to add yourself to the `Maintainers:` list so you get included in pings like https://github.com/docker-library/official-images/pull/13577#issuecomment-1324292585? :sweat_smile:

**Comment by tianon** [comment]
(Something like `19年梦醒 (@getong)` should work and be enough, FWIW)

**Comment by getong** [comment]
> (Something like `19年梦醒 (@getong)` should work and be enough, FWIW)
No, but thanks.

I delete alpine support for erlang 21, as it was released 4 years ago.

**Comment by tianon** [comment]
It probably makes sense to consider going further and removing more of those old tags from the supported/rebuilt list -- is Erlang 21 still actively supported by the project? :sweat_smile:

**Pull request merged**
