### PR TITLE
 [Friendica] Release 2024.06-rc

### PR DESCRIPTION
**Pull request by ne20002**

### CODE REVIEW

**Review by tianon — APPROVED** [review]
Thanks, this looks correct to me :smile:

@nupplaphil @mrpetovan can one of you confirm? :bow: :heart:

**Comment by ne20002** [comment]
I'm not sure if @nupplaphil is still active (see [#244](https://github.com/friendica/docker/issues/244) so I thought I'm volunteering. 
Maybe @mrpetovan or @annando can help.

**Comment by MrPetovan** [comment]
I can't approve nor merge myself. In particular, I'm not sure what these merge commits hashes are referring?

**Comment by ne20002** [comment]
Me neither, not exactly. This part I can't test or I don't know how.
I just followed the script and believe in the tools.

**Comment by MrPetovan** [comment]
All hail the tools! Let's go forward then.

**Comment by ne20002** [comment]
I'm confident that it worked. It generated the same numbers as before for the already existing releases and added the sections for the 2024.06-rc version what is exactly what I wanted to achieve.

**Comment by annando** [comment]
@ne20002 thanks for stepping in! I sadly don't have got any Docker knowledge.

**Comment by ne20002** [comment]
The numbers are the git commits of the git workflow commits named 'Runs update.sh' in the friendica-docker repository.
:)

**Comment by ne20002** [comment]
@tianon I believe we can forward then.

**Comment by yosifkit** [comment]
Thanks for confirming the changes, everyone!

**Comment by ne20002** [comment]
The last was successful. I just installed the 2024.06-rc-fpm and all is working well as expected.

**Pull request merged**
