### PR TITLE
Merge pull request #6772 from docker-library-bot/rabbitmq

### PR DESCRIPTION
**Pull request by micktie**
Update rabbitmq

Signed-off-by: michthom <michael.a.thompson@oracle.com>

### CODE REVIEW

**Comment by tianon** [comment]
This seems a bit odd; what's the intention here?

**Comment by micktie** [comment]
It is related to Oracle Linux 8 container images & pointers to the new images

**Comment by tianon** [comment]
Ok sure, but then why is the PR's title "Merge pull request #6772 from docker-library-bot/rabbitmq", and why are there changes to `library/rabbitmq` included here as well?  There's also only one commit in this PR, and it's a merge commit?

**Comment by micktie** [comment]
Ah, seems I did a commit amend rather than commit.  Corrected, so it should be ok now.

**Pull request closed without merging**
