### PR TITLE
Update photon image

### PR DESCRIPTION
**Pull request by gerrit-photon**
Update photon image

### CODE REVIEW

**Comment by yosifkit** [comment]
I'd assumed that yesterday's PR (https://github.com/docker-library/official-images/pull/11953) was just to add the `3.0` rebuild that was missing on Friday's PR (https://github.com/docker-library/official-images/pull/11933).

This PR seems a little off since it has historically been a weekly cadence on Friday for rebuild/updates. Are there some security concerns that necessitate a different schedule this week? Are all of the versions and architectures being updated today? i.e. which should we be waiting for?

**Comment by YustasSwamp** [comment]
@yosifkit thanks for the concern. Let me take a look at our pipeline for the reasoning for such behavior.

**Comment by YustasSwamp** [comment]
> @yosifkit thanks for the concern. Let me take a look at our pipeline for the reasoning for such behavior.

There were no security updates urgency. It was human mistake in dealing with the pipeline. Let's ignore these commits and continue to go with regular schedule.
Sorry for bothering you.

**Comment by tianon** [comment]
Will do! :+1:

**Pull request closed without merging**
