### PR TITLE
Add new pull subcommand

### PR DESCRIPTION
**Pull request by stuart-c**
Signed-off-by: Stuart Clark <stuart.clark@Jahingo.com>

A new subcommand which I find useful for priming the cache

### CODE REVIEW

**Comment by tianon** [comment]
Not sure how I feel about this, especially given that `docker pull` doesn't cache-fill anymore (as of Docker 1.10, which is our new minimum requirement).  We usually simulate this ourselves via `bashbrew list <args> | xargs -n1 docker pull`, which is pretty effective.

**Comment by stuart-c** [comment]
This is basically the same thing though isn't it?

**Comment by tianon** [comment]
Right, yes, that's the point I was trying to make -- one reasonably simple
line of shell for this one-off use case versus the 50 or so lines of Go for
something our official build server will never use and we only use in rare
cases ourselves (and furthermore we'd want to patch out for our official
build system in order to ensure it never ever pulls, as our configuration
there specifies via "Pull: never").

**Comment by stuart-c** [comment]
While it probably isn't of much use for the official build servers that isn't the use-case I'm going for.

Ignoring the official images totally bashbrew is a very useful tool for CI building of Docker images where repeatability and careful control of tagging are desired. We find it a very useful tool but have a few extra requirements (e.g. pulling of images so we don't have to build everything from scratch) which would be preferable to include upstream instead of having to maintain a fork.

Regarding not wanting to use it on the official servers I'm not sure I understand the need to patch the feature out, as like the "Pull: never" step for building it won't ever pull unless you specifically request it.

[As an aside I'm looking to send over a couple more PRs for other small features which are probably not useful for the official build servers, including injection of build args]

**Comment by yosifkit** [comment]
Thanks for spending time on this patch. We view the `bashbrew` tool as a build tool and `pull` doesn't seem to fit in that use case (especially since `docker pull` on `1.10+` is unable to fill build cache), so it is not something we want to add right now.

**Comment by stuart-c** [comment]
No worries. I'll use the equivalent shell @tianon gave above instead.

**Pull request closed without merging**
