### PR TITLE
Update eclipse-temurin for new releases (part 1)

### PR DESCRIPTION
**Pull request by sxa**
Updates to new quarterly release for  JDK11.0.15 and 17.0.3

### CODE REVIEW

**Comment by yosifkit** [comment]
This is going to hit the same issue as https://github.com/docker-library/python/issues/681 (and  https://github.com/docker-library/official-images/pull/11760#discussion_r794920624). So, any `Shared Tags` listed on the older images will lose all images and architectures not still in the `library/eclipse-temurin` file. So, `11.0.14.1_1-jdk`, `8u322-b06-jdk`, and others will have only windows images.

**Comment by sxa** [comment]
Thanks for letting me know. I hadn't been aware of that happening previously - will discuss with my team.

**Comment by sxa** [comment]
@yosifkit Done - we've got the full set of platforms ready for 11 and 17 now so I've modified the PR to reflect that. We'll need to see if we can do anything to be able to split them out at some point later :-)

**Comment by yosifkit** [comment]
The `library/` file needs to be a complete description of any specific tag. It is acceptable if a new tag doesn't have all of it's OS/architecture combinations, but any already published tags likely need to maintain their OS/architecture set until that tag is removed.
I think the two future options to avoid the tagging problem linked above is to either remove the old version completely from the `library/` file, or to keep all of that old version until the new version is complete. Both of these will ensure that the manifest list doesn't get updated to exclude previously supported OS/architecture combinations. (I'd probably lean toward dropping the old version, since it'll still be available to pull and doesn't likely need rebuilds triggered from base image updates.)

**Pull request merged**
