### PR TITLE
Please upgrade to the ArangoDB Release 3.4.0

### PR DESCRIPTION
**Pull request by fceller**
Add new version (3.4.0) of ArangoDB

### CODE REVIEW

**Comment by fceller** [comment]
FYI: we have switched from Debian to Alpine as base image for smaller image footprint and better security

**Comment by yosifkit** [comment]
I don't see any savings for changing to an Alpine based image (and is actually larger):

```console
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
arangodb            3.4                 6f4fac629f04        17 minutes ago      297MB
arangodb            3.4.0               6f4fac629f04        17 minutes ago      297MB
arangodb            latest              6f4fac629f04        17 minutes ago      297MB
arangodb            3.3                 b3b908d5adc9        26 hours ago        292MB
arangodb            3.3.20              b3b908d5adc9        26 hours ago        292MB
```

From the layer details, it seems the largest difference is installing `nodejs` and `foxx-cli` (which together add 82MB in `/usr/lib/node_modules/` and 17.9MB in `/root/.npm/`); are these required for arangodb?

<details>
<summary>docker history x2</summary>

```console
$ docker history arangodb:3.4
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6f4fac629f04        About an hour ago   /bin/sh -c #(nop)  CMD ["arangod"]              0B                  
e44b63236701        About an hour ago   /bin/sh -c #(nop)  EXPOSE 8529                  0B                  
0dddbfc4b6a0        About an hour ago   /bin/sh -c #(nop)  ENTRYPOINT ["/entrypoint.…   0B                  
3246db1b345f        About an hour ago   /bin/sh -c #(nop) COPY file:e045f6005e7ab029…   6.06kB              
95d3e88b53f9        About an hour ago   /bin/sh -c #(nop)  VOLUME [/var/lib/arangodb…   0B                  
c86dcbeff066        About an hour ago   /bin/sh -c cd /tmp                          …   181MB               
be5b6f7f5475        About an hour ago   /bin/sh -c mkdir /docker-entrypoint-initdb.d    0B                  
0932bcd05a7c        About an hour ago   /bin/sh -c gpg --batch --keyserver hkps://hk…   4.32kB              
db5c3370157b        7 hours ago         /bin/sh -c apk update &&     apk add gnupg p…   112MB               
76a9dd30b377        7 hours ago         /bin/sh -c #(nop)  ENV ARANGO_SIGNATURE_URL=…   0B                  
9be58b8897ff        7 hours ago         /bin/sh -c #(nop)  ENV ARANGO_PACKAGE_URL=ht…   0B                  
c8c49cc847cf        7 hours ago         /bin/sh -c #(nop)  ENV ARANGO_PACKAGE=arango…   0B                  
e04310879c74        7 hours ago         /bin/sh -c #(nop)  ENV ARANGO_URL=https://do…   0B                  
8fe7401220d8        7 hours ago         /bin/sh -c #(nop)  ENV ARANGO_VERSION=3.4.0     0B                  
b7ca703de37d        7 hours ago         /bin/sh -c #(nop)  MAINTAINER Frank Celler <…   0B                  
3239e854f50b        2 months ago        /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B                  
ee2654e0f6a3        2 months ago        /bin/sh -c #(nop) ADD file:73a973d18cce96c54…   4.2MB               
```

```console
$ docker history arangodb:3.3
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
b3b908d5adc9        27 hours ago        /bin/sh -c #(nop)  CMD ["arangod"]              0B                  
5d7ad272efc0        27 hours ago        /bin/sh -c #(nop)  EXPOSE 8529                  0B                  
891311dfa21a        27 hours ago        /bin/sh -c #(nop)  ENTRYPOINT ["/entrypoint.…   0B                  
dad01ef218d7        27 hours ago        /bin/sh -c #(nop) COPY file:01bdd453b032c9d3…   6.11kB              
3fae67d87ac1        27 hours ago        /bin/sh -c #(nop)  VOLUME [/var/lib/arangodb…   0B                  
6360bc37f6d3        27 hours ago        /bin/sh -c curl --fail -O ${ARANGO_SIGNATURE…   164MB               
b77b172f69e5        27 hours ago        /bin/sh -c mkdir /docker-entrypoint-initdb.d    0B                  
08669c847f7f        27 hours ago        /bin/sh -c apt-get update &&     apt-get ins…   16.3MB              
0dfde42653e8        27 hours ago        /bin/sh -c gpg --keyserver hkps://hkps.pool.…   4.24kB              
579875e7a867        27 hours ago        /bin/sh -c apt-get update &&     apt-get ins…   11.6MB              
8a2279fd913c        27 hours ago        /bin/sh -c #(nop)  ENV ARANGO_SIGNATURE_URL=…   0B                  
451016f65863        27 hours ago        /bin/sh -c #(nop)  ENV ARANGO_PACKAGE_URL=ht…   0B                  
e48dceb8eae8        27 hours ago        /bin/sh -c #(nop)  ENV ARANGO_PACKAGE=arango…   0B                  
790fec644051        27 hours ago        /bin/sh -c #(nop)  ENV ARANGO_URL=https://do…   0B                  
cd80592d2033        27 hours ago        /bin/sh -c #(nop)  ENV ARANGO_VERSION=3.3.20    0B                  
1d7ca5a8e4f2        2 weeks ago         /bin/sh -c #(nop)  ENV DEB_PACKAGE_VERSION=1    0B                  
675ed75729b0        2 weeks ago         /bin/sh -c #(nop)  ENV ARCHITECTURE=amd64       0B                  
e0625bcae2d3        2 weeks ago         /bin/sh -c #(nop)  MAINTAINER Frank Celler <…   0B                  
83312b124c6e        3 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B                  
a627cc31434f        3 weeks ago         /bin/sh -c #(nop) ADD file:735a0f77bbc29cf51…   101MB               
```
</details>

------
On a side note you should probably switch to `alpine:3.8` when possible to get a longer support cycle (3.7 ends November 2019, vs 3.8 in May 2020).  And also should remove `apk update` and instead do `apk add --no-cache` when installing packages.

You may also have issues with users on the new Alpine version who were expecting their scripts to be run by `bash` but are now `sh` from busybox.

**Comment by fceller** [comment]
@yosifkit yes, the new version 3.4 requires node.js. In 3.3 this was not required.

Switch to alpine reduces this overhead. However, the mean reason for this switch is security. The Alpine image contains much fewer components, which is also good for security. that is also the reason, while a would avoid adding bash. In general, ArangoDB do not need a shell into the container.

I will update to alpine:3.8.

**Comment by fceller** [comment]
@yosifkit I have switched to 3.8 and replaced the "apt update" by "--no-chache". I have also removed the "/root/.npm" directory.

**Comment by tianon** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-arches b/_bashbrew-arches
index 385729c..e91bb23 100644
--- a/_bashbrew-arches
+++ b/_bashbrew-arches
@@ -1,3 +1,4 @@
 arangodb:2.8.11 @ amd64
 arangodb:3.2.17 @ amd64
+arangodb:3.3.20 @ amd64
 arangodb:latest @ amd64
diff --git a/_bashbrew-list b/_bashbrew-list
index 2cc9fdb..dcd6769 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -4,4 +4,6 @@ arangodb:3.2
 arangodb:3.2.17
 arangodb:3.3
 arangodb:3.3.20
+arangodb:3.4
+arangodb:3.4.0
 arangodb:latest
diff --git a/arangodb_latest/Dockerfile b/arangodb_3.3.20/Dockerfile
similarity index 100%
copy from arangodb_latest/Dockerfile
copy to arangodb_3.3.20/Dockerfile
diff --git a/arangodb_3.2.17/docker-entrypoint.sh b/arangodb_3.3.20/docker-entrypoint.sh
similarity index 100%
copy from arangodb_3.2.17/docker-entrypoint.sh
copy to arangodb_3.3.20/docker-entrypoint.sh
diff --git a/arangodb_latest/Dockerfile b/arangodb_latest/Dockerfile
index 094e04c..99a7fad 100644
--- a/arangodb_latest/Dockerfile
+++ b/arangodb_latest/Dockerfile
@@ -1,30 +1,17 @@
-FROM debian:stretch
+FROM alpine:3.8
 MAINTAINER Frank Celler <info@arangodb.com>
 
-ENV ARCHITECTURE amd64
-ENV DEB_PACKAGE_VERSION 1
-ENV ARANGO_VERSION 3.3.20
-ENV ARANGO_URL https://download.arangodb.com/arangodb33/Debian_9.0
-ENV ARANGO_PACKAGE arangodb3-${ARANGO_VERSION}-${DEB_PACKAGE_VERSION}_${ARCHITECTURE}.deb
-ENV ARANGO_PACKAGE_URL ${ARANGO_URL}/${ARCHITECTURE}/${ARANGO_PACKAGE}
+ENV ARANGO_VERSION 3.4.0
+ENV ARANGO_URL https://download.arangodb.com/arangodb34/DEBIAN/amd64
+ENV ARANGO_PACKAGE arangodb3_${ARANGO_VERSION}-1_amd64.deb
+ENV ARANGO_PACKAGE_URL ${ARANGO_URL}/${ARANGO_PACKAGE}
 ENV ARANGO_SIGNATURE_URL ${ARANGO_PACKAGE_URL}.asc
 
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends gpg dirmngr \
-    && \
-    rm -rf /var/lib/apt/lists/*
+RUN apk add --no-cache gnupg pwgen nodejs npm binutils && \
+    npm install -g foxx-cli && \
+    rm -rf /root/.npm
 
-RUN gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys CD8CB0F1E0AD5B52E93F41E7EA93F5E56E751E9B
-
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends \
-        libjemalloc1 \
-        ca-certificates \
-        pwgen \
-        curl \
-        numactl \
-    && \
-    rm -rf /var/lib/apt/lists/*
+RUN gpg --batch --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys CD8CB0F1E0AD5B52E93F41E7EA93F5E56E751E9B
 
 RUN mkdir /docker-entrypoint-initdb.d
 
@@ -32,22 +19,20 @@ RUN mkdir /docker-entrypoint-initdb.d
 #   https://docs.arangodb.com/latest/Manual/Administration/Configuration/Endpoint.html
 #   https://docs.arangodb.com/latest/Manual/Administration/Configuration/Logging.html
 
-RUN curl --fail -O ${ARANGO_SIGNATURE_URL} &&       \
-    curl --fail -O ${ARANGO_PACKAGE_URL} &&         \
+RUN cd /tmp                                && \
+    wget ${ARANGO_SIGNATURE_URL}           && \
+    wget ${ARANGO_PACKAGE_URL}             && \
     gpg --verify ${ARANGO_PACKAGE}.asc     && \
-    (echo arangodb3 arangodb3/password password test | debconf-set-selections) && \
-    (echo arangodb3 arangodb3/password_again password test | debconf-set-selections) && \
-    DEBIAN_FRONTEND="noninteractive" dpkg -i ${ARANGO_PACKAGE} && \
-    rm -rf /var/lib/arangodb3/* && \
+    ar x ${ARANGO_PACKAGE} data.tar.gz     && \
+    tar -C / -x -z -f data.tar.gz          && \
     sed -ri \
         -e 's!127\.0\.0\.1!0.0.0.0!g' \
         -e 's!^(file\s*=).*!\1 -!' \
         -e 's!^\s*uid\s*=.*!!' \
-        /etc/arangodb3/arangod.conf \
-    && chgrp 0 /var/lib/arangodb3 /var/lib/arangodb3-apps \
-    && chmod 775 /var/lib/arangodb3 /var/lib/arangodb3-apps \
-    && \
-    rm -f ${ARANGO_PACKAGE}*
+        /etc/arangodb3/arangod.conf        && \
+    echo chgrp 0 /var/lib/arangodb3 /var/lib/arangodb3-apps && \
+    echo chmod 775 /var/lib/arangodb3 /var/lib/arangodb3-apps && \
+    rm -f ${ARANGO_PACKAGE}* data.tar.gz
 # Note that Openshift runs containers by default with a random UID and GID 0.
 # We need that the database and apps directory are writable for this config.
 
diff --git a/arangodb_latest/docker-entrypoint.sh b/arangodb_latest/docker-entrypoint.sh
index c346f17..6295cb0 100755
--- a/arangodb_latest/docker-entrypoint.sh
+++ b/arangodb_latest/docker-entrypoint.sh
@@ -1,13 +1,18 @@
-#!/bin/bash
-set -eo pipefail
+#!/bin/sh
+set -e
+
+if [ -z "$ARANGO_INIT_PORT" ] ; then
+    ARANGO_INIT_PORT=8999
+fi
 
 AUTHENTICATION="true"
 export GLIBCXX_FORCE_NEW=1
 
 # if command starts with an option, prepend arangod
-if [ "${1:0:1}" = '-' ]; then
-    set -- arangod "$@"
-fi
+case "$1" in
+  -*) set -- arangod "$@" ;;
+  *) ;;
+esac
 
 if [ "$1" = 'arangod' ]; then
     # /var/lib/arangodb3 and /var/lib/arangodb3-apps must exist and
@@ -16,7 +21,6 @@ if [ "$1" = 'arangod' ]; then
     # Make a copy of the configuration file to patch it, note that this
     # must work regardless under which user we run:
     cp /etc/arangodb3/arangod.conf /tmp/arangod.conf
-    cp /etc/arangodb3/arango-init-database.conf /tmp/arango-init-database.conf
 
     if [ ! -z "$ARANGO_ENCRYPTION_KEYFILE" ]; then
         echo "Using encrypted database"
@@ -25,7 +29,7 @@ if [ "$1" = 'arangod' ]; then
     fi
 
     if [ "$ARANGO_STORAGE_ENGINE" == "rocksdb" ]; then
-        echo "choosing Rocksdb storage engine"
+        echo "choosing RocksDB storage engine"
         sed -i /tmp/arangod.conf -e "s;storage-engine = auto;storage-engine = rocksdb;"
     elif [ "$ARANGO_STORAGE_ENGINE" == "mmfiles" ]; then
         echo "choosing MMFiles storage engine"
@@ -37,6 +41,9 @@ if [ "$1" = 'arangod' ]; then
         if [ -f "$ARANGO_ROOT_PASSWORD_FILE" ]; then
             ARANGO_ROOT_PASSWORD="$(cat $ARANGO_ROOT_PASSWORD_FILE)"
         fi
+        # Please note that the +x in the following line is for the case
+        # that ARANGO_ROOT_PASSWORD is set but to an empty value, please
+        # do not remove!
         if [ -z "${ARANGO_ROOT_PASSWORD+x}" ] && [ -z "$ARANGO_NO_AUTH" ] && [ -z "$ARANGO_RANDOM_ROOT_PASSWORD" ]; then
             echo >&2 'error: database is uninitialized and password option is not specified '
             echo >&2 "  You need to specify one of ARANGO_ROOT_PASSWORD, ARANGO_NO_AUTH and ARANGO_RANDOM_ROOT_PASSWORD"
@@ -52,7 +59,7 @@ if [ "$1" = 'arangod' ]; then
         
         if [ ! -z "${ARANGO_ROOT_PASSWORD+x}" ]; then
             echo "Initializing root user...Hang on..."
-            ARANGODB_DEFAULT_ROOT_PASSWORD="$ARANGO_ROOT_PASSWORD" /usr/sbin/arango-init-database -c /tmp/arango-init-database.conf || true
+            ARANGODB_DEFAULT_ROOT_PASSWORD="$ARANGO_ROOT_PASSWORD" /usr/sbin/arango-init-database -c /tmp/arangod.conf --server.rest-server false --log.level error --database.init-database true || true
             export ARANGO_ROOT_PASSWORD
         
             if [ ! -z "${ARANGO_ROOT_PASSWORD}" ]; then
@@ -65,7 +72,7 @@ if [ "$1" = 'arangod' ]; then
         echo "Initializing database...Hang on..."
 
         arangod --config /tmp/arangod.conf \
-                --server.endpoint unix:///tmp/arangodb-tmp.sock \
+                --server.endpoint tcp://127.0.0.1:$ARANGO_INIT_PORT \
                 --server.authentication false \
 		--log.file /tmp/init-log \
 		--log.foreground-tty false &
@@ -87,12 +94,18 @@ if [ "$1" = 'arangod' ]; then
             let counter=counter+1
             ARANGO_UP=1
                 arangosh \
-                    --server.endpoint=unix:///tmp/arangodb-tmp.sock \
+                    --server.endpoint=tcp://127.0.0.1:$ARANGO_INIT_PORT \
                     --server.authentication false \
                     --javascript.execute-string "db._version()" \
                     > /dev/null 2>&1 || ARANGO_UP=0
         done
 
+        if [ "$(id -u)" = "0" ] ; then
+            foxx server set default http://127.0.0.1:$ARANGO_INIT_PORT
+        else
+            echo Not setting foxx server default because we are not root.
+        fi
+
         for f in /docker-entrypoint-initdb.d/*; do
             case "$f" in
             *.sh)
@@ -102,7 +115,7 @@ if [ "$1" = 'arangod' ]; then
             *.js)
                         echo "$0: running $f"
                         arangosh ${ARANGOSH_ARGS} \
-                                --server.endpoint=unix:///tmp/arangodb-tmp.sock \
+                                --server.endpoint=tcp://127.0.0.1:$ARANGO_INIT_PORT \
                                 --javascript.execute "$f"
                         ;;
             */dumps)
@@ -112,7 +125,7 @@ if [ "$1" = 'arangod' ]; then
                             echo "restoring $d into ${DBName}";
                             arangorestore \
                                 ${ARANGOSH_ARGS} \
-                                --server.endpoint=unix:///tmp/arangodb-tmp.sock \
+                                --server.endpoint=tcp://127.0.0.1:$ARANGO_INIT_PORT \
                                 --create-database true \
                                 --include-system-collections true \
                                 --server.database "$DBName" \
@@ -123,14 +136,16 @@ if [ "$1" = 'arangod' ]; then
             esac
         done
 
+        if [ "$(id -u)" = "0" ] ; then
+            foxx server remove default
+        fi
+
         if ! kill -s TERM "$pid" || ! wait "$pid"; then
                 echo >&2 'ArangoDB Init failed.'
                 exit 1
         fi
 
         echo "Database initialized...Starting System..."
-    else
-        echo "starting over with existing database"
     fi
 
     # if we really want to start arangod and not bash or any other thing
@@ -145,16 +160,4 @@ if [ "$1" = 'arangod' ]; then
     set -- arangod "$@" --server.authentication="$AUTHENTICATION" --config /tmp/arangod.conf
 fi
 
-if [ ! -z "$ARANGO_USE_NUMA_INTERLEAVE_ALL" ]; then
-    echo "Will try to enable NUMA interleave on all nodes..."
-    # check numactl usability to provide a hint if container is not running in
-    # privileged mode
-    numa='numactl --interleave=all'
-    if $numa true &> /dev/null; then
-	set -- $numa "$@"
-    else
-	echo >&2 "error: cannot use numactl, if you are sure that it is supported by your hardware and system, please check that container is running with --security-opt seccomp=unconfined"
-    fi
-fi
-
 exec "$@"
````

</details>

**Comment by tianon** [comment]
You probably want to pin `npm install -g foxx-cli` to an explicit version in a future update (unless you know for certain that any `foxx-cli` version will be suitable in the future, but pinning would allow you to actually control updates to that dependency in your image).

> that is also the reason, while a would avoid adding bash. In general, ArangoDB do not need a shell into the container.

I think the concern there is around https://github.com/arangodb/arangodb-docker/blob/18d840d000fe41848318854eeaf316f2018c825b/alpine/3.4.0/docker-entrypoint.sh#L113 (where user-supplied scripts get sourced by this script) rather than folks looking to start a shell -- this is a change in that interface.  As long as you're aware of that and ready to help folks who run into that, that seems fine to me and we can go ahead and merge this.

**Comment by tianon** [comment]
@fceller what do you want to do here?  Does my clarification make sense?  Do you still want to merge this, or is there further work you'd like to do first?  (We're good either way now, just want to make sure you're aware of the direct implications of this change that we see.)

**Comment by fceller** [comment]
Yes, please merge. We do not want to pull „bash“ into it.

**Pull request merged**
