### PR TITLE
[nats] Release v2.9.21

### PR DESCRIPTION
**Pull request by bruth**
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.9.21)

### CODE REVIEW

**Comment by yosifkit** [comment]
> +	apk add --upgrade libcrypto3 libssl3; \

We recommend against using package upgrades (`apt-get upgrade`/`apk upgrade`/`yum upgrade`/`yum update`) for official-images. When package upgrades are applied in a dependent image, it duplicates content of the base image, making the image larger than necessary. It also only delays the inevitable "there are outdated packages". The Official Images build pipeline makes heavy use of `docker build` cache, so we make periodic base image updates to then fully rebuild all dependent images (e.g. the [Debian image updates](https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fdebian)).

>We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need, e.g. [docker-library/official-images#2171](https://github.com/docker-library/official-images/issues/2171). Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule. These refreshed base images also means that any other image in the Official Images program that is `FROM` them will also be rebuilt (as described in [the project `README.md` file](https://github.com/docker-library/official-images#library-definition-files)).
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by bruth** [comment]
@yosifkit The reason we added this line was due to some vulnerabilities found in the current Alpine image. Upgrading the packages resolves these for scanners. See this comment for context: https://github.com/nats-io/nats-docker/pull/115#discussion_r1284568228

If it is still a no-go, then I will remove the line and update the PR.

**Comment by bruth** [comment]
> Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule. These refreshed base images also means that any other image in the Official Images program that is FROM them will also be rebuilt (as described in [the project README.md file](https://github.com/docker-library/official-images#library-definition-files)).

Re-reading, so once the alpine image is updated, the NATS images will automatically be rebuilt with the latest patch (since we built on 3.18)?

**Comment by bruth** [comment]
@yosifkit Let us know what the preferred path is here, so we can remediate and get the images up on Docker Hub.

**Comment by yosifkit** [comment]
> Re-reading, so once the alpine image is updated, the NATS images will automatically be rebuilt with the latest patch (since we built on 3.18)?

Correct, which will happen with https://github.com/docker-library/official-images/pull/15156. So, please drop the `apk upgrade`.

**Comment by bruth** [comment]
@yosifkit Updated. Referenced commit: https://github.com/nats-io/nats-docker/commit/36c73754f3d7b2b2e69a0c4680a48636929012cc

**Pull request merged**
