### PR TITLE
Closes #594: Test for Golang image

### LINKED ISSUE #594: [test] golang-hello-world
Create a simple hello-world application to ensure that the language can compile (if necessary) and run (see ./test/tests/hylang-sh for an example of using expected-std-out.txt).

### PR DESCRIPTION
**Pull request by MBonell**
Hello world test for the Golang image

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Do you think it's worth directly using `go run` instead of `go build` so the Go tool figures out a good place to store the intermediate objects on-disk for us?

**Comment by MBonell** [comment]
@tianon Well, in this case is a single file, so let's use just `go run` is simpler

**Comment by tianon** [comment]
:metal:

**Pull request merged**
