### PR TITLE
Bump Traefik to v2.0.0-alpha5

### PR DESCRIPTION
**Pull request by ldez**
Hello,

This PR updates Traefik to v2.0.0-alpha5.

/cc @mmatur @emilevauge

Cheers

### CODE REVIEW

**Comment by yosifkit** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-list b/_bashbrew-list
index 5164aad..1e92318 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -10,10 +10,10 @@ traefik:2.0
 traefik:2.0-alpine
 traefik:2.0-nanoserver
 traefik:2.0-nanoserver-sac2016
-traefik:2.0.0-alpha4
-traefik:2.0.0-alpha4-alpine
-traefik:2.0.0-alpha4-nanoserver
-traefik:2.0.0-alpha4-nanoserver-sac2016
+traefik:2.0.0-alpha5
+traefik:2.0.0-alpha5-alpine
+traefik:2.0.0-alpha5-nanoserver
+traefik:2.0.0-alpha5-nanoserver-sac2016
 traefik:alpine
 traefik:faisselle
 traefik:faisselle-alpine
@@ -38,7 +38,7 @@ traefik:v2.0
 traefik:v2.0-alpine
 traefik:v2.0-nanoserver
 traefik:v2.0-nanoserver-sac2016
-traefik:v2.0.0-alpha4
-traefik:v2.0.0-alpha4-alpine
-traefik:v2.0.0-alpha4-nanoserver
-traefik:v2.0.0-alpha4-nanoserver-sac2016
+traefik:v2.0.0-alpha5
+traefik:v2.0.0-alpha5-alpine
+traefik:v2.0.0-alpha5-nanoserver
+traefik:v2.0.0-alpha5-nanoserver-sac2016
diff --git a/traefik_faisselle-alpine/Dockerfile b/traefik_faisselle-alpine/Dockerfile
index 8edbffa..364646d 100644
--- a/traefik_faisselle-alpine/Dockerfile
+++ b/traefik_faisselle-alpine/Dockerfile
@@ -8,7 +8,7 @@ RUN set -ex; \
 		x86_64) arch='amd64' ;; \
 		*) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
 	esac; \
-	wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/v2.0.0-alpha4/traefik_v2.0.0-alpha4_linux_$arch.tar.gz"; \
+	wget --quiet -O /tmp/traefik.tar.gz "https://github.com/containous/traefik/releases/download/v2.0.0-alpha5/traefik_v2.0.0-alpha5_linux_$arch.tar.gz"; \
 	tar xzvf /tmp/traefik.tar.gz -C /usr/local/bin traefik; \
 	rm -f /tmp/traefik.tar.gz; \
 	chmod +x /usr/local/bin/traefik
@@ -22,5 +22,5 @@ LABEL org.opencontainers.image.vendor="Containous" \
       org.opencontainers.image.url="https://traefik.io" \
       org.opencontainers.image.title="Traefik" \
       org.opencontainers.image.description="A modern reverse-proxy" \
-      org.opencontainers.image.version="v2.0.0-alpha4" \
+      org.opencontainers.image.version="v2.0.0-alpha5" \
 			org.opencontainers.image.documentation="https://docs.traefik.io"
diff --git a/traefik_faisselle-nanoserver-sac2016/Dockerfile b/traefik_faisselle-nanoserver-sac2016/Dockerfile
index 6d6ae41..ea62abe 100644
--- a/traefik_faisselle-nanoserver-sac2016/Dockerfile
+++ b/traefik_faisselle-nanoserver-sac2016/Dockerfile
@@ -10,5 +10,5 @@ LABEL org.opencontainers.image.vendor="Containous" \
       org.opencontainers.image.url="https://traefik.io" \
       org.opencontainers.image.title="Traefik" \
       org.opencontainers.image.description="A modern reverse-proxy" \
-      org.opencontainers.image.version="v2.0.0-alpha4" \
+      org.opencontainers.image.version="v2.0.0-alpha5" \
 			org.opencontainers.image.documentation="https://docs.traefik.io"
diff --git a/traefik_faisselle-nanoserver-sac2016/traefik.exe b/traefik_faisselle-nanoserver-sac2016/traefik.exe
index 275ea5d..2748345 100755
Binary files a/traefik_faisselle-nanoserver-sac2016/traefik.exe and b/traefik_faisselle-nanoserver-sac2016/traefik.exe differ
diff --git a/traefik_faisselle/Dockerfile b/traefik_faisselle/Dockerfile
index 98e9d25..ee15e1e 100644
--- a/traefik_faisselle/Dockerfile
+++ b/traefik_faisselle/Dockerfile
@@ -10,5 +10,5 @@ LABEL org.opencontainers.image.vendor="Containous" \
       org.opencontainers.image.url="https://traefik.io" \
       org.opencontainers.image.title="Traefik" \
       org.opencontainers.image.description="A modern reverse-proxy" \
-      org.opencontainers.image.version="v2.0.0-alpha4" \
+      org.opencontainers.image.version="v2.0.0-alpha5" \
 			org.opencontainers.image.documentation="https://docs.traefik.io"
diff --git a/traefik_faisselle/traefik b/traefik_faisselle/traefik
index 0a019a4..8d635ed 100755
Binary files a/traefik_faisselle/traefik and b/traefik_faisselle/traefik differ
```

</details>

**Comment by yosifkit** [comment]
It seems that `traefik:v2.0.0-alpha5-alpine` is failing the [`override-cmd` test](https://github.com/docker-library/official-images/tree/3f87965eeb524bd3d47d0b5f37381c71fe20f71f/test/tests/override-cmd) by passing the command as arguments to traefik instead of running them and thus not exiting.

The test is roughly `docker run traefik:v2.0.0-alpha5-alpine echo Hello world-$RANDOM-$RANDOM` but is meant to mean that `docker run -it --rm traefik:v2.0.0-alpha5-alpine sh` should work. See also [Consistency](https://github.com/docker-library/official-images/tree/3f87965eeb524bd3d47d0b5f37381c71fe20f71f#consistency) in the readme.

**Comment by ldez** [comment]
@yosifkit is it a new requirement?

**Comment by yosifkit** [comment]
Nope, it is why you added an `entrypoint.sh` in the alpine images (https://github.com/containous/traefik-library-image/pull/6).

**Comment by ldez** [comment]
It's a regression from our side, so I close this PR, sorry.

**Pull request closed without merging**
