### PR TITLE
Update amazoncorretto

### PR DESCRIPTION
**Pull request by Autumn808**
Update amazoncorretto

### CODE REVIEW

**Review by lutkerd — COMMENTED** [review]
This isn't the right version of the tags, please grab them from https://github.com/corretto/corretto-docker/commit/0ccbb9690e150194bd26c6419654722cda6595e4#commitcomment-137305343

**Review by Autumn808 — COMMENTED** [review]
Updating version and maintainers

**Comment by lutkerd** [comment]
Tag updates and additional maintainers LGTM.

**Review by yosifkit — APPROVED** [review]

**Comment by tianon** [comment]
Welcome, @Autumn808 and @chadrako :smile:

**Pull request merged**
