### PR TITLE
Rocky Linux updates for 8.6

### PR DESCRIPTION
**Pull request by NeilHanlon**
* Introduce new minimal image

### CODE REVIEW

**Comment by NeilHanlon** [comment]
There was some conversation in my previous [pr](https://github.com/docker-library/official-images/pull/12435) about the usage of 'latest', however we've had the latest tag in there since the beginning and it hasn't been an issue. Please advise!

Best,
Neil

**Comment by tianon** [comment]
Oh, maybe I can clarify what was meant there -- having a `latest` tag is totally fine, but the point is that users are not expected to `docker run foo:latest` (it only exists for enabling `docker run foo`), so `docker run foo:latest-something` is unexpected and likely misnamed; usually `foo:something` is more natural/expected (so in your case, `rockylinux:minimal` is totally sane, but up to you whether you want to include it). :+1:

The diff comment CI is failing here because it's trying to post a comment with a diff of the old tarball to the new tarball, and the diff is larger than it can successfully comment (:weary:).  Usually we only see that on major updates (like Rocky Linux 8 -> 9), and it's weird to see such a dramatic difference in the tarball file listing in a minor release.  However, it's not necessarily _entirely_ unexpected -- in cases like that, we usually just (manually) post the diff to a gist instead and link it here:

Full Diff: https://gist.github.com/docker-library-bot/6149d59f722c3f7ae57ae3ed6f2b7e47

(We use the diff to review for unexpected changes -- in the case of base images, that's typically looking for unexpected packages like `grub` accidentally sneaking in, which is something we catch frequently on other base images :sweat_smile: :heart:)

**Comment by tianon** [comment]
Oh, the diff is primarily deletions because you're introducing a new minimal image -- that's entirely expected all around. :smile:

**Comment by NeilHanlon** [comment]
> Oh, maybe I can clarify what was meant there -- having a `latest` tag is totally fine, but the point is that users are not expected to `docker run foo:latest` (it only exists for enabling `docker run foo`), so `docker run foo:latest-something` is unexpected and likely misnamed; usually `foo:something` is more natural/expected (so in your case, `rockylinux:minimal` is totally sane, but up to you whether you want to include it). +1


Ah, I see. I'll leave it out, as I doubt people will use that over the 8-minimal (and future 9-minimal) tags, anyways.

Thank you for the explanation.

Yes, I suspected the diff failures were due to the addition of the minimal image and it not finding an appropriate image to diff against -- along with a naming convention change to support multiple variants.

Best,
Neil

**Comment by tianon** [comment]
Ah, and a case of the diff-generator getting confused and re-diffing 8.5 and 8.6 -- for avoiding that in the future, I'd suggest swapping the order of the tags listed in `Tags:` (such that least-specific tags like `latest` come last in the list and most-specific tags come first).

Also, I'd suggest removing the 8.5 tags unless you're going to do further updates to 8.5 -- here's our standard boilerplate about that:

> Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

I'll merge this for now (because the 8.5 conversation is really orthogonal), but if you determine that 8.5 is not going to receive further updates, I'd love to see a follow-up that removes it. :smile:

**Pull request merged**
