### PR TITLE
added code_of_conduct

### PR DESCRIPTION
**Pull request by jivthesh**

### CODE REVIEW

**Comment by tianon** [comment]
Can you please provide some additional information like where you sourced this from and why you think this particular one is the best choice for our community?

**Comment by Veratriz** [comment]
Soy nueva y estoy de pruebas.  Gracias

**Comment by jivthesh** [comment]
@tianon This Code of Conduct is adapted from the Contributor Covenant, version 1.4, available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

**Comment by tianon** [comment]
@Veratriz please move your testing elsewhere (a personal repository would be the most appropriate place)

**Comment by hairyhenderson** [comment]
Also relevant is the "Docker Code of Conduct" here: https://github.com/docker/code-of-conduct

It's _"used at DockerCon and other events, meetups, and user groups."_ but I wonder if it'd be good to fit it to community code as well (including this repo)?

**Comment by hairyhenderson** [comment]
Oh I see @tianon's already following that thread at https://github.com/docker/code-of-conduct/issues/34 😉

**Pull request closed without merging**
