### PR TITLE
Update tomee to 8.0.16, drop 7.x

### PR DESCRIPTION
**Pull request by jungm**

### CODE REVIEW

**Comment by yosifkit** [comment]
I don't see @jungm as part of https://github.com/tomitribe/docker-tomee, but the commits listed in the library file are all correct. So, this looks fine to me.

 @lordofthejars @otaviojava @jgallimore @scriptmonkey: can one of you verify that you are ready/ok with this update?

---

```diff
old mode 100644
new mode 100755
```
Setting executability on a bunch of the Dockerfiles seems odd, but harmless.

**Comment by yosifkit** [comment]
```console
+ curl -fSL https://dist.apache.org/repos/dist/release/tomee/tomee-7.0.9/apache-tomee-7.0.9-plume.tar.gz.asc -o tomee.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

```console
+ curl -fSL https://dist.apache.org/repos/dist/release/tomee/tomee-7.1.4/apache-tomee-7.1.4-plume.tar.gz.asc -o tomee.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

Also, the `7.x` series each need an update as the current versions are no longer available.

**Comment by scriptmonkey** [comment]
@yosifkit I will check it with it the hour.

**Comment by jungm** [comment]
@yosifkit we now decided to stop supporting tomee 7.x, it has been EOL for quite some time now

related dicussion on tomee mailing list: https://lists.apache.org/thread/0xhnlqs91tz15tfvh2gsypkccyj5s3x8

**Comment by scriptmonkey** [comment]
@yosifkit I approved and merged the PR in the docker-tomee repo.  Therefore, I am good with this update.

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
