### PR TITLE
Update Jenkins to 1.605 weekly, add weekly tag

### PR DESCRIPTION
**Pull request by lamielle**
Update the 'latest' tag to 1.605 and add the weekly tag which also
points at this same hash.

### CODE REVIEW

**Comment by lamielle** [comment]
See #635 for an issue I filed to do what this PR implements.  I'd love to get this merged.  @ndeloof could you take a look?

**Comment by lamielle** [comment]
@ndeloof and/or @yosifkit any update here?  As far as I can tell this PR is fine, please let me know if there's anything I can do to move it along.  I'd really like to use this image with the latest Jenkins versions.

**Comment by ndeloof** [comment]
We don't publish weekly anymore, as the official image manual review process makes it hard to get them up-to-date. I'm going to propose jenkins-ci governance board to publish them under jenkins-ci namespace

**Comment by lamielle** [comment]
So the official images will only ever contain LTS Jenkins releases?  Just trying to understand what to expect from this source of Docker images for Jenkins.

It sounds like I should switch away from this particular image if I want up to date software.  If that is the answer feel free to close this PR and the associated issue I filed.  Thank for you the response!

**Comment by ndeloof** [comment]
yes, official image will focus on LTS release, which is what most user request as "latest"

**Comment by ndeloof** [comment]
@yosifkit  please close this issue

**Pull request closed without merging**
