### PR TITLE
[percona] update product versions

### PR DESCRIPTION
**Pull request by vorsel**
1. update all psmdb versions
2. update ps57 version
3. change base OS for ps-57 from centos8 to ol8
4. remove outdated versions of psmdb-36, psmdb-40
5. add new maintainer and remove old one

### CODE REVIEW

**Comment by tianon** [comment]
Relevant to the CI failure, I would love to check back in on https://github.com/docker-library/official-images/pull/12399#issuecomment-1123014876 -- any update on removing or updating those older versions? :grimacing:

**Comment by yosifkit** [comment]
> Relevant to the CI failure, I would love to check back in on [#12399 (comment)](https://github.com/docker-library/official-images/pull/12399#issuecomment-1123014876) -- any update on removing or updating those older versions? grimacing

Friendly ping. Any update?

**Comment by vorsel** [comment]
> > Relevant to the CI failure, I would love to check back in on [#12399 (comment)](https://github.com/docker-library/official-images/pull/12399#issuecomment-1123014876) -- any update on removing or updating those older versions? grimacing
> 
> Friendly ping. Any update?

Sorry for the late reply.
All the issues were addressed.

**Comment by yosifkit** [comment]
We recommend against using blanket package upgrades (`apt-get upgrade`/`apk upgrade`/`yum upgrade`/`yum update`) for official-images. When package upgrades are applied in a dependent image, it duplicates content of the base image, making the image larger than necessary. It also only delays the inevitable "there are outdated packages". The Official Images build pipeline makes heavy use of `docker build` cache, so we make periodic base image updates to then fully rebuild all dependent images (e.g. the [Debian image updates](https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fdebian)).

>We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need, e.g. [docker-library/official-images#2171](https://github.com/docker-library/official-images/issues/2171). Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule. These refreshed base images also means that any other image in the Official Images program that is `FROM` them will also be rebuilt (as described in [the project `README.md` file](https://github.com/docker-library/official-images#library-definition-files)).
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by tianon** [comment]
Friendly ping :bow:

**Comment by vorsel** [comment]
Hi @tianon , @yosifkit 
I apologize for such a delay, we've updated the PR, please re-check it at your convenience.

**Review by yosifkit — APPROVED** [review]

**Comment by tianon** [comment]
Thank you! :heart:

FYI, this appears to have removed `latest`, which means that tag will no longer be updated -- I'm hoping this was intentional, but if not, it should be easy to add back in another PR. :smile:

**Pull request merged**
