### PR TITLE
node: update to v15.0.0

### PR DESCRIPTION
**Pull request by SimenB**
https://nodejs.org/en/blog/release/v15.0.0/

### CODE REVIEW

**Comment by nschonni** [comment]
Should we try and figure out why `arm64v8` and `ppcle64` are having issues before landing the 15.0.1?

**Comment by SimenB** [comment]
no, we shouldn't block a bug fix for regressions in v15 on something like that

**Comment by yosifkit** [comment]
From the logs, it looks like the pp64le build worked fine but must've accidentally got deleted before the job was done (server was completely full, so "ripe" images were being cleaned); a new build is in the queue.  As for `arm64v8`, we're looking into it (`node` isn't the only failure :scream:), but it seems to be host related.

**Comment by nschonni** [comment]
✨ awesome. If we land the 15.0.1 upstream, you can make the call on whether the PR here lands here anyway

**Comment by tianon** [comment]
I've retriggered arm64v8, and the only failures are `node:15.0.0-stretch` and `node:15.0.0-stretch-slim` (not `buster` or `alpine3.12`), so IMO this is not worth holding anything up for.

**Pull request merged**
