### PR TITLE
Update node.js v9.x to v10.6.0

### PR DESCRIPTION
**Pull request by PeterDaveHello**
- https://github.com/nodejs/docker-node/pull/807#event-1716790836
- https://github.com/nodejs/node/releases/tag/v10.6.0
- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.6.0

### CODE REVIEW

**Comment by yosifkit** [comment]
<details>
<summary>Diff:</summary>

```diff
diff --git a/_bashbrew-list b/_bashbrew-list
index 3fbcf92..46b8f08 100644
--- a/_bashbrew-list
+++ b/_bashbrew-list
@@ -57,16 +57,16 @@ node:10-alpine
 node:10-jessie
 node:10-slim
 node:10-stretch
-node:10.5
-node:10.5-alpine
-node:10.5-jessie
-node:10.5-slim
-node:10.5-stretch
-node:10.5.0
-node:10.5.0-alpine
-node:10.5.0-jessie
-node:10.5.0-slim
-node:10.5.0-stretch
+node:10.6
+node:10.6-alpine
+node:10.6-jessie
+node:10.6-slim
+node:10.6-stretch
+node:10.6.0
+node:10.6.0-alpine
+node:10.6.0-jessie
+node:10.6.0-slim
+node:10.6.0-stretch
 node:alpine
 node:boron
 node:boron-alpine
diff --git a/node_alpine/Dockerfile b/node_alpine/Dockerfile
index 8ec2690..096526f 100644
--- a/node_alpine/Dockerfile
+++ b/node_alpine/Dockerfile
@@ -1,6 +1,6 @@
 FROM alpine:3.7
 
-ENV NODE_VERSION 10.5.0
+ENV NODE_VERSION 10.6.0
 
 RUN addgroup -g 1000 node \
     && adduser -u 1000 -G node -s /bin/sh -D node \
diff --git a/node_latest/Dockerfile b/node_latest/Dockerfile
index ab177e4..7164b51 100644
--- a/node_latest/Dockerfile
+++ b/node_latest/Dockerfile
@@ -21,7 +21,7 @@ RUN set -ex \
     gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
   done
 
-ENV NODE_VERSION 10.5.0
+ENV NODE_VERSION 10.6.0
 
 RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
   && case "${dpkgArch##*-}" in \
diff --git a/node_slim/Dockerfile b/node_slim/Dockerfile
index 74523c8..57de424 100644
--- a/node_slim/Dockerfile
+++ b/node_slim/Dockerfile
@@ -21,7 +21,7 @@ RUN set -ex \
     gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
   done
 
-ENV NODE_VERSION 10.5.0
+ENV NODE_VERSION 10.6.0
 
 RUN buildDeps='xz-utils' \
     && ARCH= && dpkgArch="$(dpkg --print-architecture)" \
diff --git a/node_stretch/Dockerfile b/node_stretch/Dockerfile
index d79ed1b..0ebb4cb 100644
--- a/node_stretch/Dockerfile
+++ b/node_stretch/Dockerfile
@@ -21,7 +21,7 @@ RUN set -ex \
     gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
   done
 
-ENV NODE_VERSION 10.5.0
+ENV NODE_VERSION 10.6.0
 
 RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
   && case "${dpkgArch##*-}" in \
```

</details>

**Comment by PeterDaveHello** [comment]
Thank you.

**Comment by SimenB** [comment]
Why wasn't 9 removed? Doesn't really matter I suppose, but it's EOL

**Comment by PeterDaveHello** [comment]
Should be a mistake

**Pull request merged**
