### PR TITLE
Bug fix: Possibility to use ZEO_ADDRESS with together with ADDONS

### PR DESCRIPTION
**Pull request by avoinea**

### CODE REVIEW

**Comment by yosifkit** [comment]
Changes seem fine. There seems to be a bunch of extra commits in the PR (probably because I did "squash and merge" on the previous PR). You should be able to clear them up with the following:

```console
$ # ensure you start on your master branch (the one the PR is based on)
$ git checkout master
$ # "stash" our wanted commit in another branch
$ git checkout -b temp
$ # switch back to master
$ git checkout master
$ # fetch upstream
$ git fetch https://github.com/docker-library/official-images.git master
$ # reset avoinea master to official-images master
$ git reset --hard FETCH_HEAD
$ #  cherry pick the new commit
$ git cherry-pick 7f9c048428c8589df5d769e7f5e59833d1d8a014
$ # force changes back into avoinea/master on github
$ git push -f
$ # make sure PR and log look correct and then
$ git branch -D temp
```

This should make it less likely to happen next time, though I would recommend the simplest solution is to checkout official-images master branch each time to ensure you are working from the latest tree.

**Comment by avoinea** [comment]
@yosifkit 

Fixed it, but meanwhile I found an issue in the sense that you can not use `ADDONS` and `ZEO_ADDRESS` environment variables together. Thus the second commit.

Please let me know if this is ok, or if not, how should we handle this kind of issues. Should we rebuild all tags, or?

**Comment by yosifkit** [comment]
It's up to you if you want to apply your env fixes to all the images or not.  You can do a separate PR that just does that fix to all images and then this PR to remove all the old versions, or just leave all the old versions as "unsupported".

**Comment by avoinea** [comment]
@yosifkit ok, thanks. Will use this PR for the fix and add another one latter to remove the old tags.

**Comment by yosifkit** [comment]
Sounds good!
```diff
diff --git a/plone_4.3.10/docker-entrypoint.sh b/plone_4.3.10/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_4.3.10/docker-entrypoint.sh
+++ b/plone_4.3.10/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_4.3.7/docker-entrypoint.sh b/plone_4.3.7/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_4.3.7/docker-entrypoint.sh
+++ b/plone_4.3.7/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_4.3.8/docker-entrypoint.sh b/plone_4.3.8/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_4.3.8/docker-entrypoint.sh
+++ b/plone_4.3.8/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_4.3.9/docker-entrypoint.sh b/plone_4.3.9/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_4.3.9/docker-entrypoint.sh
+++ b/plone_4.3.9/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_4/docker-entrypoint.sh b/plone_4/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_4/docker-entrypoint.sh
+++ b/plone_4/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_5.0.2/docker-entrypoint.sh b/plone_5.0.2/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_5.0.2/docker-entrypoint.sh
+++ b/plone_5.0.2/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_5.0.3/docker-entrypoint.sh b/plone_5.0.3/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_5.0.3/docker-entrypoint.sh
+++ b/plone_5.0.3/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_5.0.4/docker-entrypoint.sh b/plone_5.0.4/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_5.0.4/docker-entrypoint.sh
+++ b/plone_5.0.4/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_5.0.5/docker-entrypoint.sh b/plone_5.0.5/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_5.0.5/docker-entrypoint.sh
+++ b/plone_5.0.5/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
diff --git a/plone_latest/docker-entrypoint.sh b/plone_latest/docker-entrypoint.sh
index 5644bdb..72bd07c 100755
--- a/plone_latest/docker-entrypoint.sh
+++ b/plone_latest/docker-entrypoint.sh
@@ -10,6 +10,7 @@ python /docker-initialize.py
 if [ -e "custom.cfg" ]; then
   if [ ! -e "bin/develop" ]; then
     bin/buildout -c custom.cfg
+    python /docker-initialize.py
   fi
 fi
 
```

**Pull request merged**
