### PR TITLE
Add h2o.

### PR DESCRIPTION
**Pull request by bardiharborow**
- [x] associated with or contacted upstream?
  -  upstream [contacted](https://github.com/h2o/h2o/issues/1977)
- [x] does it fit into one of the common categories? ("service", "language stack", "base distribution")
  - general purpose web server service
- [x] is it reasonably popular, or does it solve a particular use case well?
  - 8k stars, somewhat niche but written by an engineer at Fastly and contains many novel optimizations
- [ ] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
  - will draft following positive indication re inclusion
- [ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
- [ ] 2+ dockerization review?
- [x] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
  - based on `alpine:3.9`
- [x] ~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~
  - not applicable
- [ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tianon** [comment]
To be clear, upstream in this case would _not_ be https://github.com/lkwg82/h2o.docker, but rather https://github.com/h2o/h2o.

**Comment by bardiharborow** [comment]
> To be clear, upstream in this case would _not_ be https://github.com/lkwg82/h2o.docker, but rather https://github.com/h2o/h2o.

To clarify, lkwg82/h2o.docker is the semi-official (maintained by one core maintainer) docker image for the project, it's just not under the h2o organisation for some reason. I'll ping the founding maintainer there to make sure we've all on the same page.

**Comment by tianon** [comment]
Nothing against lkwg82, but where is he listed as a "core maintainer" for h2o?  As far as I can tell, https://github.com/h2o/h2o/pull/1905 is the only contribution he's made there. :confused:

**Comment by bardiharborow** [comment]
He's a organization member which is where I got that idea from, but I'll just file a h2o/h2o issue at this point. Sorry for the confusion.

**Comment by tianon** [comment]
Any luck getting the h2o community interested in helping to maintain (or at least bless the efforts) here?

**Comment by bardiharborow** [comment]
h2o/h2o#1977 is as far as I got, not sure if that is enough.

**Comment by yosifkit** [comment]
Extreme apologies for the slow reply. :bowing_man: New images unfortunately get the least priority but often take the most time to review, so they often fall by the wayside. Fortunately, this image is fairly simple and overall Dockerization seems quite reasonable (i.e. LGTM!).

Only minor bits of feedback:
- update the `library/h2o` file with the newest `GitCommit` + version tags (still pointing to 2.2.5)
   - you are welcome to keep `2.2.5` along with adding `2.2.6` if you'd like to have an initial backfill of the older release (to be removed in another PR)
- swap `LABEL maintainer` to `org.opencontainers.image.authors` (labels aren't required on official images and you are welcome to make your own choice for which, if any, you want to have)
    > Image label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md.
- consider moving runtime dependencies (and the user creation?) to be a separate `RUN` above the `H20_VERSION` (can help layer cache across version updates)
- consider updating to alpine `3.11` (not necessary right now since `3.9` and `3.10` are still [security supported](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases))
- thoughts on providing images for pre-releases (like `2.3.0-beta2`) as well (not necessary, but can be useful for users)
- docs PR (which you noted we be drafted once we gave "positive indication re inclusion")

Thanks!

**Comment by tianon** [comment]
Closing this for now -- when the repository is updated with the requested changes and you're ready to recommit to maintaining this image, please reopen! :heart:

**Comment by pbowyer** [comment]
@bardiharborow Hi, is there anything I can do to help get this image live?

**Pull request closed without merging**
