### PR TITLE
Update Clear Linux OS to 33780

### PR DESCRIPTION
**Pull request by clrbuilder**
Update Clear Linux OS latest+base images to release 33780

@bryteise @alexjch

### CODE REVIEW

**Comment by yosifkit** [comment]
This one still has the extra `elfutils` files like last week in https://github.com/docker-library/official-images/pull/8788. Do you want to move forward on this one?

**Comment by phmccarty** [comment]
No, I would prefer to wait. The fix landed in 33790, but we were unable to release that build (or a newer one) yet.

**Comment by phmccarty** [comment]
@yosifkit A new release was just published, so we will trigger a new PR.

**Comment by phmccarty** [comment]
Superseded by #8845

**Pull request closed without merging**
