### PR TITLE
2.x branch does not yet include a LTS release

### PR DESCRIPTION
**Pull request by ndeloof**
one should not expose this one as official image

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

This doesn't remove images from the hub, but will update the "supported versions" list at the top.

**Comment by tianon** [comment]
Any particular reason it's unsuitable?  I was honestly excited to see 2.x getting updates here. :smile:

**Comment by ndeloof** [comment]
@tianon 2.x is available (as all other weekly builds) in `jenkinsci/jenkins` repository
official repo is about curated, so LTS releases. A 2.x will land here at some time, but too early for this. Typically, 2.0 is available as `jenkins:2.0` but includes a major security issue :-\

**Comment by tianon** [comment]
Ah ok, fair enough! :disappointed:

**Pull request merged**
