### PR TITLE
Update Amazon Linux images

### PR DESCRIPTION
**Pull request by kgharris**
Hi - this is Kyle from the Amazon Linux team - these are 4 new containers for our 2.0.20210813.1 release - please go ahead and put them out for us when you get a chance - thanks!

### CODE REVIEW

**Comment by tianon** [comment]
Welcome! :wave:

Since this is obviously bits coming from the right repo (and all looks correct), I'm not going to block it on the maintainer change, but I am going to cc the other image maintainers as an FYI: @amazonlinux @fred-lefebvre @samuelkarp @stewartsmith @jamieand @mysteriouspants @sktomer @cbgbt @trampal

(Easy enough to revert if Kyle here is being overzealous! :smile:)

**Comment by mysteriouspants** [comment]
Nope Kyle is all good. Sorry for not getting to this sooner.

**Comment by kgharris** [comment]
Thanks @tianon :)

**Comment by stewartsmith** [comment]
yep, all good with @kgharris

**Pull request merged**
