### PR TITLE
Switch Node image to use Joyent, Inc repo

### PR DESCRIPTION
**Pull request by chorrell**
Our repo is here: https://github.com/joyent/docker-node

(It's pretty much a copy of https://github.com/docker-library/node, so no surprises :)

### CODE REVIEW

**Comment by yosifkit** [comment]
Awesome, I am glad upstream is getting involved. :smile: :tada:

First suggestion is to put a `LICENSE` file in your repo so everyone knows the license on the files there.

I suggest that you also copy the `update.sh` and `generate-stackbrew-library.sh` from our current repo to make it easier for you to maintain.  The update script will scrape the `http://nodejs.org/dist` page to find the latest minor version for each of `0.8`, `0.10`, and `0.11` and push it into all the dockerfiles.  It also checks for updates to npm and makes sure the onbuild dockerfiles are `FROM` the most recent of their respective versions.  The update script can be run on all versions (folders in the repo) with `./update.sh` or on a specific version `./update.sh 0.10` (with or without a trailing slash on the `0.10/`).  The generate script outputs the contents of this library file (so you can do `./generate-stackbrew-library.sh > ../official-images/library/node`). It would just need an update to line 13 where the url of the repo is set, and line 15 to the new maintainer.

**Comment by chorrell** [comment]
Done and done! 

Those scripts will be super useful next time we update :)

Oh, also I just pushed another commit to update the email address for "maintainer"  -- I had a better address created for my team.

**Comment by tianon** [comment]
LGTM :heart:

Build test of #393; 8be75c674035393f7873de58708466b8600776fb (`node`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/8be75c674035393f7873de58708466b8600776fb/library/node
Cloning node (git://github.com/joyent/docker-node) ...
Processing node:0.10.35 ...
Processing node:0.10 ...
Processing node:0 ...
Processing node:latest ...
Processing node:0.10.35-onbuild ...
Processing node:0.10-onbuild ...
Processing node:0-onbuild ...
Processing node:onbuild ...
Processing node:0.10.35-slim ...
Processing node:0.10-slim ...
Processing node:0-slim ...
Processing node:slim ...
Processing node:0.11.14 ...
Processing node:0.11 ...
Processing node:0.11.14-onbuild ...
Processing node:0.11-onbuild ...
Processing node:0.11.14-slim ...
Processing node:0.11-slim ...
Processing node:0.8.28 ...
Processing node:0.8 ...
Processing node:0.8.28-onbuild ...
Processing node:0.8-onbuild ...
Processing node:0.8.28-slim ...
Processing node:0.8-slim ...
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
