### PR TITLE
Adding centOS tag

### PR DESCRIPTION
**Pull request by arthurdm**
Adding a tag for CentOS-based image.  This image runs as non-root, which allows it to run in restricted environments such as OpenShift.

This image is also important for developers that want to use CentOS for dev and RHEL for production.

### CODE REVIEW

**Comment by tianon** [comment]
This `Dockerfile` includes `COPY --from=websphere-liberty:kernel ...` which suffers from the same issues as multi-stage builds (enumerated/discussed over in https://github.com/docker-library/official-images/issues/3383#issuecomment-329259161).

**Comment by arthurdm** [comment]
Thx @tianon - I added a comment in that issue.

**Comment by tianon** [comment]
I'm not sure I fully understand the importance of providing a CentOS-based
image as well -- isn't part of the point of using Java and tools
like WebSphere Liberty that you don't care as much about the underlying
operating system?  What does this change for usage of the image from a
functional perspective?

**Comment by arthurdm** [comment]
hi @tianon - any updates on this?

**Comment by yosifkit** [comment]
This comment still applies: https://github.com/docker-library/official-images/pull/4326#issuecomment-387190856. Unfortunately, none of our tooling can handle multi-stage builds including just `COPY --from` another official image.

**Comment by arthurdm** [comment]
ok.   thanks @yosifkit - I will close this PR then.

**Pull request closed without merging**
