### PR TITLE
Update Amazon Linux images

### PR DESCRIPTION
**Pull request by iliana**

### CODE REVIEW

**Comment by iliana** [comment]
Looks like some Git LFS-related failures in the diff and the failed checks? :(

**Comment by yosifkit** [comment]
Yeah, we still can't use LFS :disappointed: (https://github.com/docker-library/bashbrew/issues/10).

**Comment by iliana** [comment]
Used to be it was just ignored, though... is it a blocker now?

**Comment by yosifkit** [comment]
Oh, it was ignored when we ran locally because we didn't have lfs installed, but the github actions definitely do :cry:.  Thoughts @tianon?

**Comment by iliana** [comment]
We could potentially modify the actions to run `git lfs uninstall` prior to cloning repos to remove the global hooks?

**Comment by iliana** [comment]
I can try and figure that out and send a PR if y'all like, since I think we're the only repo doing these shenanigans.

**Comment by tianon** [comment]
My initial thought was exactly the same before I saw your reply. :laughing: 

I did some research on LFS and it appears to support a `GIT_LFS_SKIP_SMUDGE` environment variable for disabling the smudge filters, so I think I'd rather we explore that before we get drastic and just purge LFS from the Actions environment.  I'll play a little bit and see if I can get this working properly. :+1: :heart:

**Comment by iliana** [comment]
🎉

**Comment by tianon** [comment]
Yay, success!! :smile:

**Pull request merged**
