### PR TITLE
Update bonita, add 2023.2

### PR DESCRIPTION
**Pull request by rbioteau**
* Add 2023.2 version
* Update maintainers
* Update fetch reference branch
* Remove old unsupported version

### CODE REVIEW

**Comment by yosifkit** [comment]
Using `uname -m` or `arch` for platform detection is very strongly discouraged, as it retrieves the kernel's architecture (from the host), when you really need to retrieve the userspace architecture of the image. `apk --print-arch` or `dpkg --print-architecture` are going to be the most reliable options.

---

I'm confused by the addition of `gosu` as it doesn't appear to be used anywhere because `su-exec` is used instead and installed from Alpine packages via `apk`. `gosu` version `1.13` is also a bit out of date (https://github.com/tianon/gosu/releases).

---

```dockerfile
VOLUME ["/opt/bonita/conf/logs"]
```

Does the application expect to modify the directory in a persistent way that needs to stick around from invocation to invocation? (Given the "permanence" of a `VOLUME` declaration, we recommend keeping them to only the directories the application stores active state in, and even more specifically active state that's actually necessary to keep if the container is completely destroyed and recreated, such as MySQL's `/var/lib/mysql` directory.)  I recommend documenting directories like this that users may want to save beyond container lifecycle. (But if you really want users to get an anonymous automatic volume on when they don't specify one because the logs are important, then that is also fine)

**Comment by rbioteau** [comment]
@yosifkit Thanks for the feedback !

> Using `uname -m` or `arch` for platform detection is very strongly discouraged, as it retrieves the kernel's architecture (from the host), when you really need to retrieve the userspace architecture of the image. `apk --print-arch` or `dpkg --print-architecture` are going to be the most reliable options.
> 
> I'm confused by the addition of `gosu` as it doesn't appear to be used anywhere because `su-exec` is used instead and installed from Alpine packages via `apk`. `gosu` version `1.13` is also a bit out of date (https://github.com/tianon/gosu/releases).

Indeed, `gosu` should be removed.

> ```dockerfile
> VOLUME ["/opt/bonita/conf/logs"]
> ```
> 
> Does the application expect to modify the directory in a persistent way that needs to stick around from invocation to invocation? (Given the "permanence" of a `VOLUME` declaration, we recommend keeping them to only the directories the application stores active state in, and even more specifically active state that's actually necessary to keep if the container is completely destroyed and recreated, such as MySQL's `/var/lib/mysql` directory.) I recommend documenting directories like this that users may want to save beyond container lifecycle. (But if you really want users to get an anonymous automatic volume on when they don't specify one because the logs are important, then that is also fine)

We used `VOLUME` as a way to explicit the "mountable" volumes. Regarding our use case, we should be able to remove it safely and document the mounting options.

All these changes will be applied in our development branch, is it ok on your side to approve the PR without these changes ?

We also have found an inconsistency in an older tag. Is it ok to change the git reference for this older tag without updating the version ? Will the image be rebuilt and overwritten, or is it against the publication policy ?

Thanks
Romain

**Comment by yosifkit** [comment]
> We also have found an inconsistency in an older tag. Is it ok to change the git reference for this older tag without updating the version ? Will the image be rebuilt and overwritten, or is it against the publication policy ?

Updating an already published image is perfectly fine. One of the main tenets of Docker Official Images is to rebuild for updates and security fixes. All of the official images listed in the `library` files are subject to rebuild when their base image is updated I.E., if the `ubuntu` images are updated, then all official images from `ubuntu` will be rebuilt upon those new images.

**Comment by yosifkit** [comment]
> All these changes will be applied in our development branch, is it ok on your side to approve the PR without these changes ?

For the Volume, that is up to you if you want to change it. For the unneeded `gosu` + `arch`, I'd strongly encourage their removal and updating this PR in order to keep the official images at their best.

**Comment by rbioteau** [comment]
@yosifkit I removed `gosu` and related `arch` usage. For the `VOLUME` we will make additional testing before updating the images.
We are currently performing our release rollout and the merge of the PR is kind of blocking. 
Do you think you can merge it asap ?

Thanks a lot !

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
