### PR TITLE
Add support for "-t" in test/run.sh

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Example output:
```console
$ bashbrew list debian | xargs test/run.sh -t shellshock
testing debian:8.0
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:8
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:jessie
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:oldstable
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:sid
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:6.0.10
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:6.0
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:6
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:squeeze
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:stable
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:testing
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:unstable
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:7.8
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:7
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:wheezy
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:latest
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:rc-buggy
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
testing debian:experimental
	'utc' [1/2]...skipping due to -t
	'shellshock' [2/2]...passed
```

**Comment by yosifkit** [comment]
Why not delete the TODO that this fixes? https://github.com/docker-library/official-images/blob/master/test/run.sh#L70

**Comment by tianon** [comment]
(ie, updated)

**Comment by tianon** [comment]
Although I'm not sure if this is better, or if we should just replace that `tests=( ... )` like you originally appeared to have planned on doing.

**Comment by tianon** [comment]
This way has the nice benefit that I can do something like `bashbrew list --all | xargs test/run.sh -t python-hy` without a problem.

**Comment by yosifkit** [comment]
The other way would have been able to do that, you just would not have gotten all the "skippings" for tests not specified.

**Comment by tianon** [comment]
Wouldn't it have tried to run "python-hy" on things like "debian" or
"hello-world" ?

**Comment by tianon** [comment]
(since they don't have an explicit "excludes" for those others since they
aren't global tests)

**Comment by yosifkit** [comment]
No I would have cross referenced their set of tests with the argTests to get only the applicable ones.

**Comment by tianon** [comment]
Ahh, so basically how this one works anyways, just at a higher level so we
get less output.  Hmm.

**Comment by tianon** [comment]
Ok ok ok, @yosifkit; you win.  Double loop it is:
```console
$ bashbrew list debian | xargs test/run.sh -t shellshock
testing debian:8.0
	'shellshock' [1/1]...passed
testing debian:8
	'shellshock' [1/1]...passed
testing debian:jessie
	'shellshock' [1/1]...passed
testing debian:oldstable
	'shellshock' [1/1]...passed
testing debian:sid
	'shellshock' [1/1]...passed
testing debian:6.0.10
	'shellshock' [1/1]...passed
testing debian:6.0
	'shellshock' [1/1]...passed
testing debian:6
	'shellshock' [1/1]...passed
testing debian:squeeze
	'shellshock' [1/1]...passed
testing debian:stable
	'shellshock' [1/1]...passed
testing debian:testing
	'shellshock' [1/1]...passed
testing debian:unstable
	'shellshock' [1/1]...passed
testing debian:7.8
	'shellshock' [1/1]...passed
testing debian:7
	'shellshock' [1/1]...passed
testing debian:wheezy
	'shellshock' [1/1]...passed
testing debian:latest
	'shellshock' [1/1]...passed
testing debian:rc-buggy
	'shellshock' [1/1]...passed
testing debian:experimental
	'shellshock' [1/1]...passed
```

**Comment by tianon** [comment]
And more:
```console
$ bashbrew list debian python | xargs test/run.sh
testing debian:8.0
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:8
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:jessie
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:oldstable
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:sid
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:6.0.10
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:6.0
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:6
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:squeeze
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:stable
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:testing
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:unstable
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:7.8
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:7
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:latest
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:rc-buggy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing debian:experimental
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing python:2.7.9
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2.7
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2.7.9-onbuild
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2.7-onbuild
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2-onbuild
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2.7.9-slim
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2.7-slim
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2-slim
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...passed
	'python-pip-requests-ssl' [4/6]...passed
	'python-sqlite3' [5/6]...passed
	'python-zlib' [6/6]...passed
testing python:2.7.9-wheezy
	'utc' [1/6]...passed
	'shellshock' [2/6]...passed
	'python-hy' [3/6]...
......
```

**Comment by yosifkit** [comment]
To make sure I see the last logic correctly: if I give it say `debian` and then `-t python-hy`, it should print nothing, correct?

**Comment by tianon** [comment]
```console
$ bashbrew list debian | xargs test/run.sh -t python-hy
testing debian:8.0
testing debian:8
testing debian:jessie
testing debian:oldstable
testing debian:sid
testing debian:6.0.10
testing debian:6.0
testing debian:6
testing debian:squeeze
testing debian:stable
testing debian:testing
testing debian:unstable
testing debian:7.8
testing debian:7
testing debian:wheezy
testing debian:latest
testing debian:rc-buggy
testing debian:experimental
```

**Comment by yosifkit** [comment]
That seems fine to me.

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
