### PR TITLE
Add phpMyAdmin

### PR DESCRIPTION
**Pull request by williamdes**
Closes: https://github.com/phpmyadmin/docker/issues/56

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream?
    - https://github.com/phpmyadmin/docker
-	[x] does it fit into one of the common categories? ("service", "language stack", "base distribution")
    - "service"
-	[x] is it reasonably popular, or does it solve a particular use case well?
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/pull/1642
-	[x] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[x] 2+ dockerization review?
-	[x] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
    - `FROM php:xxx`
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[x] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by williamdes** [comment]
Should be okay now, review can start

**Comment by williamdes** [comment]
@yosifkit could you please review this one

**Comment by williamdes** [comment]
@yosifkit could you please review the new phpMyAdmin image ?

**Comment by J0WI** [comment]
_@williamdes you can use the [request review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review) feature._

**Comment by tianon** [comment]
Sorry for the delay (and thanks for your patience) :pray:

---

Taking an initial pass on the Dockerization, I've got a few comments:

> ```dockerfile
> FROM php:7.4-apache
> ```

Given the number of packages being installed, I'd recommend adjusting this to be explicit about the base OS version (so `FROM php:7.4-apache-buster` instead), which will allow you to control when it updates to `bullseye`, for example (because it will likely require more changes when that occurs).

The same goes for `FROM php:7.4-fpm-alpine` -> `FROM php:7.4-fpm-alpine3.11` and `FROM php:7.4-fpm` -> `FROM php:7.4-fpm-buster`.

(This is just a suggestion -- if you'd rather just have the builds potentially fail for the benefit of them maybe not failing and update them only if necessary, that's fine too. :+1:)

---

> ```dockerfile
> RUN { \
> ... \
>     } > $PHP_INI_DIR/conf.d/opcache-recommended.ini; \
> ...
> ```

This `RUN` line is using `;` as a separator, but doesn't include `set -e` like the other `RUN` lines doing the same (it's not likely that any of those `echo`s are going to fail, but we'd rather have the build fail than silently publish an image that's missing some bit of intended configuration).

> ```dockerfile
> LABEL version=$VERSION
> ```

See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

---

> ```dockerfile
> # Download tarball, verify it using gpg and extract
> RUN set -ex; \
>     fetchDeps=" \
> ...
>     apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $fetchDeps; \
> ```

I would recommend adjusting this to use the `apt-mark` behavior used in the lines above so that if one of the packages in `fetchDeps` was already installed, it doesn't get accidentally removed.

---

> ```dockerfile
>     curl --output phpMyAdmin.tar.xz --location $URL; \
> ```

Any invocation of `curl` should include `--fail` / `-f` (at a minimum).

---

> ```dockerfile
>     tar -xf phpMyAdmin.tar.xz -C /usr/src; \
> ...
>     mv /usr/src/phpMyAdmin-$VERSION-all-languages /usr/src/phpmyadmin; \
> ```

It's not critical, but this could be written more simply using `tar`'s `--strip-components` flag to avoid needing to use `$VERSION` at all here:

```dockerfile
     mkdir /usr/src/phpmyadmin; \
     tar -xf phpMyAdmin.tar.xz -C /usr/src/phpmyadmin --strip-components=1; \
```

---

> ```dockerfile
> # Add directory for sessions to allow session persistence
>     mkdir /sessions; \
>     mkdir -p /var/nginx/client_body_temp; \
> ```

> ```bash
>     # Custom folders for sessions
>     chown ${user}:${group} /sessions /var/nginx/client_body_temp
> ```

Is this still relevant, or is this a layover from a previous version of the `Dockerfile`?

---

> ```dockerfile
>     apk del .build-deps
> ```

It's not strictly required, but I would recommend adding `--no-network` to any `apk del` instruction.

---

> ```bash
>         echo >&2 "phpMyAdmin not found in $PWD - copying now..."
> ...
> ```

This section seems like it's been copied from the Wordpress image -- I have to wonder if the underlying intent for why Wordpress does this actually applies to phpMyAdmin?

For context, this pattern was adopted in Wordpress specifically because Wordpress has a tendency to treat the code of Wordpress itself as "mutable state" -- the configuration file can be updated/modified to a minor extent via the web UI (especially the initial configuration), plugins and themes get downloaded and installed directly inside the installation directory, but most relevantly Wordpress strongly recommends allow it to do self-auto-updates.

In this sense, the image is a "seed" for your Wordpress install, after which it's self-maintaining to some degree (minus system dependencies like PHP version / updates, etc).

Looking at https://github.com/phpmyadmin/phpmyadmin/wiki/Automatic_updates, it does not appear that phpMyAdmin has similar functionality/behavior (yet?), and looking further at https://github.com/phpmyadmin/phpmyadmin/issues/6155 it does not appear to be something that seems to be a high priority either.

Given all that, I wonder why phpMyAdmin is not simply being installed directly to `/var/www/html` in the image itself and thus not needing any copying behavior in the entrypoint?

**Comment by williamdes** [comment]
Thank you @tianon for the review
@J0WI made the changes in https://github.com/phpmyadmin/docker/pull/274 :muscle: 
It is merged and I am waiting for the next version of phpMyAdmin to update the PR

Everything seems right now ?

(I apologise for the delay to fix our image after the feedback)

**Comment by williamdes** [comment]
I also made a PR to apply your recommendation on labels
https://github.com/phpmyadmin/docker/pull/275

**Comment by J0WI** [comment]
@williamdes what do you think about the `echo >&2 "phpMyAdmin not found in $PWD - copying now..."`? Will phpMyAdmin become mutable in near future?

**Comment by williamdes** [comment]
> Will phpMyAdmin become mutable in near future?

What do you mean by mutable?

**Comment by J0WI** [comment]
> What do you mean by mutable?

That the files in `/var/www/html` change during runtime

**Comment by williamdes** [comment]
> > What do you mean by mutable?
> 
> That the files in `/var/www/html` change during runtime

No, I do not see any chance of such a feature in the future

Should I remove the line y mentioned ?

**Comment by ibennetch** [comment]
I wasn't the one who wrote the original Docker code, but strongly suspect that what tianon said is correct: downloading to `/usr/src/phpmyadmin` and then copying to `/var/www/html` is simply copied from some other project that had need of such functionality.

I see no reason why phpMyAdmin can't directly extract the files to `/var/www/html`. I've opened https://github.com/phpmyadmin/docker/issues/277 to put that in our to do list.

**Comment by williamdes** [comment]
@tianon could you please re-review this request ?

**Comment by williamdes** [comment]
Did somebody at Docker have some time to review our changes?

**Comment by J0WI** [comment]
@tianon this made some progress since your last review and it would be great to get an update on this :smiley:

**Comment by tianon** [comment]
> ```dockerfile
> ARG BUILD_DATE
> ARG VCS_REF
> ```

These aren't intended for us to set, right? (because our build processes will not provide any build args, and these will thus be empty on every build)

---

> ```dockerfile
> LABEL maintainer="The phpMyAdmin Team <developers@phpmyadmin.net>" \
> ```

See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

---

> ```dockerfile
> # Add directory for sessions to allow session persistence
> ```

:smile: :wink:

---

> ```sh
>     if [ "$(id -u)" = '0' ]; then
>         case "$1" in
>             apache2*)
>                 user="${APACHE_RUN_USER:-www-data}"
>                 group="${APACHE_RUN_GROUP:-www-data}"
>                 ;;
>             *) # php-fpm
>                 user='www-data'
>                 group='www-data'
>                 ;;
>         esac
>     else
>         user="$(id -u)"
>         group="$(id -g)"
>     fi
> ```

This section appears to be unused?

**Comment by williamdes** [comment]
@J0WI do I have to update the file now on this PR ?

**Comment by J0WI** [comment]
> @J0WI do I have to update the file now on this PR ?

Right after reviewing https://github.com/phpmyadmin/docker/pull/286 you can update the `GitCommit` here.

**Comment by williamdes** [comment]
@tianon I did update the file and rebase after the latest suggestions
Thank you for the review, it should be all right now

**Comment by ibennetch** [comment]
> Given all that, I wonder why phpMyAdmin is not simply being installed directly to /var/www/html in the image itself and thus not needing any copying behavior in the entrypoint?

After I modified the code to install directly to /var/www/html in the image, there were some reports from people with advanced configurations. The primary report [uses /var/www/html as a volume](https://github.com/phpmyadmin/docker/issues/284#issuecomment-619002215). There's an additional report that I'm not sure is related. The user [has a k8s install](https://github.com/phpmyadmin/docker/issues/284#issuecomment-617258021) where nginx won't serve the static parts of phpMyAdmin.

Because of the trouble with getting updates when mounting a volume, I'm likely to revert the change to downloading directly to /var/www/html, or modify it a bit so that the code tests if /usr/share/phpmyadmin is the same version as /var/www/html and overwrites it if it's not.

I'm mentioning this here because I didn't want it to even appear like I'm trying to trick you by fixing something you mentioned, then reverting it after you'd looked at it.

**Comment by emanuelb** [comment]
The change to use `--strip-components=1` instead of previous $VERSION usage, enable downgrade attacks (attacker change the content of downloaded file via curl command to be content of old version via MITM or malicious mirror, hacked server, etc...) which will pass the GPG test (they both signed with same key), the usage of $VERSION is the fix (as the mv operation will fail because the file don't exists if versions don't match between what in variable vs folder name inside downloaded archive)
another solution is to add hash checks (using sha256sum or b2sum commands)
I reported this issue a while ago, probably to security@ email, you can see some of the content here:
https://github.com/phpmyadmin/docker/issues/43

**Comment by tianon** [comment]
*We* would definitely love to see a checksum verification on top of the existing PGP verification. :smile:

**Comment by J0WI** [comment]
> attacker change the content of downloaded file via curl command to be content of old version via MITM or malicious mirror, hacked server, etc...

I tend to agree, but if you manage to break `https://files.phpmyadmin.net/` they are in huge trouble anyway...

**Comment by emanuelb** [comment]
> > attacker change the content of downloaded file via curl command to be content of old version via MITM or malicious mirror, hacked server, etc...
> 
> I tend to agree, but if you manage to break `https://files.phpmyadmin.net/` they are in huge trouble anyway...

The usage of GPG signing is for the reason that we don't trust the network, and it can return us everything in different scenarios (SSL MITM, malicious mirror/CDN/cloud-provider, or turned to be malicious as it's hacked by attacker)
see: https://www.qubes-os.org/faq/#what-does-it-mean-to-distrust-the-infrastructure
Thus attacker must steal the signing key in order to return malicious content instead (of course anyone who download files without verification will be owned in any of the above situations)
I suggested to add verification to downloads from the website in all places which was implemented in:
https://github.com/phpmyadmin/website/issues/24
The usage of mv with $VERSION was due to my report of downgrade attacks, as the new change to use `--strip-components=1` revert it(is regression) a fix is needed, adding checksum verification as well is the best course of action with using the new `--strip-components=1` method.

**Comment by tianon** [comment]
> ... adding checksum verification as well is the best course of action ...

Especially since https://files.phpmyadmin.net appears to have officially-published SHA256 values that should be pretty trivial to consume/embed! :smile:

**Comment by J0WI** [comment]
I created https://github.com/phpmyadmin/docker/pull/289 to add the checksum, but It not a big deal as long as the checksums are served from the same server.

@tianon is this a blocker for you?

**Comment by williamdes** [comment]
@tianon Is there something blocking this PR ?

**Comment by williamdes** [comment]
@yosifkit @tianon 

All the suggestions have been applied, and I merged the SHA checksum checking part.
Would you agree to merge this one soon ?

There is one comment to read before merging: https://github.com/docker-library/official-images/pull/7288#issuecomment-625320576

**Comment by J0WI** [comment]
:ping_pong: @tianon :wink:

**Comment by williamdes** [comment]
Hi dear reviewers ;)
I rebased my PR if you could have a look ?

cc @tianon

**Comment by williamdes** [comment]
Hi @tianon 
Could you let us know what you think about this PR ?

**Comment by tianon** [comment]
Sorry for the delay -- I've just re-reviewed this, and I think it looks like it's in a good state.

In other words, LGTM

cc @yosifkit

**Comment by williamdes** [comment]
Hi @yosifkit and @tianon 
I just had a look to https://hub.docker.com/search?image_filter=official&type=image&category=database and could not find phpMyAdmin but Adminer is listed. Could you add our image to the category please ?

**Comment by tianon** [comment]
Unfortunately, that's not something we currently can control -- I'd
suggest you add your "thumbs up" on
https://github.com/docker/roadmap/issues/76

**Pull request merged**
