### PR TITLE
bump Kong to 3.0.0

### PR DESCRIPTION
**Pull request by hanshuebner**

### CODE REVIEW

**Review by gszr — COMMENTED** [review]
looks good on my end 👍

**Comment by kikito** [comment]
lgtm too 👍

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319, especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md

(This is only informational - the label already exists so I'm not going to make it a blocker, but something to consider for the future.)

**Comment by tianon** [comment]
A new major release is also a great time to revisit whether all the old versions listed here are still supported. :eyes:

As a reminder:

> Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Pull request merged**
