### PR TITLE
eclipse-temurin: add windows ltsc-2022 support

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by gdams** [comment]
@tianon @yosifkit any idea why the action failed?

**Comment by yosifkit** [comment]
I think it is just a transient GitHub actions issue; I'll restart it.

**Comment by gdams** [comment]
@yosifkit failed again :/

**Comment by tianon** [comment]
Yeah -- I've filed an issue with GitHub support; we've got another failing in the same obscure way :disappointed:

**Comment by tianon** [comment]
One thing I have noticed here (that's totally unrelated) is that the Windows variants are in the wrong order -- for the manifest list to work correctly, you'll want them listed in descending order (ltsc2022, then 1809, then ltsc2016).

**Comment by tianon** [comment]
(Otherwise when Windows pulls the manifest list, it'll see that 2016 is "supported" and just pull that one, giving a much worse experience overall.)

**Comment by tianon** [comment]
Other than that, the changes look correct/sane to me.

**Comment by gdams** [comment]
>One thing I have noticed here (that's totally unrelated) is that the Windows variants are in the wrong order -- for the manifest list to work correctly, you'll want them listed in descending order (ltsc2022, then 1809, then ltsc2016).

So do I need to change the order in which they appear in this `eclipse-temurin` file? Or is there something else I need to change?

**Comment by gdams** [comment]
>Yeah, just adjusting the order in this file will fix that.

Thanks! I've pushed an update which changes the order

**Pull request merged**
