### PR TITLE
Update spark 4.0.0-preview2

### PR DESCRIPTION
**Pull request by yaooqinn**
https://github.com/apache/spark-docker/tree/master/4.0.0-preview2

### CODE REVIEW

**Comment by tianon** [comment]
```diff
+    ln -s "$(basename $(ls /opt/spark/examples/jars/spark-examples_*.jar))" /opt/spark/examples/jars/spark-examples.jar; \
```

This chain is definitely eyebrow-raising :sweat_smile:

Can you explain a bit what it's trying to do?  Does `/opt/spark/examples/jars/spark-examples_*.jar` match multiple things, or just one?  Perhaps the `--relative` flag to `ln` is what you're looking for here so you can avoid both subshells?

**Comment by yaooqinn** [comment]
This is a user experience improvement for referencing it for quickstart w/ spark examples.

FYI, https://github.com/apache/spark-docker/pull/67

**Comment by tianon** [comment]
Sorry, let me be more clear -- `ls` in any scripting context is almost always a "code smell" because it is primarily a user interface, not intended for scripting use.

In this case, I think what you meant by this:

```diff
+    ln -s "$(basename $(ls /opt/spark/examples/jars/spark-examples_*.jar))" /opt/spark/examples/jars/spark-examples.jar; \
```

was really much more simply stated as:

```diff
+    ln -sr /opt/spark/examples/jars/spark-examples_*.jar /opt/spark/examples/jars/spark-examples.jar; \
```

(with what should be the exact same end result, but with less fiddly subshell layers in between where things could unintentionally go wrong)

**Comment by tianon** [comment]
Another alternative that's still valid, but only a single subshell (still not ideal, but more correct than the current that's shelling out to `ls` as well):

```diff
+    ln -s "$(basename /opt/spark/examples/jars/spark-examples_*.jar)" /opt/spark/examples/jars/spark-examples.jar; \
```

(The _ideal_ solution would be to ship this symlink as part of the original upstream dist, but that's perhaps a separate topic.)

**Review by tianon — APPROVED** [review]

**Pull request merged**
