### PR TITLE
haxe: remove buster, add bookworm

### PR DESCRIPTION
**Pull request by andyli**
https://github.com/docker-library/official-images/pull/17091#issuecomment-2201099734

### CODE REVIEW

**Comment by tianon** [comment]
:sob: I dropped the ball: https://github.com/docker-library/official-images/pull/16801#issuecomment-2211490133

(Alpine 3.16 needs the same treatment :heart: :eyes:)

**Review by tianon — APPROVED** [review]
This looks great and I'm happy to merge it as-is if you'd like to deal with Alpine 3.16 separately? :heart:

**Comment by tianon** [comment]
(also happy to wait if you'd rather roll it into this update)

**Comment by andyli** [comment]
Oh, no problem. I'll create another PR for the alpine update. You may merge this one first. Thanks!

**Pull request merged**
