### PR TITLE
Update photon image

### PR DESCRIPTION
**Pull request by gerrit-photon**
Update photon image

### CODE REVIEW

**Comment by michellew-vmware** [comment]
Please do not publish this PR since 1.0 openssl has bugs. 

Thanks,
Michelle from Photon OS team

**Comment by michellew-vmware** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!Please do not publish this PR since 1.0 openssl has bugs. !!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Thanks,
Michelle from Photon OS team

**Comment by tianon** [comment]
No problem -- looks like it needs to be rebased too.

**Comment by michellew-vmware** [comment]
1.0 issue has been fixed. Please help to review and merge it.

Thanks,
Michelle

**Comment by yosifkit** [comment]
Rebased to fix merge conflict; should be good to go once tests finish.

**Pull request merged**
