### PR TITLE
Update to Flink 1.12.0

### PR DESCRIPTION
**Pull request by xintongsong**
This is a replacement of #9249.

cc @rogaha @tianon @yosifkit @rmetzger @dianfu @wangyang0918

### CODE REVIEW

**Comment by baobeidaodao** [comment]
When will it be released ?

**Comment by xintongsong** [comment]
@rogaha @tianon @yosifkit 
Could someone please help take a look at this PR?

**Comment by ChethanUK** [comment]
@rmetzger Can you please review this PR? 

Offical image of 1.12.0 is not released in the docker hub yet.

**Comment by renatomariscal** [comment]
Any updates on this? My team is anxious to get the goodies of 1.12 😬

**Comment by tianon** [comment]
There's still ongoing discussion in https://github.com/docker-library/official-images/pull/9249.

**Comment by yosifkit** [comment]
#9249 was fixed and merged, so closing this one.

**Pull request closed without merging**
