### PR TITLE
Fedora Update 20240923

### PR DESCRIPTION
**Pull request by cverna**

### CODE REVIEW

**Comment by tianon** [comment]
```diff
diff --git a/fedora_latest/fedora-20240916.tar b/fedora_latest/fedora-20240922.tar
similarity index 100%
rename from fedora_latest/fedora-20240916.tar
rename to fedora_latest/fedora-20240922.tar
```

This is kind of sus, and probably worth looking into -- that should be regenerating something, not just be the exact same rootfs, right?

**Comment by tianon** [comment]
> ```diff
> diff --git a/fedora_latest/fedora-20240916.tar b/fedora_latest/fedora-20240922.tar
> similarity index 100%
> rename from fedora_latest/fedora-20240916.tar
> rename to fedora_latest/fedora-20240922.tar
> ```
> 
> This is kind of sus, and probably worth looking into -- that should be regenerating something, not just be the exact same rootfs, right?

_Especially_ given that there appear to be a large number of packages in that base image with updates available? :grimacing:

```console
$ docker run --rm --pull=always fedora:latest yum list --upgrades
latest: Pulling from library/fedora
Digest: sha256:d0207dbb078ee261852590b9a8f1ab1f8320547be79a2f39af9f3d23db33735e
Status: Image is up to date for fedora:latest
Fedora 40 - x86_64                              8.6 MB/s |  20 MB     00:02    
Fedora 40 openh264 (From Cisco) - x86_64        1.3 kB/s | 1.4 kB     00:01    
Fedora 40 - x86_64 - Updates                    2.5 MB/s |  10 MB     00:04    
Last metadata expiration check: 0:00:01 ago on Tue Sep 24 19:52:47 2024.
Available Upgrades
alternatives.x86_64                        1.27-1.fc40                   updates
audit-libs.x86_64                          4.0.2-1.fc40                  updates
coreutils.x86_64                           9.4-7.fc40                    updates
coreutils-common.x86_64                    9.4-7.fc40                    updates
crypto-policies.noarch                     20240725-1.git28d3e2d.fc40    updates
curl.x86_64                                8.6.0-10.fc40                 updates
dnf.noarch                                 4.21.1-1.fc40                 updates
dnf-data.noarch                            4.21.1-1.fc40                 updates
expat.x86_64                               2.6.3-1.fc40                  updates
fedora-gpg-keys.noarch                     40-2                          updates
fedora-release-common.noarch               40-39                         updates
fedora-release-container.noarch            40-39                         updates
fedora-release-identity-container.noarch   40-39                         updates
fedora-repos.noarch                        40-2                          updates
findutils.x86_64                           1:4.9.0-9.fc40                updates
glib2.x86_64                               2.80.3-1.fc40                 updates
glibc.x86_64                               2.39-22.fc40                  updates
glibc-common.x86_64                        2.39-22.fc40                  updates
glibc-minimal-langpack.x86_64              2.39-22.fc40                  updates
gnutls.x86_64                              3.8.6-1.fc40                  updates
krb5-libs.x86_64                           1.21.3-1.fc40                 updates
libarchive.x86_64                          3.7.2-4.fc40                  updates
libblkid.x86_64                            2.40.1-1.fc40                 updates
libcap.x86_64                              2.69-8.fc40                   updates
libcurl.x86_64                             8.6.0-10.fc40                 updates
libdnf.x86_64                              0.73.3-1.fc40                 updates
libeconf.x86_64                            0.6.2-2.fc40                  updates
libgcc.x86_64                              14.2.1-3.fc40                 updates
libgomp.x86_64                             14.2.1-3.fc40                 updates
libgpg-error.x86_64                        1.49-1.fc40                   updates
libmodulemd.x86_64                         2.15.0-12.fc40                updates
libmount.x86_64                            2.40.1-1.fc40                 updates
libnghttp2.x86_64                          1.59.0-3.fc40                 updates
librepo.x86_64                             1.18.1-1.fc40                 updates
libsmartcols.x86_64                        2.40.1-1.fc40                 updates
libsolv.x86_64                             0.7.30-1.fc40                 updates
libstdc++.x86_64                           14.2.1-3.fc40                 updates
libtirpc.x86_64                            1.3.5-0.fc40                  updates
libuuid.x86_64                             2.40.1-1.fc40                 updates
libxml2.x86_64                             2.12.8-1.fc40                 updates
libzstd.x86_64                             1.5.6-1.fc40                  updates
mpfr.x86_64                                4.2.1-4.fc40                  updates
openssl-libs.x86_64                        1:3.2.2-3.fc40                updates
p11-kit.x86_64                             0.25.5-1.fc40                 updates
p11-kit-trust.x86_64                       0.25.5-1.fc40                 updates
pam.x86_64                                 1.6.1-3.fc40                  updates
pam-libs.x86_64                            1.6.1-3.fc40                  updates
pcre2.x86_64                               10.44-1.fc40                  updates
pcre2-syntax.noarch                        10.44-1.fc40                  updates
python3.x86_64                             3.12.6-1.fc40                 updates
python3-dnf.noarch                         4.21.1-1.fc40                 updates
python3-hawkey.x86_64                      0.73.3-1.fc40                 updates
python3-libdnf.x86_64                      0.73.3-1.fc40                 updates
python3-libs.x86_64                        3.12.6-1.fc40                 updates
rpm-sequoia.x86_64                         1.7.0-1.fc40                  updates
shadow-utils.x86_64                        2:4.15.1-3.fc40               updates
tpm2-tss.x86_64                            4.1.3-1.fc40                  updates
tzdata.noarch                              2024a-5.fc40                  updates
vim-data.noarch                            2:9.1.719-1.fc40              updates
vim-minimal.x86_64                         2:9.1.719-1.fc40              updates
yum.noarch                                 4.21.1-1.fc40                 updates
zchunk-libs.x86_64                         1.5.1-1.fc40                  updates
zlib-ng-compat.x86_64                      2.1.7-2.fc40                  updates
zstd.x86_64                                1.5.6-1.fc40                  updates
```

**Comment by cverna** [comment]
Hum yes, there is something odd going on. Thanks for flagging this up. I ll check on my side what's happening.

**Comment by tianon** [comment]
Do you want us to merge this update in the meantime, or would you like to continue investigating before doing further updates?

**Comment by cverna** [comment]
Closing and will open a new PR :-)

**Pull request closed without merging**
