### PR TITLE
Update CrateDB to 5.3.0

### PR DESCRIPTION
**Pull request by mfussenegger**
Draft to run tests as we switched the base image. Please don't merge yet

### CODE REVIEW

**Comment by seut** [comment]
CrateDB 5.3.0 has been declared stable just now. 
@mfussenegger @yosifkit Could you please switch this PR to `ready-for-review` and review/merge? Thank you!

**Comment by yosifkit** [comment]
Rebased to account for https://github.com/docker-library/official-images/pull/14438. Can someone from CrateDB confirm that it is correct?

**Comment by yosifkit** [comment]
Useful bit of the force push: https://github.com/docker-library/official-images/compare/6508673541dd408501e4ee0c2ba5325052adb4fa..b720f05a7ffcc1b4089e6b75c1bea69f819a0f35#diff-3d54c8667b603b919713cf8a929ff7a68f7f8544a247d2a76c78f3f4af693a1d
```diff
 Architectures: amd64, arm64v8
 GitCommit: 2a7bfa53ecd5fdd4c0c4aa9c9bb3c9fd97e1df20
 
-Tags: 5.2.5, 5.2
+Tags: 5.2.6, 5.2
 Architectures: amd64, arm64v8
-GitCommit: c98d17879824e2cbc4522d6591db77d6ac74bc5a
+GitCommit: 8a7ad52cc562a2072a1817b58236ea7d8f176deb
 
 Tags: 4.8.4, 4.8
 Architectures: amd64, arm64v8
```

**Comment by seut** [comment]
> Rebased to account for #14438. Can someone from CrateDB confirm that it is correct?

Right, thank you!

**Pull request merged**
