### PR TITLE
Improve no-root-password with more knowledge from the manpages

### PR DESCRIPTION
**Pull request by tianon**
@vbatts care to give this some review? :smile:

### CODE REVIEW

**Comment by vbatts** [comment]
```bash
vbatts@valse ~ (master *) $ for i in $(docker images -q fedora | sort -u ); do echo $i; sh gh739.sh $i ; echo ; done                                                                                                     
717a8c89fa48

93be8052dfb8
error: crypt password detected for root: '$6$DoHwMNPipK/gAVGn$qseLnsvYNGkBBQQDoKfuYWdHR/b6jLMjDwbT32ad97.EvspmbtfqhyQezyYFrqN0Bk/iNTey1upR5i816bGMR1'

d7f0e75cf11f
```

found it ;-)

**Comment by vbatts** [comment]
so :+1:

**Comment by tianon** [comment]
:smile:

Does the logic look sane?

**Comment by tianon** [comment]
Given:
http://linuxmanpages.net/manpages/fedora21/man5/shadow.5.html
and
http://linuxmanpages.net/manpages/fedora21/man5/passwd.5.html

**Comment by tianon** [comment]
Just for completeness, the oh-so-similar:
http://manpages.debian.org/cgi-bin/man.cgi?query=passwd&apropos=0&sektion=5&manpath=Debian+unstable+sid&format=html&locale=en
and
http://manpages.debian.org/cgi-bin/man.cgi?query=shadow&apropos=0&sektion=5&manpath=Debian+unstable+sid&format=html&locale=en

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
