### PR TITLE
Update Couchbase Server CE+EE to 7.6.0

### PR DESCRIPTION
**Pull request by udkyo**
Adding new Couchbase Server release.

### CODE REVIEW

**Comment by yosifkit** [comment]
In Docker Official Images, we try hard to avoid multi-stage builds in almost every instance. Even though we maintain the gcc image, I'm not sure I'd recommend using it to build binaries compatible with a specific libc of a distribution; it'd be better to just use the gcc package from the distribution. So, we would rather that it be just a regular non-multistage build (i.e., `apt install`, build, and `apt purge` all in one `RUN`). It will help make it clearer for users viewing docker history where things came from. See also the FAQ section on [multi-stage builds](https://github.com/docker-library/faq/tree/76862506fde541f964df742db3b5abe549d9beb6#multi-stage-builds). You also should pin the `git clone` to get a specific commit id so it has better reproducibility.

I am mildly concerned about using a custom fork of `runit`. Would it confuse users when they use other images containing the same tools? 🤔

**Comment by ceejatec** [comment]
To your last point, IMHO it's a non-goal for a container image to provide tools for general use. This container image is intended to host Couchbase Server, and it contains the necessary tools for that. Users should not generally be running their own programs inside the container at all, let alone depending on the specific behaviour of the 'init' program in use.

As for the use of the gcc image, I think I understand your concern. I believe I can modify it to be a single-stage build, although it'll be difficult to ensure that it doesn't end up with significant additional "cruft" in that runit build layer since we'll need to remove all of gcc and anything it brought in. It would be far easier and safer to make it a multi-stage build and just ensure we use the same FROM line for both stages, rather than using the separate "gcc" image. What's the reasoning behind avoid multi-stage builds in general?

All that said, this is the Dockerfile we've internally tested with Server 7.6.0, which is now released, and it's the Dockerfile that was used to create our "unofficial" couchbase/server:7.6.0 image. Making either of those changes will take at least a few days to implement and validate, and we're already nearly 48 hours past our 7.6.0 release date. Would it be acceptable to commit this version for 7.6.0, with the understanding that we'll correct the issues for 7.6.1?

I also agree that we should check out a specific SHA of our runit fork; I'll make that change in the follow-up Dockerfile as well.

**Comment by whalelines** [comment]
> What's the reasoning behind avoid multi-stage builds in general?

@ceejatec that is addressed in the FAQ @yosifkit pointed you to:

>> See also the FAQ section on [multi-stage builds](https://github.com/docker-library/faq/tree/76862506fde541f964df742db3b5abe549d9beb6#multi-stage-builds).

**Comment by ceejatec** [comment]
@whalelines @yosifkit Example #2 of the "likely acceptable" use cases under the FAQ entry seems to exactly match our scenario.

**Comment by ceejatec** [comment]
@yosifkit @whalelines I've pushed an update which includes the changes you suggested; please re-review.

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
