### PR TITLE
Update Monica to v4.1.2

### PR DESCRIPTION
**Pull request by asbiin**
Update Monica to [v4.1.2](https://github.com/monicahq/monica/releases/tag/v4.1.2).

### CODE REVIEW

**Comment by parkr** [comment]
[v4.1.2](https://github.com/monicahq/monica/releases) was just released. Should we jump straight to that?

**Comment by tianon** [comment]
Actual environment variables set on the container will override the `.env` values, right? (they're just used as defaults?)

As to 4.1.2, that depends on whether you care about whether there's a 4.1.1 tag available - I don't think it's _terribly_ important (and thus you should feel free to go straight to 4.1.2 if you'd like), but you might feel otherwise. :+1:

**Comment by asbiin** [comment]
Thank you @parkr I'll update this version right now.

**Comment by asbiin** [comment]
> Actual environment variables set on the container will override the `.env` values, right? (they're just used as defaults?)

Exactly. The `.env` values are default one that make the docker run with the best values, but any environment variable will have the priority over those values.

**Review by tianon — APPROVED** [review]

**Pull request merged**
