### PR TITLE
Update memcached to 1.4.22

### PR DESCRIPTION
**Pull request by tianon**
:tada: https://github.com/memcached/memcached/pull/88#issuecomment-68571178

(includes the `SIGTERM` fix!)

### CODE REVIEW

**Comment by tianon** [comment]
Heh, SHA1 fail.

**Comment by tianon** [comment]
docker-library/memcached@52f5ecffe96c5bd0c06591d5b78f34ad503e5728 and docker-library/memcached@5fb6459a1eb138dcd9cfcd5fa1aef62ee511d335 lols

**Comment by tianon** [comment]
Build test of #385; c2e6d190ee71504c46c3531360c935675792fe84 (`memcached`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/c2e6d190ee71504c46c3531360c935675792fe84/library/memcached
Fetching memcached (git://github.com/docker-library/memcached) ...
Processing memcached:1.4.22 ...
Processing memcached:1.4 ...
Processing memcached:1 ...
Processing memcached:latest ...
```

**Comment by tianon** [comment]
```
Signal handled: Terminated.
```
:heart_eyes:

**Comment by md5** [comment]
:raised_hands:

**Comment by tianon** [comment]
:cake: @md5 :heart:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
