### PR TITLE
Update Amazon Linux Images

### PR DESCRIPTION
**Pull request by kgharris**
Corrected pull request - please create new container images for our amzn2 containers - thanks!

### CODE REVIEW

**Comment by yosifkit** [comment]
These additions seem a bit strange for a container image; are they on purpose?

```diff
+usr/libexec/vi
+usr/share/vim/
+usr/share/vim/vim82/
+usr/share/vim/vim82/defaults.vim
```

**Comment by kgharris** [comment]
Those are coming from our vim-minimal package now, which is not new - only those two files are.  So yes it's on purpose.

**Comment by tianon** [comment]
Fair enough, thanks for confirming!

**Comment by kgharris** [comment]
You're welcome - thanks for making sure!

**Pull request merged**
