### PR TITLE
Update Ubuntu 2022-09-01

### PR DESCRIPTION
**Pull request by ROCKsBot**
Update Ubuntu to latest published rootfs tarballs as of 2022-09-01.

### CODE REVIEW

**Comment by woky** [comment]
@tianon please let me know if you want to be kept in `Maintainers`. I've removed you since the https://github.com/tianon/docker-brew-ubuntu-core is no longer used. (I shall make PR to update README shortly.)

**Comment by woky** [comment]
> LGTM (but wondering if there isn't a newer Jammy. the one included is from 20220815)

Checked. There're no newer packages. (CI says _No build required_.)

**Comment by tianon** [comment]
> @tianon please let me know if you want to be kept in `Maintainers`. I've removed you since https://github.com/tianon/docker-brew-ubuntu-core is no longer used. (I shall make PR to update README shortly.)

:heart:

I am totally fine being removed (but also happy to stay listed if that's helpful to you - I'll be around/available either way :joy:).

I've now opened https://github.com/docker-library/docs/pull/2184 for the docs half of this to make sure the `Dockerfile` links still work correctly :+1:

We should probably also update https://github.com/docker-library/docs/blob/master/ubuntu/maintainer.md?plain=1, but I'm going to leave what you want that half to say up to you :eyes:

**Review by yosifkit — APPROVED** [review]

**Comment by woky** [comment]
> I am totally fine being removed (but also happy to stay listed if that's helpful to you - I'll be around/available either way joy).
> 
> We should probably also update https://github.com/docker-library/docs/blob/master/ubuntu/maintainer.md?plain=1, but I'm going to leave what you want that half to say up to you eyes

@tianon I've added you back to maintainers but it will have to wait until next month. I kept myself first as I think eventual problems will ultimately trickle down to me. :-) So no update of maintainers is needed.

Thank you for documentation update!

**Pull request merged**
