### PR TITLE
[nats] Release v2.10.11

### PR DESCRIPTION
**Pull request by bruth**
Details can be found [here](https://github.com/nats-io/nats-server/releases/tag/v2.10.11)

Introduced the ppc64le arch as well.

### CODE REVIEW

**Comment by bruth** [comment]
A couple changes in our nats-docker repo introduced the use of a build arg which appears to be causing the tests in this repo to fail. See [here](https://github.com/nats-io/nats-docker/pull/140/commits/dd5212bb262783824c561de16d8b36200a4357d9#diff-e70a6853665e4e159d3cb703b51ed6ef6a7323b6fa54865de8b1cd2aa48a43be) as an example. Doing a normal `docker build` works fine. Is there some constraint for Dockerfiles in the official images repo that prevents this from working?

**Comment by yosifkit** [comment]
> Is there some constraint for Dockerfiles in the official images repo that prevents this from working?

Yeah, we parse the Dockerfiles to determine build ordering and none of that supports putting variables in `FROM`/`--from` values.

**Comment by bruth** [comment]
Fixed @yosifkit

**Comment by albionb96** [comment]
@tianon , @yosifkit is there any reason why this is not yet released, are there any issues with this version, or is it just ongoing?

**Review by tianon — APPROVED** [review]

**Comment by tianon** [comment]
(US-based Pacific Timezone)

**Comment by bruth** [comment]
Thanks @tianon!

**Pull request merged**
