### PR TITLE
Bump Traefik to v2.4.0-rc2

### PR DESCRIPTION
**Pull request by rtribotte**
Hello,

This PR updates Traefik to [v2.4.0-rc2](https://github.com/traefik/traefik/releases/tag/v2.4.0-rc2).

/cc @ldez @jbdoumenjou @SantoDE @kevinpollet

Cheers

### CODE REVIEW

**Review by SantoDE — APPROVED** [review]
LGTM 🚀

**Review by jbdoumenjou — APPROVED** [review]
LGTM

**Review by ldez — APPROVED** [review]
LGTM

**Review by kevinpollet — APPROVED** [review]
LGTM

**Pull request merged**
