### PR TITLE
Bump traefik to v1.1.0

### PR DESCRIPTION
**Pull request by emilevauge**
Hello,

This PR updates traefik to v1.1.0.
It also adds an alpine image version.

/cc @vdemeester

Cheers

### CODE REVIEW

**Comment by tianon** [comment]
```diff
diff --git a/traefik_camembert-alpine/Dockerfile b/traefik_camembert-alpine/Dockerfile
new file mode 100644
index 0000000..45ab697
--- /dev/null
+++ b/traefik_camembert-alpine/Dockerfile
@@ -0,0 +1,16 @@
+FROM alpine:3.4
+RUN apk --update upgrade \
+    && apk --no-cache --no-progress add ca-certificates \
+    && rm -rf /var/cache/apk/*
+COPY traefik /
+EXPOSE 80
+ENTRYPOINT ["/traefik"]
+CMD ["--help"]
+
+# Metadata
+LABEL org.label-schema.vendor="Containous" \
+      org.label-schema.url="https://traefik.io" \
+      org.label-schema.name="Traefik" \
+      org.label-schema.description="A modern reverse-proxy" \    
+      org.label-schema.version="v1.1.0" \
+      org.label-schema.docker.schema-version="1.0"
\ No newline at end of file
diff --git a/traefik_camembert-alpine/Dockerfile.tmpl b/traefik_camembert-alpine/Dockerfile.tmpl
new file mode 100644
index 0000000..34aba97
--- /dev/null
+++ b/traefik_camembert-alpine/Dockerfile.tmpl
@@ -0,0 +1,16 @@
+FROM alpine:3.4
+RUN apk --update upgrade \
+    && apk --no-cache --no-progress add ca-certificates \
+    && rm -rf /var/cache/apk/*
+COPY traefik /
+EXPOSE 80
+ENTRYPOINT ["/traefik"]
+CMD ["--help"]
+
+# Metadata
+LABEL org.label-schema.vendor="Containous" \
+      org.label-schema.url="https://traefik.io" \
+      org.label-schema.name="Traefik" \
+      org.label-schema.description="A modern reverse-proxy" \    
+      org.label-schema.version="$VERSION" \
+      org.label-schema.docker.schema-version="1.0"
\ No newline at end of file
diff --git a/traefik_camembert/traefik b/traefik_camembert-alpine/traefik
similarity index 67%
rename from traefik_camembert/traefik
rename to traefik_camembert-alpine/traefik
index e0e898b..7cf55c3 100755
Binary files a/traefik_camembert/traefik and b/traefik_camembert-alpine/traefik differ
diff --git a/traefik_latest/Dockerfile b/traefik_latest/Dockerfile
index 335427d..58a2fd1 100644
--- a/traefik_latest/Dockerfile
+++ b/traefik_latest/Dockerfile
@@ -3,3 +3,11 @@ COPY certs/ca-certificates.crt /etc/ssl/certs/
 COPY traefik /
 EXPOSE 80
 ENTRYPOINT ["/traefik"]
+
+# Metadata
+LABEL org.label-schema.vendor="Containous" \
+      org.label-schema.url="https://traefik.io" \
+      org.label-schema.name="Traefik" \
+      org.label-schema.description="A modern reverse-proxy" \    
+      org.label-schema.version="v1.1.0" \
+      org.label-schema.docker.schema-version="1.0"
\ No newline at end of file
diff --git a/traefik_camembert/Dockerfile b/traefik_latest/Dockerfile.tmpl
similarity index 26%
copy from traefik_camembert/Dockerfile
copy to traefik_latest/Dockerfile.tmpl
index 335427d..8fd822c 100644
--- a/traefik_camembert/Dockerfile
+++ b/traefik_latest/Dockerfile.tmpl
@@ -3,3 +3,11 @@ COPY certs/ca-certificates.crt /etc/ssl/certs/
 COPY traefik /
 EXPOSE 80
 ENTRYPOINT ["/traefik"]
+
+# Metadata
+LABEL org.label-schema.vendor="Containous" \
+      org.label-schema.url="https://traefik.io" \
+      org.label-schema.name="Traefik" \
+      org.label-schema.description="A modern reverse-proxy" \    
+      org.label-schema.version="$VERSION" \
+      org.label-schema.docker.schema-version="1.0"
\ No newline at end of file
diff --git a/traefik_latest/traefik b/traefik_latest/traefik
index 3263eb7..7cf55c3 100755
Binary files a/traefik_latest/traefik and b/traefik_latest/traefik differ
diff --git a/traefik_camembert/Dockerfile b/traefik_reblochon/Dockerfile
similarity index 100%
rename from traefik_camembert/Dockerfile
rename to traefik_reblochon/Dockerfile
diff --git a/traefik_latest/Dockerfile.alpine b/traefik_reblochon/Dockerfile.alpine
similarity index 100%
rename from traefik_latest/Dockerfile.alpine
rename to traefik_reblochon/Dockerfile.alpine
diff --git a/traefik_camembert/certs/ca-certificates.crt b/traefik_reblochon/certs/ca-certificates.crt
similarity index 100%
rename from traefik_camembert/certs/ca-certificates.crt
rename to traefik_reblochon/certs/ca-certificates.crt
diff --git a/traefik_latest/traefik b/traefik_reblochon/traefik
similarity index 100%
copy from traefik_latest/traefik
copy to traefik_reblochon/traefik
```

**Comment by tianon** [comment]
That `alpine` variant looks nice, but is going to need a little something for https://github.com/docker-library/official-images/blob/d28cb89e79417cac50c2a8ae163a9b3b79167f79/README.md#consistency :confused:

I've filed https://github.com/docker-library/official-images/pull/2370 to somewhat more properly fix the test so that we don't accidentally miss things like this in the future. :disappointed:

**Comment by tianon** [comment]
If `traefik` doesn't have subcommands, something like this might be sufficient:
```sh
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- traefik "$@"
fi

exec "$@"
```
(from https://github.com/docker-library/redis/blob/54ec6b70a3afd6ec62a6549621c5ca1053ece7f5/3.2/alpine/docker-entrypoint.sh)

Otherwise something like what `docker` does might work:
```sh
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- traefik "$@"
fi

# if our command is a valid Traefik subcommand, let's invoke it through Traefik instead
# (this allows for "docker run traefik version", etc)
if traefik "$1" --help > /dev/null 2>&1; then
	set -- traefik "$@"
fi

exec "$@"
```
(from https://github.com/docker-library/docker/blob/1f787c2d7b53c4ed2137fa7df910794c192acaa4/1.12/docker-entrypoint.sh#L4-L13)

**Comment by emilevauge** [comment]
Ouch, I accidentally closed this PR ad cannot reopen it :sob: 
@tianon, could you reopen it?
I added an `entrypoint.sh` to alpine image to stay consistent.

**Comment by tianon** [comment]
Nope, looks like it's complaining that the branch was "force-pushed or reopened" :disappointed:

Want to open a new one? :pray:

(took a look at that script PR and it looks solid :+1:)

**Pull request closed without merging**
