### PR TITLE
Added Wheezy variants to node image

### PR DESCRIPTION
**Pull request by chorrell**

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

Build test of #484; 446e2b0075ec7db62f9ba58a77ebd60a100099fe (`node`):

```console
$ url="https://raw.githubusercontent.com/docker-library/official-images/446e2b0075ec7db62f9ba58a77ebd60a100099fe/library/node"
$ bashbrew build "$url"
Fetching node (git://github.com/joyent/docker-node) ...
Processing node:0.10.36 ...
Processing node:0.10 ...
Processing node:0.10.36-onbuild ...
Processing node:0.10-onbuild ...
Processing node:0.10.36-slim ...
Processing node:0.10-slim ...
Processing node:0.10.36-wheezy ...
Processing node:0.10-wheezy ...
Processing node:0.12.0 ...
Processing node:0.12 ...
Processing node:0 ...
Processing node:latest ...
Processing node:0.12.0-onbuild ...
Processing node:0.12-onbuild ...
Processing node:0-onbuild ...
Processing node:onbuild ...
Processing node:0.12.0-slim ...
Processing node:0.12-slim ...
Processing node:0-slim ...
Processing node:slim ...
Processing node:0.12.0-wheezy ...
Processing node:0.12-wheezy ...
Processing node:0-wheezy ...
Processing node:wheezy ...
Processing node:0.8.28 ...
Processing node:0.8 ...
Processing node:0.8.28-onbuild ...
Processing node:0.8-onbuild ...
Processing node:0.8.28-slim ...
Processing node:0.8-slim ...
Processing node:0.8.28-wheezy ...
Processing node:0.8-wheezy ...
$ bashbrew list "$url" | xargs test/run.sh
testing node:0.10.36
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10.36-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10.36-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10.36-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.10-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12.0
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:latest
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12.0-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12.0-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12.0-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.12-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8.28
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8.28-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8-onbuild
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8.28-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8-slim
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8.28-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
testing node:0.8-wheezy
	'utc' [1/2]...passed
	'shellshock' [2/2]...passed
```

**Comment by chorrell** [comment]
Ooooh, new tests! :heart_eyes:

**Comment by tianon** [comment]
Right? :smile:

We want to get some decent Node.js tests in here, too!

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
