### PR TITLE
archlinux: Release 20231119.0.193111

### PR DESCRIPTION
**Pull request by archlinux-github**
This is an automated release [1].

[1] https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/master/.gitlab-ci.yml

---

Maintainers: @SantiagoTorres @shibumi @hashworks

### CODE REVIEW

**Comment by hashworks** [comment]
This adds a new type: `multilib-devel`, which includes the respective [meta package](https://archlinux.org/packages/multilib/x86_64/multilib-devel/).

**Comment by tianon** [comment]
Am I reading correctly in https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/337a19c996695f92aac17e2002b534dee732ab0a/scripts/make-rootfs.sh#L29 that all the images include the `base` group, and that `base-devel` and `multilib-devel` are included on top of `base` in all cases?

Something you could consider is continuing to maintain `archlinux:latest`/`archlinux:base` as you do today, but swapping the other two to instead be a short `Dockerfile` that's `FROM archlinux:latest` (or `archlinux:base`) and installs the relevant metapackages instead, which would decrease the number of artifacts you have to produce directly (and give users who use more than one of them a slight space savings since they'd then all share that bottom layer).

(The limitations on `archlinux` images being `FROM archlinux` only apply to an image being `FROM` itself -- being from a different image in the same repo is just fine and how many of our images are maintained. :eyes: :+1:)

**Comment by hashworks** [comment]
You mean like:
```
FROM archlinux:base

RUN pacman -S base-devel
```
?

We explicitly don't do that, since it would break the reproducibility - which is a requirement for the `official-images` repo, AFAIK? There is no guaranty that the files in the repository won't change later on.

If that wouldn't be a problem we wouldn't need the rootfs at all.

**Comment by hashworks** [comment]
Or do you mean: Don't offer `base-devel` and `multilib-devel` in `official-images` at all? This would break existing pipelines.

**Comment by dvzrv** [comment]
Since this morning the official container image is broken (due to the keyring being out of-date for too long).
Please act now so that a new image can be released!

**Comment by aminvakil** [comment]
Having this problem also here, there is not an appropriate way to fix this right now if base image is broken.

**Comment by hashworks** [comment]
I'm sorry for any inconvenience this has caused, the delay here is on me. Until we resolve this, please use the daily images (f.e. `docker.io/archlinux/archlinux:base`).

As mentioned on IRC, it would be great if we could close this MR and merge a new one with the current process, so we can fix stuff for of end-users for now. I've already [thought about a better approach on our side](https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/100), but it will take a while to implement the required changes for all registries.

**Comment by tianon** [comment]
Yep, agreed, let's fix this ❤️  I'll close this and wait for your new PR 👍

**Comment by tianon** [comment]
Done! https://github.com/docker-library/official-images/pull/15984 👍

**Pull request closed without merging**
