### PR TITLE
Add support for "Builder: oci-import" in diff-pr

### PR DESCRIPTION
**Pull request by tianon**
See also:
- docker-library/bashbrew#51
- https://github.com/docker-library/bashbrew/pull/61
- #13769

### CODE REVIEW

**Comment by tianon** [comment]
Implementation of `bashbrew fetch` in https://github.com/docker-library/bashbrew/pull/63

**Comment by tianon** [comment]
(temporarily have stolen the commit from https://github.com/docker-library/official-images/pull/14094 so this can run and verify that it's working correctly)

**Comment by tianon** [comment]
Temporarily did the branch dance and stole the commit from https://github.com/docker-library/official-images/pull/14094 so this can run and verify that it's working correctly and now the commits are gone presumably because there's a fix for the media types in progress :joy:  I wasn't fast enough!

**Comment by tianon** [comment]
I definitely misinterpreted the error, and I'm not 100% sure why we're getting that error, actually. :sob:

I'm digging into it -- that version is old and should've fetched just fine (as I just verified with `BASHBREW_CACHE=/tmp/foo bashbrew-0.1.8 --debug fetch --arch-filter https://github.com/docker-library/official-images/raw/40fef2a0d64638c7883923397a58912026adffb3/library/ubuntu:bionic`)

**Comment by tianon** [comment]
Oh, I think I understand now -- https://github.com/docker-library/official-images/pull/14094 is updating `bionic` images on amd64 from f127810992c0981574cc137b9c83937ca1a304dc to 42d90b15646d0d8d5a2843b4246a2e82d642a352, and it's failing to fetch the "old" images so it can generate a diff, even though the images probably didn't change in any real functional/noticeable way since they're still on serial 20230126. :facepalm:

cc @woky @cjdcordeiro @mwhudson @toabctl :see_no_evil:

**Comment by tianon** [comment]
Successful "Munge PR" run: https://github.com/docker-library/official-images/actions/runs/4188887136
Successful (failing appropriately) "Test PR" run: https://github.com/docker-library/official-images/actions/runs/4188887183

```console
+ bashbrew build ubuntu:22.04
Building bashbrew/cache:82381497ce6db9acbbaadd2cc33547a61364337da7647afc83b1e42c0bcc40d1 (ubuntu:22.04)
failed oci-import build of "ubuntu" (tags "22.04, jammy-20230207, jammy, latest")
unsupported mediaType "application/vnd.docker.container.image.v1+json" for config descriptor "sha256:900f32031c55c890a735d8c1d96eee1de593fab2d6216449c7ad6ffaf180d491" (from directory "oci" in commit "7d7e89e020a975f43c39e8e4e27f724ba2e19a05")
```

:partying_face:

**Comment by tianon** [comment]
Did this in the wrong order, so GitHub stabbed me in the back. :sob:

**Comment by tianon** [comment]
Ok @yosifkit, this is officially ready for review :see_no_evil:

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
