### PR TITLE
Add Convertigo as official image

### PR DESCRIPTION
**Pull request by nicolas-albert**
Hi, I'm Nicolas from Convertigo.

Convertigo Community edition is an open source MBaaS (Mobile Back end as a Service) combined with a MADP (Mobile application development platform).

We want to publish our images as official, as gage of quality for our community.

The documentation of these images has already been written. https://github.com/docker-library/docs/pull/805

Please review and let me know if there is any room for improvement.

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[x] associated with or contacted upstream?
-	[x] does it fit into one of the common categories? ("service", "language stack", "base distribution")
    - service
-	[x] is it reasonably popular, or does it solve a particular use case well?
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/pull/805
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[x] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
    - `FROM openjdk:xxx`, but possibly will be `FROM tomcat:xxx` later
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by nicolas-albert** [comment]
Hi, may can I help you for the review:

- associated with or contacted upstream?

I'm the upstream, see https://github.com/convertigo &
https://us.linkedin.com/in/nicolasalbert

- does it fit into one of the common categories?

"service"

- is it reasonably popular, or does it solve a particular use case well?

Yes it is reasonably popular, Convertigo MBaaS is public on source forge
since years, more than 10K developers are using Convertigo technologies
today. https://sourceforge.net/projects/convertigo/

- does a documentation PR exist? (should be reviewed and merged at roughly
the same time so that we don't have an empty image page on the Hub for very
long)

https://github.com/docker-library/docs/pull/805

- existing official images have been considered as a base? (ie, if foobar
needs Node.js, has FROM node:... instead of grabbing node via other means
been considered?)

This is well documented in the Dockerfiles. We us FROM 'openjdk' instead of
FROM 'tomcat' because tomcat 7.0.73 has an icomptibility with current
Convertigo Version, so we use tomcat 7.0.72 instead (inspired by the tomcat
Dockerfile). Futur releases (7.5.0) will be adapted for the latest tomcat
version and we will be able to use FROM =E2=80=98tomcat=E2=80=99

The web-connector/Dockerfile need a 32 bit JVM, so we get it from the
debian i386 repository (inspired by the openjdk Dockerfile).

- if FROM scratch, tarballs only exist in a single commit within the
associated history?

No.

- passes current tests? any simple new tests that might be appropriate to
add? (https://github.com/docker-library/official-images/tree/master/test)

No tests yet but we can create one and add it to the PR if needed.

**Comment by tianon** [comment]
Hi!  Took a quick look, and here's some initial thoughts based on what I've seen so far: :heart:

1. all `curl` invocations should include `-f` (ie, `curl -fSL`) so that they fail appropriately when there's a failing status code from the server
2. `gpg --verify /tmp/tomcat.tar.gz.asc` should be `gpg --batch --verify /tmp/tomcat.tar.gz.asc /tmp/tomcat.tar.gz` (and all other instances of `gpg --verify` without `--batch` -- see https://github.com/docker-library/official-images/pull/1420 for more details)
3. `chmod u+x /docker-entrypoint.sh` (and any other mode changes that happen in a layer other than the one that originally introduced the file) can cause issues depending on the graph driver in use, and should be replaced by either making the local file `+x` (and committing that mode change to Git) so that the `COPY` will already have `+x` applied, or doing the `chmod` in the `RUN` line which created the file originally (`chmod -w conf/*`, etc)

I'm also not 100% sold on the idea of the `web-connector` using i386 OpenJDK from `jessie-backports` -- can you elaborate on why it needs 32bit Java, and what features it offers over the standard install of Convertigo?

**Comment by nicolas-albert** [comment]
Thank you for the review.
I applied your recommendations in our `Dockerfile`s.

The `web-connector` is the base distribution + the `web-connector` feature (also known as the HTML Connector). As not all customers uses this connector for their backend, we didn't include it in the default distribution. The 64 bit distribution is more benefic than the `web-connector` for the majority of our customers.
 
The `web-connector` is based on the native component `XulRunner` (from Mozilla) that is only qualified and built for 32 bit. So, all the `Java` stack must be 32 bit. For the web-connector's Dockerfile, I took inspiration from the `openjdk`'s `Dockerfile` (https://github.com/docker-library/openjdk/blob/e6e9cf8b21516ba764189916d35be57486203c95/8-jdk/Dockerfile) that install the JVM from `jessie-backports`.

We are open to any proposal for improvement.

**Comment by nicolas-albert** [comment]
I wanted to add a test, so I synchronized our fork.
Looks like it caused a bit of a mess here, I'm not yet an expert git, sorry :-/
I still added a test.

**Comment by TimWolla** [comment]
> I wanted to add a test, so I synchronized our fork.

Two tips:

1. Create a new git branch for every pull request, instead of re-using the `master` branch for everything. This allows you to have multiple pull requests in parallel.
2. To update your fork I recommend the following:
a) Pull in the updated master of the original repository into the master of your fork. This *must* be a fast-forward merge.
b) Check out your branch for the PR.
c) `git rebase master` to recreate your changes on top of the synchronized master.
d) `git push origin <branchname> --force-with-lease` to overwrite the branch on GitHub. This will update your pull request automatically. The `--force-with-lease` is required because of the rebase.

**Comment by nicolas-albert** [comment]
Thank @TimWolla for these tips !
This PR is broken or can it be still used ?

**Comment by TimWolla** [comment]
> This PR is broken or can it be still used ?

It can be salvaged in theory, but it is probably easier for you to just recreate your fork and re-create your changes (added library file).

**Pull request closed without merging**
