### PR TITLE
Add jupyter-base-notebook

### PR DESCRIPTION
**Pull request by vaibhavsood**
This is to create a official image request for jupyter-base-notebook, dockerfiles hosted here: https://github.com/jupyter/docker-stacks

Initiated a conversation with upstream https://github.com/jupyter/docker-stacks/issues/472

The doc PR is here: https://github.com/docker-library/docs/pull/1055

# Checklist for Review

**NOTE:** This checklist is intended for the use of the Official Images maintainers both to track the status of your PR and to help inform you and others of where we're at. As such, please leave the "checking" of items to the repository maintainers. If there is a point below for which you would like to provide additional information or note completion, please do so by commenting on the PR. Thanks! (and thanks for staying patient with us :heart:)

-	[ ] associated with or contacted upstream?
-	[ ] does it fit into one of the common categories? ("service", "language stack", "base distribution")
-	[ ] is it reasonably popular, or does it solve a particular use case well?
-	[x] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
    - https://github.com/docker-library/docs/pull/1055
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
-	[ ] 2+ dockerization review?
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
-	[x] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)

### CODE REVIEW

**Comment by tianon** [comment]
The more I read about Jupyter, the more confused I become. :disappointed:

> Project Jupyter exists to develop open-source software, open-standards, and services for interactive computing across dozens of programming languages.

Does this contain all of what's described under "The Jupyter Notebook" on https://jupyter.org/, or only a subset?

Can you provide some examples of how you think this would be used?  Would this be run as a service to provide the web interface shown on that page?  Is this something that'd be used as a base image for other projects or is it useful to deploy as-is (more like WordPress, Drupal, etc)?  Why does the proposed image name include "base" in it?

Upstream's comment from https://github.com/jupyter/docker-stacks/issues/472#issuecomment-332700914 also seems to imply they'd prefer to have more information about our process before engaging in it, but I might be misreading that.

**Comment by vaibhavsood** [comment]
Hi @tianon, thanks for the response!! These are some answers to your queries, i can help with getting further queries answered as necessary

This i think is a good basic tutorial for jupyter notebooks: https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook

> Does this contain all of what's described under "The Jupyter Notebook" on https://jupyter.org/, or only a subset?

This PR is just the dockerfile for jupyter-base-notebook, the *base* here refers to a base notebook stack https://github.com/jupyter/docker-stacks/tree/master/base-notebook#what-it-gives-you, it basically is a basic jupyter-notebook installation on top of which custom containers can be built (for e.g  a R notebook container will be built on top of base to add R functionalities)

https://github.com/jupyter/docker-stacks#visual-overview is a good overview of their stack hierarchy

> Can you provide some examples of how you think this would be used? Would this be run as a service to provide the web interface shown on that page? Is this something that'd be used as a base image for other projects or is it useful to deploy as-is (more like WordPress, Drupal, etc)? Why does the proposed image name include "base" in it?

https://github.com/jupyter/docker-stacks#quick-start is how the container is started, the container would basically start the "jupyter server" listening-in on a port, the user connects to this via a browser to use the notebook. This PR only has the base notebook dockerfile as a first step, ideally i guess others here:https://github.com/jupyter/docker-stacks  also can be added if this entire thing looks feasible

> Upstream's comment from jupyter/docker-stacks#472 (comment) also seems to imply they'd prefer to have more information about our process before engaging in it, but I might be misreading that.

Yes, i think thats right but I personally think the upstream dockerfile repo structure https://github.com/jupyter/docker-stacks probably is a good fit to be made an official repo (since they have a well-documented way to run the dockerfiles, the dockerfiles look structured and i think jupyter notebooks is getting quite popular in the ML/DL, data science fields: https://www.quora.com/How-popular-are-Jupyter-Notebooks/answer/Kao-Zi-Chong). I can help with being the bridge with upstream to get further queries answered and also get their opinions on this

**Comment by jakirkham** [comment]
cc @parente

**Comment by tianon** [comment]
Hey folks, is this PR still a desirable addition?  I believe there were some related conversations happening within the Jupyter community around this -- was there a favorable outcome there?  (Otherwise, we'd prefer to close this out and reopen once there's sufficient interest in moving this forward. :pray: :heart: :+1:)

**Comment by yosifkit** [comment]
Inactive PR, Closing for now. :heart:

**Pull request closed without merging**
