### PR TITLE
Update to Flink 1.15.0

### PR DESCRIPTION
**Pull request by gaoyunhaii**
This PR updates the flink library to the latest 1.15.0 after the new version 1.15.0 is released.

### CODE REVIEW

**Comment by yosifkit** [comment]
```Dockerfile
RUN sed -i 's/rest.address: localhost/rest.address: 0.0.0.0/g' $FLINK_HOME/conf/flink-conf.yaml
RUN sed -i 's/rest.bind-address: localhost/rest.bind-address: 0.0.0.0/g' $FLINK_HOME/conf/flink-conf.yaml
RUN sed -i 's/jobmanager.bind-host: localhost/jobmanager.bind-host: 0.0.0.0/g' $FLINK_HOME/conf/flink-conf.yaml
RUN sed -i 's/taskmanager.bind-host: localhost/taskmanager.bind-host: 0.0.0.0/g' $FLINK_HOME/conf/flink-conf.yaml
RUN sed -i '/taskmanager.host: localhost/d' $FLINK_HOME/conf/flink-conf.yaml
```

Though small, it is best practice to not make duplicates across layers of a docker image, so all changes to`flink-conf.yaml` should be in a single `RUN` (in the layer in which it was created would be best).

**Comment by gaoyunhaii** [comment]
Very thanks @yosifkit for the review! I changed the Dockerfile to merge the RUNs into the previous one.

**Comment by yosifkit** [comment]
I don't want to delay the new version any further so I'll merge, but just a note of the warning from `docker build`:

```console
[WARNING]: Empty continuation line found in:
...
[WARNING]: Empty continuation lines will become errors in a future release.
```

(I don't know of any plans to remove it anytime soon, but something to improve in future Dockerfiles.)

**Comment by gaoyunhaii** [comment]
Very thanks @yosifkit for the review! We'll fix the issue soon and also pay attention next time. Very thanks for the guidance!

**Pull request merged**
