### PR TITLE
Update docker-library images

### PR DESCRIPTION
**Pull request by tianon**
- `postgres`: 9.4.1-1.pgdg70+1, 9.3.6-1.pgdg70+1, 9.2.10-1.pgdg70+1, 9.1.15-1.pgdg70+1, 9.0.19-1.pgdg70+1
- `tomcat`: 7.0.59

### CODE REVIEW

**Comment by tianon** [comment]
- `mysql`: 5.5.42, 5.6.23

(wut, how'd we miss that)

**Comment by tianon** [comment]
- `python`: add GPG verification (docker-library/python#34)

**Comment by tianon** [comment]
Build test of #461; 4b9351b3ca549d356a225af4e39bf7c66b0d9a23 (`mysql`, `postgres`, `python`, `tomcat`):

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/4b9351b3ca549d356a225af4e39bf7c66b0d9a23/library/mysql
Fetching mysql (git://github.com/docker-library/mysql) ...
Processing mysql:5.5.42 ...
Processing mysql:5.5 ...
Processing mysql:5.6.23 ...
Processing mysql:5.6 ...
Processing mysql:5 ...
Processing mysql:latest ...
Processing mysql:5.7.5-m15 ...
Processing mysql:5.7.5 ...
Processing mysql:5.7 ...
```

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/4b9351b3ca549d356a225af4e39bf7c66b0d9a23/library/postgres
Fetching postgres (git://github.com/docker-library/postgres) ...
Processing postgres:8.4.22 ...
Processing postgres:8.4 ...
Processing postgres:8 ...
Processing postgres:9.0.19 ...
Processing postgres:9.0 ...
Processing postgres:9.1.15 ...
Processing postgres:9.1 ...
Processing postgres:9.2.10 ...
Processing postgres:9.2 ...
Processing postgres:9.3.6 ...
Processing postgres:9.3 ...
Processing postgres:9.4.1 ...
Processing postgres:9.4 ...
Processing postgres:9 ...
Processing postgres:latest ...
```

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/4b9351b3ca549d356a225af4e39bf7c66b0d9a23/library/python
Fetching python (git://github.com/docker-library/python) ...
Processing python:2.7.9 ...
Processing python:2.7 ...
Processing python:2 ...
Processing python:2.7.9-onbuild ...
Processing python:2.7-onbuild ...
Processing python:2-onbuild ...
Processing python:2.7.9-slim ...
Processing python:2.7-slim ...
Processing python:2-slim ...
Processing python:2.7.9-wheezy ...
Processing python:2.7-wheezy ...
Processing python:2-wheezy ...
Processing python:3.3.6 ...
Processing python:3.3 ...
Processing python:3.3.6-onbuild ...
Processing python:3.3-onbuild ...
Processing python:3.3.6-slim ...
Processing python:3.3-slim ...
Processing python:3.3.6-wheezy ...
Processing python:3.3-wheezy ...
Processing python:3.4.2 ...
Processing python:3.4 ...
Processing python:3 ...
Processing python:latest ...
Processing python:3.4.2-onbuild ...
Processing python:3.4-onbuild ...
Processing python:3-onbuild ...
Processing python:onbuild ...
Processing python:3.4.2-slim ...
Processing python:3.4-slim ...
Processing python:3-slim ...
Processing python:slim ...
Processing python:3.4.2-wheezy ...
Processing python:3.4-wheezy ...
Processing python:3-wheezy ...
Processing python:wheezy ...
```

```console
$ bashbrew build https://raw.githubusercontent.com/docker-library/official-images/4b9351b3ca549d356a225af4e39bf7c66b0d9a23/library/tomcat
Fetching tomcat (git://github.com/docker-library/tomcat) ...
Processing tomcat:6.0.43-jre7 ...
Processing tomcat:6.0-jre7 ...
Processing tomcat:6-jre7 ...
Processing tomcat:6.0.43 ...
Processing tomcat:6.0 ...
Processing tomcat:6 ...
Processing tomcat:6.0.43-jre8 ...
Processing tomcat:6.0-jre8 ...
Processing tomcat:6-jre8 ...
Processing tomcat:7.0.59-jre7 ...
Processing tomcat:7.0-jre7 ...
Processing tomcat:7-jre7 ...
Processing tomcat:7.0.59 ...
Processing tomcat:7.0 ...
Processing tomcat:7 ...
Processing tomcat:7.0.59-jre8 ...
Processing tomcat:7.0-jre8 ...
Processing tomcat:7-jre8 ...
Processing tomcat:8.0.18-jre7 ...
Processing tomcat:8.0-jre7 ...
Processing tomcat:8-jre7 ...
Processing tomcat:jre7 ...
Processing tomcat:8.0.18 ...
Processing tomcat:8.0 ...
Processing tomcat:8 ...
Processing tomcat:latest ...
Processing tomcat:8.0.18-jre8 ...
Processing tomcat:8.0-jre8 ...
Processing tomcat:8-jre8 ...
Processing tomcat:jre8 ...
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
