### PR TITLE
Revert "Update python-hy test"

### PR DESCRIPTION
**Pull request by tianon**
Reverts docker-library/official-images#2551

### CODE REVIEW

**Comment by tianon** [comment]
Heh, looks like the failures are actually caused by the new version of Hy, not by the test change. :innocent: :disappointed:

cc @paultag (any ideas for what we might be doing wrong?)

```console
$ docker run -it --rm python:3.6-slim bash
root@fb6e7113d667:/# pip install hy
Collecting hy
  Downloading hy-0.12.0.tar.gz (63kB)
    100% |████████████████████████████████| 71kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3xk7ny_l/hy/setup.py", line 35, in <module>
        (["git", "describe", "--tags", "--dirty"])
      File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/local/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'git'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3xk7ny_l/hy/
```

Why should Hy require `git` just to install? :confused:

**Comment by tianon** [comment]
Looks to be due to https://github.com/hylang/hy/pull/1135, which appears to have accounted for `git` failing, but not for `git` not even existing.

**Comment by tianon** [comment]
Filed https://github.com/hylang/hy/issues/1205. :+1:

**Comment by yosifkit** [comment]
Should we go with this revert or wait for the fix in https://github.com/hylang/hy/pull/1206?

**Comment by tianon** [comment]
This revert is wrong too (tests still fail both with and without this revert) -- that's what led me to dig in and find the exact issue I filed.  I only left it open as a tracker to remind us that we _do_ need to figure out something (and pinning the test to Hy 0.11.x for now and including this revert might be the best way to do that until 0.12.1).

**Comment by tianon** [comment]
ccac248 :+1:

**Pull request merged**
