### PR TITLE
Update for the release of websphre-liberty 20.0.0.10

### PR DESCRIPTION
**Pull request by crpotter**
Release updates for websphere-liberty version 20.0.0.10

### CODE REVIEW

**Comment by tianon** [comment]
Can we please figure out some way to get those massive constantly-changing license files out of the build context so that the diffs here are reasonable?

**Comment by yosifkit** [comment]
The only other image that almost had a large licenses context was https://github.com/docker-library/official-images/pull/8366 and they decided to download and verify them during the build to get them out of the build context.

I guess my question is that if they are provided for open source license compliance of software included with the websphere liberty bundle, then why is it not just part of the `wlp.zip`?  But if it is for software installed via `apt`, then surely `/usr/share/doc/[package]/copyright` is sufficient.

**Comment by tianon** [comment]
I think the misunderstanding here is on me -- I was under the impression that this was more akin to a license enabling file (since it's been here but not in `open-liberty`), not just a raw dump of open source license text.

I fully agree with @yosifkit here -- if this is just the licenses of software contained in the image and is something you want to keep in this aggregated form, it should really be generated during the build of the image itself or else it will almost always suffer bitrot (as discussed in https://github.com/docker-library/official-images/pull/8366#issuecomment-662138721 and the following comments).

**Comment by arthurdm** [comment]
thanks guys - we are looking into updating this PR with a change that pulls in the licenses via URL.

**Comment by arthurdm** [comment]
I've created [this PR](https://github.com/WASdev/ci.docker/pull/363) into the WebSphere Liberty repo.

@crpotter - once that is merged, can you please update the GitCommit for this PR?

**Comment by arthurdm** [comment]
hi @tianon / @yosifkit - I've created this new PR with the proposed license changes: https://github.com/docker-library/official-images/pull/8930

Since @crpotter is away this week, can you please review that one, and close this one?

**Pull request closed without merging**
